require('libraries/animations_cl')
require('modifiers/attributes_cl')
require('modifiers/cc_modifiers') -- generic CC/state modifiers must be linked on the client too (buff icons/textures)
-- require('modules/hero_selection/hero_selection')
-- require('modules/hero_selection/hero_replacer')
LinkLuaModifier("modifier_sex_scroll_root","items/modifiers/modifier_sex_scroll_root.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_sex_scroll_slow","items/modifiers/modifier_sex_scroll_slow.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_a_scroll", "items/modifiers/modifier_a_scroll.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_a_scroll_sated", "items/modifiers/modifier_a_scroll_sated.lua", LUA_MODIFIER_MOTION_NONE)
SendToConsole("dota_clientside_wearables false")
--LinkLuaModifier("modifier_hero_selection_skin", "modules/hero_selection/hero_replacer.lua", LUA_MODIFIER_MOTION_NONE)