"DOTAAbilities"
{
	//=====================================
	// Reduced earth (OKITA "COPY")
	//=====================================
	"okada_reduced_earth"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/okada/okada_reduced_earth"
		"AbilityTextureName"				"custom/okada/okada_reduced_earth"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"LevelsBetweenUpgrades"				"1"
		"MaxLevel"							"5"
		"AbilityCooldown"				    "12 11 10 9 8"
		"AbilityManaCost"					"100"
		"AbilityCastRange"					"700"
		"AbilityCastPoint"					"0.3"
		"AbilityCastAnimation"				"ACT_DOTA_CAST_ABILITY_1"
		"AbilityCastPoint"					"0.1"


		"precache"
		{
			"particle"		"particles/okada/okada_pierce.vpcf"
			"particle"		"particles/hijikata/hijikata_demon_pierce.vpcf"
			"particle"		"particles/okada/okada_dash.vpcf"
			"particle"		"particles/_2okada/okada_dash_red.vpcf"
			"particle"		"particles/econ/items/invoker/invoker_ti7/status_effect_alacrity_ti7.vpcf"
			
		}
		"AbilityValues"
		{
			"damage"							"200 250 300 350 400"
			"radius"							"900"
			"speed"								"2500"
			"clones_damage"						"25"
		}
	}
	//=====================================
	// Flashblade copy (SAITO)
	//=====================================
	"okada_flashblade"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/okada/okada_flashblade"
		"AbilityTextureName"				"custom/okada/okada_flashblade"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_AUTOCAST | DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES "
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"LevelsBetweenUpgrades"				"1"
		"MaxLevel"							"5"
		"AbilityCooldown"				    "12 11 10 9 8"
		"AbilityManaCost"					"200"
		"AbilityCastPoint"					"0.1"
		"AbilityCastAnimation"                      "ACT_DOTA_CAST_ABILITY_2"

		"precache"
		{
			"particle"		"particles/okada/okada_dash_slashes.vpcf"
			"particle"		"particles/okada/okada_dash_slashes_red.vpcf"
			"particle"		"particles/okada/okada_dash.vpcf"
			"particle"		"particles/_2okada/okada_dash_red.vpcf"
		}
		"AbilityValues"
		{
			"distance"								"1000"		
			"speed"									"2000"
			"root_duration"					"0.7"
			"radius"							"300"
			"damage"							"300 375 450 525 600"
			"slash_create_dist"					"150"
			"sa_bonus_damage"								"100"
		}
	}

	//=====================================
	// OKADA STRONG SLASH COPY 
	//=====================================
	"okada_chest"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/okada/okada_chest"
		"AbilityTextureName"				"custom/okada/okada_chest"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"LevelsBetweenUpgrades"				"2"
		"MaxLevel"							"5"
		"AbilityCooldown"				    "25 23 21 19 17"
		"AbilityManaCost"					"400"
		"AbilityCastPoint"					"0.4"
		"AbilityCastAnimation"                      "ACT_DOTA_CAST_ABILITY_1"

		"precache"
		{
			"particle"		"particles/okada/okada_chest_slash.vpcf"
			"particle"		"particles/okada/okada_chest_slash_red.vpcf"
		}
		"AbilityValues"
		{
			"duration"								"0.7"
			"width"									"150"
			"damage"								"400 500 600 700 800"
			"range"									"500"
			"clones_damage"							"25"
			"clones_delay"							"0.2"
			"healres_duration"						"2"
			"lock_duration"							"0.8 0.9 1 1.1 1.2"
			"sa_bonus_damage"						"200"
		}
	}

	//=====================================
	// OKADA HEATCLIFF R 
	//=====================================
	"okada_ult"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/okada/okada_ult"
		"AbilityTextureName"				"custom/okada/okada_r"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetFlags"			"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_HERO"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_PURE"
		"LevelsBetweenUpgrades"				"2"
		"MaxLevel"							"5"
		"AbilityCooldown"				    "30"
		"AbilityManaCost"					"800"
		"AbilityCastPoint"					"0.6"
		"AbilityCastRange"					"600"
		"AbilityCastRangeBuffer"			"200"
		"AbilityCastAnimation"                      "ACT_DOTA_CAST_ABILITY_4"

		"precache"
		{
			"particle"		"particles/okada/okada_slash_ult.vpcf"
			"particle"		"particles/okada/okada_slash_ult_red.vpcf"

		}
		"AbilityValues"
		{
			"duration"								"2.15"
			"damage"								"50 62.5 75 87.5 100"
			"last_strike_damage"								"250 312.5 375 437.5 500"
			"normal_strikes"						"12"
			"clones_damage"								"50"
			"dmg_reduct"								"45"
			"clone_search_radius"								"500"
			"sa_bonus_damage"								"15"
			"sa_bonus_damage_last"								"200"
		}
	}


	//=====================================
	// OKADA COMBO
	//=====================================
	"okada_combo"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/okada/okada_combo"
		"AbilityTextureName"				"custom/okada/okada_combo"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_HIDDEN | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING| DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetFlags"		"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_HERO"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_PURE"
		"LevelsBetweenUpgrades"				"25"
		"MaxLevel"							"1"
		"AbilityCooldown"				    "120"
		"AbilityManaCost"					"600"
		"AbilityCastPoint"					"0"
		"AbilityCastRange"					"600"
		"AbilityCastAnimation"                      "ACT_DOTA_CAST_ABILITY_6"

		"precache"
		{
			"particle"		"particles/units/heroes/hero_pugna/pugna_decrepify.vpcf"
			"particle"		"particles/okada/okada_combo_flash.vpcf"

			"particle"		"particles/okada/okada_combo_blood.vpcf"
			"particle"		"particles/okada/okada_combo_blood_phantom.vpcf"
			"particle"		"particles/okada/okada_combo_blood_mist.vpcf"
			"particle"		"particles/zlodemon/zlodemon_basic_circle.vpcf"

		}
		"AbilityValues"
		{
			"max_invis_duration"					"10"
			"invis_activation_delay"				"3"
			"invis_activation_radius"				"500"
			"damage_reduction_pct"				"50"
			"damage_first"					"350"
			"damage_last"					"1500"
			"movespeed"					"250"
			"healres_duration"					"1.5"
		}
	}


	//=================================================================================================================
	// MANSLAYER
	//=================================================================================================================
	"okada_manslayer"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/okada/okada_manslayer"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET| DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE | DOTA_ABILITY_BEHAVIOR_IMMEDIATE" 
		"AbilityTextureName"			"custom/okada/okada_manslayer"
		"MaxLevel"						"2"
		"AbilityCooldown"				"30"
		"AbilityCastPoint"					"0"
		"AbilityCastAnimation" 			"ACT_DOTA_ITEM_PICKUP"
		
		"precache"
		{
			"particle"					"particles/okada/okada_manslayer_ambient.vpcf"
		}

		"AbilityValues"
        {
            "passive_duration" "7"
            "active_duration" "4 7"
        }
	}

	"okada_mark"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/okada/okada_mark"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityTextureName"			"custom/okada/okada_mark"

		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_5"
		"AnimationPlaybackRate" 		"1"

		"AbilityCastPoint"				"0.2"
		"AbilityCooldown"				"40"
		"AbilityManaCost"				"0"
		"AbilityCastRange"					"600"
		"precache"
		{
			"particle"				"particles/zlodemon/zlodemon_overhead_okada_mark.vpcf"
		}


		"AbilityValues"
        {

            "revoke_duration" "2"
            "vision_duration" "5"
            "target_vision" "300"
            "mute_duration"	"1"
        }
	}
	"okada_sa_1"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/okada/okada_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/okada/okada_sa_1"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"14"

		 
		"AbilityValues"
        {
        	"flashblade_bonus"										"100"
			"chest_bonus"										"200"
			"ult_bonus"										"15"
			"ult_last_bonus"										"200"
        }		
	}
	"okada_sa_2"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/okada/okada_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/okada/okada_sa_2"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"13"

		 
		"AbilityValues"
        {
			"vision_duration"										"5"
			"vision_radius"											"2000"
        }		
	}
	"okada_sa_3"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/okada/okada_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/okada/okada_sa_3"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"12"

		 
		"AbilityValues"
        {
			"bonus_duration"										"3"

        }		
	}
	"okada_sa_4"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/okada/okada_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/okada/okada_sa_4"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"10"

		 
		"AbilityValues"
        {
			"gold_bonus"										"50"
			"item_cdr"										"25"
        }		
	}
	"okada_sa_5"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/okada/okada_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/okada/okada_sa_5"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"12"

		 
		"AbilityValues"
        {
			"value"										"100"

        }		
	}


}