
"DOTAAbilities"
{	

	//====================================
	// Parry
	//====================================
	"diarmuid_parry"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/diarmuid/diarmuid_parry"
		"MaxLevel"						"2"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"25"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_AOE |  DOTA_ABILITY_BEHAVIOR_DONT_CANCEL_CHANNEL | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL |  DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING| DOTA_ABILITY_BEHAVIOR_IGNORE_SILENCE"
		"AbilityTextureName"			"custom/diar_parry"
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"30 20"
		"AbilityManaCost"				"100 0"
		"AbilityChannelTime"			"1"
		"AbilityCastAnimation" 			"ACT_DOTA_OVERRIDE_ABILITY_4"


		"precache"
		{
			"particle"			"particles/diarmuid/parry/diar_parry_cast.vpcf"
			"particle"			"particles/diarmuid/diar_parry/diar_parry_shield.vpcf"
			"particle"			"particles/zlodemon/diar_combo/gae_buidhe_slash_counter.vpcf"
			"particle"			"particles/zlodemon/zlodemon_overhead_duel_diarmuid.vpcf"
			"particle"			"particles/zlodemon/zlodemon_overhead_duel_diarmuid_skin.vpcf"
			"particle"			"particles/zlodemon/diar_combo/gae_buidhe_slash_counter_skin.vpcf"
		}

		"AbilityValues"
		{	
			"stun_duration"				"0.1"
			"first_hit_radius"			"500"
			"shield_amount"				"400"
			"damage_cast"				"100"
			"damage"					"300 600"
			"duration"					"3"
			"disarm_duration"					"3"
			"shield_damage_decrease_flat_value"						"300 600"
		}
	}

	"diarmuid_dash"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/diarmuid/diarmuid_dash"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_CREEP"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/diarmuid_double_spearsmanship"
		"AbilityCastAnimation" 			"ACT_DOTA_RAZE_1"
		"AnimationPlaybackRate" 		"2.5"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"

		"AbilityCastPoint"                          "0.0"
        "AbilityManaCost"                           "200"
        "AbilityCooldown"                           "17 16 15 14 13"

		"precache"
		{
			"particle"				"particles/zlodemon/diar_combo/petals_jopa.vpcf"
			"particle"				"particles/okita/okita_surge_try.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_phantom_lancer.vsndevts"

		}
		"AbilityValues"
        {
            "dash_speed" "1500"
            "distance" 	"500"
            "damage" 	"250 312.5 375 412.5 500"
            "q_cdr" 	"3"
        }
	}

	//=================================================================================================================
	// Diarmuid : New combo
	//=================================================================================================================
	"diarmuid_new_combo"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/diarmuid/diarmuid_new_combo"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT|DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/diar_throw"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_7"
		"AOERadius"						"%radius"
		"AnimationPlaybackRate" 		"1.5"
		
		"precache"
		{
			"particle"				"particles/zlodemon/diar_combo/flower.vpcf"
			"particle"				"particles/zlodemon/diar_combo/gae_buidhe_slash_0.vpcf"
			"particle"				"particles/zlodemon/diar_combo/gae_buidhe_slash_0_back.vpcf"
			"particle"				"particles/zlodemon/diar_combo/gae_buidhe_slash_1.vpcf"
			"particle"				"particles/zlodemon/diar_combo/gae_buidhe_slash_1_baack.vpcf"
			"particle"				"particles/zlodemon/diar_combo/gae_buidhe_slash_2.vpcf"
			"particle"				"particles/zlodemon/diar_combo/gae_buidhe_slash_3.vpcf"
			"particle"				"particles/zlodemon/diar_combo/gae_dearg_projectile.vpcf"
			"particle"				"particles/zlodemon/diar_combo/gae_dearg_target.vpcf"
			"particle"				"particles/zlodemon/diar_combo/gae_dearg_trail.vpcf"
			"particle"				"particles/zlodemon/diar_combo/golden_rose.vpcf"
			"particle"				"particles/zlodemon/diar_combo/petals.vpcf"
			"particle"				"particles/zlodemon/diar_combo/lucio_combo_projectile.vpcf"
			"particle"				"particles/zlodemon/diar_combo/lucio_sword_target.vpcf"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"1000"
		"AbilityCastPoint"				"0.3"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"120"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"200"
		
		"AbilityValues"
        {
            "damage" "400"
            "duration" "1.4"
            "cast_range" "1000"
            "recast_timer" "2"
            "radius" "250"
            "total_damage" "1800"
            "reduced_cooldown" "60"
        }
	}
	//=================================================================================================================
	// Diarmuid : Warrior's Charge
	//=================================================================================================================
	"diarmuid_warrior_charge"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/diarmuid/diarmuid_warrior_charge"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/diarmuid_warriors_charge"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AOERadius"						"%radius"
		"AnimationPlaybackRate" 		"2.5"
		
		"precache"
		{
			"particle"				"particles/units/heroes/hero_sven/sven_storm_bolt_projectile_explosion.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_huskar.vsndevts"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"650 675 700 725 750"
		"AbilityCastRangeBuffer"		"800"
		"AbilityCastPoint"				"0.1"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"11 10 9 8 7"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"100"
		
		"AbilityValues"
        {
            "damage" "100 125 150 175 200"
            "radius" "300"
            "cooldown" "11 10 9 8 7"
            "doublespear_cd" "4"
            "combo_cd" "2"
            "duration" "0.6 0.7 0.8 0.9 1"
            "cast_range_checker" "900"
            "cast_range" "650 675 700 725 750"
        }
	}

	//========================================
	// Diarmuid - Double Spearsmanship
	//========================================

	//=================================================================================================================
	// Diarmuid : Gae Buidhe
	//=================================================================================================================
	"diarmuid_gae_buidhe"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/diarmuid/diarmuid_gae_buidhe"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_CREEP"
		"AbilityUnitTargetFlags"		"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/diarmuid_gae_buidhe"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_4"
		"AnimationPlaybackRate" 		"1.2"
		
		"precache"
		{
			"particle"				"particles/zlodemon/diar_combo/flower.vpcf"
			"particle"				"particles/zlodemon/diar_combo/golden_rose.vpcf"
			"particle"				"particles/zlodemon/diar_combo/petals.vpcf"
			"particle"					"particles/units/heroes/hero_chaos_knight/chaos_knight_reality_rift.vpcf"
			"particle"					"particles/units/heroes/hero_axe/axe_culling_blade_kill.vpcf"
			"particle"					"particles/custom/diarmuid/diarmuid_gae_cast.vpcf"
			"particle"					"particles/custom/diarmuid/diarmuid_gae_buidhe.vpcf"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_lion.vsndevts"
			"particle"					"particles/diarmuid/diar_slash_yellow_skin.vpcf"
			"particle"		"particles/custom/diarmuid/diarmuid_cull.vpcf"
			"particle"		"particles/units/heroes/hero_bounty_hunter/bounty_hunter_track_trail_circle.vpcf"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"275"
		"AbilityCastRangeBuffer"		"150"
		//"AbilityCastPoint"				"0.6"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		//"AbilityCooldown"				"30"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		//"AbilityManaCost"				"400"
		
		"AbilityValues"
        {
            "damage" "650 725 800 875 950"
            "cooldown" "30"
            "combo_cooldown" "1"
            "doublespear_window" "3"
            "attribute_window" "4"
        }
	}

	//========================================
	// Diarmuid - Love Spot
	//========================================

	//=======================================
	// Diarmuid : Minds Eye
	//=======================================
	"diarmuid_minds_eye"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/diarmuid/diarmuid_minds_eye"
		"MaxLevel"						"1"
		"RequiredLevel"					"25"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityTextureName"			"custom/diarmuid_attribute_minds_eye"	
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"15"
		"AbilityManaCost"				"0"

		"precache"
		{
			"particle"					"particles/zlodemon/zlodemon_overhead_eye.vpcf"
		}

		"AbilityValues"
        {
            "duration" "1.5"
            "magic_res" "20"
            "evasion" "75"
            "radius" "1500"
        }
	}

	//=================================================================================================================
	// Diarmuid : Gae Dearg
	//=================================================================================================================
	"diarmuid_gae_dearg"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/diarmuid/diarmuid_gae_dearg"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_CREEP"
		"AbilityUnitTargetFlags"		"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PURE"
		"AbilityTextureName"			"custom/diarmuid_gae_dearg"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AbilityType"					"ABILITY_TYPE_ULTIMATE"
		"AnimationPlaybackRate" 		"1.0"
		
		"precache"
		{
			"particle"				"particles/zlodemon/diar_combo/flower_red.vpcf"
			"particle"				"particles/zlodemon/diar_combo/red_rose.vpcf"
			"particle"				"particles/zlodemon/diar_combo/petals_red.vpcf"
			"particle"			"particles/units/heroes/hero_chaos_knight/chaos_knight_reality_rift.vpcf"
			"particle"			"particles/units/heroes/hero_axe/axe_culling_blade_kill.vpcf"
			"particle"			"particles/items_fx/dagon.vpcf"
			"particle" 			"particles/custom/diarmuid/gae_dearg_slash.vpcf"
			"particle" 			"particles/custom/diarmuid/gae_dearg_slash_flash.vpcf"
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_lion.vsndevts"
			"particle"			"particles/diarmuid/diar_slash_red_skin.vpcf"
			"particle"		"particles/custom/diarmuid/diarmuid_cull.vpcf"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"350"
		"AbilityCastRangeBuffer"		"200"
		"AbilityCastPoint"				"0.8"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"30"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"500"
		
		"AbilityValues"
        {
            "min_damage" "500 625 750 875 1000"
            "max_damage" "600 750 900 1050 1200"
            "min_damage_dist" "350"
            "max_damage_dist" "200"
            "duration" "15.0"
            "doublespear_window" "3"
            "cooldown" "30"
            "combo_cooldown" "1.0"
            "attribute_window" "4"
        }
	}

	//=======================================
	// Diarmuid Attribute : Improve parry
	//=======================================
	"diarmuid_attribute_parry"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/diarmuid/diarmuid_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/diar_parry"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"7"

		"precache"
		{
		}

		"AbilityValues"
        {
            "bonus_damage_reduction" "300"
            "bonus_damage" "300"
            "vision_duration" "5"
            "bonus_q_range" "500"
        }
	}
	//=======================================
	// Diarmuid Attribute : Improve Love Spot
	//=======================================

	//=======================================
	// Diarmuid Attribute : Mind's Eye
	//=======================================
	"diarmuid_attribute_minds_eye"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/diarmuid/diarmuid_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/diarmuid_attribute_minds_eye"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"12"

		"precache"
		{
		}

		"AbilityValues"
        {
            "duration" "1.0"
            "radius" "1500"
            "active_duration" "1.5"
            "magic_resist" "50"
            "evasion" "75"
        }
	}
	
	//=======================================
	// Diarmuid Attribute : Golden Rose of Mortality
	//=======================================
	"diarmuid_attribute_golden_rose"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/diarmuid/diarmuid_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/diarmuid_attribute_golden_rose"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"8"

		"precache"
		{
		}

		"AbilityValues"
        {
            "damage_per_stack" "1"
            "cost_reduce" "150"
        }
	}

	//=======================================
	// Diarmuid Attribute : Crimson Rose of Exorcism
	//=======================================
	"diarmuid_attribute_crimson_rose"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/diarmuid/diarmuid_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/diarmuid_attribute_crimson_rose"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"10"

		"precache"
		{
		}

		"AbilityValues"
        {
            "revoke_per_stack" "1.5"
            "mana_per_stack" "500"
            "cost_reduce" "150"
            "mana_duration" "15"
        }
	}

	//=======================================
	// Diarmuid Attribute : Double Spear Strike
	//=======================================
	"diarmuid_attribute_doublespear"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/diarmuid/diarmuid_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/diarmuid_attribute_double_spear_strike"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"14"

		"precache"
		{
		}

		"AbilityValues"
        {
            "use_window" "7.0"
            "attack_speed" "55"
            "cost_reduce_buidhe" "100"
            "cost_reduce_dearg" "100"
        }
	}

	//=======================================
	// Diarmuid : Rampant Warrior Proxy
	//=======================================
}