"DOTAAbilities"
{
	//=================================================================================================================
	// Nero : Aestus Domus Aurea
	//=================================================================================================================

	//=================================================================================================================
	// Nero : Fiery Finale
	//=================================================================================================================

	//=================================================================================================================
	// Nero : Tres Fontaine Ardent
	//=================================================================================================================

	//=====================================
	// Nero : Gladiusanus Blauserum
	//=====================================

	//=================================================================================================================
	// Nero : Rosa Ichthys
	//=================================================================================================================
	"nero_rosa_ichthys"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/nero_rosa_ichthys"
		"AbilityCastAnimation" 			"ACT_DOTA_IDLE"
		
		// Ability stats
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"1050"
		"AbilityCastRangeBuffer"		"0"
		"AbilityCastPoint"				"0.3"
		"AbilityCooldown"				"21"
		"AbilityManaCost"				"400"
		
		// Ability special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "damage" "400 500 600 700 800"
            "max_range" "1450"
            "stun_duration" "0.7 0.9 1.1 1.3 1.5"
        }
		
		// Data driven
		//-------------------------------------------------------------------------------------------------------------
		"precache"						
		{
			"particle"			"particles/custom/archer/archer_overedge_slash.vpcf"
			"particle"			"particles/units/heroes/hero_legion_commander/legion_duel_start_text_burst_flare.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_lion.vsndevts"
		}
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"			"nero_ability"
				"Function"				"OnRIStart"
				"MaxRange"				"%max_range"
			}
		}
		
		"OnProjectileHitUnit"
		{
			"DeleteOnHit"			"false"
			
			"RunScript"
			{
				"ScriptFile"    "nero_ability"
				"Function"      "OnRIHit"
				"Damage"		"%damage"
				"StunDuration"	"%stun_duration"
			}
		}
		
		"Modifiers"
		{
			"modifier_rosa_ichthys_anim"
			{
				"OverrideAnimation"     "ACT_DOTA_CAST_ABILITY_1"	
				"Duration"			"1.0"
				"IsHidden"			"1"
				"Properties"
				{
					"MODIFIER_PROPERTY_OVERRIDE_ANIMATION_RATE"		"0.7"
				}
			}
			"modifier_laus_anim"
			{
				"OverrideAnimation"     "ACT_DOTA_CAST_ABILITY_2"	
				"Duration"			"1.0"
				"IsHidden"			"1"
				"Properties"
				{
					"MODIFIER_PROPERTY_OVERRIDE_ANIMATION_RATE"		"1.0"
				}
			}
		}
	}

	//=================================================================================================================
	// Nero : Luas Saint Cladius
	//=================================================================================================================

	// [restored] возвращён после ошибочной чистки
	// [restored] возвращён после ошибочной чистки
}