"DOTAAbilities"
{
	//=================================================================================================================
	// Nero : Tres Fontaine Ardent
	//=================================================================================================================
	
	//=====================================
	// Nero : Gladiusanus Blauserum
	//=====================================

	//=================================================================================================================
	// Nero : Rosa Ichthys
	//=================================================================================================================
	"nero_rosa_ichthys"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/nero/nero_rosa_ichthys"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/nero_rosa_ichthys"
		"AbilityCastAnimation" 			"ACT_DOTA_ATTACK_EVENT"
		
		// Ability stats
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"550"
		"AbilityCastRangeBuffer"		"0"
		"AbilityCastPoint"				"0.3"
		"AbilityCooldown"				"21"
		"AbilityManaCost"				"400"

		// Data driven
		//-------------------------------------------------------------------------------------------------------------
		"precache"						
		{
			"particle"			"particles/custom/archer/archer_overedge_slash.vpcf"
			"particle"			"particles/units/heroes/hero_legion_commander/legion_duel_start_text_burst_flare.vpcf"
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_lion.vsndevts"
		}		

		// Ability special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "damage" "325 425 525 625 700"
            "max_range" "550"
            "stun_duration" "0.75 0.75 1.0 1.0 1.25"
        }
	}

	//=================================================================================================================
	// Nero : Aestus Domus Aurea
	//=================================================================================================================
	"nero_aestus_domus_aurea"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/nero/nero_aestus_domus_aurea"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityTextureName"			"custom/nero_aestus_domus_aurea"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_2"
		"AbilityType"					"ABILITY_TYPE_ULTIMATE"
		"AnimationPlaybackRate" 		"1.0"
		"AbilityCastPoint"				"0.5"
		
		"precache"
		{
			"particle"				"particles/custom/nero/nero_domus_ring_energy.vpcf"
			"particle"				"particles/custom/nero/nero_domus_ray.vpcf"
			"particle"				"models/particle/legion_duel_banner.vmdl"
			"particle"				"particles/items2_fx/radiance_owner.vpcf"
			"particle"				"particles/units/heroes/hero_phoenix/phoenix_supernova_radiance.vpcf"
			"particle"				"particles/custom/nero/nero_domus_ring_border.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_legion_commander.vsndevts"
		}
		
		"AbilityCooldown"			"54"
		"AbilityManaCost"			"800"
		"AbilityCastRange"			"1050"
		
		"AbilityValues"
        {
            "delay" "1.5"
            "radius" "1050"
            "duration" "12.0"
            "resist_reduc" "-3 -6 -9 -12 -15"
            "armor_reduc" "-3 -6 -9 -12 -15"
            "movespeed_reduc" "-10 -10 -15 -15 -20"
        }
	}

	//=================================================================================================================
	// Nero : Luas Saint Cladius
	//=================================================================================================================
	"nero_laus_saint_claudius"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/nero/nero_laus_saint_claudius"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/nero_laus_saint"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		
		// Ability stats
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"500"
		"AbilityCastRangeBuffer"		"0"
		"AbilityCastPoint"				"0.3"
		"AbilityCooldown"				"70"
		"AbilityManaCost"				"400"
		
		// Data driven
		//-------------------------------------------------------------------------------------------------------------
		"precache"						
		{
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_lion.vsndevts"
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_ember_spirit.vsndevts"
		}

		// Ability special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "damage" "1500"
            "stun_duration" "1.5"
            "burn_damage" "400"
            "duration" "3"
        }		
	}
}