
"DOTAAbilities"
{
	//=======================================
  // Atalanta: Traps (spellbook)
  //=======================================
  //=======================================
  // Atalanta: Sting Shot (traps)
  //=======================================
  //=======================================
  // Atalanta: Cobweb Shot (traps)
  //=======================================
  //=======================================
  // Atalanta: Entangling Trap (traps)
  //=======================================
  //=======================================
  // Atalanta: Reload (traps)
  //=======================================

  //=======================================
  // Atalanta: Tauropolos 
  //=======================================

  //=======================================
  // Atalanta: Phoebus Catastrophe Proxy
  //=======================================
  "atalanta_phoebus_catastrophe_proxy"
  {
    "BaseClass"						"ability_lua"
    "ScriptFile"					"abilities/atalanta/phoebus_catastrophe_proxy"
    "MaxLevel"						"1"
    "AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
    "AbilityTextureName"			"custom/atalanta_phoebus_catastrophe"
    
    "AbilityCastPoint"				"1.4"
    "AbilityCooldown"				"140"
    "AbilityManaCost"				"300"

    "AbilityValues"
        {
            "range" "3000"
            "aoe" "600"
            "arrow_aoe" "200"
            "barrage_arrows" "60"
            "snipe_arrows" "11"
            "delay" "2.4"
            "cast_time" "1.4"
            "arrows_damage_percentage" "75"
        }
  }
}