#base "atalanta_calydonian_snipe.kv"
#base "atalanta_attributes.kv"

"DOTAAbilities"
{
  //=======================================
  // Atalanta: Celestial Arrow
  //=======================================
  "atalanta_celestial_arrow"
  {
    "BaseClass"						     "ability_lua"
    "ScriptFile"					     "abilities/atalanta/celestial_arrow"
    "MaxLevel"						     "5"
    "AbilityBehavior"				   "DOTA_ABILITY_BEHAVIOR_POINT"
    "AbilityTextureName"			 "windrunner_powershot"
    "AbilityUnitDamageType"    "DAMAGE_TYPE_PHYSICAL"
    "AbilityCastPoint"				 "0.0"
    "AbilityCooldown"				   "0"
    "AbilityManaCost"				   "0"
    "LevelsBetweenUpgrades"		 "1"
    "AbilityManaCost"     "20"

    "precache"
    {
      "particle"					"particles/econ/items/windrunner/windrunner_ti6/windrunner_spell_powershot_channel_ti6_shock_ring.vpcf"
      "particle"					"particles/units/heroes/hero_windrunner/windrunner_spell_powershot.vpcf"
      "particle"					"particles/custom/atalanta/atalanta_shock_ring.vpcf"
      "particle"					"particles/custom/atalanta/atalanta_arrow.vpcf"
      "particle"					"particles/custom/atalanta/atalanta_arrow_10stack.vpcf"
      "soundfile"					"soundevents/game_sounds_heroes/game_sounds_windrunner.vsndevts"
    }

    "AbilityValues"
        {
            "range" "1200 1350 1500 1650 1800"
            "bonus_arrows" "0 1 2 3 4"
            "bonus_damage" "175"
            "damage_per_level" "5"
            "agility_per_stack" "1 2 3 4 5"
            "casttime_reduction_per_stack" "1.25 1.75 2.25 2.75 3.25"
            "max_stacks" "10"
            "stacks_duration" "10"
            "damage" "100"
            "bonus_range_per_agi" "6"
            "last_spurt_duration" "7"
            "base_ms" "0"
            "ms_per_unit" "10"
            "base_evade" "0"
            "evade_per_unit" "10"
            "stacking_debuff_duration" "7"
        }
  }

  //=======================================
  // Atalanta: Calydonian Hunt
  //=======================================
  "atalanta_calydonian_hunt"
  {
    "BaseClass"						"ability_lua"
    "ScriptFile"					"abilities/atalanta/calydonian_hunt"
    "MaxLevel"						"5"
    "AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
    "AbilityUnitTargetTeam"     "DOTA_UNIT_TARGET_TEAM_ENEMY"
    "AbilityUnitTargetType"     "DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_CREEP"
    "AbilityUnitDamageType"     "DAMAGE_TYPE_PURE"
    "AbilityTextureName"			"custom/atalanta_calydonian_hunt"
    "AbilityCastAnimation"    "ACT_DOTA_CAST_ABILITY_3"
    "AbilityCastPoint"				"0.25"
    "AbilityCastRange"             "2000 2250 2500 2750 3000"
    "AbilityCooldown"				"16"
    "AbilityManaCost"				"200"
    "LevelsBetweenUpgrades"				"1"

    "precache"
    {
      "particle"					"particles/econ/items/enchantress/enchantress_lodestar/ench_lodestar_death.vpcf"
      "particle"          "particles/zlodemon/zlodemon_overhead_eye.vpcf"
      "soundfile"					"soundevents/game_sounds_heroes/game_sounds_naga_siren.vsndevts"
      "soundfile"         "soundevents/game_sounds_heroes/game_sounds_bounty_hunter.vsndevts"
    }

    "AbilityValues"
        {
            "max_stacks" "5"
            "debuff_duration" "5.0"
            "root_duration" "1.1 1.5 1.9 2.3 2.7"
            "sight_duration" "5.0 6.0 7.0 8.0 9.0"
            "attribute_stack_bonus" "2"
            "attribute_bonus_duration" "2"
            "root_cooldown" "8"
            "sight_radius" "2000 2250 2500 2750 3000"
            "slow_amount" "-35"
            "slow_duration" "3"
            "sight_perc" "60"
            "passive_radius" "2000 2250 2500 2750 3000"
            "damage" "3"
        }
  }  

  //=======================================
  // Atalanta: Golden Apple
  //=======================================
  "atalanta_golden_apple"
  {
    "BaseClass"						"ability_lua"
    "ScriptFile"					"abilities/atalanta/golden_apple"
    "MaxLevel"						"1"
    "AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
    "AbilityTextureName"			"custom/atalanta_golden_apple"
    
    "AbilityCastPoint"				"0.3"
    "AbilityCooldown"				"45"
    "AbilityManaCost"				"200"
    "AbilityCastAnimation"    "ACT_DOTA_CAST_ABILITY_3"

    "precache"
    {
      "particle"					"particles/units/heroes/hero_enchantress/enchantress_natures_attendants_lvl4.vpcf"
      "particle"					"particles/econ/items/juggernaut/jugg_arcana/juggernaut_arcana_v2_teleport_model_glow.vpcf"
      "particle"					"particles/units/heroes/hero_furion/furion_base_attack.vpcf"
      "particle"          "particles/econ/generic/generic_progress_meter/generic_progress_circle.vpcf"
      "soundfile"					"soundevents/game_sounds_heroes/game_sounds_enchantress.vsndevts"
    }

    "AbilityValues"
        {
            "range" "2000"
            "lure_duration" "3"
            "aoe" "400"
            "swap_duration" "2"
        }
  }

  //=======================================
  // Atalanta: Crossing Arcadia
  //=======================================
  "atalanta_crossing_arcadia"
  {
    "BaseClass"						"ability_lua"
    "ScriptFile"					"abilities/atalanta/crossing_arcadia"
    "MaxLevel"						"2"
    "LevelsBetweenUpgrades"			"25"
    "AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES"
    "AbilityTextureName"			"custom/atalanta_crossing_arcadia"
    "AbilityCastAnimation"      "ACT_DOTA_ATTACK_EVENT"
    "AbilityUnitDamageType"     "DAMAGE_TYPE_PHYSICAL"
    "AbilityCastPoint"				"0.05"
    "AbilityCooldown"				"18 15"
    "AbilityManaCost"				"200"

    "precache"
    {
      "particle"					"particles/units/heroes/hero_enchantress/enchantress_impetus.vpcf"
    }

    "AbilityValues"
        {
            "range" "900 900"
            "jump_time" "0.05"
            "aoe" "200"
            "stun_duration" "0"
            "leapback_range" "900 900"
            "jump_duration" "0.5"
            "attribute_swap_duration" "3"
            "cast_range" "99999"
            "arrow_cost" "3"
        }
  }

  //=======================================
  // Atalanta: Last Spurt
  //=======================================
  "atalanta_last_spurt"
  {
    "BaseClass"						"ability_lua"
    "ScriptFile"					"abilities/atalanta/last_spurt"
    "MaxLevel"						"1"
    "AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_DONT_CANCEL_MOVEMENT | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING | DOTA_ABILITY_BEHAVIOR_HIDDEN"
    "AbilityTextureName"			"custom/atalanta_last_spurt"
    "AbilityCastAnimation"    "ACT_DOTA_ATTACK_EVENT"

    "AbilityCastPoint"				"0.0"
    "AbilityCooldown"				"25"
    "AbilityManaCost"				"0"
    
    "precache"
    {
      "particle"					"particles/units/heroes/hero_windrunner/windrunner_windrun.vpcf"
      "soundfile"					"soundevents/game_sounds_heroes/game_sounds_windrunner.vsndevts"
    }

    "AbilityValues"
        {
            "base_ms" "0"
            "ms_per_unit" "10"
            "duration" "7"
            "aoe" "700"
            "base_evade" "20"
            "evade_per_unit" "10"
        }
  }

  //=======================================
  // Atalanta: Priestess of the Hunt
  //=======================================
  "atalanta_priestess_of_the_hunt"
  {
    "BaseClass"						"ability_lua"
    "ScriptFile"					"abilities/atalanta/priestess_of_the_hunt"
    "MaxLevel"						"1"
    "AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET|DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
    "AbilityCooldown"     "0"
    "AbilityTextureName"			"custom/atalanta_priestess_of_the_hunt"
    
    "precache"
    {
    }

    "AbilityValues"
        {
            "arrows" "10"
            "bonus_damage" "10"
            "cost" "10"
        }
  }
  

  //===========================================
  // Atalanta: Tauropolos - Bow of Heaven (Buff)
  //===========================================

  //=======================================
  // Atalanta: Phoebus Catastrophe: Barrage
  //=======================================
  "atalanta_phoebus_catastrophe_barrage"
  {
    "BaseClass"						    "ability_lua"
    "ScriptFile"					    "abilities/atalanta/phoebus_catastrophe_barrage"
    "MaxLevel"						    "5"
    "LevelsBetweenUpgrades"		"2"
    "AbilityBehavior"				  "DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
    "AbilityTextureName"			"custom/atalanta_phoebus_catastrophe"
    "AbilityUnitDamageType"   "DAMAGE_TYPE_PHYSICAL"
    "AbilityCastPoint"				"0.8"
    "AbilityCooldown"				  "36"
    "AbilityManaCost"				  "800"

    "precache"
    {
      "particle"					"particles/econ/items/enchantress/enchantress_virgas/ench_impetus_virgas.vpcf"
      "particle"					"particles/econ/items/monkey_king/arcana/death/mk_spring_arcana_death_ground_impact.vpcf"
      "particle"					"particles/econ/items/rubick/rubick_force_gold_ambient/rubick_telekinesis_land_force_impact_rings_gold.vpcf"
      "particle"					"particles/econ/items/rubick/rubick_force_gold_ambient/rubick_telekinesis_land_force_impact_d_gold.vpcf"
      "particle"					"particles/custom/screen_green_splash.vpcf"
      "particle"					"particles/custom/atalanta/atalanta_barrage_marker.vpcf"
      "soundfile"					"soundevents/game_sounds_heroes/game_sounds_skywrath_mage.vsndevts"
      "soundfile"					"soundevents/game_sounds_heroes/game_sounds_mirana.vsndevts"
    }

    "AbilityValues"
        {
            "range" "2500"
            "aoe" "600"
            "arrow_aoe" "280"
            "arrows" "27 30 33 36 39"
            "arrows_cap" "80"
            "arrows_per_arrow" "1"
            "delay" "1.25"
            "cast_point" "0.8"
            "slow" "50"
            "slow_duration" "0.4"
            "arrows_damage_percentage" "40"
        }
  }

  //=======================================
  // Atalanta: Phoebus Catastrophe: Snipe
  //=======================================
  "atalanta_phoebus_catastrophe_snipe"
  {
    "BaseClass"						"ability_lua"
    "ScriptFile"					"abilities/atalanta/phoebus_catastrophe_snipe"
    "MaxLevel"						"1"
    "AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
    "AbilityTextureName"			   "custom/atalanta_phoebus_catastrophe"
    "AbilityUnitDamageType"       "DAMAGE_TYPE_PHYSICAL"
    "AbilityCastPoint"				    "1"
    "AbilityCooldown"				     "140"
    "AbilityManaCost"				     "300"

    "precache"
    {
      "particle"					"particles/econ/items/enchantress/enchantress_virgas/ench_impetus_virgas.vpcf"
      "particle"					"particles/econ/items/monkey_king/arcana/death/mk_spring_arcana_death_ground_impact.vpcf"
      "particle"					"particles/econ/items/rubick/rubick_force_gold_ambient/rubick_telekinesis_land_force_impact_rings_gold.vpcf"
      "particle"					"particles/econ/items/rubick/rubick_force_gold_ambient/rubick_telekinesis_land_force_impact_d_gold.vpcf"
      "particle"					"particles/custom/archer/archer_broken_phantasm/archer_broken_phantasm_crosshead.vpcf"
      "particle"					"particles/custom/screen_green_splash.vpcf"
      "particle"					"particles/custom/atalanta/atalanta_crosshair.vpcf"
      "soundfile"					"soundevents/game_sounds_heroes/game_sounds_skywrath_mage.vsndevts"
      "soundfile"					"soundevents/game_sounds_heroes/game_sounds_mirana.vsndevts"
    }

    "AbilityValues"
        {
            "range" "3000"
            "arrow_aoe" "200"
            "arrows" "10"
            "delay" "2.4"
            "arrows_damage_percentage" "50"
        }
  }

  //=======================================
  // Atalanta Attribute : Arrows of the Big Dipper
  //=======================================
  "atalanta_attribute_arrows_of_the_big_dipper"
  {
    // General		//------------------------------------------------------------------------------------------------------------
    "BaseClass"						"ability_lua"
    "ScriptFile"					"abilities/atalanta/attributes"
    "MaxLevel"						"1"
    "AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
    "AbilityTextureName"			"custom/atalanta_arrows_of_the_big_dipper"
    
    "AbilityCastPoint"				"0.0"
    "AbilityCooldown"				"9999"
    "AbilityManaCost"				"10"

    "precache"
    {
    }

    "AbilityValues"
        {
            "attribute_bonus_range" "100"
            "attribute_vision_radius" "150"
            "attribute_vision_duration" "2"
            "attribute_arrows_needed" "3"
            "attribute_range_per_agi" "3"
            "attribute_aoe_per_agi" "1"
            "conversion" "50"
        }
  }

  //=======================================
  // Atalanta Attribute : Hunter's Mark
  //=======================================
  "atalanta_attribute_hunters_mark"
  {
    // General		//------------------------------------------------------------------------------------------------------------
    "BaseClass"						"ability_lua"
    "ScriptFile"					"abilities/atalanta/attributes"
    "MaxLevel"						"1"
    "AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
    "AbilityTextureName"			"custom/atalanta_hunters_mark"
    
    "AbilityCastPoint"				"0.0"
    "AbilityCooldown"				"9999"
    "AbilityManaCost"				"9"

    "precache"
    {
    }

    "AbilityValues"
        {
            "bonus_duration" "2"
            "cooldown_reduction" "1"
            "slow_aoe" "1200"
            "slow_amount" "-35"
            "slow_duration" "3"
        }
  }

  //=======================================
  // Atalanta Attribute : Golden Apple
  //=======================================
  "atalanta_attribute_golden_apple"
  {
    // General		//------------------------------------------------------------------------------------------------------------
    "BaseClass"						"ability_lua"
    "ScriptFile"					"abilities/atalanta/attributes"
    "MaxLevel"						"1"
    "AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
    "AbilityTextureName"			"custom/atalanta_golden_apple"
    
    "AbilityCastPoint"				"0.0"
    "AbilityCooldown"				"9999"
    "AbilityManaCost"				"13"

    "precache"
    {
    }

    "AbilityValues"
        {
            "range" "2000"
            "lure_duration" "1.5"
            "aoe" "300"
            "attribute_swap_duration" "6"
            "attribute_stack_bonus" "2"
            "attribute_bonus_duration" "2"
        }
  }

  //=======================================
  // Atalanta Attribute : Crossing Arcadia Plus
  //=======================================
  "atalanta_attribute_crossing_arcadia_plus"
  {
    // General		//------------------------------------------------------------------------------------------------------------
    "BaseClass"						"ability_lua"
    "ScriptFile"					"abilities/atalanta/attributes"
    "MaxLevel"						"1"
    "AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
    "AbilityTextureName"			"custom/atalanta_crossing_arcadia"
    
    "AbilityCastPoint"				"0.0"
    "AbilityCooldown"				"9999"
    "AbilityManaCost"				"10"

    "precache"
    {
    }

    "AbilityValues"
        {
            "extra_arrows" "2"
            "base_ms" "0"
            "duration" "7"
            "bonus_range" "300"
        }
  }
  //=======================================
  // Atalanta Attribute : Bow of Heaven
  //=======================================

  //=======================================
  // Atalanta: Phoebus Catastrophe Proxy
  //=======================================
  "atalanta_phoebus_catastrophe_proxy"
  {
    "BaseClass"           "ability_lua"
    "ScriptFile"          "abilities/atalanta/phoebus_catastrophe_proxy"
    "MaxLevel"            "1"
    "AbilityBehavior"       "DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
    "AbilityTextureName"      "custom/atalanta_phoebus_catastrophe"
    
    "AbilityCastPoint"        "1.4"
    "AbilityCooldown"       "140"
    "AbilityManaCost"       "300"

    "AbilityValues"
        {
            "range" "3000"
            "aoe" "600"
            "arrow_aoe" "200"
            "barrage_arrows" "60"
            "snipe_arrows" "10"
            "delay" "2.4"
            "cast_time" "1.4"
            "arrows_damage_percentage" "50"
        }
  }
  //=======================================
  // Atalanta: Big Dipper
  //=======================================
  "atalanta_big_dipper"
  {
    "BaseClass"               "ability_lua"
    "ScriptFile"              "abilities/atalanta/atalanta_big_dipper"
    "MaxLevel"            "5"
    "AbilityTextureName"          "custom/atalanta_tauropolos"
    "AbilityBehavior"           "DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_CHANNELLED | DOTA_ABILITY_BEHAVIOR_AOE"
    "AbilityUnitTargetTeam"         "DOTA_UNIT_TARGET_TEAM_ENEMY"
    "AbilityUnitTargetType"         "DOTA_UNIT_TARGET_HERO"
    "AbilityCastAnimation"    "ACT_DOTA_CAST_ABILITY_1"
    "AbilityUnitTargetFlags"        "DOTA_UNIT_TARGET_FLAG_NOT_MAGIC_IMMUNE_ALLIES"
    "AbilityUnitDamageType"         "DAMAGE_TYPE_MAGICAL"

    "LevelsBetweenUpgrades"     "2"

    "AbilityCastPoint"            "0.0"
    "AbilityChannelTime"          "0.75"
    "AbilityCooldown"           "26"
    "AbilityManaCost"           "400"
    "AbilityCastRange"            "3000"

    "precache"
    {
      "particle"              "particles/heroes/anime_hero_tanya/tanya_elinium_projectile.vpcf"
      "particle"              "particles/items3_fx/silver_edge_slow.vpcf"
      "particle"              "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/maiden_crystal_nova_cowlofice.vpcf"
      "particle"              "particles/items4_fx/meteor_hammer_cast.vpcf"
      "soundfile"             "soundevents/heroes/anime_hero_tanya.vsndevts"
    }

    "AbilityValues"
        {
            "width" "128"
            "speed" "2400"
            "radius" "350"
            "damage" "600 750 900 1050 1200"
            "duration" "3.5"
            "slow" "-40"
            "range" "3000"
        }
  }
}