"DOTAAbilities"
{
	//===================================================
	// Gilles De Rais : Rlyeh Text - Hysteria
	//===================================================
	"gilles_hysteria"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilles/gilles_hysteria"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/gilles/gilles_hysteria"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"

		"AnimationPlaybackRate" 		"1.5"
		"AOERadius"						"%radius"		
		
		"precache"
		{
			"particle"		"particles/units/heroes/hero_life_stealer/life_stealer_infested_unit.vpcf"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"900"
		"AbilityCastPoint"				"0.3"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"14.0"

		
		"AbilityValues"
        {
            "mana_cost" "20"
            "attack_speed" "100"
            "damage" "30"
            "duration" "2.0"
            "disarm_duration" "1 1.25 1.5 1.75 2"
        }
	}
}