"DOTAAbilities"
{
	//===================================================
	// Gilles De Rais : Rlyeh Text - Misery
	//===================================================
	"gilles_misery"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilles/gilles_misery"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityTextureName"			"custom/gilles/gilles_misery"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"1.5"	
		
		"precache"
		{
			"particle"		"particles/econ/items/warlock/warlock_staff_hellborn/warlock_upheaval_hellborn_debuff"
			"particle"		"particles/units/heroes/hero_enigma/enigma_malefice.vpcf"
			"particle"		 "particles/status_fx/status_effect_enigma_malefice.vpcf"

		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"900"
		"AbilityCastPoint"				"0.25"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"14.0"

		
		"AbilityValues"
        {
            "mana_cost" "20"
            "duration" "2"
            "damage" "80 100 120 140 160"
            "microcd" "1"
            "stun_duration" "0.3"
        }
	}
}