"DOTAAbilities"
{
	//===================================================
	// Gilles De Rais : Summon Oceanic Demon
	//===================================================
	"gilles_summon_jellyfish"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilles/gilles_summon_jellyfish"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/gille_summon_demon"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1.0"
		"AOERadius"						"%radius"		
		
		"precache"
		{
			"model"					"models/gilles/gilles_starfish.vmdl"
			"particle"				"particles/custom/gilles/gilles_summon_jellyfish.vpcf"
			"particle"				"particles/custom/gilles/gilles_jellyfish_explode_blood.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_nevermore.vsndevts"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_necrolyte.vsndevts"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"700"
		"AbilityCastPoint"				"0.1"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"7"

		
		"AbilityValues"
        {
            "mana_cost" "10"
            "radius" "300"
            "summon_count" "3"
            "duration" "2.0"
            "damage" "60 75 90 105 120"
            "slow_pct" "0"
        }
	}

	"gilles_jellyfish_passive"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilles/gilles_summon_jellyfish"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_HIDDEN | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityTextureName"			"custom/gille_summon_demon"
		"MaxLevel"						"1"
		
		"precache"
		{
			"model"					"models/gilles/gilles_starfish.vmdl"
			"particle"				"particles/custom/gilles/gilles_summon_jellyfish.vpcf"
			"particle"				"particles/econ/items/bloodseeker/bloodseeker_eztzhok_weapon/bloodseeker_bloodbath_eztzhok.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_nevermore.vsndevts"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_necrolyte.vsndevts"
		}

		"AbilityValues"
        {
        }
		
		"OnSpelLStart"
		{
		}
	}

}