"DOTAAbilities"
{
	//===================================================
	// Gilles De Rais : Abyssal Contract
	//===================================================
	"gilles_abyssal_contract"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilles/gilles_abyssal_contract"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityTextureName"			"custom/gille_abyssal_contract"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_4"
		"AbilityType"					"ABILITY_TYPE_ULTIMATE"
		"AnimationPlaybackRate" 		"1.0"
		"AOERadius"						"%radius"

		"LinkedAbilities"				"gille_tentacle_hook gille_tentacle_wrap gille_subterranean_skewer gille_gigantic_horror_passive"
		
		"precache"
		{
			"model"			"models/gilles/gilles_squid.vmdl"
			"model"			"models/zc/tidehuntertentacle_reference.vmdl"
			"particle"		"particles/custom/gilles/abyssal_contract_smoke.vcpf"
			"particle"		"particles/custom/gilles/abyssal_contract_sigil.vpcf"
			"particle"		"particles/custom/gilles/abyssal_contract_pulse.vpcf"
			"particle"		"particles/custom/gilles/abyssal_contract_tentacles.vpcf"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_pudge.vsndevts"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_spectre.vsndevts"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_centaur.vsndevts"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_magnataur.vsndevts"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_treant.vsndevts"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_warlock.vsndevts"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_tidehunter.vsndevts"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_lion.vsndevts"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_enigma.vsndevts"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"700"
		"AbilityCastPoint"				"0.2"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"45.0"

		
		"AbilityValues"
        {
            "summon_delay" "3"
            "radius" "1000"
            "damage" "500 625 750 875 1000"
            "max_health" "750 937.5 1125 1312.5 1500"
            "attack_damage" "150 187.25 225 262.75 300"
            "stun_duration"				"1"
        }
	}

	//=================================================================================================================
	// Gilles De Rais : Tentacle Hook
	//=================================================================================================================
	"gille_tentacle_hook"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_BOTH"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityTextureName"			"custom/zc_tentacle_hook"
		"AbilityCastAnimation" 			"ACT_DOTA_ATTACK2"
		"AnimationPlaybackRate" 		"2.0"
		"AbilityCastRange"				"%range"
		"AbilityCastPoint"				"0.3"
		"AbilityCooldown"				"10.0"

	    "precache"
	    {
	    }		
		"AbilityValues"
        {
            "range" "1000"
        }
		"OnSpellStart"
		{
            "RunScript"
            {
 			 	"ScriptFile"	"gille_ability"
			 	"Function"		"OnTentacleHookStart"   
			 	"Target"		"POINT"        	
            }		
			"LinearProjectile"
			{
				"Target"      	"POINT"
			    "EffectName"  	""
			    "MoveSpeed"   	"1800"
			    "StartRadius"   "150"
			    "StartPosition" "attach_origin"
			    "EndRadius"     "150"
			    "FixedDistance" "%range"
			    "TargetTeams"   "DOTA_UNIT_TARGET_TEAM_BOTH"
			    "TargetTypes"   "DOTA_UNIT_TARGET_HERO"
			    "TargetFlags"   "DOTA_UNIT_TARGET_FLAG_NONE"
			    "HasFrontalCone"  "0"
			    "ProvidesVision" "0"
			}
		}
		
		"OnProjectileHitUnit"
		{
			"DeleteOnHit"			"false"
            "RunScript"
            {
 			 	"ScriptFile"	"gille_ability"
			 	"Function"		"OnTentacleHookHit"           	
            }
		}
	}


	//=================================================================================================================
	// Gilles De Rais : Tentacle Wrap
	//=================================================================================================================
	"gille_tentacle_wrap"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/gilles/gille_tentacle_wrap"
		"MaxLevel"						"5"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityTextureName"			"custom/zc_tentacle_wrap"
		"AbilityCastRange"				"1000"
		"AbilityCastPoint"				"0.1"
		"AbilityCooldown"				"10.0"
		"AbilityCastAnimation" 			"ACT_DOTA_ATTACK2"
		"AnimationPlaybackRate" 		"1.0"
		"precache"
		{
			"particle"		"particles/units/heroes/hero_tidehunter/tidehunter_spell_ravage_hit_wrap.vpcf"

		}

		"AbilityValues"
        {
            "root_duration" "1.5 1.75 2.0 2.25 2.5"
        }
	}

	//===================================================
	// Gilles De Rais : Subterranean Skewer
	//===================================================
	"gille_subterranean_skewer"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/gilles/gille_subterranean_skewer"
		"MaxLevel"						"5"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityTextureName"			"tidehunter_ravage"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1.0"
		
		"precache"
		{
			"particle"		"particles/units/heroes/hero_tidehunter/tidehunter_spell_ravage_hit.vpcf"

		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"1000"
		"AbilityCooldown"				"25"
		"AbilityCastPoint"				"0.3"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"29.0"

		
		"AbilityValues"
        {
            "range" "1000"
            "damage" "300 400 500 600 700"
            "stun_duration" "1.1 1.2 1.3 1.4 1.5"
        }

	}

	//===================================================
	// Gilles De Rais : Integrate
	//===================================================
	"gilles_squidlordz_integrate_data" 
	{
	    "BaseClass"    			"ability_lua"
	    "ScriptFile"    			"abilities/gilles/gilles_squidlordz_integrate_data"
	    "MaxLevel"				 "1"
	    "AbilityTextureName" 	"custom/gille_integrate"
	    "AbilityBehavior"		"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
	    "AbilityCooldown"		"2"

	    "precache"
	    {
	    }

		"AbilityValues"
        {
            "movespeed" "150"
            "attackspeed" "150"
            "health" "500"
        }


	}

	//================================================
	// Gilles De Rais : Gigantic Horror Passive
	//================================================
	"gille_gigantic_horror_passive"
	{
		"AbilityBehavior" 				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"BaseClass" 					"ability_lua"
		"ScriptFile" 					"abilities/gilles/gille_gigantic_horror_passive"
		"AbilityTextureName"            "undying_decay"
		"MaxLevel"                      "5"
		"precache"
		{
			
		}

		"AbilityValues"
        {
            "health_regen" "10"
            "damage_threshold" "300 400 500 600 700"
            "additional_damage" "130"
        }

	}

	//========================================
	// SquidLordz Contaminate
	//========================================
	"gilles_squidlordz_contaminate"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilles/gilles_squidlordz_contaminate"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/gille_contaminate"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_2"
		"AnimationPlaybackRate" 		"2.0"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"

		"precache"
		{
			"particle"	"particles/custom/gilles/squidlord_contaminate.vpcf"
			"particle"	"particles/custom/gilles/contaminate_debuff.vpcf"
			"particle"	"particles/units/heroes/hero_pugna/pugna_netherblast.vpcf"
			"soundfile"	"soundevents/game_sounds_heroes/game_sounds_shadow_demon.vsndevts"
			"soundfile"	"soundevents/game_sounds_heroes/game_sounds_venomancer.vsndevts"
		}

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"30.0"
		"AbilityCastPoint"				"0.35"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"0"

		
		"AbilityValues"
        {
            "radius" "800"
            "damage" "700 950 1200 1450 1700"
            "duration" "5"
        }
	}
}