#base "gilles_prelati_spellbook.kv"
#base "gilles_summon_jellyfish.kv"
#base "gilles_rlyeh_text.kv"
#base "gilles_cthulhu_favour.kv"
#base "gilles_abyssal_contract.kv"

"DOTAAbilities"
{	

	//=================================================================================================================
	// Combo activator
	//=================================================================================================================
	"gilles_combo_activator"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilles/gilles_combo_activator"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET|DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityTextureName"			"custom/gille_larret_de_mort"
		"MaxLevel"						"1"
		"AbilityCooldown"				"10"
		
		"AbilityValues"
        {

        }
	}


	//===================================================
	// Gilles De Rais : L'Arret de Mort (COMBO NEW)
	//===================================================
	"gilles_combo_new"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilles/gilles_combo_new"
		"MaxLevel"						"1"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/gille_larret_de_mort"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_4"
		"AnimationPlaybackRate" 		"1.0"
		"AOERadius"						"%radius"		
		
		"precache"
		{	
			"particle"		"particles/gilles/new_combo/gilles_new_combo_1.vpcf"
			"particle"		"particles/gilles/new_combo/gilles_new_combo_2.vpcf"
			"particle"		"particles/gilles/new_combo/kraken_model_1.vpcf"
			"particle"		"particles/gilles/new_combo/gilles_combo_kraken_2.vpcf"
			"particle"		"particles/gilles/new_combo/gilles_new_combo_kraken_blood_kill.vpcf"
			"particle"		"particles/zlodemon/zlodemon_basic_circle.vpcf"
			"particle"		"particles/custom/screen_scarlet_splash.vpcf"
			"particle"		"particles/units/heroes/hero_bloodseeker/bloodseeker_rupture.vpcf"
			//"particle"		"particles/gilles/new_combo/blood_rain.vpcf"

		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"1000"
		"AbilityCastPoint"				"0.5"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"120"

		
		"AbilityValues"
        {
            "radius" "1000"
            "knockup_duration" "0.5"
            "cast_delay" "2"
            "initial_damage" "1250"
            "explosion_damage" "1250"
            "blood_duration" "8"
            "damage_per_sec" "5"
            "manacost" "80"
            "slow"		"90"
        }
		
	
		
	}	
	//=======================================
	// Gilles De Rais Attribute : Eye for Art
	//=======================================
	"gilles_eye_for_art_attribute"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilles/gilles_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/gille_attribute_eye_for_art"
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"9"

		"precache"
		{
		}

		"AbilityValues"
        {
            "radius" "1500"
            "duration" "2.0"
        }
	}

	//=================================================================================================================
	// Eye for Art Passive
	//=================================================================================================================
	"gilles_eye_for_art_passive"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilles/gilles_eye_for_art"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE|DOTA_ABILITY_BEHAVIOR_HIDDEN|DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityTextureName"			"custom/gille_attribute_eye_for_art"
		"MaxLevel"						"1"
		"AbilityCooldown"				"10"
		"precache"
		{
			"particle"					"particles/zlodemon/zlodemon_overhead_eye.vpcf"
		}
		
		"AbilityValues"
        {
            "radius" "1500"
            "duration" "2"
        }
	}

	//=======================================
	// Gilles De Rais Attribute : Outer God Favour
	//=======================================
	"gilles_outer_god_attribute"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilles/gilles_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/gilles/gilles_outer_god_favour"
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"12"

		"precache"
		{
		}

		"AbilityValues"
        {
            "regen_pct" "10"
            "block_duration" "5.0"
        }
	}

	//=======================================
	// Gilles De Rais Attribute : Demonic Horde
	//=======================================
	"gilles_demonic_horde_attribute"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilles/gilles_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/gilles/gilles_demonic_horde"
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"10"

		"precache"
		{
		}

		"AbilityValues"
        {
            "summon_count" "6"
            "duration" "15.0"
        }
	}

	//=======================================
	// Gilles De Rais Attribute : Sunken City
	//=======================================
	"gilles_sunken_city_attribute"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilles/gilles_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/gilles/gilles_sunken_city"
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"13"

		"precache"
		{
		}

		"AbilityValues"
        {
            "root_dur" "3.0"
            "stun_dur" "1"
            "end_damage" "400"
        }
	}

	//=======================================
	// Gilles De Rais Attribute : Abyssal Connection
	//=======================================
	"gilles_abyssal_connection_attribute"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilles/gilles_attributes"
		"MaxLevel"						"5"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/gilles/gilles_abyssal_connection"
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"14"

		"LinkedAbilities"				"gilles_squidlordz_integrate_data gilles_squidlordz_contaminate"

		"precache"
		{
		}

		"AbilityValues"
        {
            "radius" "800"
            "damage" "700 900 1100 1300 1500"
            "duration" "10.0"
            "movespeed" "150"
            "attackspeed" "50"
            "health" "500"
        }
	}


	//===================================================
	// Gilles De Rais : L'Arret de Mort
	//===================================================
	"gille_larret_de_mort"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/gille_larret_de_mort"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"1.0"
		"AOERadius"						"%radius"		
		
		"precache"
		{	
			"particle"		"particles/units/heroes/hero_warlock/warlock_upheaval.vpcf"
			"particle"		"particles/units/heroes/hero_phoenix/phoenix_supernova_reborn_shockwave.vpcf"
			"particle"		"particles/custom/screen_scarlet_splash.vpcf"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"1000"
		"AbilityCastPoint"				"0.3"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"150.0"

		
		"AbilityValues"
        {
            "radius" "1000"
            "knockup_duration" "0.5"
            "cast_delay" "1.0"
            "initial_damage" "50"
            "blood_duration" "12.0"
            "damage_per_sec" "10"
        }
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"gille_ability"
				"Function"		"OnGilleComboStart"
				"Damage"		"%initial_damage"
				"KnockupDuration"	"%knockup_duration"
			}
		}
		
		"Modifiers"
		{
			"modifier_larret_de_mort_cooldown"
			{
				"IsDebuff"	"1"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_gille_combo"
			{
		        "EffectName"    "particles/units/heroes/hero_bloodseeker/bloodseeker_rupture.vpcf"
		        "EffectAttachType"  "follow_origin"
				"Duration"		"12"
				"IsDebuff"		"1"
				"ThinkInterval"		"1.0"
				"OnIntervalThink"
				{
					"RunScript"
					{
						"ScriptFile"	"gille_ability"
						"Function"		"OnGilleComboThink"
						"DPS"			"%damage_per_sec"
					}
				}
				"OnRespawn"
				{
					"RunScript"
					{
						"ScriptFile"	"gille_ability"
						"Function"		"RemoveAllPoisons"
					}
				}
			}
			"modifier_gigantic_horror_freeze"
			{
				"EffectName"				"particles/units/heroes/hero_pugna/pugna_decrepify.vpcf"	
				"EffectAttachType"			"follow_overhead"
				"Duration"		"1.5"
				"OverrideAnimation"		"ACT_DOTA_CAST_ABILITY_3"
				"Properties"
				{
					"MODIFIER_PROPERTY_OVERRIDE_ANIMATION_RATE"		"0.5"
				}
				"States"
				{
					"MODIFIER_STATE_STUNNED"		"MODIFIER_STATE_VALUE_ENABLED"
					"MODIFIER_STATE_UNSELECTABLE" "MODIFIER_STATE_VALUE_ENABLED"
					"MODIFIER_STATE_INVULNERABLE"    "MODIFIER_STATE_VALUE_ENABLED"
					"MODIFIER_STATE_NO_HEALTH_BAR"	"MODIFIER_STATE_VALUE_ENABLED"
					"MODIFIER_STATE_COMMAND_RESTRICTED" "MODIFIER_STATE_VALUE_ENABLED"
				}
			}
		}
	}	

	//=======================================
	// Gilles De Rais Attribute : Improve Black Magic
	//=======================================
	"gille_attribute_improve_black_magic"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/gille_attribute_improve_black_magic"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"16"

		"precache"
		{
		}

		"AbilityValues"
        {
            "curse_damage" "400"
            "curse_duration" "4.0"
            "torment_multiplier" "15.0"
        }
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"gille_ability"
				"Function"		"OnBlackMagicImproved"
			}
		}
	}

	//=======================================
	// Gilles De Rais Attribute : Mental Pollution
	//=======================================
	"gille_attribute_mental_pollution"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/gille_attribute_mental_pollution"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"11"

		"precache"
		{
		}

		"AbilityValues"
        {
            "max_madness" "15"
            "corpse_cooldown" "2.0"
        }
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"gille_ability"
				"Function"		"OnMentalPollutionAcquired"
			}
		}
	}

	//=======================================
	// Gilles De Rais Attribute : Abyssal Connection
	//=======================================
	"gille_attribute_abyssal_connection"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/gille_attribute_abyssal_connection"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"13"

		"precache"
		{
		}

		"AbilityValues"
        {
            "bonus_damage" "200"
            "bonus_radius" "200"
            "high_damage" "110"
        }
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"gille_ability"
				"Function"		"OnAbyssConnectionAcquired"
			}
		}
	}

	//=======================================
	// Gilles De Rais Attribute : Abyssal Connection - Tier 2
	//=======================================
	"gille_attribute_abyssal_connection_2"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/gille_attribute_abyssal_connection_2"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"13"

		"precache"
		{
		}

		"AbilityValues"
        {
            "bonus_health" "30"
            "bonus_aspd" "50"
        }
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"gille_ability"
				"Function"		"OnAbyssConnection2Acquired"
			}
		}
	}

}