"DOTAAbilities"
{
	//===================================================
	// Gilles De Rais : Cthulhu Favour
	//===================================================
	"gilles_cthulhu_favour"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilles/gilles_cthulhu_favour"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityTextureName"			"custom/gilles/gilles_cthulhu"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_2"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PHYSICAL"
		"AnimationPlaybackRate" 		"1.5"
		"AOERadius"						"%radius"		
		
		"precache"
		{
			"particle"		"particles/custom/gilles/cthulhu_favour_cast.vpcf"
			"particle"		"particles/custom/gilles/cthulhu_favour_circle.vpcf"
			"particle"		"particles/custom/gilles/cthulhu_favour_splash.vpcf"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"750"
		"AbilityCastPoint"				"0.2"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"27.0"

		
		"AbilityValues"
        {
            "radius" "600"
            "duration" "5"
            //"spawn_damage" "40 50 60 70 80"
            "prock_damage" "30 37.5 45 52.5 60"
            "spawn_interval" "0.2"
            "mana_cost" "40"
            "range" "750"
            "root_duration" "0.5"
            "lock_duration" "0.5"
        }
	}

	
}