"DOTAAbilities"
{
	//===================================================
	// Gilles De Rais : Rlyeh Text - Torment
	//===================================================
	"gilles_torment"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilles/gilles_torment"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/gilles/gilles_torment"
		"AbilityCastAnimation" 			"ACT_DOTA_ATTACK2"
		"AnimationPlaybackRate" 		"2.25"
		"AOERadius"						"%radius"		
		
		"precache"
		{
			"particle"		"particles/custom/gilles/torment_debuffhellborn_debuff.vpcf"
			"particle"		"particles/custom/gilles/torment_cast.vpcf"
			"soundfile"		"soundevents/hero_zc.vsndevts"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"990"
		"AbilityCastPoint"				"0.23"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"12.6"

		
		"AbilityValues"
        {
            "mana_cost" "20"
            "radius" "330"
            "damage" "154 193 231 270 308"
            "distance_damage" "33.0 41.2 49.5 57.8 66.0"
            "duration" "4.4"
        }
	}
}