"DOTAAbilities"
{
	//===================================================
	// Gilles De Rais : Rlyeh Text - Smother
	//===================================================
	"gilles_smother"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilles/gilles_smother"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/gilles/gilles_smother"
		"AbilityCastAnimation" 			"ACT_DOTA_ATTACK"
		"AnimationPlaybackRate" 		"2.25"
		"AOERadius"						"%radius"		
		
		"precache"
		{
			"particle"		"particles/custom/gilles/smother_ground_fire.vpcf"
			"particle"		"particles/custom/gilles/smother_cast_warp.vpcf"
			"particle"		"particles/custom/gilles/smother_debuff.vpcf"
			"particle"		"particles/custom/gilles/smother_explode.vpcf"
			"soundfile"		"soundevents/hero_zc.vsndevts"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"900"
		"AbilityCastPoint"				"0.25"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"14.0"

		
		"AbilityValues"
        {
            "mana_cost" "20"
            "radius" "300"
            "damage" "150 187.5 225 267.5 300"
            "explosion_damage" "200 250 300 350 400"
            "duration" "4.0"
            "stun_duration" "0.5"
            "healres_duration" "2"
            "int_damage" "1"
        }
	}
}