"DOTAAbilities"
{

	//=======================================
	// Ozy ЧАКРАМ (Q)
	//=======================================
	"ozy_light_chacram"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_light_chacram"
		"MaxLevel"						"5"
		"LevelsBetweenUpgrades"				"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityTextureName"			"custom/ozy/ozy_chacram"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1"

		"AbilityCooldown"				"10"
		"AbilityCastPoint"					"0.2"
		"AbilityCastRange"				"1000"
		"AbilityManaCost"					"100"

		"LinkedAbilities"					"ozy_light_chacram_recast"
		"LinkedAbilitiesRow"				"2"

		"precache"
		{
			"particle"				"particles/ozy/ozy_chacram.vpcf"
			"particle"				"particles/ozy/chacram_unit_hold.vpcf"
			"particle"				"particles/zlodemon/zlodemon_basic_circle.vpcf"

		}

		"AbilityValues"
        {
            "radius" 				"128"
            "distance"				"1100"
            "duration" 				"1 1.1 1.2 1.3 1.4"
            "damage" 				"100 125 150 175 200"
            "jopa_recast_duration" 		"1"
        }
	}
	//=======================================
	// Ozy ЧАКРАМ RECAST (Q-Q)
	//=======================================
	"ozy_light_chacram_recast"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_light_chacram_recast"
		"MaxLevel"						"5"
		"LevelsBetweenUpgrades"				"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/ozy/ozy_chacram"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1"

		"AbilityCooldown"				"1"
		"AbilityCastPoint"					"0"
		"AbilityCastRange"				"9999"
		"AbilityManaCost"					"0"


		"precache"
		{
			"particle"				"particles/ozy/ozy_chacram.vpcf"
			"particle"				"particles/ozy/ozy_chacram_hook.vpcf"
		}

		"AbilityValues"
        {
            "radius" 				"128"
            "distance"				"500"
            "duration" 				"0.4 0.5 0.6 0.7 0.8"
            "damage" 				"220 275 330 385 440"
        }
	}

	//=======================================
	// Ozy protection (W)
	//=======================================
	"ozy_protection_of_sun_god"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_protection_of_sun_god"
		"MaxLevel"						"5"
		"LevelsBetweenUpgrades"				"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT| DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityTextureName"			"custom/ozy/ozy_flash_barrier"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_FRIENDLY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_HERO"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_2"
		"AnimationPlaybackRate" 		"1"

		"AbilityCooldown"				"12"
		"AbilityCastPoint"					"0.2"
		"AbilityCastRange"				"1000"
		"AbilityManaCost"					"200"


		"precache"
		{
			"particle"				"particles/ozy/sun_god_barrier.vpcf"
			"particle"				"particles/ozy/ozy_blind.vpcf"
			"particle"				"particles/ozy/ozy_flash_barrier.vpcf"

		}

		"AbilityValues"
        {
            "radius" 				"500"
            "duration" 				"6"
            "barrier" 				"200 250 300 350 400"
            "damage" 				"100"
            "blind" 				"100"
            "slow_duration" 		"2"
            "slow_percentage" 		"15"
        }
	}

	//=======================================
	// Ozy PILLAR (E)
	//=======================================
	"ozy_light_pillar"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_light_pillar"
		"MaxLevel"						"5"
		"LevelsBetweenUpgrades"				"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityTextureName"			"custom/ozy/light_pillar"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"1"

		"AbilityCooldown"				"18"
		"AbilityCastPoint"					"0.2"
		"AbilityCastRange"				"1000"
		"AbilityManaCost"				"400"


		"precache"
		{
			"particle"				"particles/ozy/ozy_light_pillar_runes.vpcf"
			"particle"				"particles/ozy/ozy_light_pillar_endcap.vpcf"

		}

		"AbilityValues"
        {
            "radius" 				"350"
            "delay"					"1"
            "stun_duration" 		"0.8"
            "damage" 				"500 625 750 875 1000"
            "damage_per_int" 		"1.5"
        }
	}




	//=======================================
	// Ozy mystic eyes (F)
	//=======================================
	"ozy_mystic_eyes"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_mystic_eyes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET| DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityTextureName"			"custom/ozy/mystic_eyes"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_HERO"
		"AbilityCooldown"				"15"
		"AbilityManaCost"				"0"
		"AbilityCastPoint"				"0"


		"precache"
		{
			"particle"				"particles/zlodemon/immunity_sphere_buff_sun.vpcf"
			"particle"				"particles/ozy/ozy_mystic_eyes_target.vpcf"


		}

		"AbilityValues"
        {
            "duration" 				"1.5"
            "stun_duration" 		"1"
        }
	}

	//=====================================
	// 
	//=====================================
	"ozy_spawn_boat"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/ozy/ozy_spawn_boat"
		"AbilityTextureName"				"custom/ozy/ozy_boat"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"MaxLevel"							"2"
		"LevelsBetweenUpgrades" 			"26"
		"AbilityCooldown"				    "0"
		"AbilityManaCost"					"0"
		"AbilityCastPoint"					"0"
		"AbilityCastRange"					"1000"
		"LinkedAbilities"				"ozy_boat_anchor ozy_boat_beam ozy_boat_sunstrike ozy_move_boat ozy_teleport_boat ozy_boat_orbital_laser"


		"precache"
		{
			"particle"		"particles/ozy/piramid/ozy_piramid_passive_effect.vpcf"
			"particle"		"particles/ui_mouseactions/range_finder_cone.vpcf"
			"particle"		"particles/ozy/boat/boat_marker.vpcf"


			
		}
		"AbilityValues"
		{
			"mana_regen_max"			"100 200"
			"mana_regen_min"			"25 50"
			"mana_regen_distance"		"1500"
		}
	}
	//=====================================
	//  [[[BOAT]]] ANCHOR (Q)
	//=====================================
	"ozy_boat_anchor"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/ozy/ozy_boat_anchor"
		"AbilityTextureName"				"custom/ozy/ozy_boat_anchor"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT |DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"MaxLevel"							"1"
		"AbilityCooldown"				    "10"
		"AbilityManaCost"					"100"
		"AbilityCastPoint"					"0"
		"AbilityCastRange"					"1300"
		"precache"
		{
			"particle"		"particles/ozy/boat/ozy_boat_anchor_indicator.vpcf"
			"particle"		"particles/ozy/boat/ozy_boat_anchor_impact_jopa2.vpcf"
		}


		"AbilityValues"
		{
			"damage"							"350"
			"damage_per_level"					"10"
			"live_duration"						"10"
			"hit_radius"						"300"
			"aura_radius"						"400"
			"slow"								"20"
			"cast_range"								"1300"
		}
	}
	//=====================================
	// [[[BOAT]]] BEAM (W)
	//=====================================
	"ozy_boat_beam"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/ozy/ozy_boat_beam"
		"AbilityTextureName"				"custom/ozy/ozy_boat_beam"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT |DOTA_ABILITY_BEHAVIOR_VECTOR_TARGETING | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"MaxLevel"							"1"
		"AbilityCooldown"				    "10"
		"AbilityManaCost"					"200"
		"AbilityCastPoint"					"0"
		"AbilityCastRange"					"1300"

		"precache"
		{
			"particle"		"particles/ozy/boat/ozy_boat_laser_linear.vpcf"	
			"particle"		"particles/karna/brahmastra_laser/ground_burn.vpcf"	
		}


		"AbilityValues"
		{
			"damage"							"400"
			"damage_per_level"					"10"
			"max_distance"						"1200"
			"width"								"200"
			"lock_duration"						"1.5"
			"burn_damage"						"250"
			"burn_damage_per_level"				"10"
		}
	}
	//=====================================
	//[[[BOAT]]] SUNSTRIKES (E) 
	//=====================================
	"ozy_boat_sunstrike"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/ozy/ozy_boat_sunstrike"
		"AbilityTextureName"				"custom/ozy/light_pillar"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT  | DOTA_ABILITY_BEHAVIOR_VECTOR_TARGETING|DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"MaxLevel"							"1"
		"AbilityCooldown"				    "10"
		"AbilityManaCost"					"400"
		"AbilityCastPoint"					"0"
		"AbilityCastRange"					"1300"

		"precache"
		{
			"particle"				"particles/ozy/ozy_light_pillar_runes.vpcf"
			"particle"				"particles/ozy/ozy_light_pillar_endcap.vpcf"
		}
		"AbilityValues"
		{
			"base_damage"							"500 700"
			"damage_per_level"						"10 15"
			"max_distance"							"1900"
			"radius" 				"350"
            "delay"					"1"
            "delay_between_strikes"	"0.5"
            "stun_duration" 		"0.8"
		}
	}
	//=====================================
	// 
	//=====================================
	"ozy_move_boat"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/ozy/ozy_move_boat"
		"AbilityTextureName"				"custom/ozy/ozy_boat_move"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"MaxLevel"							"1"
		"AbilityCooldown"				    "0.5"
		"AbilityManaCost"					"0"
		"AbilityCastRange"					"9999"
		"AbilityCastPoint"					"0"


		"AbilityValues"
		{
			"speed"							"500"
			"max_distance"							"1500"
		}
	}

	//=====================================
	// 
	//=====================================
	"ozy_teleport_boat"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/ozy/ozy_teleport_boat"
		"AbilityTextureName"				"custom/ozy/ozy_boat"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_CHANNELLED"
		"MaxLevel"							"1"
		"AbilityCooldown"				    "30"
		"AbilityManaCost"					"0"
		"AbilityCastRange"					"99999"
		"AbilityChannelTime"			"3"
		"AbilityCastPoint"					"0"


		"precache"
		{
			"particle"  "particles/units/heroes/hero_keeper_of_the_light/keeper_of_the_light_recall.vpcf"
			
		}
		"AbilityValues"
		{
			"delay"							"3"
			"max_distance"					"1500"
			"minimum_damage"				"400"
		}
	}

	//=======================================
	// Ozy [[BOAT]] ORBITAL (R)
	//=======================================
	"ozy_boat_orbital_laser"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_boat_orbital_laser"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE|DOTA_ABILITY_BEHAVIOR_CHANNELLED"
		"AbilityTextureName"			"custom/ozy/ozy_boat_laser"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"AbilityCooldown"				"20"
		"AbilityCastPoint"					"0"
		"AbilityCastRange"				"1300"
		"AbilityManaCost"				"0"
		"AbilityChannelTime"			"10"


		"precache"
		{
			"particle"				"particles/ozy/boat/boat_orbital_laser.vpcf"
			"particle"				"particles/karna/karna_buff_burn.vpcf"

		}

		"AbilityValues"
        {
            "radius" 									"350"
            "damage_per_second" 						"200"
            "damage_per_second_per_level" 				"10"
            "mana_drain_per_second" 					"250 200"
            "mana_drain_increase_per_second" 			"10"
            "damage_per_second_increase" 				"200"
            "damage_per_second_increase_per_level" 		"10"
            "stacks_duration"							"0.5"
            "move_speed"								"300"
        }
	}

	//=======================================
	// Ozy [[BOAT]] ORBITAL MOVEMENT (R-R)
	//=======================================
	"ozy_boat_orbital_laser_move"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_boat_orbital_laser_move"
		"MaxLevel"						"5"
		"LevelsBetweenUpgrades"				"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT|DOTA_ABILITY_BEHAVIOR_IMMEDIATE|DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/ozy/ozy_boat_laser"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"1"

		"AbilityCooldown"				"0"
		"AbilityCastPoint"					"0"
		"AbilityCastRange"				"99999"
		"AbilityManaCost"				"0"


		"precache"
		{
			"particle"				"particles/ozy/ozy_light_pillar_runes.vpcf"
			"particle"				"particles/ozy/ozy_light_pillar_endcap.vpcf"

		}

		"AbilityValues"
        {
            "radius" 									"350"
        }
	}
	//=====================================
	// 
	//=====================================
	"ozy_spawn_piramid"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/ozy/ozy_spawn_piramid"
		"AbilityTextureName"				"custom/ozy/ozy_spawn_piramid"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"LevelsBetweenUpgrades"				"2"
		"MaxLevel"							"5"
		"AbilityCooldown"				    "40"
		"AbilityManaCost"					"800"
		"AbilityCastRange"					"1000"
		"AbilityCastPoint"					"0.5"
		"AbilityCastAnimation"				"ACT_DOTA_CAST_ABILITY_6"
		"LinkedAbilities"				"ozy_piramid_cage ozy_piramid_barrier ozy_piramid_curse ozy_piramid_aura ozy_piramid_beam"
		"LinkedAbilitiesRow"			"2"

		"precache"
		{
			"particle"		"particles/ozy/piramid/ozy_piramid_passive_effect.vpcf"
			"particle"		"particles/ozy/piramid/ozymandias_piramid_spawn.vpcf"
			"particle"		"particles/ozy/piramid/ozy/piramid/eruption.vpcf"
			"particle"		"particles/zlodemon/zlodemon_overhead_eye.vpcf"
			"particle"		"particles/econ/items/zeus/zeus_immortal_2021/zeus_immortal_2021_shard_gold_slow_smoke.vpcf"

			
		}
		"AbilityValues"
		{
			"damage"							"600 750 900 1050 1200"
			"radius"							"500"
			"summon_delay"						"2"
			"max_health"						"1000 1300 1600 1900 2200"
			"damage_first"						"300 375 450 525 600"
			"slow_first"						"30"
			"damage_reduction_max"				"70"
			"damage_reduction_distance_max"		"2500"
			"damage_reduction_distance_min"		"1000"
		}
	}

	//================================================
	// Piramid cage (Q)
	//================================================
	"ozy_piramid_cage"
	{
		"BaseClass" 					"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_piramid_cage"
		"AbilityBehavior" 				"DOTA_ABILITY_BEHAVIOR_POINT| DOTA_ABILITY_BEHAVIOR_IMMEDIATE|DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_AOE|DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityTextureName"            "custom/ozy/ozy_piramid_cage"
		"MaxLevel"                      "5"
		"AbilityCastRange"				"1500"
		"AbilityCooldown"				"15"
		"AbilityManaCost"				"0"
		"AbilityCastPoint"				"0"

		"precache"
		{
			"particle"		"particles/units/heroes/hero_disruptor/disruptor_kineticfield.vpcf"
		}

		"AbilityValues"
        {
            "duration" "1"
            "radius"	"400"
            "root_duration"	"0.05"
        }
	}

	//=======================================
	// Ozy piramid protection (W)
	//=======================================
	"ozy_piramid_barrier"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_piramid_barrier"
		"MaxLevel"						"5"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_CHANNELLED|DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING|DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityTextureName"			"custom/ozy/piramid_barrier"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_FRIENDLY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_HERO"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_2"
		"AbilityChannelTime"			"4"
		"AnimationPlaybackRate" 		"1"

		"AbilityCooldown"				"8"
		"AbilityManaCost"				"0"


		"precache"
		{
			"particle"				"particles/ozy/piramid/piramid_barrier_new.vpcf"

		}

		"AbilityValues"
        {
            "duration" 				"4"
            "barrier" 				"1000 1250 1500 1750 2000"
        }
	}


	//================================================
	// Piramid aura
	//================================================
	"ozy_piramid_aura"
	{
		"BaseClass" 					"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_piramid_aura"
		"AbilityBehavior" 				"DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE |DOTA_ABILITY_BEHAVIOR_NO_TARGET |DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING"
		"AbilityTextureName"            "custom/ozy/piramid_aura"
		"MaxLevel"                      "5"
		"AbilityCastRange"				"1500"

		"AbilityCooldown"				"1"
		"AbilityValues"
        {
            "radius" "1500"
            "bonus_mr" "4 5 6 7 8"
            "bonus_regen" "20 25 30 35 40"
        }
	}

	//================================================
	// Piramid defence
	//================================================
	"ozy_piramid_auto_defence"
	{
		"BaseClass" 					"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_piramid_auto_defence"
		"AbilityBehavior" 				"DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE | DOTA_ABILITY_BEHAVIOR_TOGGLE  | DOTA_ABILITY_BEHAVIOR_IMMEDIATE| DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE"
		"AbilityTextureName"            "custom/ozy/piramid_defence"
		"MaxLevel"                      "5"
		"AbilityCastRange"				"1500"
		"AbilityCooldown"				"0"
		"AbilityManaCost"				"0"
		"AbilityCastPoint"				"0"

		"precache"
		{
			"particle"		"particles/ozy/piramid/piramid_beam.vpcf"
			"particle"		"particles/heroes/anime_hero_leonidas/leonidas_thermopylae_enomotia_sphere_ring.vpcf"

			
		}

		"AbilityValues"
        {
            "radius" "1500"
            "delay" "1"
            "hit_radius" "150"
            "damage" "200"
            "max_targets" "3"
            "delay_before_damage" "0.5"
        }
	}

	//=======================================
	// Piramid curse
	//=======================================
	"ozy_piramid_curse"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_piramid_curse"
		"MaxLevel"						"5"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT| DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_IMMEDIATE|DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE"
		"AbilityTextureName"			"custom/ozy/curse_of_ra"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"


		"AbilityCooldown"				"30"
		"AbilityManaCost"				"0"
		"AbilityCastRange"				"1500"
		"AbilityCastPoint"				"0"


		"precache"
		{
			"particle"				"particles/ozy/piramid/ozy_piramid_curse_blast.vpcf"
			"particle"				"particles/ozy/piramid/curse_debuff_enemy.vpcf"
			"particle"				"particles/ozy/piramid/ozy_piramid_curse_precast.vpcf"
			"particle"				"particles/ozy/piramid/ozy_scale.vpcf"
		}

		"AbilityValues"
        {
            "radius" "400"
            "duration" "5"
            "delay" 	"0.5"
            "damage" 	"100 125 150 175 200"
            "stat_debuff" 	"10 12.5 15 17.5 20"
            "health_debuff"	"200"
            "armor_debuff" 	"2 2.5 3 3.5 4"
            "magres_debuff" 	"10 12.5 15 17.5 20"
        }
	}
	//=======================================
	// Piramid beam
	//=======================================
	"ozy_piramid_beam"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_piramid_beam"
		"MaxLevel"						"5"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT| DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_IMMEDIATE|DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE"
		"AbilityTextureName"			"custom/ozy/ozy_piramid_beam"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"


		"AbilityCooldown"				"30"
		"AbilityManaCost"				"0"
		"AbilityCastRange"				"1500"
		"AbilityCastPoint"				"0"


		"precache"
		{
			"particle"				"particles/ozy/piramid/ozy_piramid_beam_precast.vpcf"
			"particle"				"particles/ozy/piramid/piramid_laser_dmg.vpcf"
			"particle"				"particles/ozy/piramid/piramid_laser_beam_1.vpcf"

		}

		"AbilityValues"
        {
            "radius" 			"500"
            "duration" 			"2"
            "delay" 			"1.5"
            "damage" 			"1000 1250 1500 1750 2000"
            "damage_per_int"	"5"
        }
	}

	//=======================================
	// Piramid combo
	//=======================================
	"ozy_combo"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_combo"
		"MaxLevel"						"5"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_HIDDEN | DOTA_ABILITY_BEHAVIOR_POINT| DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_IMMEDIATE|DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE"
		"AbilityTextureName"			"custom/ozy/ozy_combo"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"


		"AbilityCooldown"				"150"
		"AbilityManaCost"				"0"
		"AbilityCastRange"				"5000"
		"AbilityCastPoint"				"0"

		"precache"
		{
			"particle"				"particles/ozy/ozy_combo_ground_marker.vpcf"
			"particle"				"particles/ozy/ozy_piramid_statusfx.vpcf"
			"particle"				"particles/ozy/piramid/ozymandias_piramid_drop_ground.vpcf"
			"particle"				"particles/ozy/ozy_combo_trail.vpcf"

		}

		"AbilityValues"
        {
            "radius" 			"500"
            "outer_radius" 		"1000"
            "duration" 			"1"
            "delay" 			"3"
            "damage" 			"2000"
            "damage_big"		"4000"
            "stun_duration"		"1"
        }
	}

	"ozy_sa_1"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/ozy/ozy_spawn_piramid"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"12"
		"LinkedAbilities"				"ozy_piramid_auto_defence"

		 
		"AbilityValues"
        {
        	"vision_radius"										"2000"
        	"vision_activation_duration"						"3.3"
        }		
	}
	"ozy_sa_2"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/ozy/ozy_boat"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"15"

		 
		"AbilityValues"
        {
			"vision_duration"										"5"
			"vision_radius"											"2000"
        }		
	}
	"ozy_sa_3"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/ozy/mystic_eyes"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"8"

		 
		"AbilityValues"
        {
			"bonus_duration"										"3"
			"bonus_onkill_passive_radius"							"300"

        }		
	}
	"ozy_sa_4"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/ozy/ozy_sa_4"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"10"

		 
		"AbilityValues"
        {
			"gold_bonus"										"50"
			"item_cdr"										"25"
			"sa_debuff_duration"										"0.6"
        }		
	}
	"ozy_sa_5"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/ozy/ozy_sa_5"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"12"

		 
		"AbilityValues"
        {
			"value"										"100"

        }		
	}

}