"DOTAAbilities"
{

	//=======================================
	// Ozy ЧАКРАМ (Q)
	//=======================================
	"ozy_light_chacram"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_light_chacram"
		"MaxLevel"						"5"
		"LevelsBetweenUpgrades"				"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityTextureName"			"custom/ozy/ozy_chacram"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1"

		"AbilityCooldown"				"15"
		"AbilityCastPoint"					"0.2"
		"AbilityCastRange"				"1000"
		"AbilityManaCost"					"100"


		"precache"
		{
			"particle"				"particles/ozy/ozy_chacram.vpcf"
		}

		"AbilityValues"
        {
            "radius" 				"128"
            "distance"				"1100"
            "duration" 				"0.5 0.62 0.75 0.87 1"
            "damage" 				"200 250 300 350 400"
        }
	}


	//=======================================
	// Ozy protection (W)
	//=======================================
	"ozy_protection_of_sun_god"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_protection_of_sun_god"
		"MaxLevel"						"5"
		"LevelsBetweenUpgrades"				"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT| DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityTextureName"			"custom/ozy/ozy_flash_barrier"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_FRIENDLY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_HERO"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_2"
		"AnimationPlaybackRate" 		"1"

		"AbilityCooldown"				"20 18 16 14 12"
		"AbilityCastPoint"					"0.2"
		"AbilityCastRange"				"1000"
		"AbilityManaCost"					"200"


		"precache"
		{
			"particle"				"particles/ozy/sun_god_barrier.vpcf"
			"particle"				"particles/ozy/ozy_blind.vpcf"
			"particle"				"particles/ozy/ozy_flash_barrier.vpcf"

		}

		"AbilityValues"
        {
            "radius" 				"500"
            "duration" 				"8"
            "barrier" 				"200 250 300 350 400"
            "damage" 				"200 250 300 350 400"
            "blind" 				"100"
            "slow_duration" 		"2"
            "slow_percentage" 		"30"
        }
	}

	//=======================================
	// Ozy PILLAR (E)
	//=======================================
	"ozy_light_pillar"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_light_pillar"
		"MaxLevel"						"5"
		"LevelsBetweenUpgrades"				"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityTextureName"			"custom/ozy/light_pillar"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"1"

		"AbilityCooldown"				"25"
		"AbilityCastPoint"					"0.2"
		"AbilityCastRange"				"1000"
		"AbilityManaCost"				"400"


		"precache"
		{
			"particle"				"particles/ozy/ozy_light_pillar_runes.vpcf"
			"particle"				"particles/ozy/ozy_light_pillar_endcap.vpcf"

		}

		"AbilityValues"
        {
            "radius" 				"350"
            "delay"					"1"
            "stun_duration" 		"0.8"
            "damage" 				"600 750 900 1050 1200"
        }
	}


	//=======================================
	// Ozy mystic eyes (F)
	//=======================================
	"ozy_mystic_eyes"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_mystic_eyes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET| DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityTextureName"			"custom/ozy/mystic_eyes"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_HERO"
		"AbilityCooldown"				"15"
		"AbilityManaCost"				"0"


		"precache"
		{
			"particle"				"particles/zlodemon/immunity_sphere_buff_sun.vpcf"
			"particle"				"particles/ozy/ozy_mystic_eyes_target.vpcf"


		}

		"AbilityValues"
        {
            "duration" 				"3"
            "stun_duration" 		"1"
        }
	}

	//=====================================
	// 
	//=====================================
	"ozy_spawn_boat"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/ozy/ozy_spawn_boat"
		"AbilityTextureName"				"custom/ozy/ozy_boat"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"MaxLevel"							"1"
		"AbilityCooldown"				    "0"
		"AbilityManaCost"					"0"
		"AbilityCastRange"					"1000"



		"precache"
		{
			"particle"		"particles/ozy/piramid/ozy_piramid_passive_effect.vpcf"


			
		}
		"AbilityValues"
		{
			"damage"							"1000"
			"radius"							"500"
			"summon_delay"						"2"
			"max_health"						"1500"
			"damage_first"						"500"
			"slow_first"						"50"
		}
	}
	//=====================================
	// 
	//=====================================
	"ozy_move_boat"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/ozy/ozy_move_boat"
		"AbilityTextureName"				"custom/ozy/ozy_boat"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"MaxLevel"							"1"
		"AbilityCooldown"				    "0.5"
		"AbilityManaCost"					"0"
		"AbilityCastRange"					"9999"


		"AbilityValues"
		{
			"speed"							"500"
			"max_distance"							"1500"
		}
	}

	//=====================================
	// 
	//=====================================
	"ozy_teleport_boat"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/ozy/ozy_teleport_boat"
		"AbilityTextureName"				"custom/ozy/ozy_boat"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_CHANNELLED"
		"MaxLevel"							"1"
		"AbilityCooldown"				    "30"
		"AbilityManaCost"					"0"
		"AbilityCastRange"					"9999"
		"AbilityChannelTime"			"3"


		"precache"
		{
			"particle"  "particles/units/heroes/hero_keeper_of_the_light/keeper_of_the_light_recall.vpcf"
			
		}
		"AbilityValues"
		{
			"delay"							"3"
			"max_distance"					"1500"
			"minimum_damage"				"400"
		}
	}
	//=====================================
	// 
	//=====================================
	"ozy_spawn_piramid"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/ozy/ozy_spawn_piramid"
		"AbilityTextureName"				"custom/ozy/ozy_spawn_piramid"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"LevelsBetweenUpgrades"				"2"
		"MaxLevel"							"5"
		"AbilityCooldown"				    "40"
		"AbilityManaCost"					"800"
		"AbilityCastRange"					"1000"
		"AbilityCastPoint"					"0.5"
		"AbilityCastAnimation"				"ACT_DOTA_CAST_ABILITY_6"


		"precache"
		{
			"particle"		"particles/ozy/piramid/ozy_piramid_passive_effect.vpcf"
			"particle"		"particles/ozy/piramid/ozymandias_piramid_spawn.vpcf"
			"particle"		"particles/ozy/piramid/ozy/piramid/eruption.vpcf"

			
		}
		"AbilityValues"
		{
			"damage"							"1000"
			"radius"							"500"
			"summon_delay"						"2"
			"max_health"						"1500"
			"damage_first"						"500"
			"slow_first"						"50"
		}
	}

	//================================================
	// Piramid flashka (ПРИКОЛ, ЭТОГО НЕТ!!!)
	//================================================
	"ozy_piramid_flash"
	{
		"BaseClass" 					"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_piramid_flash"
		"AbilityBehavior" 				"DOTA_ABILITY_BEHAVIOR_NO_TARGET| DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityTextureName"            "custom/ozy/ozy_piramid_flash"
		"MaxLevel"                      "5"
		"AbilityCastRange"				"1500"
		"AbilityCooldown"				"15"
		"AbilityManaCost"				"0"
		"AbilityCastPoint"				"0"

		"precache"
		{
			"particle"		"particles/ozy/piramid/flashka_na_a.vpcf"
		}

		"AbilityValues"
        {
            "radius" "1500"
            "delay" "1"
        }
	}

	//=======================================
	// Ozy piramid protection (W)
	//=======================================
	"ozy_piramid_barrier"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_piramid_barrier"
		"MaxLevel"						"5"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_CHANNELLED"
		"AbilityTextureName"			"custom/ozy/piramid_barrier"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_FRIENDLY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_HERO"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_2"
		"AbilityChannelTime"			"4"
		"AnimationPlaybackRate" 		"1"

		"AbilityCooldown"				"8"
		"AbilityManaCost"				"0"


		"precache"
		{
			"particle"				"particles/ozy/piramid/piramid_barrier_new.vpcf"

		}

		"AbilityValues"
        {
            "duration" 				"4"
            "barrier" 				"1000 1500 2000 2500 3000"
        }
	}


	//================================================
	// Piramid aura
	//================================================
	"ozy_piramid_aura"
	{
		"BaseClass" 					"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_piramid_aura"
		"AbilityBehavior" 				"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityTextureName"            "custom/ozy/piramid_aura"
		"MaxLevel"                      "5"
		"AbilityCastRange"				"1000"

		"AbilityValues"
        {
            "radius" "1000"
            "bonus_mr" "5 6.25 7.5 8.75 10"
            "bonus_regen" "40 50 60 70 80"
        }
	}

	//================================================
	// Piramid defence
	//================================================
	"ozy_piramid_auto_defence"
	{
		"BaseClass" 					"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_piramid_auto_defence"
		"AbilityBehavior" 				"DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE | DOTA_ABILITY_BEHAVIOR_TOGGLE  | DOTA_ABILITY_BEHAVIOR_IMMEDIATE| DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE"
		"AbilityTextureName"            "custom/ozy/piramid_defence"
		"MaxLevel"                      "5"
		"AbilityCastRange"				"1500"
		"AbilityCooldown"				"0"
		"AbilityManaCost"				"0"
		"AbilityCastPoint"				"0"

		"precache"
		{
			"particle"		"particles/ozy/piramid/piramid_beam.vpcf"
			"particle"		"particles/heroes/anime_hero_leonidas/leonidas_thermopylae_enomotia_sphere_ring.vpcf"

			
		}

		"AbilityValues"
        {
            "radius" "1500"
            "delay" "1"
            "hit_radius" "150"
            "damage" "100 125 150 175 200"
            "max_targets" "3"
            "delay_before_damage" "0.5"
        }
	}

	//=======================================
	// Piramid curse
	//=======================================
	"ozy_piramid_curse"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_piramid_curse"
		"MaxLevel"						"5"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT| DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_IMMEDIATE|DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE"
		"AbilityTextureName"			"custom/ozy/curse_of_ra"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"


		"AbilityCooldown"				"30 28 26 24 22"
		"AbilityManaCost"				"0"
		"AbilityCastRange"				"1500"


		"precache"
		{
			"particle"				"particles/ozy/piramid/ozy_piramid_curse_blast.vpcf"
			"particle"				"particles/ozy/piramid/curse_debuff_enemy.vpcf"
			"particle"				"particles/ozy/piramid/ozy_piramid_curse_precast.vpcf"
			"particle"				"particles/ozy/piramid/ozy_scale.vpcf"
		}

		"AbilityValues"
        {
            "radius" "400"
            "duration" "5"
            "delay" 	"0.5"
            "damage" 	"100 125 150 175 200"
            "stat_debuff" 	"10 12.5 15 17.5 20"
            "health_debuff"	"200 250 300 350 400"
            "armor_debuff" 	"2 2.5 3 3.5 4"
            "magres_debuff" 	"4 5 6 7 8"
        }
	}
	//=======================================
	// Piramid beam
	//=======================================
	"ozy_piramid_beam"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/ozy/ozy_piramid_beam"
		"MaxLevel"						"5"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT| DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_IMMEDIATE|DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE"
		"AbilityTextureName"			"custom/ozy/ozy_piramid_beam"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"


		"AbilityCooldown"				"40 38 36 34 32"
		"AbilityManaCost"				"0"
		"AbilityCastRange"				"1500"


		"precache"
		{
			"particle"				"particles/ozy/piramid/ozy_piramid_beam_precast.vpcf"
			"particle"				"particles/ozy/piramid/piramid_laser_dmg.vpcf"
			"particle"				"particles/ozy/piramid/piramid_laser_beam_1.vpcf"

		}

		"AbilityValues"
        {
            "radius" "500"
            "duration" "2"
            "delay" 	"1.5"
            "damage" 	"800 1000 1200 1400 1600"
        }
	}
}