		"DOTAAbilities"
{
	//=======================================★★★★★
	// Scathach: Wisdom of Dun Scaith
	//=======================================★★★★★
	"scathach_wisdom_of_dun_scaith"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/scathach/scathach_wisdom_of_dun_scaith"
		"MaxLevel"						"1"
		"RequiredLevel"					"25"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/scathach/scathach_wisdom_of_dun_scaith"
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"33"
		"AbilityManaCost"				"0"

		"precache"
		{
			"particle"			"particles/zlodemon/immunity_sphere_buff.vpcf"
		}

		"AbilityValues"
        {
            "duration" "2.7"
        }
	}
}