#base "scathach_red_wind.kv"
#base "scathach_gait_one.kv"
#base "scathach_gait_two.kv"
#base "scathach_gait_three.kv"
#base "scathach_gae_bolg.kv"
#base "scathach_pinning_thorn.kv"
#base "scathach_wisdom_of_dun_scaith.kv"
#base "scathach_gae_bolg_jump.kv"
#base "scathach_gae_bolg_combo.kv"
#base "scathach_red_creed_combo.kv"

"DOTAAbilities"
{
	//=======================================★★★★★
	// 
	//=======================================★★★★★
	"scathach_gae_bolg_spawn"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/scathach/scathach_gae_bolg_spawn"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityTextureName"			"custom/scathach/scathach_summon_1"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastPoint"				"0.5"
		"AbilityCooldown"				"40 36 32 28 24"
		"AbilityCastRange"				"1400"
		"AbilityManaCost"				"400"
		"AbilityCastAnimation" 			"ACT_DOTA_ITEM_PICKUP"
		"AnimationPlaybackRate" 		"1.0"
		

		"precache"
		{
				"particle"		"particles/custom/scathach/gb_test_1.vpcf"
				"particle"		"particles/custom/scathach/spear_trail_multiple.vpcf"
				"particle"		"particles/custom/scathach/gae_bolg_alt_outline.vpcf"
				"particle"		"particles/scathach/scathach_barrage_spear.vpcf"
				"particle"		"particles/custom/scathach/gae_bolg_alt_outline.vpcf"
				"particle"		"particles/scathach/scat_barrage_spear_explosion.vpcf"
		}

		"AbilityValues"
        {
            "duration" "10"
            "gb_spawn_amount" "4"
            "damage"		   "300 375 450 525 600"
            "range"		   "1400"
            "shoot_cd"		   "0.75"
            "hit_radius"		   "100"
            "speed"		   "3000"
            "agi_scaling"		   "1.5"
            "sa_cd"		   "30"
            "sa_dmg"		   "100"
            "sa_stun_duration"		   "1"
        }
	}

	//=================================================================================================================
	// Combo - Gate of Skye
	//=================================================================================================================
	"scathach_gate_of_skye"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/scathach/scathach_gate_of_skye"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/scathach/scathach_combo_gate_of_sky"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1.0"
		"AbilityCastPoint"				"0.3"
		"AbilityCastRange"				"800"
 		"AbilityCooldown"				"180"
		"AbilityManaCost"				"800"
		"precache"
		{
				"particle"		"particles/custom/scathach/scathach_gate.vpcf"
				"particle"		"particles/scathach/scathach_gate_debuff.vpcf"
				"particle"		"particles/scathach/scathach_gate_aoe_ring.vpcf"
				"particle"		"particles/custom/scathach/gate_of_skye_field.vpcf"
				"soundfile"		"soundevents/game_sounds_heroes/game_sounds_mars.vsndevts"
				"soundfile"		"soundevents/game_sounds_heroes/game_sounds_crystal_maiden.vsndevts"
		}
		"AbilityValues"
        {
        	"anim_duration"				"3"
        	"active_duration"			"9" //better not touch both durations or else sounds will fuck up
        	"radius"					"3000"
        	"damage_per_second"			"100"
        	"healing_reduction"			"40"
        	"slow"						"20"
        	"execute_threshold"			"40"
        	"execute_duration"			"2"
        }
	}

	//=================================================================================================================
	// Nobu - Gun shot (Q)
	//=================================================================================================================
	"scathach_gae_bolg_shoot"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/scathach/scathach_gae_bolg_shoot"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT|DOTA_ABILITY_BEHAVIOR_HIDDEN|DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/scathach/scathach_summon"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1.0"
		"AbilityCastPoint"				"0.0"
		"AbilityCastRange"				"1400"
 		"AbilityCooldown"				"0.75"
		"AbilityManaCost"				"100"
		"AbilityValues"
        {

        }
	}

	//=================================================================================================================
	// Nobu - Gun shot (Q)
	//=================================================================================================================
	"scathach_mentor"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/scathach/scathach_mentor"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"25"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET|DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_FRIENDLY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO"
		"AbilityTextureName"			"custom/scathach/scathach_wisdom_of_dun_scaith"
		"AbilityCastRange"				"1000"
 		"AbilityCooldown"				"0"
		"AbilityManaCost"				"0"
		"AbilityValues"
        {

        }
	}
	//=======================================★★★★★
	// Attribute: Primeval Rune
	//=======================================★★★★★
	"scathach_primeval_rune_attribute"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/scathach/scathach_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/scathach/scathach_primeval_rune_attribute"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"13"

		"precache"
		{
		}

		"AbilityValues"
        {
            "red_wind_damage" "100"
            "red_wind_range" "200"
            "red_wind_stun" "0.2"
            "gait_one_damage" "1"
            "gait_two_damage" "1"
            "gait_three_damage" "1.5"
        }
	}

	//=======================================★★★★★
	// Attribute: Branches of Tonelico
	//=======================================★★★★★
	"scathach_branches_of_tonelico_attribute"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/scathach/scathach_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/scathach/scathach_branches_of_tonelico_attribute"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"17"

		"precache"
		{
		}

		"AbilityValues"
        {
            "healres_duration" "3"
            "agi_scaling" "1.5"
            "sa_cd"		   "30"
            "sa_dmg"		   "500"
            "sa_stun_duration"		   "1"
            "sa_radius"		   "200"
            "sa_time"		   "3"
        }
	}

	//=======================================★★★★★
	// Attribute: Improve Pinning God Killer Thorns
	//=======================================★★★★★
	"scathach_pinning_thorn_attribute"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/scathach/scathach_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/scathach/scathach_pinning_thorn_attribute"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"10"

		"precache"
		{
		}

		"AbilityValues"
        {
            "base_damage" "600"
            "explosion_damage" "600"
            "agility_ratio" "3"
            "gae_bolg_agi" "3"
        }
	}

	//=======================================★★★★★
	// Attribute: Wisdom of Dun Scaith
	//=======================================★★★★★
	"scathach_wisdom_of_dun_scaith_attribute"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/scathach/scathach_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/scathach/scathach_wisdom_of_dun_scaith"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"7"

		"precache"
		{
		}

		"AbilityValues"
        {
            "linken_duration" "3"
            "agility_gain" "30"
        }
	}
	
	//=======================================★★★★★
	// Attribute: God Slayer
	//=======================================★★★★★
	"scathach_god_slayer_attribute"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/scathach/scathach_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/scathach/scathach_god_slayer_attribute"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"14"

		"precache"
		{
		}

		"AbilityValues"
        {
            "agility_per_kill" "0.5"
            "hp_per_kill" "3"
            "agility_per_divine_kill" "1"
            "hp_per_divine_kill" "6"
        }
	}
	
	//=======================================★★★★★
	// Attribute: Combo List
	//=======================================★★★★★
	"scathach_combo_list"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/scathach/scathach_attributes"
		"MaxLevel"						"1"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/scathach/scathach_gae_bolg_combo"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"0"
		"AbilityManaCost"				"0"

		"precache"
		{
		}

		"AbilityValues"
        {
            "radius" "3000"
            "duration" "2"
            "slow_duration" "7"
            "crack_time" "2"
            "crack_width" "500"
            "crack_distance" "5000"
            "damage" "600"
            "slow_pct" "75"
        }
	}
	
	//=======================================★★★★★
	// Combo: Scathach Red Creed
	//=======================================★★★★★
	"scathach_combo_2_proxy"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/scathach/scathach_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/scathach/scathach_red_creed_combo"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"110"
		"AbilityManaCost"				"0"

		"precache"
		{
		}

		"AbilityValues"
        {
            "cast_delay" "1.3"
            "range" "1200"
            "projectiles" "12"
            "radius" "600"
            "explosion_radius" "1000"
            "extra_projectiles" "11"
            "damage_primary" "175"
            "damage_secondary" "225"
            "retreat_distance" "800"
        }
	}
}