"DOTAAbilities"
{
	//=================================================================================================================
	// Scathach: Funeral Gait - Legion's Bite (W -> W -> W)
	//=================================================================================================================
	"scathach_gait_three"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/scathach/scathach_gait_three"
		"MaxLevel"						"5"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_CREEP"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/scathach/scathach_gait"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_4"
		"AnimationPlaybackRate" 		"1.0"	
		"precache"
		{
			"particle"					"particles/custom/archer/archer_overedge_slash.vpcf"
			"particle"					"particles/custom/emiya/overedge_swords.vpcf"
			"particle"					"particles/units/heroes/hero_centaur/centaur_warstomp.vpcf"
			"particle"					"particles/units/heroes/hero_queenofpain/queen_shadow_strike.vpcf"
			"particle"					"particles/custom/scathach/scathach_gait_three_swing.vpcf"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_juggernaut.vsndevts"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_phantom_lancer.vsndevts"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_centaur.vsndevts"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"800"
		"AbilityCastPoint"				"0.15"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"20"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"100"
		
		"AbilityValues"
        {
            "radius" "350"
            "damage" "400 500 600 700 800"
            "cast_range" "800"
            "cost_reduction" "50"
            "agi_ratio" "1.5"
            "agi_scale" "1.5"
        }
	}	
}