"DOTAAbilities"
{
	//=================================================================================================================
	// Scathach : Gae Bolg Alternative - The Spear of Impaling Barbed Death
	//=================================================================================================================
	"scathach_gae_bolg"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/scathach/scathach_gae_bolg"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_CREEP"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/scathach/scathach_gae_bolg"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_5"
		"AnimationPlaybackRate" 		"1.0"
		
		"IsCastableWhileHidden"			"1"
		
		"precache"
		{
			"particle"		"particles/units/heroes/hero_chaos_knight/chaos_knight_reality_rift.vpcf"
			"particle"		"particles/scathach/gae_bolg_pierce_alt.vpcf"
			"particle"		"particles/custom/diarmuid/gae_dearg_slash.vpcf"
			"particle"		"particles/generic_gameplay/screen_blood_splatter.vpcf"
			"particle"		"particles/custom/lancer/lancer_culling_blade_kill.vpcf"
			"particle"		"particles/custom/scathach/bramble_scathach.vpcf"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_lion.vsndevts"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"300"
		"AbilityCastRangeBuffer"		"1000"
		"AbilityCastPoint"				"0.6"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"25"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"400"
		
		"AbilityValues"
        {
            "delay" "0.6"
            "damage" "400 500 600 700 800"
            "damage_per_stack" "40 50 60 70 80"
            "stun_duration" "0.1"
            "healres_duration" "3"
            "healing_reduction" "40"
            "slow_per_stack" "2" //manually used number
            "curse_duration" "10"//manually used number
            "max_stacks" "10"	 //manually used number
        }
	}
}