"DOTAAbilities"
{
	//=================================================================================================================
	// Scathach: Pinning God Killer Thorns (D)
	//=================================================================================================================
	"scathach_pinning_thorn"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/scathach/scathach_pinning_thorn"
		"MaxLevel"						"2"
		"RequiredLevel"					"25"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/scathach/scathach_pinning_thorn"
		"AbilityCastAnimation" 			"ACT_DOTA_ITEM_PICKUP"
		"AnimationPlaybackRate" 		"1.0"
		
		"precache"
		{
			"particle"		"particles/units/heroes/hero_axe/axe_culling_blade_kill.vpcf"
			"particle"		"particles/custom/scathach/gae_bolg.vpcf"
			"particle"		"particles/cu_chulain/gae_bolg_explosion.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_lion.vsndevts"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"2000"
		"AbilityCastRangeBuffer"		"99999"
		"AbilityCastPoint"				"0.1"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"45.0"


		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"400"
		
		"AbilityValues"
        {
            "cast_delay" "1.3"
            "radius" "500"
            "range" "2000"
            "damage" "300 450"
            "damage_secondary" "300 450"
            "agi_ratio" "3 6"
            "damage_per_hero_level" "5 10"
        }
	}	
}