"DOTAAbilities"
{
	//=====================================
	// Scathach: Creed Blast (Q -> D)
	//=====================================
	"scathach_red_creed_combo"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/scathach/scathach_red_creed_combo"
		"MaxLevel"						"1"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_CREEP"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/scathach/scathach_red_creed_combo"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_6"
		"AnimationPlaybackRate" 		"1.0"

		"precache"
		{
			"particle"					"particles/custom/scathach/gae_bolg.vpcf"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"1200"
		"AbilityCastPoint"				"0.15"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"110"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"800"
		
		"AbilityValues"
        {
            "cast_delay" "1.3"
            "range" "1200"
            "projectiles" "12"
            "radius" "600"
            "explosion_radius" "1000"
            "extra_projectiles" "11"
            "damage_primary" "175"
            "damage_secondary" "225"
            "retreat_distance" "800"
        }
	}
}