"DOTAAbilities"
{
	//=======================================★★★★★
	// Scathach: Red Wind (Q)
	//=======================================★★★★★
	"scathach_red_wind"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/scathach/scathach_red_wind"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AUTOCAST"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_YES"
		"AbilityTextureName"			"custom/scathach/scathach_red_wind"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_EMP"
		"AbilityCastRange"				"700"
		"AbilityCastRangeBuffer"		"10"
		"AbilityCastPoint"				"0.2"
		"AbilityCooldown"				"14 13 12 11 10"
		"AbilityManaCost"				"100"

		"precache"
		{
			"particle"			"particles/custom/scathach/abilityflash.vpcf"
			"particle"			"particles/custom/scathach/red_wind_lightning_1.vpcf"
			"particle"			"particles/custom/scathach/red_wind_lightning_2.vpcf"
			"particle"			"particles/custom/scathach/gae_bolg_spear_trail.vpcf"
			"particle"			"particles/custom/scathach/gae_bolg_fire_trail.vpcf"
			"particle"			"particles/custom/scathach/red_wind_impact.vpcf"
			"particle"			"particles/custom/scathach/red_wind_impact.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_phantom_lancer.vsndevts"
		}

		"AbilityValues"
        {
            "damage" "200 250 300 350 400"
            "distance" "700"
            "stun_duration" "0.5"
        }
	}
}