// Dota Heroes File
"DOTAAbilities"
{
	//=================================================================================================================
	// Scathach : Wisdom of haunt ground Passive
	//=================================================================================================================
	//=================================================================================================================
	// Scathach : Immortal Passive
	//=================================================================================================================
	//=================================================================================================================
	// Scathach Attribute : Primeval Rune
	//=================================================================================================================
	//=================================================================================================================
	// Scathach Attribute : God Slayer
	//=================================================================================================================
	//=================================================================================================================
	// Scathach Attribute : Branch of Tonelico
	//=================================================================================================================
	//=================================================================================================================
	// Scathach Attribute : Wisdom of haunt ground
	//=================================================================================================================
	//=================================================================================================================
	// Scathach Attribute : Immortal
	//=================================================================================================================
	//=================================================================================================================
	// Scathach : Combo : Gate of Sky (F)
	//=================================================================================================================
	"scathach_combo_gate_of_sky"
	{
		"BaseClass"						"ability_datadriven"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		//หารูปมาใส่
		"AbilityTextureName"			"custom/scathach/scathach_combo_gate_of_sky"
		"MaxLevel"						"1"
		"AbilityCastPoint"				"1.0"
		"AbilityCooldown"				"180"
		"AbilityCastRange"				"1500"
		"AbilityManaCost"				"800"
		"AbilityCastAnimation"			"ACT_DOTA_AMBUSH"
		"AnimationPlaybackRate"			"1"
		"precache"
		{
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_luna.vsndevts"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_mars.vsndevts"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_windrunner.vsndevts"
			"particle"					"particles/custom/scathach/scathach_gate_ground.vpcf"
			"particle"					"particles/custom/scathach/scathach_gate.vpcf"
			"particle"					"particles/econ/items/windrunner/windrunner_cape_cascade/windrunner_windrun_burst_cascade.vpcf"
			"particle"					"particles/custom/scathach/gate_of_skye_field.vpcf"
			"particle"					"particles/custom/scathach/gate_of_skye_reborn.vpcf"

			"particle"		"particles/custom/scathach/scathach_blast.vpcf"
			"particle"		"particles/custom/scathach/scathach_frost.vpcf"
			"particle"		"particles/custom/tamamo/combo/fire_explosion_column.vpcf"
			"particle"		"particles/items_fx/healing_clarity.vpcf"
			"particle"		"particles/units/heroes/hero_mirana/mirana_spell_arrow_launch.vpcf"
		}
		"AbilityValues"
        {
            "duration" "5.1"
            "range" "1500"
            "dmg" "2500"
            "mana_burn_sec" "40"
            "interval" "0.1"
            "slow_debuff" "-30"
            "cooldown" "180"
            "pull_duration" "4.0"
            "reduction" "-10"
        }
		"OnAbilityPhaseStart"
		{
			"RunScript"
			{
				"ScriptFile"	"abilities/scathach/scathach_abilities"
				"Function"		"OnGateOfSkySound"
			}
		}
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"abilities/scathach/scathach_abilities"
				"Function"		"OnGateOfSkyCast"
			}
		}
		"Modifiers"
		{
			"modifier_gate_of_sky_pull"
			{
				"Passive"			"0"
				"IsHidden"			"0"
				"IsDebuff"			"0"
				"IsPurgable"		"0"
				"OnCreated"
				{
					"RunScript"
					{
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						//"Function"		"OnGateOfSkyPull"
					}
				}
				"OnDestroy"
				{
					"RunScript"
					{
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						"Function"		"OnGateOfSkyPullStop"
					}
				}
				"ThinkInterval"  "%interval"
				"OnIntervalThink"
				{
					"RunScript"
					{
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						"Function"		"OnGateOfSkyBurnMana"
					}
				}
			}
			"modifier_gate_of_sky_pull_aura"
			{
				"Passive"			"0"
				"IsHidden"			"0"
				"IsDebuff"			"0"
				"Duration"			"%pull_duration"
				"Aura"				"modifier_gate_of_sky_pull"
				"Aura_Radius"		"%range"
				"Aura_Teams"		"DOTA_UNIT_TARGET_TEAM_ENEMY"
				"Aura_Types"		"DOTA_UNIT_TARGET_ALL"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_gate_of_sky_no_blink"
			{
				"Passive"			"0"
				"IsHidden"			"0"
				"IsDebuff"			"1"
				"IsPurgable"		"0"
				"Properties"
				{
				    "MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE" "%slow_debuff" 
				}
				"ThinkInterval"  "0.1"
				"OnIntervalThink"
				{
					"RunScript"
					{
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						"Function"		"OnGateOfSkyPull"
					}
				}
				"OnCreated"
				{
					"AttachEffect"
					{
						"Target"			"TARGET"
						"EffectName"        "particles/econ/items/windrunner/windrunner_cape_cascade/windrunner_windrun_burst_cascade.vpcf"
						"EffectAttachType"  "follow_origin"
						"ControlPoints"
						{
							"00"	"0 0 0"
						}
					}
				}
			}
			"modifier_gate_of_sky_buff"
			{
				"Passive"			"0"
				"IsHidden"			"0"
				"IsDebuff"			"0"
				"IsBuff"			"1"
				"IsPurgable"		"0"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
				"Properties"
				{
					"MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE" "%reduction"
				}
			}
			"modifier_gate_of_sky_check"
			{
				"Passive"			"0"
				"IsHidden"			"0"
				"IsDebuff"			"0"
				"Aura"				"modifier_gate_of_sky_no_blink"
				"Aura_Radius"		"%range"
				"Duration"			"%duration"
				"Aura_Teams"		"DOTA_UNIT_TARGET_TEAM_ENEMY"
				"Aura_Types"		"DOTA_UNIT_TARGET_ALL"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			
				"OnCreated"
				{
					"RunScript"
					{
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						"Function"		"OnGateOfSkyCreate"
					}
				}
				"OnDestroy"
				{
					"RunScript"
					{
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						"Function"		"OnGateOfSkyDestroy"
					}
				}
				"OnDeath"
				{
					"RunScript"
					{
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						"Function"		"OnGateOfSkyDeath"
					}
				}
			}
			"modifier_gate_of_sky_cooldown"
			{
				"IsPurgable"		"0"
				"IsBuff"			"0"
				"IsHidden"			"0"
				"IsDebuff"			"1"
				"IsPurgable"		"0"
				"Duration"			"%cooldown"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE | MODIFIER_ATTRIBUTE_PERMANENT"
			}
		}
	}
	//=================================================================================================================
	// Scathach : Combo : Double Gae Bolg Alternative (R)
	//=================================================================================================================
	"scathach_combo_double_gae_bolg"
	{
		"BaseClass"						"ability_datadriven"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		//หารูปมาใส่
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_CREEP"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/scathach/scathach_combo_double_gae_bolg"
		"MaxLevel"						"1"
		"AbilityCastPoint"				"0.8"
		"AbilityCooldown"				"200"
		"AbilityManaCost"				"800"
		"AbilityCastRange"				"400"
		"AbilityCastRangeBuffer"		"600"
		"AbilityCastAnimation"			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate"			"0.7"
		"precache"
		{
			"particle"		"particles/units/heroes/hero_chaos_knight/chaos_knight_reality_rift.vpcf"
			"particle"		"particles/units/heroes/hero_centaur/centaur_double_edge.vpcf"
			"particle"		"particles/units/heroes/hero_axe/axe_culling_blade_kill.vpcf"
			"particle"		"particles/custom/lancer/lancer_heart_break_txt.vpcf"
			"particle"		"particles/items_fx/dagon.vpcf"
			"particle"		"particles/custom/diarmuid/gae_dearg_slash.vpcf"
			"particle"		"particles/units/heroes/hero_huskar/huskar_burning_spear.vpcf"
			"particle"		"particles/custom/lancer/lancer_gae_bolg_projectile.vpcf"
			"particle"		"particles/units/heroes/hero_warlock/warlock_rainofchaos_start_breakout_fallback_mid.vpcf"
			"particle"		"particles/units/heroes/hero_elder_titan/elder_titan_echo_stomp_cracks.vpcf"
			"particle"		"particles/custom/lancer/lancer_gae_bolg_hit.vpcf"
			"particle"  	"particles/custom/lancer/soaring/spear.vpcf"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_lion.vsndevts"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_drowranger.vsndevts"
			"particle"		"particles/custom/scathach/scathach_blast.vpcf"
			"particle"		"particles/custom/scathach/scathach_frost.vpcf"
			"particle"		"particles/custom/tamamo/combo/fire_explosion_column.vpcf"
			"particle"		"particles/items_fx/healing_clarity.vpcf"
			"particle"		"particles/units/heroes/hero_mirana/mirana_spell_arrow_launch.vpcf"
		}
		"AbilityValues"
        {
            "gae_malee_dmg" "200"
            "gae_thrown_dmg" "600"
            "radius" "1200"
            "cooldown" "200"
        }
		"OnAbilityPhaseStart"
		{
			"RunScript"
			{
				"ScriptFile"	"abilities/scathach/scathach_abilities"
				"Function"		"OnGaeComboCast"
			}
		}
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"abilities/scathach/scathach_abilities"
				"Function"		"OnGaeComboStart"
			}
		}
		"OnProjectileHitUnit"
		{
			"DeleteOnHit"	"1"
			"RunScript"
			{
				"ScriptFile"	"abilities/scathach/scathach_abilities"
				"Function"		"OnGaeComboHit"
			}
		}
		"Modifiers"
		{
			"modifier_combo_double_gae_bolg_cooldown"
			{
				"IsPurgable"		"0"
				"IsBuff"			"0"
				"IsHidden"			"0"
				"IsDebuff"			"1"
				"IsPurgable"		"0"
				"Duration"			"%cooldown"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE | MODIFIER_ATTRIBUTE_PERMANENT" 
			}
		}
	}

	// [restored] возвращён после ошибочной чистки
	// [restored] возвращён после ошибочной чистки
	// [restored] возвращён после ошибочной чистки
	// [restored] возвращён после ошибочной чистки
	// [restored] возвращён после ошибочной чистки
}