// Dota Heroes File
"DOTAAbilities"
{
	//=================================================================================================================
	// Scathach : Wisdom of haunt ground Passive
	//=================================================================================================================
	"scathach_wisdom_of_haunt_ground"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/scathach/scathach_attribute_wisdom_of_haunt_ground"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_NONE"
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"0"
		"AbilityManaCost"				"0"

		"AbilityValues"
        {
            "detect_range" "1200"
            "detect_duration" "3"
            "cooldown_duration" "60"
        }
		"Modifiers"
		{
			"modifier_wisdom_passive"
			{
				"Passive"			"1"
				"IsHidden"			"0"
				"IsDebuff"			"0"
				"IsBuff"			"1"
				"Aura"				"modifier_wisdom_trigger"
				"Aura_Radius"		"%detect_range"
				"Aura_Teams"		"DOTA_UNIT_TARGET_TEAM_ENEMY"
				"Aura_Types"		"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_CREEP | DOTA_UNIT_TARGET_BASIC"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE | MODIFIER_ATTRIBUTE_PERMANENT"
				"ThinkInterval"  "0.1"
				"OnIntervalThink"
				{
					"RunScript"
					{
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						"Function"		"OnWisdomSpellThink"
					}
				}
			}
			"modifier_wisdom_trigger"
			{
				"Passive"			"0"
				"IsHidden"			"1"
				"IsDebuff"			"1"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
				"OnAbilityExecuted"
				// Any ability (including items) was used by the unit with this modifier.
				{
					"RunScript"
					{
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						"Function"		"OnWisdomOsHauntGroundDetect"
					}
				}
			}
			"modifier_wisdom_target"
			{
				"Passive"			"0"
				"IsHidden"			"0"
				"IsDebuff"			"1"
				"IsPurgable"		"0"
				//"Duration"			"%detect_duration"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
				"Properties"
				{
					"MODIFIER_PROPERTY_PROVIDES_FOW_POSITION" "1"
				}
			}
			"modifier_wisdom_spell_block"
			{
				"Passive"			"1"
				"IsHidden"			"0"
				"IsDebuff"			"0"
				"IsBuff"			"1"
				"IsPurgable"		"0"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE | MODIFIER_ATTRIBUTE_PERMANENT"
				"OnDestroy"
				{
					"RunScript"
					{
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						"Function"		"OnWisdomSpellBlockDestroy"
					}
				}
			}
			"modifier_wisdom_spell_block_cooldown"
			{
				"Passive"			"0"
				"IsHidden"			"0"
				"IsDebuff"			"1"
				"IsBuff"			"0"
				"IsPurgable"		"0"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE | MODIFIER_ATTRIBUTE_PERMANENT"
				"Duration"			"%cooldown_duration"
				"OnDestroy"
				{
					"RunScript"
					{
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						"Function"		"OnWisdomSpellBlockCooldownEnd"
					}
				}
			}
		}
	}
	//=================================================================================================================
	// Scathach : Immortal Passive
	//=================================================================================================================
	"scathach_immortal"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/scathach/scathach_attribute_immortal"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"0"
		"AbilityManaCost"				"0"

		"precache"
		{
			"particle"		"particles/items_fx/aegis_respawn.vpcf"
		}

		"AbilityValues"
        {
            "bonus_evade" "25"
            "crit_chance" "50"
            "crit_multiply" "200"
            "bonus_aspd" "130"
            "bonus_agi" "3"
            "bonus_mr" "0"
        }
		"Modifiers"
		{
			"modifier_immortal_passive"
			{
				"Passive"			"0"
				"IsHidden"			"0"
				"IsDebuff"			"0"
				"IsBuff"			"1"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE | MODIFIER_ATTRIBUTE_PERMANENT"
				"OnHeroKilled"
				{
					"RunScript"
					{
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						"Function"		"OnImmortalKill"
					}
				}
				"OnDeath"
				{
					"RunScript"
					{
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						"Function"		"OnImmortalDead"
					}
				}
			}
			"modifier_immortal_agi"
			{
				"Passive"			"0"
				"IsHidden"			"1"
				"IsDebuff"			"0"
				"IsPurgable"		"0"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE | MODIFIER_ATTRIBUTE_PERMANENT"
				"Properties"
				{
					"MODIFIER_PROPERTY_STATS_AGILITY_BONUS" "%bonus_agi"
					"MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BONUS" "%bonus_mr"
				}
			}
			"modifier_immortal_crit"
			{
				"Passive"		"0"
				"IsHidden"		"1"
				"IsPurgable" 	"0"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE | MODIFIER_ATTRIBUTE_PERMANENT"
				"OnAttackStart"
				{
					"RemoveModifier"
					{
						"ModifierName"	"modifier_immortal_crit_hit"
						"Target"
 						{
 							"Center"	"CASTER"
 							"Flags"		"DOTA_UNIT_TARGET_FLAG_INVULNERABLE"
 						}
					}
					"Random"
					{
						"Chance"	"%crit_chance"
						"OnSuccess"
						{
							"RunScript"
							{
								"ScriptFile"			"abilities/scathach/scathach_abilities"
								"Function"				"OnImmortalCrit"
							}
						}
					}
				}
			}
			"modifier_immortal_crit_hit"
			{
				"IsHidden"		"1"
				"Attributes"	"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
				"Properties"
				{
					"MODIFIER_PROPERTY_PREATTACK_CRITICALSTRIKE"	"%crit_multiply"

				}
				"OnAttackLanded"
				{
			    	"FireEffect"
			    	{
			    		"EffectName"		"particles/units/heroes/hero_juggernaut/jugg_crit_blur_impact.vpcf"
			    		"EffectAttachType"	"attach_hitloc"
			    		"Target"			"TARGET"
			    	}
			        "RemoveModifier"
			        {
			            "ModifierName"  	"modifier_immortal_crit_hit"
						"Target"
 						{
 							"Center"	"CASTER"
 							"Flags"		"DOTA_UNIT_TARGET_FLAG_INVULNERABLE"
 						}
   			        }			
				}
			}
			"modifier_immortal_evade"
			{
				"Passive"			"0"
				"IsHidden"			"1"
				"IsDebuff"			"0"
				"IsPurgable"		"0"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE | MODIFIER_ATTRIBUTE_PERMANENT"
				"Properties"
				{
					"MODIFIER_PROPERTY_EVASION_CONSTANT" "%bonus_evade"
				}
			}
			"modifier_immortal_aspd"
			{
				"Passive"			"0"
				"IsHidden"			"1"
				"IsDebuff"			"0"
				"IsPurgable"		"0"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE | MODIFIER_ATTRIBUTE_PERMANENT"
				"Properties"
				{
					"MODIFIER_PROPERTY_ATTACKSPEED_BONUS_CONSTANT" "%bonus_aspd"
				}
			}
			"modifier_immortal_revive"
			{
				"Passive"			"0"
				"IsHidden"			"0"
				"IsDebuff"			"0"
				"IsBuff"			"1"
				"IsPurgable"		"0"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE | MODIFIER_ATTRIBUTE_PERMANENT"
				"OnTakeDamage"
				// "%attack_damage" is set to the damage value after mitigation
				{
					"RunScript"
					{
						"DamageTaken"   "%attack_damage"
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						"Function"		"OnImmortalRevive"
					}
				}
			}
		}
	}
	//=================================================================================================================
	// Scathach Attribute : Primeval Rune
	//=================================================================================================================
	"scathach_attribute_primeval_rune"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/scathach/scathach_attribute_primeval_rune"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"0"
		"AbilityManaCost"				"12"

		"AbilityValues"
        {
            "bonus_armor" "10"
            "bonus_mr" "10"
            "duration" "10"
        }
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"abilities/scathach/scathach_abilities"
				"Function"		"OnPrimevalRuneAcquired"
			}
		}
	}
	//=================================================================================================================
	// Scathach Attribute : God Slayer
	//=================================================================================================================
	"scathach_attribute_god_slayer"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/scathach/scathach_attribute_god_slayer"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"0"
		"AbilityManaCost"				"15"

		"AbilityValues"
        {
            "bonus_dmg" "20"
            "cast_delay" "1.0"
            "distance" "1500"
            "base_dmg" "500"
            "bonus_agi_ratio" "15"
            "stun" "1"
            "knockback" "200"
            "spearman_agi" "1"
        }
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"abilities/scathach/scathach_abilities"
				"Function"		"OnGodSlayerAcquired"
			}
		}
	}
	//=================================================================================================================
	// Scathach Attribute : Branch of Tonelico
	//=================================================================================================================
	"scathach_attribute_branch_tonelico"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/scathach/scathach_attribute_branch_tonelico"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"0"
		"AbilityManaCost"				"17"

		"AbilityValues"
        {
            "gae_malee_bonus" "30"
            "gae_malee_threshold" "5"
            "gae_range_bonus" "400"
        }
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"abilities/scathach/scathach_abilities"
				"Function"		"OnBranchTonelicoAcquired"
			}
		}
	}
	//=================================================================================================================
	// Scathach Attribute : Wisdom of haunt ground
	//=================================================================================================================
	"scathach_attribute_wisdom_of_haunt_ground"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/scathach/scathach_attribute_wisdom_of_haunt_ground"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"0"
		"AbilityManaCost"				"19"

		"AbilityValues"
        {
            "cooldown" "60"
            "radius" "2000"
            "duration" "3"
            "true_invis_duration" "1"
        }
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"abilities/scathach/scathach_abilities"
				"Function"		"OnWisdomOfHauntGroundAcquired"
			}
		}
	}
	//=================================================================================================================
	// Scathach Attribute : Immortal
	//=================================================================================================================
	"scathach_attribute_immortal"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/scathach/scathach_attribute_immortal"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"0"
		"AbilityManaCost"				"10"

		"AbilityValues"
        {
            "bonus_agi" "3"
            "bonus_mr" "1"
            "bonus_evade" "25"
            "crit_chance" "50"
            "crit_multiply" "200"
            "bonus_aspd" "130"
            "immortal" "1"
        }
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"abilities/scathach/scathach_abilities"
				"Function"		"OnImmortalAcquired"
			}
		}
	}
	//=================================================================================================================
	// Scathach : Combo : Gate of Sky (F)
	//=================================================================================================================
	"scathach_combo_gate_of_sky"
	{
		"BaseClass"						"ability_datadriven"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		//หารูปมาใส่
		"AbilityTextureName"			"custom/scathach/scathach_combo_gate_of_sky"
		"MaxLevel"						"1"
		"AbilityCastPoint"				"1.0"
		"AbilityCooldown"				"180"
		"AbilityCastRange"				"1500"
		"AbilityManaCost"				"800"
		"AbilityCastAnimation"			"ACT_DOTA_AMBUSH"
		"AnimationPlaybackRate"			"1"
		"precache"
		{
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_luna.vsndevts"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_mars.vsndevts"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_windrunner.vsndevts"
			"particle"					"particles/custom/scathach/scathach_gate_ground.vpcf"
			"particle"					"particles/custom/scathach/scathach_gate.vpcf"
			"particle"					"particles/econ/items/windrunner/windrunner_cape_cascade/windrunner_windrun_burst_cascade.vpcf"
			"particle"					"particles/custom/scathach/gate_of_skye_field.vpcf"
			"particle"					"particles/custom/scathach/gate_of_skye_reborn.vpcf"

		}
		"AbilityValues"
        {
            "duration" "5.1"
            "range" "1500"
            "dmg" "2500"
            "mana_burn_sec" "40"
            "interval" "0.1"
            "slow_debuff" "-30"
            "cooldown" "180"
            "pull_duration" "4.0"
            "reduction" "-10"
        }
		"OnAbilityPhaseStart"
		{
			"RunScript"
			{
				"ScriptFile"	"abilities/scathach/scathach_abilities"
				"Function"		"OnGateOfSkySound"
			}
		}
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"abilities/scathach/scathach_abilities"
				"Function"		"OnGateOfSkyCast"
			}
		}
		"Modifiers"
		{
			"modifier_gate_of_sky_pull"
			{
				"Passive"			"0"
				"IsHidden"			"0"
				"IsDebuff"			"0"
				"IsPurgable"		"0"
				"OnCreated"
				{
					"RunScript"
					{
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						//"Function"		"OnGateOfSkyPull"
					}
				}
				"OnDestroy"
				{
					"RunScript"
					{
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						"Function"		"OnGateOfSkyPullStop"
					}
				}
				"ThinkInterval"  "%interval"
				"OnIntervalThink"
				{
					"RunScript"
					{
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						"Function"		"OnGateOfSkyBurnMana"
					}
				}
			}
			"modifier_gate_of_sky_pull_aura"
			{
				"Passive"			"0"
				"IsHidden"			"0"
				"IsDebuff"			"0"
				"Duration"			"%pull_duration"
				"Aura"				"modifier_gate_of_sky_pull"
				"Aura_Radius"		"%range"
				"Aura_Teams"		"DOTA_UNIT_TARGET_TEAM_ENEMY"
				"Aura_Types"		"DOTA_UNIT_TARGET_ALL"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_gate_of_sky_no_blink"
			{
				"Passive"			"0"
				"IsHidden"			"0"
				"IsDebuff"			"1"
				"IsPurgable"		"0"
				"Properties"
				{
				    "MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE" "%slow_debuff" 
				}
				"ThinkInterval"  "0.1"
				"OnIntervalThink"
				{
					"RunScript"
					{
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						"Function"		"OnGateOfSkyPull"
					}
				}
				"OnCreated"
				{
					"AttachEffect"
					{
						"Target"			"TARGET"
						"EffectName"        "particles/econ/items/windrunner/windrunner_cape_cascade/windrunner_windrun_burst_cascade.vpcf"
						"EffectAttachType"  "follow_origin"
						"ControlPoints"
						{
							"00"	"0 0 0"
						}
					}
				}
			}
			"modifier_gate_of_sky_buff"
			{
				"Passive"			"0"
				"IsHidden"			"0"
				"IsDebuff"			"0"
				"IsBuff"			"1"
				"IsPurgable"		"0"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
				"Properties"
				{
					"MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE" "%reduction"
				}
			}
			"modifier_gate_of_sky_check"
			{
				"Passive"			"0"
				"IsHidden"			"0"
				"IsDebuff"			"0"
				"Aura"				"modifier_gate_of_sky_no_blink"
				"Aura_Radius"		"%range"
				"Duration"			"%duration"
				"Aura_Teams"		"DOTA_UNIT_TARGET_TEAM_ENEMY"
				"Aura_Types"		"DOTA_UNIT_TARGET_ALL"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			
				"OnCreated"
				{
					"RunScript"
					{
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						"Function"		"OnGateOfSkyCreate"
					}
				}
				"OnDestroy"
				{
					"RunScript"
					{
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						"Function"		"OnGateOfSkyDestroy"
					}
				}
				"OnDeath"
				{
					"RunScript"
					{
						"ScriptFile"	"abilities/scathach/scathach_abilities"
						"Function"		"OnGateOfSkyDeath"
					}
				}
			}
			"modifier_gate_of_sky_cooldown"
			{
				"IsPurgable"		"0"
				"IsBuff"			"0"
				"IsHidden"			"0"
				"IsDebuff"			"1"
				"IsPurgable"		"0"
				"Duration"			"%cooldown"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE | MODIFIER_ATTRIBUTE_PERMANENT"
			}
		}
	}
	//=================================================================================================================
	// Scathach : Combo : Double Gae Bolg Alternative (R)
	//=================================================================================================================
	"scathach_combo_double_gae_bolg"
	{
		"BaseClass"						"ability_datadriven"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		//หารูปมาใส่
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_CREEP"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/scathach/scathach_combo_double_gae_bolg"
		"MaxLevel"						"1"
		"AbilityCastPoint"				"0.8"
		"AbilityCooldown"				"200"
		"AbilityManaCost"				"800"
		"AbilityCastRange"				"400"
		"AbilityCastRangeBuffer"		"600"
		"AbilityCastAnimation"			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate"			"0.7"
		"precache"
		{
			"particle"		"particles/units/heroes/hero_chaos_knight/chaos_knight_reality_rift.vpcf"
			"particle"		"particles/units/heroes/hero_centaur/centaur_double_edge.vpcf"
			"particle"		"particles/units/heroes/hero_axe/axe_culling_blade_kill.vpcf"
			"particle"		"particles/custom/lancer/lancer_heart_break_txt.vpcf"
			"particle"		"particles/items_fx/dagon.vpcf"
			"particle"		"particles/custom/diarmuid/gae_dearg_slash.vpcf"
			"particle"		"particles/units/heroes/hero_huskar/huskar_burning_spear.vpcf"
			"particle"		"particles/custom/lancer/lancer_gae_bolg_projectile.vpcf"
			"particle"		"particles/units/heroes/hero_warlock/warlock_rainofchaos_start_breakout_fallback_mid.vpcf"
			"particle"		"particles/units/heroes/hero_elder_titan/elder_titan_echo_stomp_cracks.vpcf"
			"particle"		"particles/custom/lancer/lancer_gae_bolg_hit.vpcf"
			"particle"  	"particles/custom/lancer/soaring/spear.vpcf"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_lion.vsndevts"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_drowranger.vsndevts"
		}
		"AbilityValues"
        {
            "gae_malee_dmg" "200"
            "gae_thrown_dmg" "600"
            "radius" "1200"
            "cooldown" "200"
        }
		"OnAbilityPhaseStart"
		{
			"RunScript"
			{
				"ScriptFile"	"abilities/scathach/scathach_abilities"
				"Function"		"OnGaeComboCast"
			}
		}
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"abilities/scathach/scathach_abilities"
				"Function"		"OnGaeComboStart"
			}
		}
		"OnProjectileHitUnit"
		{
			"DeleteOnHit"	"1"
			"RunScript"
			{
				"ScriptFile"	"abilities/scathach/scathach_abilities"
				"Function"		"OnGaeComboHit"
			}
		}
		"Modifiers"
		{
			"modifier_combo_double_gae_bolg_cooldown"
			{
				"IsPurgable"		"0"
				"IsBuff"			"0"
				"IsHidden"			"0"
				"IsDebuff"			"1"
				"IsPurgable"		"0"
				"Duration"			"%cooldown"
				"Attributes"		"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE | MODIFIER_ATTRIBUTE_PERMANENT" 
			}
		}
	}
}