"DOTAAbilities"
{
	//=======================================★★★★★
	// Scathach: Funeral Gait - Fangs of Earth (W)
	//=======================================★★★★★
	"scathach_gait_one"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/scathach/scathach_gait_one"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityType"					"DOTA_ABILITY_TYPE_BASIC"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_ITEM_PICKUP"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"AbilityTextureName"			"custom/scathach/scathach_gait"
		"LinkedAbilities"				"scathach_gait_two scathach_gait_three"
		
		// Ability Stats		//------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"500"
		"AbilityCastPoint"				"0.2"
		"AbilityCooldown"				"20"
		"AbilityManaCost"				"200"
		
		// Precache		//------------------------------------------------------------------------------------------------------------
		"precache"
		{
			"particle"			"particles/custom/scathach/scathach_gait_one.vpcf"
			"particle"			"particles/custom/scathach/scathach_gait_one_second_swing.vpcf"
			"particle"			"particles/custom/lu_bu/assault_two_crit.vpcf"
		}
		
		// Ability Special		//------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "damage" "150 180 210 240 270"
            "angle" "180"
            "radius" "500"
            "knockback_duration" "0.3"
            "knockback_distance" "75"
            "activity_duration" "4"
            "root_duration" "1"
            "agi_scale" "1"
        }
	}
}