"DOTAAbilities"
{
	//========================================
	// Verg Avesta
	//========================================
	"angra_mainyu_verg_avesta"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/angra_mainyu/angra_mainyu_verg_avesta"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/avenger_verg_avesta"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_6"
		"AbilityType"					"DOTA_ABILITY_TYPE_ULTIMATE"
		"AbilityUnitTargetFlags"		"DOTA_UNIT_TARGET_FLAG_INVULNERABLE | DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"

		"precache"
		{
			"particle"		"particles/econ/items/sniper/sniper_charlie/sniper_assassinate_impact_blood_charlie.vpcf"
			"particle"		"particles/units/heroes/hero_nevermore/nevermore_shadowraze.vpcf"
			"particle"		"particles/custom/avenger/avenger_verg_avesta.vpcf"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_witchdoctor.vsndevts"
		}

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"1"
		"AbilityCastPoint"				"0.7"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"800"
		
		"AbilityValues"
        {
            //"multiplier" "100 110 120 130 140"
            "damage"	"400 475 550 625 700"
            //"reset_delay" "4 5.25 6.5 7.75 9"
            //"angra_regen" "100"
            //"mana_restore_percentage" "33"
            //"marker_duration" "10"
            //"return_bonus" "40"
            "radius" "700"
            "delay" "0.5"
            "lost_health_amp" "50"
        }
	}

}