#base "angra_mainyu_verg_avesta.kv"

"DOTAAbilities"
{
	//========================================
	// Avenger : Pool of Corruption
	//========================================
	"angra_puddle"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/angra_mainyu/angra_puddle"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET|DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/angra/puddle"
		"MaxLevel"						"5"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"2"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_6"
		"AbilityType"					"ABILITY_TYPE_ULTIMATE"
		"AbilityUnitTargetFlags"		"DOTA_UNIT_TARGET_FLAG_INVULNERABLE | DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"

		"precache"
		{
			"particle"		"particles/angra_jopa_pool.vpcf"
			"particle"		"particles/units/heroes/hero_clinkz/clinkz_tar_bomb_debuff.vpcf"
		}

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"18"
		"AbilityCastPoint"				"0.4"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"400"
		
		"AbilityValues"
        {
        	"duration" "6"
        	"damage" "50 62.5 75 87.5 100"
        	"heal_per_tick" "20 25 30 35 40"
            "radius" "400"
         	"lock_duration" "1 1.25 1.5 1.75 2"
         	"revoke_duration" "1"
         	"puddle_cooldown"	"1"
        }
	}

	//========================================
	// Murderous instinct
	//========================================
	"angra_murderous"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/angra_mainyu/angra_murderous"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityTextureName"			"custom/avenger_murderous_instinct"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_2"
		"AbilityType"					"DOTA_ABILITY_TYPE_BASIC"
		"LinkedAbilities"				"avenger_unlimited_remains"
		"precache"
		{
			"particle"			"particles/units/heroes/hero_broodmother/broodmother_spiderlings_spawn.vpcf"
			"particle"			"particles/units/heroes/hero_ogre_magi/ogre_magi_bloodlust_buff.vpcf"
			"particle"			"particles/units/heroes/hero_juggernaut/jugg_crit_blur_impact.vpcf"
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_ogre_magi.vsndevts"
		}

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"10"
		"AbilityCastPoint"				"0.1"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"100"
		
		"AbilityValues"
        {
            "duration" "10"
            "mr"	"6 7 8 9 10"
            "armor" "2 2.5 3 3.5 4"
            "regen" "30 37.5 45 52.5 60"
            "mana" "30 37.5 45 52.5 60"
        }
	}



	//=================================================================================================================
	// Mainyu Self Amp Passive
	//=================================================================================================================
	"angra_mainyu_demon_incarnate_passive"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/angra_mainyu/angra_mainyu_demon_incarnate_passive"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/gawain_attribute_blessing_of_fairy"
		"MaxLevel"						"1"

		"AbilityValues"
        {
            "damage_amp" "0"
        }
	}

	//================================================
	// Avenger Passive for autoattack
	//================================================
	"avenger_autoattack"
	{
		"AbilityBehavior" 		"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"BaseClass" 					"ability_lua"
		"ScriptFile" 					"abilities/avenger/avenger_autoattack"
		"AbilityTextureName"            "custom/diarmuid_minds_eye"
		"MaxLevel"                      "1"
		"precache"
		{
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_phantom_assassin.vsndevts"
		}
		
	}
	//=====================================
	// Avenger : Dark Passage
	//=====================================
	"avenger_dark_passage"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
        "ScriptFile"                    "abilities/avenger/dark_passage"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityTextureName"			"custom/avenger_dark_passage"
		"MaxLevel"						"1"

		"precache"
		{
			"particle"		"particles/units/heroes/hero_phantom_assassin/phantom_assassin_phantom_strike_end.vpcf"
			"particle"		"particles/custom/avenger/avenger_dark_passage_start.vpcf"
			"particle"		"particles/custom/avenger/avenger_dark_passage_start_trueform.vpcf"
			"particle"		"particles/custom/avenger/avenger_dark_passage_end.vpcf"
			"particle"		"particles/custom/avenger/avenger_dark_passage_end_trueform.vpcf"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_antimage.vsndevts"
		}

		// Casting
		//-------------------------------------------------------------------------------------------------------------
        "AbilityCastRange"              "0"
        "AbilityCastPoint"              "0.1"
        "AbilityCastAnimation"          "ACT_DOTA_CAST_ABILITY_6"
        "AnimationPlaybackRate" 		"3.0"
		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"8"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"0"
		
		"AbilityValues"
        {
            "health_cost" "50"
            "range" "500"
            "reduced_cooldown" "5"
            "penalty_cooldown" "30"
        }
		
		//"OnSpellStart"
		//{
		//	"RunScript"
		//	{
		//	 	"ScriptFile"	"avenger_ability"
		//	 	"Function"		"OnDPStart"
		//	 	"Target"		"POINT"
		//	 	"Range"			"%range"
		//	 	"HealthCost"	"%health_cost"
		//	}
		//	"FireSound"
		//	{
		//		"EffectName"	"Hero_ShadowDemon.ShadowPoison.Release"
		//		"Target"		"CASTER"
		//	}
		//	"AttachEffect"
		//	{
		//		"EffectName"		"particles/units/heroes/hero_phantom_assassin/phantom_assassin_phantom_strike_end.vpcf"
		//		"EffectAttachType"	"follow_origin"
		//		"Target"			"CASTER"
		//	}
		//}

		//"Modifiers"
		//{
		//	"modifier_dark_passage"
		//	{
		//		"IsHidden"		"0"
		//		"IsDebuff"		"1"
		//		"Duration"		"15.0"
		//		"Attributes"	"MODIFIER_ATTRIBUTE_MULTIPLE"

		//		"OnRespawn"
		//		{
		//			 "RunScript"
		//			 {
		//			 	"ScriptFile"	"avenger_ability"
		//			 	"Function"	"OnDarkPassageRespawn"
		//			 }
		//		}
		//	}
		//}
	}

	//========================================
	// Avenger : Murderous Instinct
	//========================================

	//========================================
	// Avenger : Unlimited Remains
	//========================================
	"avenger_unlimited_remains"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/avenger/avenger_unlimited_remains"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/avenger_unlimited_remains"
		"MaxLevel"						"5"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_6"

		"precache"
		{
			"particle"		"particles/units/heroes/hero_nevermore/nevermore_shadowraze.vpcf"
			"model"			"models/avenger/trueform/trueform.vmdl"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_nevermore.vsndevts"
			"particle"			"particles/units/heroes/hero_axe/axe_beserkers_call_owner.vpcf"
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_broodmother.vsndevts"
		}
		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"7"
		"AbilityCastPoint"				"0.2"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"100"
		
		"AbilityValues"
        {
            "spawn_number" "5"
            "damage" "100 125 150 175 200"
            //"multiply_period" "99"
        }
		

	}

	//================================================
	// Unlimited Remain passive
	//================================================
	"avenger_remain_passive"
	{
		"AbilityBehavior" 		"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"BaseClass" 					"ability_lua"
		"ScriptFile" 					"abilities/avenger/avenger_remain_passive"
		"AbilityTextureName"            "custom/avenger_unlimited_remains"
		"MaxLevel"                      "5"


		"AbilityValues"
        {
            "damage" "100 125 150 175 200"
            //"multiply_period" "99"
        }	
	}

	//=====================================
	// Avenger : Tawrich Zarich
	//=====================================
	"avenger_tawrich_zarich"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/avenger/avenger_tawrich_zarich"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetFlags"		"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityTextureName"			"custom/avenger_tawrich_zarich"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_2"
		
		"AbilityCastPoint"				"0.3"
		"AbilityCastRange"				"400"
		"AbilityCastRangeBuffer"		"100"
		"AbilityCooldown"				"16"
		"AbilityManaCost"				"200"

		"LinkedAbilities"				"avenger_vengeance_mark"
		
		"precache"
		{
			"particle"			"particles/econ/courier/courier_mechjaw/mechjaw_death_sparks.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_bounty_hunter.vsndevts"
		}

		"AbilityValues"
        {
            "crit_dmg" "130 145 160 175 190"
            "duration" "1 1.25 1.5 1.75 2"
            "slow_duration" "2"
            "slow_amount" "50"
            "num_attacks" "6"
            "damage_per_attack" "60 75 90 105 120"
        }

	}

	//=====================================
	// Avenger : Vengeance Mark
	//=====================================
	"avenger_vengeance_mark"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/avenger/avenger_vengeance_mark"
		"MaxLevel"						"5"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/avenger_vengence_mark"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_6"
		
		"AbilityCastPoint"				"0.2"
		"AbilityCastRange"				"300"
		"AbilityCastRangeBuffer"		"100"
		"AbilityCooldown"				"15"
		"AbilityManaCost"				"200"
		
		"precache"
		{
			"particle"			"particles/units/heroes/hero_doom_bringer/doom_bringer_lvl_death_bonus.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_doombringer.vsndevts"
		}

		"AbilityValues"
        {
            "damage" "400 500 600 700 800"
            //"delay" "0.5"
            //"return_percentage" "60 70 80 90 100"
            "duration" "1 1.25 1.5 1.75 2"
        }

	}

	//=====================================
	// Avenger : Blood Mark
	//=====================================
	"avenger_blood_mark"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/avenger/avenger_blood_mark"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityTextureName"			"custom/avenger_blood_mark"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_6"
		
		"AbilityCastPoint"				"0.3"
		"AbilityCastRange"				"600"
		"AbilityCastRangeBuffer"		"150"
		"AbilityCooldown"				"20"
		"AbilityManaCost"				"200"
		
		"precache"
		{
			"particle"			"particles/units/heroes/hero_doom_bringer/doom_bringer_lvl_death_bonus.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_doombringer.vsndevts"
		}

		"AbilityValues"
        {
            "damage" 	"500"
            "heal"		"500"
        }


	}
	//========================================
	// Avenger : True Form
	//========================================
	"avenger_true_form"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/avenger/avenger_true_form"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_AUTOCAST"
		"AbilityTextureName"			"custom/avenger_true_form"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"22"
		"AbilityCastPoint"				"0"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"0"

		"LinkedAbilities"				"angra_puddle"

		"precache"
		{
			"model"		"models/avenger/trueform/trueform.vmdl"
			"particle"	"particles/units/heroes/hero_terrorblade/terrorblade_metamorphosis.vpcf"
			"particle"	"particles/units/heroes/hero_terrorblade/terrorblade_metamorphosis_transform.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_terrorblade.vsndevts"
		}
		
		"AbilityValues"
        {
            "bonus_health" "375 469 562 656 750"
            "bonus_healing_power" "50"
            "duration" "12"
        }
		
	}

	//========================================
	// Avenger : Demon Core
	//========================================

	//========================================
	// Avenger : Verg Avesta
	//========================================

	//========================================
	// Avenger : Endless Loop(combo)
	//========================================
	"avenger_endless_loop"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/avenger/avenger_endless_loop"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/avenger_endless_loop"
		"MaxLevel"						"1"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_6"
		"precache"
		{
			"particle"		"particles/econ/items/sniper/sniper_charlie/sniper_assassinate_impact_blood_charlie.vpcf"
			"particle"		"particles/units/heroes/hero_nevermore/nevermore_shadowraze.vpcf"
			"particle"		"particles/units/heroes/hero_abaddon/abaddon_borrowed_time.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_nightstalker.vsndevts"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_life_stealer.vsndevts"
		}

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"140"
		"AbilityCastPoint"				"0.36"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"0"
		
		"AbilityValues"
        {
            "duration" "12.0"
        }
		

	}

	//=======================================
	// Avenger Attribute : Improve Dark Passage
	//=======================================
	"avenger_attribute_improve_dark_passage"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/avenger/avenger_attribute_improve_dark_passage"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/avenger_attribute_improve_dark_passage"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"8"

		"precache"
		{
		}

		"AbilityValues"
        {
            "cooldown" "5"
            "range" "1000"
        }
		
	}

	//=======================================
	// Avenger Attribute : Blood Mark
	//=======================================
	"avenger_attribute_blood_mark"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/avenger/avenger_attribute_blood_mark"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/avenger_blood_mark"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"8"
		

		"precache"
		{
		}

		"AbilityValues"
        {
           	"damage" 	"500"
            "heal"		"500"
        }
		
	}

	//=======================================
	// Avenger Attribute : Overdrive
	//=======================================
	"avenger_attribute_overdrive"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/avenger/avenger_attribute_overdrive"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/avenger_attribute_overdrive"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"10"

		"precache"
		{
		}

		"AbilityValues"
        {
            "consec_time" "2"
            "initial_aspd" "20"
            "max_aspd" "640"
        }
		
	}

	//=================================================================================================================
	// Avenger : Overdrive
	//=================================================================================================================
	"avenger_overdrive"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/avenger/avenger_overdrive"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/avenger_overdrive"
		"MaxLevel"						"1"
		
		"AbilityValues"
        {
            "aspd_bonus" "80"
            "duration" "2"
        }
		
	}


	//=======================================
	// Avenger Attribute : Demon Incarnate
	//=======================================
	"avenger_attribute_demon_incarnate"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/avenger/avenger_attribute_demon_incarnate"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/avenger_attribute_demon_incarnate"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"12"

		"precache"
		{
		}

		"AbilityValues"
        {
            "return_bonus" "30"
            "trueform_cdr" "4.0"
        }
		
	}

	//=======================================
	// Avenger : Vengeful Incarnate
	//=======================================
	"angra_revenge"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/angra_mainyu/angra_revenge"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE|DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"MaxLevel"						"1"
		"RequiredLevel"					"25"
		
		"AbilityValues"
        {
            "radius" "500"
        }
	}


	//=======================================
	// Avenger Attribute : Vengeful Incarnate
	//=======================================
	"avenger_attribute_revenge"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/avenger/avenger_attribute_revenge"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/angra/revenge"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"6"


		"AbilityValues"
        {
            "return_bonus" "30"
            "trueform_cdr" "4.0"
        }
		
	}

	// [restored] возвращён после ошибочной чистки
}