"DOTAAbilities"
{
	//================================================
	// Diarmuid Passive for autoattack
	//================================================


	//========================================
	// Diarmuid - Love Spot
	//========================================

	//=================================================================================================================
	// Diarmuid : Warrior's Charge
	//=================================================================================================================
	//========================================
	// Diarmuid - Double Spearsmanship
	//========================================
	"diarmuid_double_spearsmanship"
	{
		"BaseClass"						"ability_datadriven"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityTextureName"			"custom/diarmuid_double_spearsmanship"
		"MaxLevel"						"5"
		"LevelsBetweenUpgrades"			"1"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_2"
		"precache"
		{
			"particle"			"particles/units/heroes/hero_invoker/invoker_alacrity_buff.vpcf"
			"particle"		"particles/custom/diarmuid/diarmuid_red_trail.vpcf"
			"particle"		"particles/custom/diarmuid/diarmuid_yellow_trail.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_invoker.vsndevts"
		}

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"19"
		"AbilityCastPoint"				"0.3"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"200"
		
		"AbilityValues"
        {
            "duration" "12.0"
            "proc_chance" "20 30 40 50 60"
            "proc_chance_combo" "40 60 80 100 100"
        }
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"		"diarmuid_ability"
				"Function"			"OnDSStart"
				"Duration"		"%duration"	
			}
			"FireSound"
			{
				"EffectName"		"Hero_Invoker.Alacrity"
				"Target"			"CASTER"
			}
		}

		"Modifiers"
		{
			"modifier_double_spearsmanship"
			{
				"EffectName"		"particles/units/heroes/hero_invoker/invoker_alacrity_buff.vpcf"
				"EffectAttachType"	"follow_overhead"

				"OnAttackLanded"
				{
					"Random"
					{
						"Chance"	"%proc_chance"
						"OnSuccess"
						{
							"RunScript"
							{
								"ScriptFile"		"diarmuid_ability"
								"Function"			"OnDSLanded"
							}
						}
					}
				}
				"Properties"
				{
					//"MODIFIER_PROPERTY_BASE_ATTACK_TIME_CONSTANT"		"%bat"
				}		
			}
			"modifier_rampant_warrior_combo"
			{
				"EffectName"		"particles/units/heroes/hero_invoker/invoker_alacrity_buff.vpcf"
				"EffectAttachType"	"follow_overhead"
				"OnCreated"
				{
					"AttachEffect"
					{
						"Target"	"CASTER"
						"EffectName"	"particles/custom/diarmuid/diarmuid_red_trail.vpcf"
						"EffectAttachType"	"start_at_customorigin"
						"ControlPointEntities"
						{
							"CASTER"	"attach_weapon1"
						}
					}

					"AttachEffect"
					{
						"Target"	"CASTER"
						"EffectName"	"particles/custom/diarmuid/diarmuid_yellow_trail.vpcf"
						"EffectAttachType"	"start_at_customorigin"
						"ControlPointEntities"
						{
							"CASTER"	"attach_weapon2"
						}
					}


				}

				"OnAttackLanded"
				{
					"Random"
					{
						"Chance"	"%proc_chance_combo"
						"OnSuccess"
						{
							"RunScript"
							{
								"ScriptFile"		"diarmuid_ability"
								"Function"			"OnDSLanded"
							}
						}
					}
				}
				"Properties"
				{
					//"MODIFIER_PROPERTY_BASE_ATTACK_TIME_CONSTANT"		"%bat"
				}		
			}
		}
	}

	//========================================
	// Diarmuid - Rampant Warrior
	//========================================
	"diarmuid_rampant_warrior"
	{
		"BaseClass"						"ability_datadriven"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/diarmuid_rampant_warrior"
		"MaxLevel"						"1"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_2"
		"precache"
		{
			"particle"		"particles/units/heroes/hero_juggernaut/jugg_crit_blur_impact.vpcf"
			"particle"		"particles/units/heroes/hero_ursa/ursa_enrage_buff.vpcf"
			"particle"		"particles/items_fx/aegis_respawn.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_clinkz.vsndevts"
		}

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"100"
		"AbilityCastPoint"				"0.3"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"200"
		
		"AbilityValues"
        {
            "duration" "12.0"
            "crit_damage" "175.0"
            "duration_penalty" "4.0"
        }
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"		"diarmuid_ability"
				"Function"			"OnRampantWarriorStart"
				"Duration"		"%duration"	
			}
		}

		"Modifiers"
		{
			"modifier_rampant_warrior_cooldown"
			{
				"IsDebuff"	"1"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}

			"modifier_rampant_warrior"
			{
				"EffectName"		"particles/units/heroes/hero_ursa/ursa_enrage_buff.vpcf"
				"EffectAttachType"	"follow_origin"		
				"OnAttackStart"
				{
					"RemoveModifier"
					{
						"ModifierName"	"modifier_rampant_warrior_crit_hit"
						"Target"
 						{
 							"Center"	"CASTER"
 							"Flags"		"DOTA_UNIT_TARGET_FLAG_INVULNERABLE"
 						}
					}

					"Random"
					{
						"Chance"	"100"
						"OnSuccess"
						{
							"RunScript"
							{
								"ScriptFile"		"diarmuid_ability"
								"Function"			"OnRampantWarriorCrit"
							}
						}
					}
				}
			}

			"modifier_rampant_warrior_crit_hit"
			{
				"IsHidden"		"1"
				"Attributes"	"MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
				"Properties"
				{
					"MODIFIER_PROPERTY_PREATTACK_CRITICALSTRIKE" "%crit_damage"
				}
				"OnAttackLanded"
				{
			    	"FireEffect"
			    	{
			    		"EffectName"		"particles/units/heroes/hero_juggernaut/jugg_crit_blur_impact.vpcf"
			    		"EffectAttachType"	"attach_hitloc"
			    		"Target"			"TARGET"
			    	}
			        "RemoveModifier"
			        {
			            "ModifierName"  	"modifier_rampant_warrior_crit_hit"
						"Target"
 						{
 							"Center"	"CASTER"
 							"Flags"		"DOTA_UNIT_TARGET_FLAG_INVULNERABLE"
 						}   
			        }			
				}
			}
		}
	}

	//=================================================================================================================
	// Diarmuid : Gae Buidhe
	//=================================================================================================================
	"diarmuid_gae_buidhe"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_CREEP"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/diarmuid_gae_buidhe"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_4"
		"AnimationPlaybackRate" 		"1.2"
		
		"precache"
		{
			"particle"		"particles/units/heroes/hero_chaos_knight/chaos_knight_reality_rift.vpcf"
			"particle"		"particles/units/heroes/hero_axe/axe_culling_blade_kill.vpcf"
			"particle"		"particles/custom/diarmuid/diarmuid_gae_cast.vpcf"
			"particle"		"particles/custom/diarmuid/diarmuid_gae_buidhe.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_lion.vsndevts"
			"particle"		"particles/units/heroes/hero_ogre_magi/ogre_magi_bloodlust_buff_symbol.vpcf"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"250"
		"AbilityCastRangeBuffer"		"75"
		"AbilityCastPoint"				"0.8"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"21.0"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"500"
		
		"AbilityValues"
        {
            "delay" "1.0"
            "damage" "500 625 750 875 1000"
            "number_stacks" "10 11 12 13 14"
            "unit_reduction" "50"
            "health_reduction_TT" "500 550 600 650 700"
            "range" "250"
            "cast_time" "0.8"
            "bleed_duration" "20"
        }
		
		"OnAbilityPhaseStart"
		{
			"RunScript"
			{
				"ScriptFile"	"diarmuid_ability"
				"Function"		"OnGaeCastStart"
				"CastTime"		"%cast_time"
			}
		}
		"OnSpellStart"
		{
			 "RunScript"
			 {
			 	"ScriptFile"	"diarmuid_ability"
			 	"Function"		"OnBuidheStart"
			 	"Damage"		"%damage"
			 	"nStacks"		"%number_stacks"
			 	"unitReduction"	"%unit_reduction"
			 	"CastTime"		"%cast_time"
			 }
		}
		"Modifiers"
		{
			"modifier_gae_buidhe"
			{
				"IsHidden"		"0"
				"IsDebuff"		"1"
				"Attributes"	"MODIFIER_ATTRIBUTE_MULTIPLE | MODIFIER_ATTRIBUTE_PERMANENT"
				"OnDeath"
				{
					"RunScript"
					{
					 	"ScriptFile"	"diarmuid_ability"
					 	"Function"		"OnBuidheBearerDeath"
					}
				}
			}
			"modifier_gae_buidhe_passive"
			{
				"Passive"	"1"
				"IsHidden"	"1"
				"OnDeath"
				{
					 "RunScript"
					 {
					 	"ScriptFile"	"diarmuid_ability"
					 	"Function"		"OnBuidheOwnerDeath"
					 }
				}
				"OnRespawn"
				{
					 "RunScript"
					 {
					 	"ScriptFile"	"diarmuid_ability"
					 	"Function"		"OnBuidheOwnerDeath"
					 }
				}
			}
			"modifier_mark_of_mortality"
			{
				"EffectName" 	"particles/units/heroes/hero_bounty_hunter/bounty_hunter_track_trail_circle.vpcf"
	            "EffectAttachType" "follow_origin"	
				"Duration"		"10"
				"IsDebuff"		"1"
			}
			"modifier_diarmuid_gae_buidhe_anim"
			{
				"IsHidden"			"1"
				"Duration"			"1.0"
				"OverrideAnimation"		"ACT_DOTA_CAST_ABILITY_4_END"
				"Properties"
				{
					"MODIFIER_PROPERTY_OVERRIDE_ANIMATION_RATE"		"2.0"
				}
			}			
		}
	}

	//=================================================================================================================
	// Diarmuid : Gae Dearg
	//=================================================================================================================
	"diarmuid_gae_dearg"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_CREEP"
		"AbilityUnitTargetFlags"		"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PURE"
		"AbilityTextureName"			"custom/diarmuid_gae_dearg"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AbilityType"					"ABILITY_TYPE_ULTIMATE"
		"AnimationPlaybackRate" 		"1.0"
		
		"precache"
		{
			"particle"		"particles/units/heroes/hero_chaos_knight/chaos_knight_reality_rift.vpcf"
			"particle"		"particles/units/heroes/hero_axe/axe_culling_blade_kill.vpcf"
			"particle"		"particles/items_fx/dagon.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_lion.vsndevts"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"500"
		"AbilityCastRangeBuffer"		"75"
		"AbilityCastPoint"				"0.9"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"27.0"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"500"
		
		"AbilityValues"
        {
            "delay" "1.1"
            "min_damage" "500 575 650 725 800"
            "max_damage" "700 850 950 1100 1250"
            "range" "500"
            "cast_time" "0.9"
            "number_stacks" "5 6 7 8 9"
            "unit_reduction" "100"
            "mortality_pct" "20"
        }
		
		"OnAbilityPhaseStart"
		{
			"RunScript"
			{
				"ScriptFile"	"diarmuid_ability"
				"Function"		"OnGaeCastStart"
				"CastTime"		"%cast_time"
			}
		}
		"OnSpellStart"
		{
			 "RunScript"
			 {
			 	"ScriptFile"	"diarmuid_ability"
			 	"Function"		"OnDeargStart"
			 	"MinDamage"		"%min_damage"
			 	"MaxDamage"		"%max_damage"
			 	"nStacks"		"%number_stacks"	//for casting dearg with doublespear on
			 	"unitReduction"	"%unit_reduction"	//for casting dearg with doublespear on
			 	"CastTime"		"%cast_time"
			 }
		}
		"Modifiers"
		{
			"modifier_diarmuid_gae_dearg_anim"
			{
				"IsHidden"			"1"
				"Duration"			"1.0"
				"OverrideAnimation"		"ACT_DOTA_CAST_ABILITY_3_END"
				"Properties"
				{
					"MODIFIER_PROPERTY_OVERRIDE_ANIMATION_RATE"		"2.0"
				}
			}	
		}
	}


	//=======================================
	// Diarmuid Attribute : Improve Love Spot
	//=======================================

	//=======================================
	// Diarmuid Attribute : Mind's Eye
	//=======================================
	"diarmuid_attribute_minds_eye"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/diarmuid_attribute_minds_eye"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"12"

		"precache"
		{
		}

		"AbilityValues"
        {
        }
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"diarmuid_ability"
				"Function"		"OnMindEyeAcquired"
			}
		}
	}


	//================================================
	// Diarmuid Attribute : Mind's Eye
	//================================================
	"diarmuid_minds_eye"
	{
		"AbilityBehavior" 		"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"BaseClass" 					"ability_datadriven"
		"AbilityTextureName"            "custom/diarmuid_attribute_minds_eye"
		"MaxLevel"                      "1"
		
		"Modifiers"
		{
			"diarmuid_minds_eye_passive"
			{
				"Passive"                        "1"
				"IsHidden"                        "0"
				"OnCreated"
				{
					"RunScript"
					{
						"ScriptFile"	"diarmuid_ability"
						"Function"		"OnMindEyeStart"
					}
				}
				//"OnRespawn"
				//{
				//	"RunScript"
				//	{
				//		"ScriptFile"	"diarmuid_ability"
				//		"Function"		"OnMindEyeStart"
				//	}
				//}	
				//"OnDeath"
				//{
				//	"RunScript"
				//	{
				//		"ScriptFile"	"diarmuid_ability"
				//		"Function"		"OnMindEyeEnd"
				//	}					
				//}
		  	}
		}
	}

	//=======================================
	// Diarmuid Attribute : Golden Rose of Mortality
	//=======================================

	//=======================================
	// Diarmuid Attribute : Crimson Rose of Exorcism
	//=======================================



	//=======================================
	// Diarmuid Attribute : Double Spear Strike
	//=======================================

	//========================================
	// Diarmuid : Double Spear Strike
	//========================================

	// [restored] возвращён после ошибочной чистки
	// [restored] возвращён после ошибочной чистки
	// [restored] возвращён после ошибочной чистки
}