"DOTAAbilities"
{
   
   	//=======================================
	// Demon king nobunaga - hueta (Q)
	//=======================================
	"demon_king_beam"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/demon_king_nobunaga/demon_king_beam"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET|DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL" 
		"AbilityTextureName"			"custom/maou/q"

		"AbilityCastRange"				"1000"
		"AbilityCastRangeBuffer"		"100"
		"AbilityCastPoint"				"0.2"
		"AbilityCooldown"				"5"
		"AbilityManaCost"				"100"
		"precache"
		{
			"particle"		"particles/maou/hand_beam/maou_hand_beam_.vpcf"

			"particle"		"particles/maou/ground_slam/maou_ground_slam_.vpcf"

			"particle"		"particles/maou/maou_nobu_gun.vpcf"


		}
		"AbilityValues"
		{
			"slam_damage"				"200 250 300 350 400"
			"slam_aoe_radius"						"400"
			"slam_air_dur"							"0.3"

			"beam_damage"						"300 375 450 525 600"
			"beam_search_radius"				"500"
			"beam_max_bounces"						"3"
			"beam_width"						"150"

			"gun_max_range"						"1500"
			"gun_laser_width"					"200"
			"guns_damage"					"300 375 450 525 600"
			"guns_delay"					"0.2"

		}
	}


	//=======================================
	// Demon king nobunaga - Extermination (W)
	//=======================================
	"demon_king_extermination"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/demon_king_nobunaga/demon_king_extermination"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL" 
		"AbilityTextureName"			"custom/maou/w"

		"AbilityCastRange"				"250"
		"AbilityCastRangeBuffer"		"0"
		"AbilityCastPoint"				"1"
		"AbilityCooldown"				"15 14 13 12 11"
		"AbilityManaCost"				"200"
		"AbilityCastAnimation" 			"ACT_DOTA_ITEM_PICKUP"
		"AnimationPlaybackRate" 		"1"
		"precache"
		{
			"particle"		"particles/demon_king_nobunaga/extermination_cast_base.vpcf"
			"particle"		"particles/demon_king_nobunaga/extermination_cast_hand_smoke.vpcf"
			"particle"		"particles/muramasa/muramasa_rush_burn.vpcf"
			"particle"		"particles/maou/w_hit/maou_w_hit.vpcf"
			"particle"		"particles/maou_w_slash/maou_w_slash.vpcf"
			"particle"		"particles/demon_king_nobunaga/fire_ground.vpcf"
		}
		"AbilityValues"
		{
			"damage_hit"				"500 600 700 800 900"
			"lock_duration"				"0.8 1 1.2 1.4 1.6"
			"stun_duration"				"0.3"
			"burn_dps"			"100 125 150 175 200"
			"burn_duration"			"2.5"
			"dash_distance_trigger"				"250" // castrange + buffer, not active
			"dash_distance_max"					"1300"
			"damage_dash"			"300 350 400 450 500"
			"dash_delay"				"0.25"
			"dash_speed"				"2500"

		}
	}


	//=======================================
	// Demon king nobunaga - BLINK (E)
	//=======================================
	"demon_king_blink"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/demon_king_nobunaga/demon_king_blink"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT|DOTA_ABILITY_BEHAVIOR_IMMEDIATE|DOTA_ABILITY_BEHAVIOR_AOE|DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL" 
		"AbilityTextureName"			"custom/maou/e"

		"AbilityCastRange"				"400"
		"AbilityCooldown"				"18"
		"AbilityManaCost"				"400"
		"precache"
		{
			"particle"		"particles/maou/maou_invis.vpcf"

			"particle"		"particles/maou_blink/maou_blink_main.vpcf"
			"particle"		"particles/maou_blink/maou_blink_main_ground.vpcf"
			"particle"		"particles/maou_blink/maou_blink_land.vpcf"
			"particle"		"particles/maou_blink/maou_burning_hand.vpcf"

		}
		"AbilityValues"
		{
			"damage_total"				"600 750 900 1050 1200"
			"invis_dur"					"0.5"
			"range"						"400"
			"total_duration"						"0.4"
			"damage_ticks"						"4"
			"aoe_radius"						"400"
		}
	}


	//=======================================
	// Demon king nobunaga - Release (D)
	//=======================================
	"demon_king_release"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/demon_king_nobunaga/demon_king_release"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"25"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET|DOTA_ABILITY_BEHAVIOR_IMMEDIATE|DOTA_ABILITY_BEHAVIOR_AOE|DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING|DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL" 
		"AbilityTextureName"			"custom/maou/d"

		"AbilityCastRange"				"500"
		"AbilityCooldown"				"30"
		"AbilityManaCost"				"0"
		"precache"
		{
			"particle"		"particles/maou/maou_release/maou_release_.vpcf"

			"particle"		"particles/maou/ambient_jopa/ambient_jopa.vpcf"


		}
		"AbilityValues"
		{
			"total_damage_base"				"500"
			"aoe_radius"						"500"
			"total_duration"						"1"
			"damage_ticks"						"5"
			"damage_per_stack"						"200"
			"sa_barrier_duration"						"10"
		}
	}


	//=======================================
	// Demon king nobunaga - Materialization (F)
	//=======================================
	"demon_king_materialization"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/demon_king_nobunaga/demon_king_materialization"
		"MaxLevel"						"2"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"25"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE|DOTA_ABILITY_BEHAVIOR_AOE|DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL" 
		"AbilityTextureName"			"custom/maou/f"

		"AbilityCastRange"				"750"
		"AbilityCooldown"				"30"
		"AbilityManaCost"				"0"

		"precache"
		{
			"particle"		"particles/demon_king_nobunaga/fire_ground.vpcf"
		}

		"AbilityValues"
		{
			"maximum_stack_count"					"10"
			"sa_1_damage_min"						"200"
			"sa_1_mana"								"50"
			"sa_1_cd"								"2"
			//burning ground SA
			"sa_dps"				"50"
			"sa_aoe_radius"				"500"
			"sa_duration"				"7"
			"sa_2_spell_amp"						"15"
			"sa_2_spell_amp_duration"				"2"
			"sa_4_stat_bonus"						"2"

		}
	}

	//=======================================
	// Demon king nobunaga - breath (R)
	//=======================================
	"demon_king_breath"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/demon_king_nobunaga/demon_king_breath"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				" DOTA_ABILITY_BEHAVIOR_POINT|DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL" 
		"AbilityTextureName"			"custom/maou/r"	
		"AbilityCastAnimation" 			"ACT_DOTA_ITEM_PICKUP"
		"AnimationPlaybackRate" 		"1"
		"AbilityCastRange"				"1500"
		"AbilityCooldown"				"30"
		"AbilityManaCost"				"600"
		"AbilityCastPoint"				"0.3"
		"precache"
		{
			"particle"		"particles/maou/fire_breath/maou_breathe_fire_.vpcf"
			"particle"		"particles/zlodemon/zlodemon_basic_circle.vpcf"
			"particle"		"particles/maou/breath_blackhole/enigma_blackhole_ti5_2.vpcf"
			"particle"		"particles/maou/breath_blackhole/maou_black_hole_center_precast.vpcf"

		}
		"AbilityValues"
		{
			"damage_fire"				"400 500 600 700 800"
			"range"						"1500"
			"minimal_range"				"1000"
			"total_duration"						"0.5"
			"black_hole_duration"						"3"
			"aoe_radius"						"500"
			"black_hole_delay"				"0.7"
			"black_hole_damage"				"100 125 150 175 200" //per sec
			"black_hole_pull_str"			"200"					  //per sec
		}
	}

	//=======================================
	// Demon king nobunaga - Combo
	//=======================================
	"demon_king_combo"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/demon_king_nobunaga/demon_king_combo"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT|DOTA_ABILITY_BEHAVIOR_AOE|DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE|DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL" 
		"AbilityTextureName"			"custom/maou/combo"

		"AbilityCastRange"				"3000"
		"AbilityCastPoint"				"0.2"
		"AbilityCooldown"				"150"
		"AbilityManaCost"				"400"
		"precache"
		{
			"particle"		"particles/demon_king_nobunaga/combo_kostya_spawn_ground.vpcf"
			"particle"		"particles/maou_combo/maou_combo_shrapnel.vpcf"
		}
		"AbilityValues"
		{

			"duration"					"10"
			"aoe_damage_passive"					"300"
			"combo_damage_reduction_pct"					"50"
			"recast_damage"				"750"
			"last_explosion_radius" "1000"
            "last_explosion_damage" "2000"
			"passive_damage_area"				"700"
			"radius_blast"				"600"
			"radius"				"1500"
			"recast_counter"				"5"
		}
	}

	 "demon_king_combo_recast"
	{		
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/demon_king_nobunaga/demon_king_combo_recast"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_HIDDEN|DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE|DOTA_ABILITY_BEHAVIOR_IGNORE_SILENCE | DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/maou/combo_recast"
		
		"precache"
		{
			"particle"			"particles/custom/karna/brahmastra_kundala/brahmastra_kundala_ray.vpcf"
			"particle"			"particles/custom/karna/brahmastra_kundala/brahmastra_kundala_explosion_beam.vpcf"
			"particle"			"particles/karna/kundala_aoe.vpcf"	
			"particle"			"particles/custom/lancer/lancer_gae_bolg_projectile.vpcf"			
				
		}

		"AbilityCooldown"				"1"
		"AbilityManaCost"				"0"
		
		"AbilityValues"
        {
        	"combo_damage_reduction_pct" "50"
            "radius" "550"
            "small_radius" "300"
            "damage" "750"
            "delay" "1.5"
            "last_explosion_radius" "1000"
            "last_explosion_damage" "2000"
        }
	}

	"demon_king_attribute_1"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/demon_king_nobunaga/demon_king_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/maou/sa_1"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"10"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {

			"sa_dps"				"50"
			"sa_aoe_radius"				"500"
			"sa_duration"				"7"
			"sa_1_damage_min"						"200"
			"sa_1_mana"								"50"
			"sa_1_cd"								"2"
			"sa_1_radius"							"500"
        }		
	}
	"demon_king_attribute_2"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/demon_king_nobunaga/demon_king_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/maou/sa_2"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"10"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
			"sa_2_spell_amp"						"15"
			"sa_2_spell_amp_duration"				"2"

        }		
	}
	"demon_king_attribute_3"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/demon_king_nobunaga/demon_king_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/maou/sa_3"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"10"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
        	"guns_dmg_mod"		"50"
        	"life_time"			"30"

        }		
	}
	"demon_king_attribute_4"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/demon_king_nobunaga/demon_king_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/maou/sa_4"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"10"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
			"sa_4_stat_bonus"						"2"
			"sa_barrier_duration"						"10"

        }		
	}
	"demon_king_attribute_5"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/demon_king_nobunaga/demon_king_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/maou/sa_5"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"10"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
        	"slam"			"1"
        	"beam"		"1"
        	"guns"		"1"
        	"strike"	"2"
        	"dash"		"1"
        	"blink"		"2"
        	"fire"		"1"
        	"hole"		"1"

        }		
	}


	///////////////////////////////////////////////NOBBUS abilities

	"maou_nobbus_herc_slam"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/demon_king_nobunaga/maou_nobbus_herc_slam"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/berserker_5th_fissure_strike"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"2.0"
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"500"
		"AbilityCastPoint"				"0.2"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"5"
		//"AbilityDamage"					"300 350 400 450 500"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"100"
		"precache"
		{
			"particle"		"particles/zlodemon/heracles/heracles_fissure_nobbus.vpcf"
		}
		

		"AbilityValues"
        {
            "width" "125"
            "damage" "300"
            "range" "500"
            "jump_range" "500"
            "stun_duration" "0.4"
        }		
	}



	"maou_nobbus_gumi_dash"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/demon_king_nobunaga/maou_nobbus_gumi_dash"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PURE"
		"AbilityTextureName"			"custom/okita/okita_mumyo"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"2.0"
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"700"
		"AbilityCastPoint"				"0.1"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"1"
		//"AbilityDamage"					"300 350 400 450 500"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"50"
        "precache"
		{
			"particle"				"particles/okita/okita_vendetta_try.vpcf"
			"particle"				"particles/okita/okita_surge_try.vpcf"
			"particle"				"particles/custom/false_assassin/tsubame_gaeshi/tsubame_gaeshi_windup_indicator_flare.vpcf"
			"particle"				"particles/custom/false_assassin/tsubame_gaeshi/slashes.vpcf"
			"particle"				"particles/okita/okita_afterimage_windrunner.vpcf"
		}

		"AbilityValues"
        {
            "width" "150"
            "base_damage" "50"
            "range" "700"
            "speed" "1400"
            "damage_per_hit" "0"
        }		
	}

	"maou_nobbus_tank_rockets"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/demon_king_nobunaga/maou_nobbus_tank_rockets"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/maou/nobu_tank_2"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"2.0"
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"300"


		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"1"
		//"AbilityDamage"					"300 350 400 450 500"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"100"
		"precache"
		{
			"particle"		"particles/econ/items/gyrocopter/hero_gyrocopter_atomic/gyro_rocket_barrage_atomic.vpcf"
		}
		

		"AbilityValues"
        {
            "damage" "20"
            "amount" "16"
            "search_radius" "300"
        }		
	}

	"maou_nobbus_tank_ram"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/demon_king_nobunaga/maou_nobbus_tank_ram"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityTextureName"			"custom/maou/nobu_tank_1"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"2.0"
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastPoint"				"0.2"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"2"


		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"100"
		"precache"
		{
			"particle"		"particles/zlodemon/heracles/heracles_fissure_nobbus.vpcf"
		}
		

		"AbilityValues"
        {
            "duration" "1"
            "speed_const" "800"
        }		
	}


}