"DOTAAbilities"
{
	//=======================================
	// Assassin - Death's Approach
	//=======================================

	"khsn_ambush"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_ambush"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
	    "AbilityTextureName"			"custom/kinghassan/flamesofgehenna"
	    "AbilityCastAnimation"      	"ACT_DOTA_CAST_ABILITY_1"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"

		//"LinkedAbilities"				"khsn_ambush_blink"
		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"13"
		"AbilityCastPoint"				"0.0"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"100"		

		// Special
		//-------------------------------------------------------------------------------------------------------------

		"precache"
		{
			"particle"		"particles/kinghassan/khsn_trail_scepter.vpcf"
			"particle"		"particles/custom/false_assassin/tsubame_gaeshi/tsubame_gaeshi_windup_indicator_flare.vpcf"
			"particle"		"particles/kinghassan/khsn_shadowraze.vpcf"
			"particle"		"particles/kinghassan/khsn_flame_kappa.vpcf"
		}

		"AbilityValues"
        {	
        	"cast_point"		"0.001"
            "invis_duration" 	"1"
            "duration" "6"
            "ms_bonus" "10 12.5 15 17.5 20"
            "damage"   			"200 250 300 350 400"
            "shield"   			"200 250 300 350 400"
            "shield_duration" 	"6"
            "bonus_range" 	"400"

            "attribute_true_sight_range"	"800"
            "attribute_true_sight_duration"	"3"
        }
	}

	//=======================================
	// Assassin - Evening Bell
	//=======================================

	"khsn_mde"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_mde"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_5"
		"AbilityTextureName"			"custom/kinghassan/khsn_bell"
		"AbilityCastPoint"				"0.1"

		"AbilityCooldown"				"32 30 28 26 24"

		"AbilityManaCost"				"200"

		"precache"
		{
			"particle"		"particles/kinghassan/khsn_shroud/khsn_shroud.vpcf"
			"particle"		"particles/kinghassan/khsn_siphon.vpcf"
		}
		
		"AbilityValues"
        {
        	"azrael_cast_point"		"0.2"
        	"death_door_duration" "6"
        	"radius" "650"
        	"duration" "5.0"
        	"dps" 	"60 75 90 105 120"
        	"heal"  "60 75 90 105 120"
            "damage_percent" "5"
            "ms_bonus" "20 24 28 32 36"
            "bonus_armor" "2 2.5 3 3.5 4"
            "azrael_damage" 	"100 125 150 175 200"
            "dd_dmg_percent" 		"50"
            "azrael_max_storage"	"400 500 600 700 800"
            "azrael_health_threshold" "10"

            "linger_duration" "0.3"
            "attribute_damage_reduction"	"10"
            "attribute_heal_reduction"		"10"
        }
	}

	//=======================================
	// Assassin - Azrael
	//=======================================

	"khsn_azrael"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_azrael"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/kinghassan/khsn_azrael"
		"AbilityCastAnimation" 			"ACT_DOTA_IDLE"
		"AnimationPlaybackRate" 		"1.0"
		
		"AbilityCastRange"				"650"
		"AbilityCastRangeBuffer"		"300"
		"AbilityCastPoint"				"0.2"
		"AbilityManaCost"				"0"
		"precache"
		{
			"particle"		"particles/kinghassan/khsn_domus_ray.vpcf"
			"particle"		"particles/kinghassan/khsn_feathers.vpcf"
			"particle"		"particles/kinghassan/khsn_shadow.vpcf"
			"particle"		"particles/kinghassan/khsn_azrael_skull/khsn_death_door_overhead_dynamic.vpcf"
		}
		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
            "damage" 			"100 125 150 175 200"
            "dmg_percent" 		"50"
            "maximum_stored"	"400 500 600 700 800"
            "health_threshold" "10"
            "death_door_duration" "6"
            "damage_reduction" "10"
        }		
	}

	//=======================================
	// combo activator xd
	//=======================================

	"khsn_mde_end"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_mde"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityCastAnimation" 			"ACT_DOTA_IDLE"
		"AbilityTextureName"			"custom/kinghassan/flamesofgehenna"
		"AbilityCastPoint"				"0.1"
	}

	//=======================================
	// Assassin - Mortuary Slash
	//=======================================

	"khsn_slash"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_slash"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
	    "AbilityTextureName"			"custom/kinghassan/eveningbell"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityCastPoint"				"0.2"
	    "AbilityCastAnimation"      	"ACT_DOTA_IDLE"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"20"
        "AbilityCastRange"              "800"
		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"400"		
		"precache"
		{
			"particle"		"particles/kinghassan/azrael/hassanult.vpcf"
			"particle"		"particles/kinghassan/azrael/hassanultarea.vpcf"
			"particle"		"particles/kinghassan/khsn_shield_cast.vpcf"
			"particle"		"particles/king_hassan/khsn_shield.vpcf"
		}
		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "cast_delay" "0.5"
            "damage" "500 625 750 875 1000"
            "stun" "0.6 0.7 0.8 0.9 1"
            "length" "800"
            "width" "310"
            "speed" "8000"
            "block_per_unit" "200 250 300 350 400"
            "block_max" 	 "600 750 900 1050 1200"
        }
	}

	//=======================================
	// Assassin - Inexorable Stare
	//=======================================

	"khsn_grab"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_grab"
		"MaxLevel"						"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_CHANNELLED |DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/kinghassan/presenceconcealment"
		//"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_4"
		"AbilityCastAnimation"			"ACT_DOTA_CHANNEL_ABILITY_4"
		"AnimationPlaybackRate" 		"1.0"

		"AbilityCastPoint"				"0.2"
		"AbilityCastRange"				"500"
		"AbilityCastRangeBuffer"		"200"
		"AbilityCooldown"				"60 40"
		"AbilityManaCost"				"200"
		"AbilityChannelTime"            "1.5 2.5"
		
		"precache"
		{
			"particle"		"particles/custom/kinghassan/kinghassan_lahm/kinghassan_lahm.vpcf"
			"particle"		"particles/kinghassan/khsn_grab_dummy_smoke.vpcf"
			"particle"		"particles/kinghassan/khsn_grab_dummy_smoke_appear.vpcf"
			"particle"		"particles/kinghassan/kinghassan_grab_dummy_status.vpcf"
		}

		"AbilityValues"
        {
            "cast_range" "500"
            "channel_duration" "1.5 2.5"
            "damage_per_second" "200"
            "mr_reduction" 	"0 25"
        }
	}

	//=======================================
	// Assassin - Phantasmal Flame (skolko mozhno, yob tvoy mat)
	//=======================================

	"khsn_aoe_flame"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_aoe_flame"
		"MaxLevel"						"5"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/kinghassan/khsn_flame"
		"AbilityCastAnimation"			"ACT_DOTA_DIE"

		"AbilityCastPoint"				"0.45"
		"AbilityCooldown"				"45"
		"AbilityManaCost"				"800"
		"LevelsBetweenUpgrades"			"2"
		"precache"
		{
			"particle"		"particles/kinghassan/khsn_flame_aoe_swirl.vpcf"
			"particle"		"particles/kinghassan/khsn_aoe_flame_magnetic_ring.vpcf"
			"particle"		"particles/kinghassan/khsn_flame.vpcf"
			"particle"		"particles/kinghassan/khsn_flame_kappa.vpcf"
			"particle"		"particles/kinghassan/khsn_shadowraze.vpcf"
			"particle"		"particles/units/heroes/hero_skeletonking/skeletonking_hellfireblast_debuff.vpcf"
		}
		"AbilityValues"
		{		
			"radius"						"550"
			"damage_first"					"200 225 250 275 300"
			"damage_burn"					"300 350 400 450 500" 
			"radius_last"					"650"
			"damage_last"					"200 250 300 350 400"
			"flame_duration"				"3"
			"flame_damage_per_second"		"30 40 50 60 70"
			"slow_percentage"				"40 45 50 55 60"
		}
	}

	//=======================================
	// Assassin - Battle Continuation
	//=======================================

	"khsn_bc"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_bc"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"AbilityTextureName"			"custom/kinghassan/khsn_bc"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"

		"AbilityCooldown"				"99"
		
		"AbilityValues"
        {
            "cooldown" "99"
        }
	}

	//=======================================
	// Combo - The Valley of Death
	//=======================================

	"khsn_combo_arena"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_combo_arena"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/kinghassan/khsn_combo"
		"AbilityCastPoint"				"0.2"
		//"AbilityCastRange"				"99999"

		"AbilityCooldown"				"160"

		"AbilityManaCost"				"200"

		"precache"
		{
			"particle"		"particles/kinghassan/khsn_combo_area_test/khsn_combo_area_ground_line.vpcf"
			"particle"		"particles/kinghassan/khsn_combo_area_test/khsn_combo_area_ray.vpcf"
			"particle"		"particles/units/heroes/hero_night_stalker/nightstalker_void.vpcf"
		}
		
		"AbilityValues"
        {
        	"duration"				"8"
            "width"					"1200"
            "length"				"2000"
            "heal_reduction"		"60"
            "damage_punishment" 	"1500"
            "damage" 				"2000"
            "dummy_duration" 		"1"
            "health_threshold" 		"20"
        }
	}

	"khsn_combo_arena_recast"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_combo_arena"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/kinghassan/khsn_azrael"
		"AbilityCastAnimation" 			"ACT_DOTA_IDLE"
		"AnimationPlaybackRate" 		"1.0"
		
		"AbilityCastPoint"				"0.2"
		"AbilityManaCost"				"0"
		"AbilityCooldown"				"20"
		"precache"
		{
			"particle"		"particles/kinghassan/khsn_domus_ray.vpcf"
			"particle"		"particles/kinghassan/khsn_feathers.vpcf"
			"particle"		"particles/kinghassan/khsn_shadow.vpcf"
			"particle"		"particles/kinghassan/khsn_azrael_skull/khsn_death_door_overhead_dynamic.vpcf"
		}
		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
        }		
	}

	//=======================================
	// Assassin - Attributes
	//=======================================

	"khsn_boundary_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/kinghassan/khsn_boundary"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"6"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
            "bonus_as" "150"
            "as_duration" "5"
            "bonus_range" "300"
        }		
	}
	"khsn_presence_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/kinghassan/khsn_presence"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"13"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
        	"linger_duration"	"0.3"
            "damage_penalty"	"10"
            "heal_penalty"		"20"
        }		
	}
	"khsn_azrael_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/kinghassan/khsn_attribute_azrael"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"12"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
            "first_dmg" "100"
            "second_dmg" "150"
            "duration" "3"
        }		
	}
	"khsn_bc_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/kinghassan/khsn_bc"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"15"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
            "cooldown" "99"
            "duration" "2"
        }		
	}
	"khsn_flame_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/kinghassan/faith"
		"AbilityCooldown"				"9999"

		"LinkedAbilities"				"khsn_blink"

		"AbilityManaCost"				"8"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
            "mr_reduction"			"25"
        }
	}

	//=======================================
	// unused shit
	//=======================================

	//=======================================
	// Assassin - Blink Strike
	//=======================================
	"khsn_blink"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_blink"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL" 
		"AbilityTextureName"			"custom/kinghassan/khsn_blink"

		"AbilityCastRange"				"500"
		"AbilityCastRangeBuffer"		"75"
		
		
		"AbilityCastPoint"				"0.2"
		"AbilityCooldown"				"25"
		"AbilityManaCost"				"100"

		"AbilityValues"
        {
            "duration" "3"
            "attr_as" "40 60 80 100 120"
            "pepeg_dmg_bonus" "60 75 90 105 120"
            "range" "300"
            "turn_rate" "98"
            "width" "200"
            "damage" "300"
            "silence_duration" "1"
            "lock_duration" "2"
        }
	}

	//=======================================
	// Assassin - Eternal Flame (active)
	//=======================================

	"khsn_flame_active"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_flame_active"
		"MaxLevel"						"1"
		"RequiredLevel"					"25"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_HIDDEN | DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityTextureName"			"custom/kinghassan/khsn_flame_attr"

		"AbilityManaCost"				"200"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"30"

		"AbilityValues"
        {
            "cooldown" "10"
            "base_mana_per_second" "20"
            "add_mana_per_second" "8"
            "duration" "10"
        }		
	}

	//=======================================
	// Combo - The Angel That Announces Death
	//=======================================

	"khsn_combo"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_combo"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/kinghassan/khsn_combo"
		"AbilityCastPoint"				"0.1"
		"AbilityCastRange"				"99999"

		"AbilityCooldown"				"200"

		"AbilityManaCost"				"200"
		
		"AbilityValues"
        {
            "damage" "2500"
            "dmg_percent" "125"
            "health_threshold" "22"
            "sequence_duration" "60"
        }
	}

	//=======================================
	// Assassin - Phantasmal Flame
	//=======================================

	"khsn_flame"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_fire"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/kinghassan/khsn_flame"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"1.0"
		
		"AbilityCastRange"				"250"
		"AbilityCastPoint"				"0.4"
		"AbilityManaCost"				"400"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"30 28 26 24 22"

		"AbilityValues"
        {
            "main_damage" "400 550 700 850 1000"
            "damage_per_second" "50 75 100 125 150"
            "distance" "750"
            "flame_speed" "1050"
            "flame_width_start" "100"
            "flame_width_end" "250"
            "stun_duration" "0.7 1.0 1.4 1.7 2.0"
            "flame_duration" "1.5 2.0 2.5 3.0 3.5"
        }		
	}

	//=======================================
	// Assassin - Phantasmal Flame (Shadow Raze variant)
	//=======================================

	"khsn_raze1"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_raze"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"1.3"
		"AbilityTextureName"			"custom/kinghassan/khsn_flame1"
		"AbilityCastPoint"				"0.3"
		"AbilityCastRange"				"300"

		"AbilityCooldown"				"12 11 10 9 8"
		"AbilityManaCost"				"200"
		
		"AbilityValues"
        {
            "damage" "300 350 400 450 500"
            "damage_per_second" "30 45 60 75 90"
            "range" "300"
            "radius" "250"
            "duration" "2"
        }
	}

	"khsn_raze2"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_raze"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"1.3"
		"AbilityTextureName"			"custom/kinghassan/khsn_flame2"
		"AbilityCastPoint"				"0.3"
		"AbilityCastRange"				"550"

		"AbilityCooldown"				"12 11 10 9 8"
		"AbilityManaCost"				"200"
		
		"AbilityValues"
        {
            "damage" "300 350 400 450 500"
            "damage_per_second" "30 45 60 75 90"
            "range" "550"
            "radius" "250"
            "duration" "2"
        }
	}

	"khsn_raze3"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_raze"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"1.3"
		"AbilityTextureName"			"custom/kinghassan/khsn_flame3"
		"AbilityCastPoint"				"0.3"
		"AbilityCastRange"				"800"

		"AbilityCooldown"				"12 11 10 9 8"
		"AbilityManaCost"				"200"
		
		"AbilityValues"
        {
            "damage" "300 350 400 450 500"
            "damage_per_second" "30 45 60 75 90"
            "range" "800"
            "radius" "250"
            "duration" "2"
        }
	}

	//=======================================
	// Assassin - Phantasmal Flame (Backstab variant)
	//=======================================

	"khsn_stab"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_stab"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"1.3"
		"AbilityTextureName"			"custom/kinghassan/khsn_flame3"
		"AbilityCastPoint"				"0.3"
		"AbilityCastRange"				"300"

		"AbilityCooldown"				"20 18 16 14 12"
		"AbilityManaCost"				"400"
		
		"AbilityValues"
        {
            "damage" "150 200 250 300 350"
            "range" "300"
            "radius" "250"
            "lock_duration" "1.6 1.8 2 2.2 2.4"
            "backstab_multiplier" "2"
            "silence_duration" "0.8 0.9 1 1.1 1.2"
        }
	}

	//=======================================
	// Assassin - Death's Presence
	//=======================================

	"khsn_presence"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kinghassan/khsn_presence"
		"AbilityTextureName"			"custom/kinghassan/khsn_presence"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		
		"AbilityValues"
        {
            "aura_radius" "500"
            "damage_reduction" "10"
        }
	}
}