"DOTAAbilities"
{

	//========================================
	// Lancelot : Double Edge
	//========================================
	
	//========================================
	// Lancelot : Knight of Honor
	//========================================

	//========================================
	// Lancelot : Arondite
	//========================================
	"lancelot_arondite"
	{
		"BaseClass"						"ability_datadriven"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityTextureName"			"custom/lancelot_arondite"
		"AbilityType"					"ABILITY_TYPE_ULTIMATE"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"precache"
		{
			"particle"		"particles/custom/lancelot/lancelot_arondite.vpcf"
			"particle"		"particles/custom/lancelot/lancelot_arondite_aoe_warp.vpcf"
			"particle"		"particles/custom/lancelot/lancelot_arondite_ambient.vpcf"
			"particle"		"particles/units/heroes/hero_brewmaster/brewmaster_thunder_clap.vpcf"
			"particle"		"particles/units/heroes/hero_dragon_knight/dragon_knight_breathe_fire.vpcf"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_phoenix.vsndevts"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_sven.vsndevts"
		}

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"50"
		"AbilityCastPoint"				"0.0"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"800"
		
		"AbilityValues"
        {
            "damage" "400 450 500 550 600"
            "bonus_damage" "12 14 16 18 20"
            "bonus_allstat" "4 8 12 16 20"
            "duration" "10"
            "radius" "500"
        }
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"		"lancelot_ability"
				"Function"			"OnAronditeStart"
				"Duration"			"%duration"
				"Damage"			"%damage"
				"Radius"			"%radius"
			}
			"FireSound"
			{
				"EffectName"	"Hero_Sven.GodsStrength"
				"Target"		"CASTER"
			}
		}
		
		"OnProjectileHitUnit"
		{
			"DeleteOnHit"			"true"
            "RunScript"
            {
 			 	"ScriptFile"	"lancelot_ability"
			 	"Function"		"OnEternalFlameHit"           	
            }
		}
		"Modifiers"
		{
			"modifier_arondite"
			{
				"Duration"	"%duration"
				"OnCreated"
				{
					"AttachEffect"
					{
						"Target"			"CASTER"
						"EffectName"		"particles/custom/lancelot/lancelot_arondite.vpcf"
						"EffectAttachType"	"follow_customorigin"
						"ControlPointEntities"
						{
							"CASTER"		"attach_sword"
							"CASTER"		"attach_sword"
							"CASTER"		"attach_sword"
						}
					}
					"AttachEffect"
					{
						"Target"			"CASTER"
						"EffectName"		"particles/custom/lancelot/lancelot_arondite.vpcf"
						"EffectAttachType"	"follow_customorigin"
						"ControlPointEntities"
						{
							"CASTER"		"attach_sword"
							"CASTER"		"attach_sword"
							"CASTER"		"attach_sword"
						}
					}
					"AttachEffect"
					{
						"Target"			"CASTER"
						"EffectName"		"particles/custom/lancelot/lancelot_arondite_ambient.vpcf"
						"EffectAttachType"	"follow_customorigin"
						"ControlPointEntities"
						{
							"CASTER"		"attach_origin"
						}
					}
				}
				"OnAttackLanded"
				{	
					"RunScript"
					{
						"ScriptFile"	"lancelot_ability"
						"Function"		"OnAronditeAttackLanded"
					}	
				}
				"Properties"
				{
					"MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE"	"%bonus_damage"
					"MODIFIER_PROPERTY_STATS_AGILITY_BONUS"		"%bonus_allstat"
					"MODIFIER_PROPERTY_STATS_STRENGTH_BONUS"	"%bonus_allstat"
					"MODIFIER_PROPERTY_STATS_INTELLECT_BONUS"	"%bonus_allstat"
				}
				"States"
				{
					"MODIFIER_STATE_UNSELECTABLE" "MODIFIER_STATE_VALUE_ENABLED"
				}
			}
			"modifier_arondite_crit"
			{
				"Duration"	"%duration"
				"IsHidden"	"1"
				"OnAttackStart"
				{
					"RemoveModifier"
					{
						"ModifierName"	"modifier_arondite_crit_hit"
						"Target"		"CASTER"
					}

					"Random"
					{
						"Chance"	"25"
						"OnSuccess"
						{
							"RunScript"
							{
								"ScriptFile"		"lancelot_ability"
								"Function"			"OnAronditeCrit"
							}
						}
					}
				}
			}

			"modifier_arondite_crit_hit"
			{
				"IsHidden"		"1"
				"Properties"
				{
					"MODIFIER_PROPERTY_PREATTACK_CRITICALSTRIKE" "250"
				}
				"OnAttackLanded"
				{
			    	"FireEffect"
			    	{
			    		"EffectName"		"particles/units/heroes/hero_juggernaut/jugg_crit_blur_impact.vpcf"
			    		"EffectAttachType"	"attach_hitloc"
			    		"Target"			"TARGET"
			    	}
			        "RemoveModifier"
			        {
			            "ModifierName"  	"modifier_arondite_crit_hit"
			            "Target"   			"CASTER"    
			        }			
				}
			}
		}
	}

	//=================================================================================================================
	// Lancelot : Eternal Arms Mastership
	//=================================================================================================================

	//=====================================
	// Lancelot : SMG Barrage
	//=====================================

	// [restored] возвращён после ошибочной чистки
	// [restored] возвращён после ошибочной чистки
}