"DOTAAbilities"
{
	//========================================
	// Berserker : Courage
	//========================================
	"heracles_courage"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/heracles/heracles_courage"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityTextureName"			"custom/berserker_5th_courage"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_2"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AnimationPlaybackRate" 		"2.0"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		//"AbilityCastRange"				"400"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"20"
		"AbilityCastPoint"				"0.3"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"200"
		"precache"
		{
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_axe.vsndevts"
			"particle"				"particles/custom/berserker/courage/buff.vpcf"
			"particle"				"particles/custom/berserker/courage/debuff.vpcf"
			"particle"				"particles/custom/berserker/courage/stun_explosion.vpcf"
			"particle"				"particles/zlodemon/herc_ground_slam.vpcf"
		}
		
		"AbilityValues"
        {
            "self_damage_inc" "0"
            "physical_block"	"30"
            "damage_reduction" "-30 -35 -40 -45 -50"
            "self_str_inc" "10 12.5 15 17.5 20"
            //"self_str_inc_base" "25"
            "bonus_damage" "4 5 6 7 8"
            "self_damage_inc_base" "40"
            "duration" "7"
            "enemy_duration" "4"
            "radius" "500"
            "bonus_ms" "4 5 6 7 8"
            "self_ms_inc_base" "10"
            "bonus_as" "10 12.5 15 17.5 20"
            "self_as_inc_base" "25"
            "damage" "200 250 300 350 400"
            "stun_duration" "0.2"
             "active_radius" "350"
        }
	}
}