#base "heracles_courage.kv"
#base "heracles_berserk.kv"
#base "heracles_nine_lives.kv"

"DOTAAbilities"
{
	//=======================================
	// Berserker - Fissure(Q)
	//=======================================

	"heracles_fissure"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/heracles/heracles_fissure"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/berserker_5th_fissure_strike"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"2.0"
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"900"
		"AbilityCastPoint"				"0.5"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"12 11 10 9 8"
		//"AbilityDamage"					"300 350 400 450 500"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"100"
		"precache"
		{
			"particle"		"particles/zlodemon/heracles/heracles_fissure.vpcf"
		}
		

		"AbilityValues"
        {
            "width" "125"
            "damage" "200 250 300 350 400"
            "range" "900"
            "stun_duration" "0.5 0.65 0.8 0.95 1.1"
        }		
	}


	//=======================================
	// Berserker - Grab(W)
	//=======================================


	//=======================================
	// Berserker - Tiny Airlanes
	//=======================================

	"pepeg_jump"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/heracles/pepeg_jump"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/heracles/pepeg_jump"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"2.0"
		
		"AOERadius"						"%radius"
		"AbilityCastPoint"				"0.2"
		"AbilityManaCost"				"400"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"30 28 26 24 22"

		"AbilityValues"
        {
            "speed" "1700"
            "fly_duration" "0.7"
            "max_height" "750"
            "damage" "150 188 225 263 300"
            "radius" "500"
            "slow" "10 20 30 40 50"
            "target_slow" "40 55 70 85 100"
            "range" "1000"
            "berserked_range" "800"
            "target_damage" "250 313 375 438 500"
            "pepeg_damage" "250 313 375 438 500"
            "health_percent" "3 3.5 4 4.5 5"
            "mute_duration" "0.7 0.85 1 1.15 1.3"
        }		
	}
	//=================================================================================================================
	// Berserker : Divinity / God hand
	//=================================================================================================================
	"pepeg_divinity"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/heracles/pepeg_divinity"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityTextureName"			"custom/berserker_5th_attribute_god_hand"
		"MaxLevel"						"2"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"

		"AbilityValues"
        {
            //"physical_block" "30 60"
            "bonus_mr" "0 10"
            "duration" "4"
            "regen_percent" "10"
            "health_percent" "25 60"
            "debuff_duration" "7"
            "debuff_str" "50"
            "revival_damage" "500"
        }
		
		"Modifiers"
		{
			"modifier_divinity_damage_block"
			{
				"Passive"		"1"
				"IsHidden"		"0"
				"Properties"
				{
					"MODIFIER_PROPERTY_PHYSICAL_CONSTANT_BLOCK"	"%damage_reduction"
					"MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BONUS"	"%bonus_mr"
					"MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS"	"%bonus_armor"
				}
			}
		}
	}

	//===================================================
	// Berserker : Fissure Strike
	//===================================================

	

	//========================================
	// Berserker : Madman's Roar
	//========================================
	"berserker_5th_madmans_roar"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/heracles/pepeg_roar"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/berserker_5th_madmans_roar"
		"AbilityCastAnimation" 			"ACT_DOTA_OVERRIDE_ABILITY_2"
		"AnimationPlaybackRate" 		"3.0"
		"MaxLevel"						"1"
		"AbilityCastPoint"				"0.45"
		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"150"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"200"
		"precache"
		{
			"particle"		"particles/custom/screen_face_splash.vpcf"
			"particle"		"particles/custom/barbatos/barbatos_combo.vpcf"
			"particle"		"particles/zlodemon/arbuz_combo.vpcf"
			"particle"		"particles/zlodemon/matthias_combo.vpcf"
			"particle"		"particles/zlodemon/matthias_secret.vpcf"
		}
		
		"AbilityValues"
        {
            "damage" "600"
            "lock_duration_1" "3"
            "damage2" "400"
            "lock_duration_2" "2"
            "damage3" "300"
            "lock_duration_3" "1"
            "slow" "-30"
            "moderate_slow" "-20"
            "stun_duration" "1.0"
            "bers_duration" "3.0"
        }
	}
	

	//========================================
	// Berserker : Eternal Rage Passive
	//========================================
	"berserker_5th_berserk_attribute_passive"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/heracles/berserker_5th_berserk_attribute_passive"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/berserker_5th_berserk_attribute_passive"
		"MaxLevel"						"1"
		"precache"
		{
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_centaur.vsndevts"
		}

		

	}

	//===================================================
	// Berserker : Nine Lives
	//===================================================

	//========================================
	// Berserker : God Hand
	//========================================
	"berserker_5th_god_hand"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/heracles/berserker_5th_god_hand"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/berserker_5th_god_hand"
		"MaxLevel"						"1"
		"precache"
		{
			"particle"			"particles/custom/berserker/god_hand/stomp.vpcf"
			"particle"			"particles/items_fx/aegis_respawn.vpcf"
			"particle"			"particles/custom/berserker/god_hand/debuff.vpcf"
		}

		

	}
	//========================================
	// Berserker : Reincarnation
	//========================================
	"berserker_5th_reincarnation"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/heracles/berserker_5th_reincarnation"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/berserker_5th_attribute_reincarnation"
		"MaxLevel"						"1"
		"precache"
		{
			"particle"			"particles/custom/berserker/reincarnation/regen_buff.vpcf"
		}
		"AbilityValues"
        {
            "duration" "4"
            "regen_percent" "10"
        }
		"03"
		{
			"var_type"				"FIELD_INTEGER"
			"duration"				"4"
		}
		"04"
		{
			"var_type"				"FIELD_INTEGER"
			"regen_percent"			"10"
		}

		

	}
	//=======================================
	// Berserker Attribute : Improve Divinity
	//=======================================
	"berserker_5th_attribute_improve_divinity"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/heracles/berserker_5th_attribute_improve_divinity"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/berserker_5th_attribute_improve_divinity"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"8"

		"precache"
		{
		}

		"AbilityValues"
        {
            "bonus_mr" "10"
            "bonus_armor" "0"
        }
		
	}
	//=======================================
	// Berserker Attribute : Eternal Rage
	//=======================================
	"berserker_5th_attribute_berserk"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/heracles/berserker_5th_attribute_berserk"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/berserker_5th_attribute_berserk"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"12"

		"precache"
		{
		}

		"AbilityValues"
        {
            "bash_chance" "35"
            "bash_duration" "1"
            "bash_damage" "25"
            "nine_cdr" "15"
            "mana_convert_ratio" "0.2"
        }
		
	}
	//=======================================
	// Berserker Attribute : God Hand
	//=======================================
	"berserker_5th_attribute_god_hand"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/heracles/berserker_5th_attribute_god_hand"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/berserker_5th_attribute_god_hand"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"12"

		"precache"
		{
		}

		"AbilityValues"
        {
            "health_percent" "500"
            "duration" "11"
            "health_for_life" "100000"
        }
		
	}

	//=======================================
	// Berserker Attribute : Inhuman Strength
	//=======================================
	"berserker_5th_attribute_reincarnation"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/heracles/berserker_5th_attribute_reincarnation"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/berserker_5th_attribute_reincarnation"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"7"

		"precache"
		{
		}

		"AbilityValues"
        {
            "duration" "4"
            "regen_percent" "10"
            "max_stack" "5"
            "damage_sustain" "20000"
            "bonus_count_percentage" "300"
        }
		
	}

	//=======================================
	// Berserker Attribute : Mad Enchancement
	//=======================================
	"heracles_mad_enhancement_attribute"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/heracles/heracles_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/heracles/heracles_mad_enhancement"		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"13"

		"precache"
		{
		}

		"AbilityValues"
        {
            "berserk_duration" "6.0"
        }		
	}

	"heracles_mad_enhancement_passive"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/heracles/heracles_attributes"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_HIDDEN | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityTextureName"			"custom/heracles/heracles_mad_enhancement"
		"MaxLevel"						"1"
		
		"AbilityValues"
        {
        }
		
		"OnSpelLStart"
		{
		}
	}

	// [restored] возвращён после ошибочной чистки
}