"DOTAAbilities"
{
	//========================================
	// Berserker : Courage
	//========================================
	"berserker_5th_courage"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/heracles/berserker_5th_courage"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityTextureName"			"custom/berserker_5th_courage"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_2"
		"AnimationPlaybackRate" 		"2.0"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"400"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"6 6 5 5 4"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"200"
		"precache"
		{
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_axe.vsndevts"
			"particle"				"particles/custom/berserker/courage/buff.vpcf"
			"particle"				"particles/custom/berserker/courage/debuff.vpcf"
			"particle"				"particles/custom/berserker/courage/stun_explosion.vpcf"
		}
		
		"AbilityValues"
        {
            "armor_reduction" "-3 -4.5 -6 -7.5 -9"
            "damage_reduction" "-20 -40 -60 -80 -100"
            "bonus_damage" "30 40 50 60 70"
            "aspd_bonus" "55"
            "ms_bonus" "4 5 6 7 8"
            "str_debuff" "-5"
            "max_stack" "5"
            "duration" "12"
        }

		
		
		
	}
	
	//========================================
	// Berserker : Berserk
	//========================================
}