"DOTAHeroes"
{
	//=======================================
	//	White Saber(Extra) - Gawain
	//=======================================
	"npc_dota_hero_gawain"
	{
		"override_hero"					"npc_dota_hero_omniknight"
		"DisableWearables" 				"1"
		"Model"							"models/gawain/gawain.vmdl"
		//"Model"						"models/development/invisiblebox.vmdl"
		"ModelScale"					"1.45"
		"LoadoutScale"         "1.45"
        "SpectatorLoadoutScale"   	"1.45"
		//"HeroID"						"127"
		"DrawParticlesWhileHidden" 		"1"

		"AbilityLayout"					"6"
		"Ability1"						"gawain_heat"
		"Ability2"						"gawain_blade_of_the_devoted"
		"Ability3"						"gawain_sun_of_galatine"
		"Ability4"						"gawain_artificial_sun"		
		"Ability5"						"fate_empty1"
		"Ability6"						"gawain_excalibur_galatine"
		"Ability7"						"gawain_meltdown"
		"Ability8"						"gawain_blessing_of_fairy"
		"Ability9"						"gawain_excalibur_galatine_detonate"
		"Ability10"						"presence_detection_passive"
		"Ability11"						"attribute_bonus_custom"
		"Ability12"						"gawain_excalibur_galatine_combo"
		"Ability14"						"gawain_blessing_proxy"
		"Ability15"						"hero_base_stats_bonus"

		"Combo"							"gawain_excalibur_galatine_combo"
		"AttributeNumber"				"5"
		"Attribute1"					"gawain_attribute_blessing_of_fairy"
		"Attribute2"					"gawain_attribute_res_sov"
		"Attribute3"					"gawain_attribute_belt"
		"Attribute4"					"gawain_attribute_kots"
		"Attribute5"					"gawain_attribute_meltdown"

		"StatusHealth"					"1350"
		"StatusHealthRegen"				"7.0"
		"StatusMana"					"1000"
		"StatusManaRegen"				"4.0"
		
		"ArmorPhysical"					"4"
		"MagicalResistance"				"15"
		
		"AttackCapabilities"			"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackRange"					"150"
		"AttackDamageMin"				"47"
		"AttackDamageMax"				"57"
		"AttackRate"					"0.9"
		
		"AttributePrimary"				"DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength"			"0"
		"AttributeStrengthGain"			"3.1"
		"AttributeBaseAgility"			"0"
		"AttributeAgilityGain"			"2.0"
		"AttributeBaseIntelligence"		"0"
		"AttributeIntelligenceGain"		"1.7"
		
		"MovementSpeed"					"375"
		"MovementTurnRate"				"0.8"

		"VisionDaytimeRange"			"1000"
		"VisionNighttimeRange"			"1000"
	}
}