"DOTAAbilities"
{
	//=====================================
	//
	//=====================================
	"hijikata_dash"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_dash"
		"AbilityTextureName"				"custom/hijikata/hijikata_q"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"LevelsBetweenUpgrades"				"1"
		"MaxLevel"							"5"
		"AbilityCooldown"				    "10 9 8 7 6"
		"AbilityManaCost"					"100"
		"AbilityCastRange"					"1500"
		"AbilityCastPoint"					"0.2"
		"AbilityCastAnimation"                      "ACT_DOTA_CAST_ABILITY_1"

		"LinkedAbilities"				"hijikata_dash_recast"
		"precache"
		{
			"particle"		"particles/hijikata/hijikata_dash_radius.vpcf"
			"particle"		"particles/hijikata/hijikata_bullet.vpcf"
		}
		"AbilityValues"
		{
			"distance"								"1500"		//Optimum distance.
			"speed"									"2000"
			"recast_duration"									"4" 	
			"damage"									"200 250 300 350 400"
			"damage_second"								"200 250 300 350 400"
		}
	}

	//=====================================
	//
	//=====================================
	"hijikata_dash_recast"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_dash_recast"
		"AbilityTextureName"				"custom/hijikata/hijikata_dash"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_AOE|DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE|DOTA_ABILITY_BEHAVIOR_NO_TARGET|DOTA_ABILITY_BEHAVIOR_IMMEDIATE|DOTA_ABILITY_BEHAVIOR_HIDDEN|DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"MaxLevel"							"5"
		"AbilityCooldown"				    "0"
		"AbilityManaCost"					"0"
		"AbilityCastPoint"					"0.0"
		"AbilityCastAnimation"                      "ACT_DOTA_CAST_ABILITY_1_END"
		"precache"
		{
			"particle"		"particles/hijikata/hijikata_sword_dash.vpcf"
			"particle"		"particles/hijikata/hijikata_dash_slash.vpcf"
			"particle"		"particles/econ/items/void_spirit/void_spirit_immortal_2021/void_spirit_immortal_2021_astral_step_dmg_blood.vpcf"
			"particle"		"particles/hijikata/hijikata_dash_effects.vpcf"
		}
		"AbilityValues"
		{
			"distance"								"1500"		
			"speed"									"2000"
			"damage"								"200 250 300 350 400"
		}
	}

	//=====================================
	// Demon of the battlefield (W)
	//=====================================
	"hijikata_demon"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_demon"
		"AbilityTextureName"				"custom/hijikata/hijikata_demon"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"MaxLevel"							"5"
		"AbilityCooldown"				    "10 9 8 7 6"
		"LevelsBetweenUpgrades"				"1"
		"AbilityManaCost"					"200"
		"AbilityCastPoint"					"0.2"
		"AbilityCastRange"				"550"
		"AbilityCastRangeBuffer"		"100"

		"AbilityCastAnimation"              "ACT_DOTA_CAST_ABILITY_2"
		"precache"
		{
			"particle"		"particles/hijikata/hijikata_demon_pierce.vpcf"
			"particle"		"particles/hijikata/hijikata_cleave.vpcf"
		}
		"AbilityValues"
		{
			"radius"								"750"		
			"damage"									"200 250 300 350 400"
			"buff_duration"								"3 3.5 4 4.5 5"		
			"as_value"									"100 150 200 250 300"
			"hp_percentage_diff_to_damage"				"10"
			"slow_duration" "1"
            "slow_amount" "60"
            "bonus_damage" "100"
            "base_damage" "30 35 40 45 50"
		}
	}
	//=====================================
	//
	//=====================================
	"hijikata_duel"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_duel"
		"AbilityTextureName"				"custom/hijikata/hijikata_duel"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_HERO"
		"MaxLevel"							"5"
		"LevelsBetweenUpgrades"				"2"
		"AbilityCooldown"				    "25 23 21 19 17"
		"AbilityManaCost"					"400"
		"AbilityCastPoint"					"0.3"
		"AbilityCastRange"				"550"
		"AbilityCastRangeBuffer"		"100"
		"AbilityCastPoint"				"0.3"
		"AbilityCastAnimation"                      "ACT_DOTA_CAST_ABILITY_5"
		"precache"
		{
			"particle"		"particles/hijikata/hijikata_duel.vpcf"
			"particle"		"particles/hijikata/hijikata_duel_text.vpcf"
			"particle"		"particles/hijikata/hijikata_duel_victory.vpcf"
		}
		"AbilityValues"
		{
			"duration"									"6"		
			"dmg_res"									"25 31.25 37.5 43.75 50"
			"dmg_increase"								"10 15 20 25 30"
			"radius"									"1000"
			"cast_range"								"550"
			"armor"										"15"
			"mr"										"10"
			"ms"										"30"
			"health_regen"										"150"
			"mana_regen"										"100"
			"regen_duration"									"5"
		}
	}



	//=====================================
	//
	//=====================================
	"hijikata_madness"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_madness"
		"AbilityTextureName"				"custom/hijikata/hijikata_berserk"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_HERO"
		"MaxLevel"							"1"
		"AbilityCooldown"				    "9"
		"AbilityManaCost"					"100"
		"AbilityCastPoint"					"0.0"
		"AbilityCastAnimation"                      "ACT_DOTA_DISABLED"
		"AnimationPlaybackRate" 		"1.5"
		"precache"
		{
			"particle"		"particles/custom/lancelot/lancelot_arondite_ambient.vpcf"
			"particle"		"particles/hijikata/hijikata_eye.vpcf"
		}
		"AbilityValues"
		{
			"duration"								"3"		
		}
	}

	//=====================================
	//
	//=====================================
	"hijikata_laws"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_laws"
		"AbilityTextureName"				"custom/hijikata/hijikata_laws"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_NO_TARGET|DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_HERO"
		"MaxLevel"							"2"
		"AbilityCooldown"				    "0.5"
		"AbilityManaCost"					"0"
		"AbilityCastPoint"					"0.5"
		"LevelsBetweenUpgrades"			"25"
		"AbilityCastAnimation"                      "ACT_DOTA_DISABLED"
		"AnimationPlaybackRate" 		"1.5"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_PURE"
		"precache"
		{
			"particle"		"particles/custom/lancelot/lancelot_arondite_ambient.vpcf"
			"particle"		"particles/hijikata/hijikata_eye.vpcf"
		}
		"AbilityValues"
		{
			"max_stacks"								"5 7"		
			"dmg_per_stack"									"25 50"
			"health_per_stack"								"100 200"
			"damage_take_per_stack_percent"							"10"
			"last_damage_take_per_stack_percent"							"25"
			"stun_duration"									"3"
			"check_range"									"500"
		}
	}

	//=====================================
	//
	//=====================================
	"hijikata_ult"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_ult"
		"AbilityTextureName"				"custom/hijikata/hijikata_ult"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT|DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"MaxLevel"							"5"
		"LevelsBetweenUpgrades"			"2"
		"AbilityCooldown"				    "30 28 26 24 22"
		"AbilityManaCost"					"800"
		"AbilityCastPoint"					"0.0"
		"AbilityCastAnimation"                      "ACT_DOTA_CAST_ABILITY_6"
		"AbilityCastRange"					"1100"
		"precache"
		{
			"particle"		"particles/econ/items/centaur/centaur_ti9/centaur_double_edge_ti9_bloodspray_src.vpcf"
			"particle"		"particles/units/hijikata/ult/hijikata_ult.vpcf"
			"particle"		"particles/units/hijikata/hijikata_bullet_combo.vpcf"
			"particle"		"particles/units/hijikata/hijikata_bullet.vpcf"
			"particle"		"particles/units/hijikata/ult/hijikata_ult_combo.vpcf"
		}
		"AbilityValues"
		{
			"damage"									"750 950 1150 1350 1550"		
			"max_damage_pct_self"						"150"
			"ms_slow"									"50"
			"distance"									"1100"
			"width"										"100"
			"duration"									"1.5"
			"max_damage_pct"							"150"
			"knockback_distance"						"300"
			"damage_combo"								"2000"	
			"delay"										"0.8"
		}
	}
	//=====================================
	//
	//=====================================
	"hijikata_fierce_journey"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/hijikata/hijikata_fierce_journey"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"AbilityTextureName"			"custom/hijikata/hijikata_sa3"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_HIDDEN"

		"AbilityCooldown"				"75"
		
		"AbilityValues"
        {
            "cooldown" "75"
            "health_restored" "25"
            "duration" "1"
        }
	}	

	//=====================================
	//
	//=====================================
	"hijikata_combo"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_combo"
		"AbilityTextureName"				"custom/hijikata/hijikata_combo"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT|DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"MaxLevel"							"1"
		"AbilityCooldown"				    "160"
		"AbilityManaCost"					"0"
		"AbilityCastPoint"					"0.5"
		"AbilityCastAnimation"                      "ACT_DOTA_CAST_ABILITY_5"

		"LinkedAbilities"				"hijikata_target_dash hijikata_knockup"

		"precache"
		{
			"particle"		"particles/hijikata/hijikata_combo_onground.vpcf"
		}
		"AbilityValues"
		{
			"duration"										"12"	
			"Width"											"500"		
			"distance"										"4000"
			"ally_speed"									"550"
			"hijikata_speed"								"700"
			"ally_speed_per_second"							"50"
			"hijikata_speed_per_second"						"70"
			"stun_duration"									"1"
			"first_strike_damage"							"800"
			"first_strike_range"							"950"
			"second_strike_range"							"350"
			"second_strike_width"							"200"
			"second_strike_damage"							"700"
			"third_strike_damage"							"2000"
			"third_strike_range"							"1650"
			"third_strike_width"							"300"
		}
	}

	//=====================================
	//		Combo 2nd cast
	//====================================

	"hijikata_target_dash"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_target_dash"
		"AbilityTextureName"				"custom/hijikata/hijikata_combo"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET|DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"MaxLevel"							"1"
		"AbilityCooldown"				    "3"
		"AbilityManaCost"					"0"
		"AbilityCastPoint"					"0.2"
		"AbilityCastRange"					  	"900"
		"AbilityCastAnimation"                      "ACT_DOTA_CAST_ABILITY_1_END"
		"precache"
		{
			"particle"		"particles/hijikata/hijikata_dash_slash.vpcf"
		}
		"AbilityValues"
		{
			"damage"									"800"	
			"range"										"950"
			"radius"										"150"
			"duration"										"1"
		}
	}

	//=====================================
	//		Combo 3rd cast
	//====================================

	"hijikata_knockup"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_knockup"
		"AbilityTextureName"				"custom/hijikata/hijikata_combo"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT|DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"MaxLevel"							"1"
		"AbilityCooldown"				    "3"
		"AbilityManaCost"					"0"
		"AbilityCastPoint"					"0.2"
		"AbilityCastAnimation"                      "ACT_DOTA_CAST_ABILITY_3"
		"precache"
		{
			"particle"		"particles/hijikata/hijikata_knockup_slash_new.vpcf"
		}
		"AbilityValues"
		{
			"damage"									"700"		
			"duration"									"1"
			"width"										"200"
			"range"										"350"
		}
	}
    

	"hijikata_shinsengumi_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/hijikata/hijikata_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/hijikata/hijikata_sa4"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"11"

		 
		"AbilityValues"
        {
			"armor"										"15"
			"mr"										"10"
			"ms"										"30"
			"health_regen"										"150"
			"mana_regen"										"100"
			"regen_duration"									"5"
        }		
	}

	"hijikata_battle_continuation_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/hijikata/hijikata_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/hijikata/hijikata_sa3"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"12"

		 
		"AbilityValues"
        {
            "cooldown" "75"
            "health_restored" "25"
            "duration" "1"
        }		
	}

	"hijikata_eternal_madness_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/hijikata/hijikata_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/hijikata/hijikata_sa"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"10"

		 
		"AbilityValues"
        {
            "recast_amount" "3"
            "bonus_damage" "25"
            "bonus_health" "100"
            "max_stacks" "7"
        }		
	}

	"hijikata_tactics_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/hijikata/hijikata_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/hijikata/hijikata_sa2"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"13"

		 
		"AbilityValues"
        {
            "max_damage_pct" "150"
            "slow_duration" "1"
            "slow_amount" "60"
            "bonus_damage" "100"
        }		
	}
	
	"hijikata_fierce_sincerity_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/hijikata/hijikata_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/hijikata/hijikata_sa5"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"12"

		 
		"AbilityValues"
        {
            "cleave_radius" 			"500"
            "cleave_damage_pct" 		"50"
            "damage_bonus" 				"100"
            "shinsengumi_damage_bonus"  "150"
        }		
	} 
 
}