"DOTAAbilities"
{
	//=====================================
	//
	//=====================================
	"hijikata_dash"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_dash"
		"AbilityTextureName"				"custom/hijikata/hijikata_q"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_PHYSICAL"
		"LevelsBetweenUpgrades"				"1"
		"MaxLevel"							"5"
		"AbilityCooldown"				    "9.0 8.1 7.2 6.3 5.4"
		"AbilityManaCost"					"100"
		"AbilityCastRange"					"1500"
		"AbilityCastPoint"					"0.2"
		"AbilityCastAnimation"                      "ACT_DOTA_CAST_ABILITY_1"

		"LinkedAbilities"				"hijikata_dash_recast"
		"precache"
		{
			"particle"		"particles/hijikata/hijikata_dash_radius.vpcf"
			"particle"		"particles/hijikata/hijikata_bullet.vpcf"
		}
		"AbilityValues"
		{
			"distance"								"1500"		
			"speed"									"2000"
			"recast_duration"									"4" 	
			"damage"									"100 125 150 175 200"
			"damage_second"								"100 125 150 175 200"
			"sa_atk_dmg_mod"								"1"
		}
	}

	//=====================================
	//
	//=====================================
	"hijikata_dash_recast"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_dash_recast"
		"AbilityTextureName"				"custom/hijikata/hijikata_dash"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_AOE|DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE|DOTA_ABILITY_BEHAVIOR_NO_TARGET|DOTA_ABILITY_BEHAVIOR_HIDDEN|DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_PHYSICAL"
		"MaxLevel"							"5"
		"AbilityCooldown"				    "0"
		"AbilityManaCost"					"0"
		"AbilityCastPoint"					"0.0"
		"AbilityCastAnimation"                      "ACT_DOTA_CAST_ABILITY_1_END"
		"precache"
		{
			"particle"		"particles/hijikata/hijikata_sword_dash.vpcf"
			"particle"		"particles/hijikata/hijikata_dash_slash.vpcf"
			"particle"		"particles/econ/items/void_spirit/void_spirit_immortal_2021/void_spirit_immortal_2021_astral_step_dmg_blood.vpcf"
			"particle"		"particles/hijikata/hijikata_dash_effects.vpcf"
		}
		"AbilityValues"
		{
			"distance"								"1500"		
			"speed"									"2000"
			"damage"								"100 125 150 175 200"
			"sa_atk_dmg_mod"								"1"
		}
	}

	//=====================================
	// Demon of the battlefield (W)
	//=====================================
	"hijikata_demon"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_demon"
		"AbilityTextureName"				"custom/hijikata/hijikata_demon"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_PHYSICAL"
		"MaxLevel"							"5"
		"AbilityCooldown"				    "15 14 13 12 11"
		"LevelsBetweenUpgrades"				"1"
		"AbilityManaCost"					"200"
		"AbilityCastPoint"					"0.2"
		"AbilityCastRange"				"550"
		"AbilityCastRangeBuffer"		"100"
		"LinkedAbilities"				"hijikata_demon_recast"
		"AbilityCastAnimation"              "ACT_DOTA_CAST_ABILITY_2"
		"precache"
		{
			"particle"		"particles/hijikata/hijikata_demon_pierce.vpcf"
			"particle"		"particles/hijikata/hijikata_cleave.vpcf"
		}
		"AbilityValues"
		{
			"radius"								"750"		
			"damage"									"160 200 240 280 320"
			"buff_duration"								"3 3.5 4 4.5 5"		
			"as_value"									"50"
			"hp_percentage_diff_to_damage"				"3" // MAX HEALTH TO DAMAGE
			"slow_duration" "2"
            "slow_amount" "60"
            "bonus_damage" "100"
            "base_damage" "38 44 50 56 62"
            "sa_atk_dmg_mod"								"1"
		}
	}

	//=====================================
	// Demon of the battlefield 2(W recast)
	//=====================================
	"hijikata_demon_recast"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_demon_recast"
		"AbilityTextureName"				"custom/hijikata/hijikata_demon"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT|DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_PHYSICAL"
		"MaxLevel"							"5"
		"AbilityCooldown"				    "1"
		"LevelsBetweenUpgrades"				"1"
		"AbilityManaCost"					"0"
		"AbilityCastPoint"					"0.3"
		"AbilityCastAnimation"              "ACT_DOTA_CAST_ABILITY_ROT"
		"precache"
		{
			"particle"		"particles/hijikata/hijikata_cleave.vpcf"
		}
		"AbilityValues"
		{	
			"damage"									"62.5 78.1 93.8 109.4 125.0"
			"radius"									"500"
			"heal"										"5 6.25 7.5 8.75 10"
		}
	}
	//=====================================
	//
	//=====================================
	"hijikata_duel"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_duel"
		"AbilityTextureName"				"custom/hijikata/hijikata_duel"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_HERO"
		"MaxLevel"							"5"
		"LevelsBetweenUpgrades"				"2"
		"AbilityCooldown"				    "25 23 21 19 17"
		"AbilityManaCost"					"200"
		"AbilityCastPoint"					"0.3"
		"AbilityCastRange"				"550"
		"AbilityCastRangeBuffer"		"100"
		"AbilityCastPoint"				"0.3"
		"LinkedAbilities"				"hijikata_duel_recast"
		"AbilityCastAnimation"                      "ACT_DOTA_CAST_ABILITY_5"
		"precache"
		{
			"particle"		"particles/hijikata/hijikata_duel.vpcf"
			"particle"		"particles/hijikata/hijikata_duel_text.vpcf"
			"particle"		"particles/hijikata/hijikata_duel_victory.vpcf"
			"particle"		"particles/zlodemon/zlodemon_overhead_duel.vpcf"
		}
		"AbilityValues"
		{
			"duration"									"6"		
			"dmg_res"									"25 31.25 37.5 43.75 50"
			"dmg_increase"								"10 12.5 15 17.5 20"
			"radius"									"1000"
			"cast_range"								"550"
			"armor"										"2"
			"mr"										"10"
			"ms"										"30"
			"health_regen"										"150"
			"mana_regen"										"100"
			"regen_duration"									"5"
		}
	}
	//=================================================================================================================
	// Duel recast
	//=================================================================================================================
	"hijikata_duel_recast"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/hijikata/hijikata_duel_recast"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT|DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PHYSICAL"
		"AbilityTextureName"			"custom/hijikata/hijikata_new_e"
		"AbilityCastAnimation"                      "ACT_DOTA_CAST_ABILITY_2"
		"precache"
		{
			"particle"			"particles/zlodemon/hijik_afterimage.vpcf"
			"particle"			"particles/zlodemon/hijik_afterimage_2.vpcf"
		}
		
		// Ability stats
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"750"
		"AbilityCastPoint"				"0.2"
		"AbilityCooldown"				"25 23 21 19 17"
		"AbilityManaCost"				"200"
		
		// Ability special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "total_strikes" "6"
            "damage" "15 18.75 22.5 26.25 30"
            "damage_per_attack" "0.1 0.125 0.15 0.175 0.2"
            "radius" "350"
        }
		
		
		
	}


	//=====================================
	//
	//=====================================
	"hijikata_madness"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_madness"
		"AbilityTextureName"				"custom/hijikata/hijikata_berserk"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_HERO"
		"MaxLevel"							"1"
		"AbilityCooldown"				    "9"
		"AbilityManaCost"					"0"
		"AbilityCastPoint"					"0.0"
		"AbilityCastAnimation"                      "ACT_DOTA_DISABLED"
		"AnimationPlaybackRate" 		"1.5"
		"precache"
		{
			"particle"		"particles/custom/lancelot/lancelot_arondite_ambient.vpcf"
			"particle"		"particles/hijikata/hijikata_eye.vpcf"
		}
		"AbilityValues"
		{
			"duration"								"3"		
			"max_ms"								"600"	
			"max_attack_damage"						"200"	
			"ms_per_stack"						"1"
			"distance_for_stack"						"25"
		}
	}

	//=====================================
	//
	//=====================================
	"hijikata_laws"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_laws"
		"AbilityTextureName"				"custom/hijikata/hijikata_laws"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_NO_TARGET|DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_HERO"
		"MaxLevel"							"2"
		"AbilityCooldown"				    "0.5"
		"AbilityManaCost"					"0"
		"AbilityCastPoint"					"0.5"
		"LevelsBetweenUpgrades"			"25"
		"AbilityCastAnimation"                      "ACT_DOTA_DISABLED"
		"AnimationPlaybackRate" 		"1.5"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_PURE"
		"precache"
		{
			"particle"		"particles/custom/lancelot/lancelot_arondite_ambient.vpcf"
			"particle"		"particles/hijikata/hijikata_eye.vpcf"
		}
		"AbilityValues"
		{
			"max_stacks"								"5 7"		
			"dmg_per_stack"									"15 30"
			"health_per_stack"								"50 100"
			"damage_take_per_stack_percent"							"10"
			"last_damage_take_per_stack_percent"							"25"
			"stun_duration"									"3"
			"check_range"									"500"
		}
	}

	//=====================================
	//
	//=====================================
	"hijikata_ult"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_ult"
		"AbilityTextureName"				"custom/hijikata/hijikata_ult"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT|DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_MAGICAL"
		"MaxLevel"							"5"
		"LevelsBetweenUpgrades"			"2"
		"AbilityCooldown"				    "30 28 26 24 22"
		"AbilityManaCost"					"800"
		"AbilityCastPoint"					"0.0"
		"AbilityCastAnimation"                      "ACT_DOTA_CAST_ABILITY_6"
		"AbilityCastRange"					"1100"
		"precache"
		{
			"particle"		"particles/econ/items/centaur/centaur_ti9/centaur_double_edge_ti9_bloodspray_src.vpcf"
			"particle"		"particles/units/hijikata/ult/hijikata_ult.vpcf"
			"particle"		"particles/hijikata/hijikata_bullet_combo.vpcf"
			"particle"		"particles/hijikata/hijikata_bullet.vpcf"
			"particle"		"particles/units/hijikata/ult/hijikata_ult_combo.vpcf"
			"particle"		"particles/hijikata/ult_charge_effect.vpcf"
			"particle"		"particles/hijikata/hijikata_ult_ground_marker.vpcf"
		}
		"AbilityValues"
		{
			"damage"									"300 350 400 450 500"	
			"attack_damage_mod"						 	"120 140 160 180 200"	
			"max_damage_pct_self"						"150"
			"ms_slow"									"50"
			"distance"									"1100"
			"width"										"135"
			"duration"									"1.5"
			"max_damage_pct"							"150"
			"knockback_distance"						"300"
			"damage_combo"								"2750"	
			"delay"										"0.8"
			"health_pct_to_max_damage"										"75"
			"stack_reset_delay"										"5"
			"stacks_damage_pct"							"23 28 33 38 43"
			"stacks_damage_pct_bonus"							"17"
			"silence_duration"							"1"
			"max_stacks_width"							"300"
		}
	}
	//=====================================
	//
	//=====================================
	"hijikata_fierce_journey"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/hijikata/hijikata_fierce_journey"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"AbilityTextureName"			"custom/hijikata/hijikata_sa3"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_HIDDEN"

		"AbilityCooldown"				"75"
		"precache"
		{
				"particle"		"particles/status_fx/status_effect_pudge_dismember_default.vpcf"
				"particle"		"particles/hijikata/hijikata_bc_proc_particle.vpcf"
		}

		"AbilityValues"
        {
            "cooldown" "75"
            "health_restored" "25"
            "duration" "1"
        }
	}	

	//=====================================
	//
	//=====================================
	"hijikata_combo"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_combo"
		"AbilityTextureName"				"custom/hijikata/hijikata_combo"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT|DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_PHYSICAL"
		"MaxLevel"							"1"
		"AbilityCooldown"				    "176"
		"AbilityManaCost"					"0"
		"AbilityCastPoint"					"0.55"
		"AbilityCastAnimation"                      "ACT_DOTA_CAST_ABILITY_5"

		"LinkedAbilities"				"hijikata_target_dash hijikata_knockup"

		"precache"
		{
			"particle"		"particles/hijikata/hijikata_combo_onground.vpcf"
		}
		"AbilityValues"
		{
			"duration"										"11"	
			"Width"											"500"		
			"distance"										"4000"
			"ally_speed"									"550"
			"hijikata_speed"								"700"
			"ally_speed_per_second"							"50"
			"hijikata_speed_per_second"						"70"
			"stun_duration"									"0.9"
			"first_strike_damage"							"720"
			"first_strike_range"							"855"
			"second_strike_range"							"315"
			"second_strike_width"							"180"
			"second_strike_damage"							"630"
			"third_strike_damage"							"1800"
			"third_strike_range"							"1485"
			"third_strike_width"							"270"
		}
	}

	//=====================================
	//		Combo 2nd cast
	//====================================

	"hijikata_target_dash"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_target_dash"
		"AbilityTextureName"				"custom/hijikata/hijikata_combo"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET|DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_PHYSICAL"
		"MaxLevel"							"1"
		"AbilityCooldown"				    "3"
		"AbilityManaCost"					"0"
		"AbilityCastPoint"					"0.2"
		"AbilityCastRange"					  	"900"
		"AbilityCastAnimation"                      "ACT_DOTA_CAST_ABILITY_1_END"
		"precache"
		{
			"particle"		"particles/hijikata/hijikata_dash_slash.vpcf"
		}
		"AbilityValues"
		{
			"damage"									"720"	
			"range"										"800"
			"radius"										"150"
			"duration"										"0.9"
		}
	}

	//=====================================
	//		Combo 3rd cast
	//====================================

	"hijikata_knockup"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"					    "abilities/hijikata/hijikata_knockup"
		"AbilityTextureName"				"custom/hijikata/hijikata_combo"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_POINT|DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"				"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"				"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"				"DAMAGE_TYPE_PHYSICAL"
		"MaxLevel"							"1"
		"AbilityCooldown"				    "3"
		"AbilityManaCost"					"0"
		"AbilityCastPoint"					"0.2"
		"AbilityCastAnimation"                      "ACT_DOTA_CAST_ABILITY_3"
		"precache"
		{
			"particle"		"particles/hijikata/hijikata_knockup_slash_new.vpcf"
		}
		"AbilityValues"
		{
			"damage"									"630"		
			"duration"									"0.9"
			"width"										"180"
			"range"										"300"
		}
	}
    

	"hijikata_shinsengumi_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/hijikata/hijikata_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/hijikata/hijikata_sa4"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"15"

		 
		"AbilityValues"
        {
			"armor"										"15"
			"mr"										"10"
			"ms"										"30"
			"health_regen"										"150"
			"mana_regen"										"100"
			"regen_duration"									"5"
        }		
	}

	"hijikata_battle_continuation_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/hijikata/hijikata_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/hijikata/hijikata_sa3"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"10"

		 
		"AbilityValues"
        {
            "cooldown" "75"
            "health_restored" "25"
            "duration" "1"
        }		
	}

	"hijikata_eternal_madness_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/hijikata/hijikata_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/hijikata/hijikata_sa"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"12"

		 
		"AbilityValues"
        {
            "recast_amount" "3"
            "bonus_damage" "15"
            "bonus_health" "50"
            "max_stacks" "7"
        }		
	}

	"hijikata_tactics_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/hijikata/hijikata_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/hijikata/hijikata_sa2"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"13"

		 
		"AbilityValues"
        {
            "max_damage_pct" "150"
            "slow_duration" "2"
            "slow_amount" "60"
            "bonus_damage" "100"
            "max_ms"								"600"	
			"max_attack_damage"						"200"	
			"ms_per_stack"						"1"
			"distance_for_stack"						"25"
        }		
	}
	
	"hijikata_fierce_sincerity_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/hijikata/hijikata_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/hijikata/hijikata_sa5"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"8"

		 
		"AbilityValues"
        {
            "cleave_radius" 			"500"
            "cleave_damage_pct" 		"50"
            "damage_bonus" 				"100"
            "shinsengumi_damage_bonus"  "150"
        }		
	} 
 
}