"DOTAAbilities"
{
	//====================================
	// Aozaki Aoko : Shield
	//====================================
	"aoko_shield"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/aoko/aoko_shield"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_CHANNELLED | DOTA_ABILITY_BEHAVIOR_AUTOCAST"
		"AbilityTextureName"			"custom/aoko/aoko_shield"
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"7"
		"AbilityManaCost"				"50"
		"AbilityChannelTime"			"1"
		"AbilityCastAnimation" 			"ACT_SCRIPT_CUSTOM_8"

		"LinkedAbilities"				"aoko_jumpback"

		"precache"
		{
			"particle"			"particles/aoko/aoko_shield.vpcf"
			"particle"			"particles/aoko/aoko_red_warp.vpcf"
			"particle"			"particles/aoko/aoko_blue_warp.vpcf"
		}

		"AbilityValues"
		{	
			"cast_point"				"0.0"
			"mana"						"20 25 30 35 40"
			"mana_cost"					"50"
			"channel_duration"			"1"
			"shield_amount"				"400"
			"distance"					"450"
			"cooldown_reduction"		"5"
			"stack_gain"				"10"
			"shield_damage_decrease_flat_value"				"300 375 450 525 600"
		}
	}

	//=================================================================================================================
	// Aozaki Aoko: Blazing Starmine: Retreat
	//=================================================================================================================
	"aoko_jumpback"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/aoko/aoko_jumpback"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"AbilityTextureName"			"custom/aoko/aoko_jumpback"
		"AbilityCastAnimation" 			"ACT_DOTA_IDLE"
		"AnimationPlaybackRate" 		"0.25"
		"AbilityCastPoint"				"0.2"
		"AbilityCooldown"				"9"
		"AbilityManaCost"				"50"

		"precache"
		{
			"particle"					"particles/aoko/aoko_beam_laser_ground.vpcf"
		}
		
		"AbilityValues"
		{
			"cast_point"			"0.2"
			"mana_cost"				"50"
			"range"					"520"
			"beam_count"			"13"
			"beam_forward"			"75"
			"damage"				"150 187.5 225 262.5 300"
			"radius"				"150"
			"sphere_damage"			"60 70 80 90 100"
			"sphere_lock"			"1.1 1.2 1.3 1.4 1.5"
			"attribute_ms"			"30%"
			"attribute_ms_duration"	"6"
			"stack_gain"			"10"
		}
	}

	//=================================================================================================================
	// Aozaki Aoko: Workout Routine
	//=================================================================================================================
	"aoko_facebreaker"
	{
		"BaseClass"             		"ability_lua"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_CHANNELLED | DOTA_ABILITY_BEHAVIOR_OVERSHOOT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"

		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"

		"AbilityTextureName"			"custom/aoko/aoko_facebreaker"
		"ScriptFile"					"abilities/aoko/aoko_facebreaker"

		"AbilityCastAnimation" 			"ACT_SCRIPT_CUSTOM_7"
		"AnimationPlaybackRate" 		"2.0"

		"LinkedAbilities"				"aoko_sphere"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		//"AbilityCastPoint"				"0.3"
		"AbilityChannelTime"			"0.3"
		"AbilityCastRange"				"600"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"12"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"100"

		"precache"
		{
			"particle"					"particles/aoko/aoko_facebreaker.vpcf"
		}

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
        	"cast_point"				"0.0"
        	"channel_duration"			"0.3"
        	"mana_cost"					"100"
            "width" 					"300"
            "range" 					"600"
            "damage"					"200 250 300 350 400"
            "stun_duration"				"0.2"
            "attribute_shield_amount"	"600 675 750 825 900"
            "attribute_shield_duration"	"2"
            "stack_gain"				"30"
        }
	}

	//=================================================================================================================
	// Aozaki Aoko: Floating Starmine
	//=================================================================================================================
	"aoko_sphere"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/aoko/aoko_sphere"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_HIDDEN | DOTA_ABILITY_BEHAVIOR_OVERSHOOT | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"

		"AbilityCastAnimation" 			"ACT_SCRIPT_CUSTOM_10"
		"AnimationPlaybackRate" 		"1.0"

		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/aoko/aoko_sphere"
		"AbilityCastRange"				"1100"

		"AbilityCastPoint"				"0.2"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"100"
		"AbilityCharges"				"3"
		//"AbilityChargeRestoreTime"		"25 22.5 20 17.5 15"
		"AbilityCooldown"				"0.0"

		"precache"
		{
			"particle"					"particles/aoko/aoko_sphere.vpcf"
			"particle"					"particles/aoko/aoko_sphere_cast.vpcf"
			"particle"					"particles/aoko/aoko_sphere_aoe_area.vpcf"
			"particle"					"particles/aoko/aoko_sphere_meltdown.vpcf"
		}
		
		"AbilityValues"
		{
			"cast_point"					"0.2"
			"charge_amount"					"3"
			"base_charge_restore_time"		"10 9 8 7 6"
        	"mana_cost"						"100"
			"damage"						"100 125 150 175 200"
			"duration"						"5"
			"radius"						"500"
			"attribute_healres"				"-30"
			"attribute_healres_duration"	"4"
			"explosion_count"				"4"
			"proximity_explosion_count"		"4"
			"proximity_radius"				"200"
			"vision_radius"					"250"
			"range"							"1100"
			"explosion_stacks"				"5"
		}
	}

	//=======================================
	// Aozaki Aoko - Browning Starmine: Burst
	//=======================================
	"aoko_short_beam"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/aoko/aoko_short_beam"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"

		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1.0"

		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/aoko/aoko_short_beam"
		//"AbilityCastRange"				"300"

		"AbilityCastPoint"				"0.2"

		"LinkedAbilities"				"aoko_lazers"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"200"
		"AbilityCooldown"				"14"

		"precache"
		{
			"particle"					"particles/aoko/aoko_beam_laser_short.vpcf"
		}
		
		"AbilityValues"
		{	
			"cast_point"							"0.2"
        	"mana_cost"								"200"
			"damage"								"250 312.5 375 437.5 500"
			"circuit_amplify_per_stack"				"0.4"
			"range"									"600"
			"sphere_damage"							"200 250 300 350 400"
			"sphere_root"							"1.4 1.5 1.6 1.7 1.8"
			"sphere_disarm"							"2.0 2.5 3.0 3.5 4.0"
			"attribute_magical_damage_reduction"	"20"
			"attribute_debuff_duration"				"5"
			"attribute_int_scaling"					"1"
			"stack_gain"							"20"
		}
	}

	//=================================================================================================================
	// Aozaki Aoko: Browning Starmine: Barrage
	//=================================================================================================================
	"aoko_lazers"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/aoko/aoko_lazers"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_CHANNELLED | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"

		"AbilityCastAnimation" 			"ACT_SCRIPT_CUSTOM_9"
		"AnimationPlaybackRate" 		"1.0"

		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/aoko/aoko_lazers"
		//"AbilityCastRange"				"300"

		"AbilityCastPoint"				"0.2"
		"AbilityChannelTime"			"0.8"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"200"
		"AbilityCooldown"				"14"

		"precache"
		{
			"particle"					"particles/aoko/aoko_beam_laser_rapid.vpcf"
		}
		
		"AbilityValues"
		{
			"cast_point"				"0.2"
			"channel_duration"			"0.8"
        	"mana_cost"					"200"
			"damage"					"20 25 30 35 40"
			"circuit_amplify_per_stack"	"0.4"
			"range"						"1100"
			"sphere_damage"				"20 25 30 35 40"
			"sphere_slow_duration"		"1 1.2 1.4 1.6 1.8"
			"sphere_slow"				"30"
			"attribute_int_scaling"		"0.1"
			"attribute_vision_duration"	"3"
			"stack_gain"				"4"
			"max_stacks"				"20"
		}
	}

	//=================================================================================================================
	// Aozaki Aoko: Stance Swap
	//=================================================================================================================

	"aoko_swap"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/aoko/aoko_swap"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_SILENCE"

		"AbilityTextureName"			"custom/aoko/aoko_swap"
		
		"AbilityValues"
		{
			"cast_point"				"0"
		}
	}

	//=================================================================================================================
	// Aozaki Aoko: High-Speed Magic Circuits
	//=================================================================================================================
	"aoko_circuits"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/aoko/aoko_circuits"
		"MaxLevel"						"2"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"25"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_DONT_CANCEL_CHANNEL | DOTA_ABILITY_BEHAVIOR_IGNORE_SILENCE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityUnitTargetFlags"		"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityTextureName"			"custom/aoko/aoko_circuits"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		
		// Cast
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"30 20"
		"AbilityManaCost"				"0"
		
		// Ability Special
		//-------------------------------------------------------------------------------------------------------------
		"precache"
		{
			"particle"					"particles/aoko/aoko_overload_ambient.vpcf"
			"particle"					"particles/aoko/aoko_circuits_blue.vpcf"
			"particle"					"particles/aoko/aoko_circuits_red.vpcf"
			"particle"					"particles/aoko/aoko_circuits_overload.vpcf"
		}

		"AbilityValues"
		{	
			"cast_point"					"0.0"
			"stack_max"						"100"
			"stacks_duration"				"12" //stacks duration and overload duration, as well as combo overload duration, require manual particle fixes because i'm pepega
			"manaregen_per_stack"			"1 1.3"
			"manacost_increase_per_stack"	"0"
			"overload_magres"				"15 20"
			"overload_armor"				"15 20"
			"overload_lifesteal"			"30 45"
			"overload_ms"					"25 30"
			"attribute_cdr_per_stack"		"0.1"
			"overload_duration"				"20"
			"overload_threshold"			"100"
			"overload_sphere_charge_time"	"4"
			"overload_cc_immune_duration"	"0 1.5"
			"blue_cc_immune_duration"		"0 7"
		}		
	}

	//=================================================================================================================
	// Aozaki Aoko: Forced Rotation Acceleration
	//=================================================================================================================

	"aoko_intimidation"
	{
		"BaseClass"             		"ability_lua"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"

		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"

		"AbilityTextureName"			"custom/aoko/aoko_intimidation"
		"ScriptFile"					"abilities/aoko/aoko_intimidation"

		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_6"
		"AnimationPlaybackRate" 		"1.0"

		"LinkedAbilities"				"aoko_3_beams"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastPoint"				"0.45"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"20"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"400"

		"precache"
		{
			"particle"					"particles/aoko/aoko_intimidation_grab.vpcf"
			"particle"					"particles/aoko/aoko_intimidation_impact.vpcf"
			"particle"					"particles/aoko/aoko_intimidation_hands_trail.vpcf"
		}

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
        	"cast_point"			"0.45"
        	"mana_cost"				"400"
            "speed" 				"3000"
            "range" 				"1000"			
            "grab_damage"			"200 250 300 350 400"
            "impact_health_damage"	"400 500 600 700 800"
            "impact_aoko_damage"	"600 750 900 1050 1200"
            "impact_radius"			"600"
            "slow_duration"			"2"
            "slow_pct"				"40 45 50 55 60"
            "lock_duration"			"1"
            "sphere_damage"			"0"
            "grab_stacks"			"10"
            "impact_stacks"			"20"
        }
	}

	//=================================================================================================================
	// Aozaki Aoko: Severe Break Slider
	//=================================================================================================================
	"aoko_3_beams"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/aoko/aoko_3_beams"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/aoko/aoko_slider"
		"AbilityCastAnimation" 			"ACT_SCRIPT_CUSTOM_11"
		"AnimationPlaybackRate" 		"1"

		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		//"AbilityCastRange"				"1200"
		"AbilityCastPoint"				"0.2"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"30"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"300"

		"precache"
		{
			"particle"					"particles/aoko/aoko_big_beam.vpcf"
			"particle"					"particles/aoko/aoko_big_beam_runes.vpcf"
			"particle"					"particles/aoko/aoko_big_beam_runes_leg.vpcf"
		}
		
		"AbilityValues"
        {
        	"cast_point"				"0.2"
        	"mana_cost"					"300"
            "damage" 					"300 400 500 600 700"
            "damage_leg" 				"450 600 750 900 1050"
            "attribute_int_scale"		"0.5"
            "attribute_int_scale_leg"	"0.75"
            "duration" 					"0.5"
            "distance" 					"1400"
            "radius" 					"200"
            "first_threshold"			"40"
            "second_threshold"			"80"
            "window_duration"			"2.5"
            "sphere_dps"				"100 125 150 175 200"
			"sphere_slow"				"40"
            "stack_gain"				"10"
        }
	}

	//=================================================================================================================
	// Aozaki Aoko: Fifth Magic - Blue
	//=================================================================================================================
	"aoko_blue"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/aoko/aoko_blue"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_FRIENDLY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO"

		"AbilityCastAnimation" 			"ACT_SCRIPT_CUSTOM_15"
		"AnimationPlaybackRate" 		"1.0"

		"AbilityTextureName"			"custom/aoko/aoko_blue"
		
		"AbilityCastRange"				"1500"

		"AbilityCastPoint"				"0.3"
		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"400"
		"AbilityCooldown"				"300"

		"precache"
		{
			"particle"					"particles/aoko/aoko_res_overhead.vpcf"
			"particle"					"particles/aoko/aoko_blue_runes.vpcf"
			"particle"					"particles/aoko/aoko_blue_runes_target.vpcf"
			"particle"					"particles/aoko/aoko_blue_flowers.vpcf"
			"particle"					"particles/aoko/aoko_blue_pulse_ring_white.vpcf"
			"particle"					"particles/aoko/aoko_blue_pulse_ring_green.vpcf"
			"particle"					"particles/aoko/aoko_blue_pulse_ring_pink.vpcf"
			"particle"					"particles/aoko/aoko_blue_pulse_ring_blue.vpcf"
			"particle"					"particles/aoko/aoko_blue_pulse_ring_yellow.vpcf"
		}
		
		"AbilityValues"
		{
			"cast_point"						"0.3"
        	"mana_cost"							"400"
			"duration"							"60"
			"cast_range"						"1000"
			"ally_search_radius"				"500"
			"shield_amount"						"3500"
			"attribute_bonus_shield"			"1500"
			"attribute_bonus_cast_range"		"500"
			"attribute_ms"						"700"
			"attribute_ms_duration"				"7"
			"end_shield_amount"					"10000"
			"end_shield_decay"					"2000"
			"end_shield_duration"				"5"
		}
	}

	//=======================================
	// Aozaki Aoko - Attributes
	//=======================================

	"aoko_circuits_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/aoko/aoko_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/aoko/aoko_circuits_attribute"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"8"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
        	"shield_cooldown_reduction"		"5"
        	"jumpback_ms"					"30%"
			"jumpback_ms_duration"			"6"
			"overload_cc_immune_duration"	"1.5"
			"blue_cc_immune_duration"		"7"
        }		
	}

	"aoko_first_star_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/aoko/aoko_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/aoko/aoko_first_star"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"9"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
        	"facebreaker_shield_amount"	"600 675 750 825 900"
        	"sphere_healres"			"30"
			"sphere_healres_duration"	"4"
        }		
	}

	"aoko_bullet_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/aoko/aoko_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/aoko/aoko_incantation"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"10"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
        	"short_beam_debuff_power"	"20"
        	"short_beam_duration"		"5"
        	"short_beam_int_scale"		"1"
        	"lazers_int_scale"			"0.1"
        	"lazers_vision_duration"	"3"
        }		
	}

	"aoko_incantation_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/aoko/aoko_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/aoko/aoko_bullet"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"11"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
        	"severe_int_scale"			"0.5"
        	"severe_int_scale_leg"		"0.75"
        }		
	}

	"aoko_magician_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/aoko/aoko_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/aoko/aoko_magician"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"10"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
        	"blue_bonus_range"			"0"
        	"blue_shield_amount"		"1500"
        	"blue_ms"					"700"
			"blue_ms_duration"			"7"
        	"cdr_per_stack"				"0.1"
        }		
	}

	//=================================================================================================================
	// Unused dogshit section
	//=================================================================================================================
	//=================================================================================================================
	// Aozaki Aoko: Browning Starmine - Spark
	//=================================================================================================================

	"aoko_beam"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/aoko/aoko_beam"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"

		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1.0"

		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/altera/altera_sword"
		//"AbilityCastRange"				"300"

		"AbilityCastPoint"				"0.2"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"50"
		"AbilityCooldown"				"3"

		"precache"
		{
			"particle"					"particles/aoko/aoko_beam_laser_simple.vpcf"
		}
		
		"AbilityValues"
		{
			"damage"					"100 150 200 250 300"
			"range"						"800"
		}
	}

	//=================================================================================================================
	// Aozaki Aoko: Acceleration Kick
	//=================================================================================================================
	"aoko_round_kick"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/aoko/aoko_round_kick"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityTextureName"			"custom/ryougi/ryougi_backflip"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_2"
		"AnimationPlaybackRate" 		"1.0"
		//"AbilityCastPoint"				"0.1"
		"AbilityCooldown"				"12"
		"AbilityManaCost"				"100"
		
		"AbilityValues"
		{
			"cast_point"			"0.0"
			"damage"				"300 375 450 525 600"
			"radius"				"400"
		}
	}

	//=================================================================================================================
	// Aozaki Aoko: Star Fist
	//=================================================================================================================
	"aoko_punch"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/aoko/aoko_punch"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_OVERSHOOT"
		"AbilityTextureName"			"custom/okita/okita_seigan"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_2"
		"AnimationPlaybackRate" 		"1.0"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityManaCost"				"400"
		"AbilityCooldown"				"18"
		"AbilityCastPoint"				"0.2"
		"AbilityCastRange"				"350"
		
		"AbilityValues"
		{	
			"cast_point"			"0.2"
		}
	}

	//=================================================================================================================
	// Aozaki Aoko: Cardio Routine
	//=================================================================================================================
	"aoko_dailin"
	{
		"BaseClass"             		"ability_lua"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"

		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"

		"AbilityTextureName"			"custom/edmon/enfer"
		"ScriptFile"					"abilities/aoko/aoko_dailin"

		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_6"
		"AnimationPlaybackRate" 		"1.0"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastPoint"				"0.3"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"20"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"400"

		"precache"
		{
			"particle"					"particles/aoko/aoko_blast.vpcf"
		}

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "speed" "3000"
            "range" "800"
        }
	}
}