"DOTAAbilities"
{
	//=======================================★★★★★
	// Robin: Yew Bow
	//=======================================★★★★★
	"robin_yew_bow"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/robin/robin_yew_bow"
		"AbilityTextureName"			"custom/robin/robin_yew_bow"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"precache"
		{
			"soundfile"	"soundevents/game_sounds_heroes/game_sounds_sniper.vsndevts"
			"particle"		"particles/custom/robin/robin_yew_bow.vpcf"
			"particle"		"particles/custom/robin/robin_yew_bow_impact.vpcf"
			"particle"		"particles/custom/robin/robin_yew_bow_poison.vpcf"
			"particle"		"particles/custom/robin/robin_crosshair_lockon.vpcf"
		}
		
		// Ability General
		//-------------------------------------------------------------------------------------------------------------
		"AbilityType"					"DOTA_ABILITY_TYPE_BASIC"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_NORMAL_WHEN_STOLEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitTargetFlags"		"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES | DOTA_UNIT_TARGET_FLAG_INVULNERABLE"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"SpellDispellableType"			"SPELL_DISPELLABLE_NO"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_YES"
		"AbilityCastAnimation" 				"ACT_DOTA_CAST_ABILITY_7"

		// Ability Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"1400"
		"AbilityCastRangeBuffer"		"400"
		"AbilityCastPoint"				"1.2"
		"AnimationPlaybackRate" 		"1.2"

		// Ability Resource
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"30"
		"AbilityManaCost"				"800"
		
		// Values
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
		{
			"cast_delay"				"1.50"
			"projectile_speed"			"2500"
			"range"						"1400"
			"damage"					"400 500 600 700 800"
			"damage_stack"				"20 24 28 32 36"
			"silence_duration"			"1.50"
			"poison_detonation_radius"	"1000"
		}
	}
}