"DOTAAbilities"
{
	//=======================================★★★★★
	// Robin : Workshop Tools
	//=======================================★★★★★
	"robin_tools"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/robin/robin_tools"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL "
		"AbilityTextureName"			"custom/robin/robin_tools"
		"AbilityCooldown"				"0.0"
		"AbilityCastPoint"				"0.0"
		"LinkedAbilities"				"robin_tools_its_a_trap robin_tools_mysterious_substance robin_tools_pitfall robin_tools_wolfs_bane"
	}

	"robin_tools_close"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/robin/robin_tools"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/robin/robin_tools"
		
		"AbilityCooldown"				"0.0"
		"AbilityCastPoint"				"0.0"
	}
}