"DOTAAbilities"
{
	//=======================================★★★★★
	// Robin: Yew Bow
	//=======================================★★★★★
	"robin_yew_tree_combo"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/robin/robin_yew_tree_combo"
		"AbilityTextureName"			"custom/robin/robin_yew_tree_combo"
		"MaxLevel"						"1"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"precache"
		{
			"soundfile"	"soundevents/game_sounds_heroes/game_sounds_sniper.vsndevts"
			"particle"		"particles/custom/robin/robin_yew_bow.vpcf"
			"particle"		"particles/custom/robin/robin_yew_bow_combo_impact.vpcf"
			"particle"		"particles/custom/robin/robin_yew_bow_combo_poison.vpcf"
			"particle"		"particles/custom/robin/robin_yew_bow_impact.vpcf"
			"particle"		"particles/custom/robin/robin_yew_bow_poison.vpcf"
			"particle"		"particles/custom/robin/robin_crosshair_lockon.vpcf"
		}
		
		// Ability General
		//-------------------------------------------------------------------------------------------------------------
		"AbilityType"					"DOTA_ABILITY_TYPE_BASIC"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_NORMAL_WHEN_STOLEN | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitTargetFlags"		"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES | DOTA_UNIT_TARGET_FLAG_INVULNERABLE"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"SpellDispellableType"			"SPELL_DISPELLABLE_NO"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_YES"
		"AbilityCastAnimation" 				"ACT_DOTA_CAST_ABILITY_3"

		// Ability Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"2500"
		"AbilityCastRangeBuffer"		"200"
		"AbilityCastPoint"				"0.1"

		// Ability Resource
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"180"
		"AbilityManaCost"				"800"
		
		// Values
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
		{
			"cast_delay"				"3.4"
			"projectile_speed"			"2500"
			"range"						"2500"
			"radius"					"1800"
			"damage"					"800"
			"damage_stack"				"50"
			"poison_damage"				"4000"
			"silence_duration"			"1.50"
			"poison_detonation_radius"	"1000"
		}
	}
}