#base "nero_tres_fontaine_ardent.kv"
#base "nero_gladiusanus_blauserum.kv"
#base "nero_rosa_ichthys.kv"
#base "nero_aestus_domus_aurea.kv"
#base "nero_laus_saint_claudius.kv"
#base "nero_aestus_estus.kv"

"DOTAAbilities"
{
	//=======================================
	// Nero Attribute : Pari Tenu Blauserum
	//=======================================
	"nero_attribute_pari_tenu_blauserum"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/nero/nero_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/nero/nero_pari"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"16"

		"LinkedAbilities"				"nero_tres_buffed nero_gladiusanus_buffed nero_rosa_buffed nero_spectaculi_buffed"

		"precache"
		{
		}

		"AbilityValues"
        {
            "gladiu_aspd" "8"
            "rosa_slow" "-30"
            "tres_attack" "2"
            "stun_duration" "0.35"
            "agi_damage" "5"
        }
	}

	//=======================================
	// Nero Attribute : Improve Imperial Privilege
	//=======================================
	"nero_attribute_improve_imperial_privilege"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/nero/nero_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/nero_attribute_improve_imperial_privilege"
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"9"
	}

	//=======================================
	// Nero Attribute : Invictus Spiritus
	//=======================================
	"nero_attribute_invictus_spiritus"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/nero/nero_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/nero_attribute_invictus_spiritus"
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"9"
	}


	//=================================================================================================================
	// Nero : Invictus Spiritus
	//=================================================================================================================
	"nero_invictus_spiritus"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/nero/nero_invictus_spiritus"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO"
		"AbilityTextureName"			"custom/nero_attribute_invictus_spiritus"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_4"
		"AbilityCastRange"				"700"
		"AbilityCastRangeBuffer"		"200"
		"AbilityCastPoint"				"0.3"
		"AbilityCooldown"				"130"
		"AbilityManaCost"				"200"
	}

	//=======================================
	// Nero Attribute : Soverign's Glory
	//=======================================
	"nero_attribute_soverigns_glory"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/nero/nero_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/nero/nero_glory"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"12"

		"precache"
		{
		}

		"AbilityValues"
        {
            "bonus_aoe" "150"
            "armor_reduction" "3"
            "mr_reduction" "5"
            "chance" "50"
        }
	}
	//=======================================
	// Nero Attribute : Diabolis Vectis
	//=======================================
	"nero_attribute_diabolis_vectis"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/nero/nero_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/nero/nero_vectis"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"6"

		"precache"
		{
		}

		"AbilityValues"
        {
            "bonus_aoe" "150"
            "armor_reduction" "3"
            "mr_reduction" "5"
            "chance" "50"
        }
	}
}