"DOTAAbilities"
{
	//=================================================================================================================
	// Nero: Aestus Estus Passive
	//=================================================================================================================
	"nero_aestus_estus_passive"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/nero/nero_aestus_estus_passive"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_HIDDEN | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityTextureName"			"custom/nero/nero_gladiusanus_blauserum"
		"MaxLevel"						"1"
		
		"AbilityValues"
        {
            "cdr_per_hit" "1"
            "dmg_on_hit" "75"
        }
		
		"OnSpelLStart"
		{
		}
	}
}