"DOTAAbilities"
{
	//===================================================
	// Archer : Nine Lives
	//===================================================
	"kuro_nine_lives"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kuro/kuro_nine_lives"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/archer_5th_nine_lives"
		"AbilityCastAnimation" 			"ACT_DOTA_ITEM_PICKUP"		
		
		"precache"
		{
			"particle"					"particles/custom/berserker/nine_lives/hit.vpcf"
			"particle"					"particles/custom/berserker/nine_lives/last_hit.vpcf"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_earth_spirit.vsndevts"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_ogre_magi.vsndevts"
		}
		
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"300"
		"AbilityCastPoint"				"0.2"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"35"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"600"
		
		"AbilityValues"
        {
            "radius" "275"
            "damage" "70 80 90 100 110"
            "radius_lasthit" "375"
            "damage_lasthit" "500 575 650 725 800"
            "stun_duration" "0.75"
            "range" "700"
            "cooldown" "35"
            "cooldown_reduction" "35"
            "manacost" "600"
        }
	}


	"kuro_rosa_ichthys"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/kuro/kuro_rosa_ichthys"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/nero_rosa_ichthys"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		
		// Ability stats
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"700"
		"AbilityCastRangeBuffer"		"125"
		"AbilityCastPoint"				"0.2"
		"AbilityCooldown"				"12"
		"AbilityManaCost"				"200"

		// Data driven
		//-------------------------------------------------------------------------------------------------------------
		"precache"						
		{
			"particle"			"particles/custom/archer/archer_overedge_slash.vpcf"
			"particle"			"particles/units/heroes/hero_legion_commander/legion_duel_start_text_burst_flare.vpcf"
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_lion.vsndevts"
			"particle"		"particles/custom/nero/nero_scorched_earth_child_embers_rosa.vpcf"
		}		

		// Ability special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "damage" "350 425 500 575 650"
            "range" "700"
            "stun_duration" "1.5"
            "aestus_cooldown" "3"
            "projection_damage" "125 150 175 200 225"
            "aestus_range" "900"
            "cooldown" "12"
            "manacost" "200"
        }
	}
}