"DOTAAbilities"
{
	//=======================================★★★★★
	// Lu Bu: Rebellious Spirit (D)
	//=======================================★★★★★
	"lu_bu_rebellious_spirit"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/lu_bu/lu_bu_rebellious_spirit"
		"MaxLevel"						"2"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityType"					"DOTA_ABILITY_TYPE_BASIC"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityTextureName"			"custom/lu_bu/lu_bu_rebellious_spirit"
		
		// Ability Stats		//------------------------------------------------------------------------------------------------------------
		
		// Precache		//------------------------------------------------------------------------------------------------------------
		"precache"
		{
			"particle"			"particles/custom/enkidu/enkiduenergyblades.vpcf"
			"particle"				"particles/units/heroes/hero_huskar/huskar_berserkers_blood_glow.vpcf"
		}
		
		// Ability Special		//------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "maximum_resistance" "15 30"
            "maximum_mana_regen" "10 20"
            "hp_threshold_max" "20"
        }
	}
}