#base "true_assassin_ambush.kv"
#base "true_assassin_dirk.kv"
#base "true_assassin_selfmod.kv"
#base "true_assassin_snatch_strike.kv"
#base "true_assassin_zabaniya.kv"

"DOTAAbilities"
{
	//========================================
	// True Assassin : Delusional Illusion
	//========================================
	"true_assassin_combo"
	{
		"BaseClass"						"ability_datadriven"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/true_assassin_combo"
		"MaxLevel"						"1"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_6"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AnimationPlaybackRate" 		"1.0"
		"precache"
		{
			"particle"				"particles/custom/ta/zabaniya_projectile.vpcf"
			"particle"				"particles/units/heroes/hero_chaos_knight/chaos_knight_reality_rift.vpcf"
			"particle"				"particles/econ/items/phantom_assassin/phantom_assassin_arcana_elder_smith/pa_arcana_loadout.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_nightstalker.vsndevts"
		}
		

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"160"
		"AbilityCastPoint"				"0.0"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"100"
		
		"AbilityValues"
        {
            "search_radius" "650"
            "duration" "8.0"
            "base_damage" "500"
            "bonus_damage" "25"
        }
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"		"ta_ability"
				"Function"			"OnDIStart"
			}
		}
		"Modifiers"
		{
			"modifier_delusional_illusion_cooldown"
			{
				"IsDebuff"	"1"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}

		}
	}

	//=====================================
	// True Assassin : Combo Zabaniya
	//=====================================
	"true_assassin_combo_zab"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/ta_zabaniya"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_6"
		"AbilityCastPoint"				"0.0"
		"AnimationPlaybackRate" 		"1.0"

		"precache"
		{
			"particle"		"particles/custom/ta/zabaniya_projectile.vpcf"
			"particle"		"particles/units/heroes/hero_chaos_knight/chaos_knight_reality_rift.vpcf"
			"particle"		"particles/custom/ta/zabaniya_fiendsgrip_hands_combo.vpcf"
			"particle"		"particles/custom/ta/zabaniya_ulti_smoke.vpcf"
			"particle"		"particles/econ/items/phantom_assassin/phantom_assassin_arcana_elder_smith/pa_arcana_loadout.vpcf"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_phantom_assassin.vsndevts"
			"particle" 		"particles/units/heroes/hero_phantom_assassin/phantom_assassin_stifling_dagger.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_nightstalker.vsndevts"
		}
		
		"AbilityCastRange"				"1500"
		"AbilityCastRangeBuffer"		"300"
		"AbilityCooldown"				"0"
		
		"precache"
		{
		}

		"AbilityValues"
        {
        }

		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"		"ta_ability"
				"Function"			"OnDIZabStart"
			}
		}
		"OnProjectileHitUnit"
		{
			"DeleteOnHit"			"true"
			"RunScript"
			{
				"ScriptFile"    "ta_ability"
				"Function"      "OnDIZabHit"
			}
		}
	}
	
	//=================================================================================================================
	// TA : Protection from Wind
	//=================================================================================================================
	"true_assassin_protection_from_wind"
	{
		"BaseClass"						"ability_lua"
		"precache"
		{
			"particle"		"particles/okita/okita_windrun.vpcf"
		}
		"ScriptFile"					"abilities/true_assassin/true_assassin_protection_from_wind"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityTextureName"			"custom/true_assassin_attribute_protection_from_wind"
		"MaxLevel"						"2"
		"AbilityCooldown"				"20"
		
		"AbilityValues"
        {
            "duration" "4"
            "ms_bonus" "50"
            "behavior" "2 4"
        }
	}

	
	//=======================================
	// TA Attribute : Improve Presence Concealment
	//=======================================
	"true_assassin_attribute_improve_presence_concealment"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/true_assassin_attribute_improve_presence_concealment"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"13"

		"precache"
		{
		}

		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"ta_ability"
				"Function"		"OnImprovePresenceConcealmentAcquired"
			}
		}
	}

	//=======================================
	// TA Attribute : Weakening Venom
	//=======================================
	"true_assassin_attribute_weakening_venom"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/true_assassin_attribute_weakening_venom"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"10"

		"precache"
		{
		}

		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"ta_ability"
				"Function"		"OnWeakeningVenomAcquired"
			}
		}
	}

	//=======================================
	// TA Attribute : Shadow Strike
	//=======================================
	"true_assassin_attribute_shadow_strike"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/true_assassin_attribute_shadow_strike"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"12"

		"precache"
		{
		}

		"AbilityValues"
        {
            "zab_curse_dur" "1.5"
            "zab_add_dmg" "5"
            "combo_bonus_damage" "100"
            "zab_bonus_damage" "50"
        }
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"ta_ability"
				"Function"		"OnShadowStrikeAcquired"
			}
		}
	}

	//=======================================
	// TA Attribute : Arm of Shaytan
	//=======================================
	"true_assassin_attribute_shaytan_arm"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/true_assassin_shaytan_arm"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"10"

		"precache"
		{
		}

		"AbilityValues"
        {
            "snatch_agi_dmg" "1.5"
        }
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"ta_ability"
				"Function"		"OnShaytanArmAcquired"
			}
		}
	}
	//=======================================
	// TA Attribute : Desert Nomad
	//=======================================
	"true_assassin_attribute_desert_nomad"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/true_assassin/ta_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/true_assassin/desert_nomad"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"8"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
            "health_percent" "25"
        }		
	}
}