"DOTAAbilities"
{
	//=====================================
	// True Assassin : Dirk
	//=====================================
	"true_assassin_dirk"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/true_assassin/true_assassin_dirk"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PHYSICAL"
		"AbilityTextureName"			"custom/true_assassin_dirk"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_4"
		"AnimationPlaybackRate" 		"1.0"
		"AbilityUnitTargetFlags"		"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityCastPoint"				"0.1"
		"AbilityCastRange"				"700 750 800 850 900"
		"AbilityCooldown"				"1.8"
		"AbilityManaCost"				"100"

		"precache"
		{
			"particle"					"particles/units/heroes/hero_phantom_assassin/phantom_assassin_stifling_dagger.vpcf"
			"particle"					"particles/units/heroes/hero_dazzle/dazzle_poison_debuff.vpcf"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_phantom_assassin.vsndevts"
		}

		"AbilityValues"
        {
            "damage" "50 62.5 75 87.5 100"
            "poison_dot" "10 12.5 15 17.5 20"
            "poison_slow" "5"
            "duration" "6"
            "range" "700 750 800 850 900"
            "atk_ratio" "20"
            "max_daggers" "5"
            "restock_dur" "2.5"
            "agi_mult" "0.2"
        }
	}	
}