"DOTAAbilities"
{
	//=====================================
	// True Assassin : Snatch Strike
	//=====================================
	"true_assassin_snatch_strike"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/true_assassin/true_assassin_snatch_strike"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/true_assassin_snatch_strike"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"1.0"
		
		"AbilityCastPoint"				"0.56"
		//"AbilityCastRange"				"%range"
		"AbilityCooldown"				"18"
		"AbilityManaCost"				"400"
		
		"precache"
		{
			"particle"					"particles/units/heroes/hero_night_stalker/nightstalker_void.vpcf"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_nightstalker.vsndevts"
		}

		"AbilityValues"
        {
            "damage" "375 469 562 656 750"
            "duration" "8"
            "bonus_strength" "8 10 14 16 20"
            "range" "450"
        }
	}
}