"DOTAAbilities"
{
	//=====================================
	// True Assassin : Zabaniya
	//=====================================
	"true_assassin_zabaniya"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/true_assassin/true_assassin_zabaniya"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitTargetFlags"		"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PURE"
		"AbilityTextureName"			"custom/true_assassin_zabaniya"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_6"
		"AbilityType"					"ABILITY_TYPE_ULTIMATE"
		"AnimationPlaybackRate" 		"1.5"

		"precache"
		{
			"particle"				"particles/custom/ta/zabaniya_projectile.vpcf"
			"particle"				"particles/custom/ta/zabaniya_ulti_smoke.vpcf"
			"particle"				"particles/custom/ta/zabaniya_fiendsgrip_hands.vpcf"
			"particle"				"particles/econ/items/phantom_assassin/phantom_assassin_arcana_elder_smith/pa_arcana_loadout.vpcf"
			"particle"				"particles/units/heroes/hero_axe/axe_culling_blade_kill_b.vpcf"
			"particle"				"particles/units/heroes/hero_nevermore/nevermore_shadowraze.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_nightstalker.vsndevts"
		}
		
		"AbilityCastPoint"				"0.7"
		"AbilityCastRange"				"700"
		"AbilityCastRangeBuffer"		"150"
		"AbilityCooldown"				"25"
		//"AbilityDamage"					"800 1025 1250 1475 1700"
		"AbilityManaCost"				"800"
		
		"precache"
		{
		}

		"AbilityValues"
        {
            "delay" "0.7"
            "damage" "750 937.5 1125 1312.5 1500"
            "curse_duration" "2.0"
            "bonus_curse_duration" "1.5"
            "heal_reduction" "-80"
        }
	}
}