"DOTAAbilities"
{
	//=================================================================================================================
	// Lancelot : Eternal Arms Mastership
	//=================================================================================================================
	"lancelot_arms_mastership"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/lancelot/lancelot_arms_mastership"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityTextureName"			"custom/lancelot_arms_mastership"
		"MaxLevel"						"1"
		"AbilityCooldown"				"20"
		"precache"
		{
			"particle"					"particles/prototype_fx/item_linkens_buff.vpcf"
			"particle"					"particles/custom/abaddon_death_coil_explosion.vpcf"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_abaddon.vsndevts"
		}
		
		"AbilityValues"
        {
            "active_duration" "5"
            "crit_chance" "25"
            "crit_damage" "200"
            "proc_dmg_reduct" "30"
            "proc_dur" "0.5"
        }
	}
}