"DOTAAbilities"
{
	//=====================================
	// Lancelot : SMG Barrage
	//=====================================

	"lancelot_minigun"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/lancelot/lancelot_minigun"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PHYSICAL"
		"AbilityTextureName"			"custom/lancelot_smg_barrage"
		"AbilityCastAnimation" 			"ACT_DOTA_CHANNEL_END_ABILITY_1"
		"AnimationPlaybackRate" 		"1.0"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
        "LinkedAbilities"                               "lancelot_dash"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastPoint"				"0.3"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"0"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		//"AbilityManaCost"				"0"

		"precache"
		{
			"particle"					"particles/heroes/anime_hero_lancelot/lancelot_minigun_projectile.vpcf"
		}
		
		"AbilityValues"
		{
			"duration"				"5"
			"bullets_per_second"	"10"
			"base_damage"			"20 25 30 35 40"
			"atk_damage"			"10 12.5 15 17.5 20"
			"range"					"1250"
			"mana_per_bullet"		"5"
			"cooldown_per_second"	"3"
			"width"					"96"
			"speed"					"2500"
			"slow_turning"			"-100"
			"ms_slow"				"25"
		}
	}

	"lancelot_minigun_end"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/lancelot/lancelot_minigun"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PHYSICAL"
		"AbilityTextureName"			"custom/lancelot_smg_barrage"
		"AbilityCastAnimation" 			"ACT_DOTA_CHANNEL_END_ABILITY_1"
		"AnimationPlaybackRate" 		"0.9"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastPoint"				"0.0"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		//"AbilityCooldown"				"0"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		//"AbilityManaCost"				"0"
		
		"AbilityValues"
		{
		}
	}
}