#base "lancelot_knight_of_honor.kv"
#base "lancelot_combo_arondite_overload.kv"
//#base "lancelot_durandal.kv"
//#base "lancelot_vajra.kv"
//#base "lancelot_harpe.kv"
//#base "lancelot_hrunt_naeg.kv"
//#base "lancelot_minigun.kv"
#base "eternal_arms.kv"
#base "lancelot_smg_barrage.kv"
#base "lancelot_arondite.kv"

"DOTAAbilities"
{	
	//=================================================================================================================
	// Lancelot - dash (Q-W)
	//=================================================================================================================
	"lancelot_dash"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/lancelot/lancelot_dash"
		"MaxLevel"						"1"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES|DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityTextureName"			"custom/lancelot/lancelot_dash"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_2"
		"AnimationPlaybackRate" 		"1.0"
		"MaxLevel"						"1"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityManaCost"				"100"
		"AbilityCooldown"				"3"
		"AbilityCastPoint"				"0.1"

		"AbilityValues"
        {
        	"distance"				"400"
        	"speed"					"1200"
        }
	}
	//====================================
	// Lancelot rosa
	//====================================
	"lancelot_rosa"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/lancelot/lancelot_rosa"
		"MaxLevel"						"5"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT|DOTA_ABILITY_BEHAVIOR_HIDDEN|DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES |DOTA_ABILITY_BEHAVIOR_AUTOCAST"
		"AbilityTextureName"			"custom/lancelot/lancelot_rosa"
		"AbilityCastPoint"				"0.1"
		"AbilityCooldown"				"20"
		"AbilityManaCost"				"250"



		"precache"
		{
			"particle"			"particles/lancelot/lancelot_slash_rosa.vpcf"
			"particle"			"particles/custom/kinghassan/azraelflash.vpcf"
		}

		"AbilityValues"
		{	
			"cast_point"				"0.1"
			"damage"					"200 250 300 350 400"
			"stun_duration"				"0.3"
			"radius"					"450"
			"dash_radius"					"375"
			"mana"						"200 250 300 350 400"
		}
	}

	//====================================
	// Lancelot overload
	//====================================
	"lancelot_arondight_overload"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/lancelot/lancelot_arondight_overload"
		"MaxLevel"						"5"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT|DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/lancelot/lancelot_arondight_overload"
		"AbilityCastPoint"				"0.4"
		"AbilityCooldown"				"10"
		"AbilityManaCost"				"400"



		"precache"
		{
			"particle"			"particles/custom/lancelot/arondight_overload_new_explosion.vpcf"
			"particle"			"particles/custom/kinghassan/azraelflash.vpcf"
			"particle"			"particles/lancelot/lancelot_slash_overload.vpcf"
		}

		"AbilityValues"
		{	
			"cast_point"				"0.4"
			"damage"					"500 625 750 875 1000"
			"stun_duration"				"0.5"
			"radius"					"450"
		}
	}
	//====================================
	// Lancelot parry
	//====================================
	"lancelot_parry"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/lancelot/lancelot_parry"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_CHANNELLED"
		"AbilityTextureName"			"custom/lancelot/lancelot_parry"
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"15 14 13 12 11"
		"AbilityManaCost"				"200"
		"AbilityChannelTime"			"1"
		"AbilityCastAnimation" 			"ACT_DOTA_OVERRIDE_ABILITY_4"


		"precache"
		{
			"particle"			"particles/lancelot/lancelot_slash_parry.vpcf"
			"particle"			"particles/lancelot/shield/lancelot_parry.vpcf"
		}

		"AbilityValues"
		{	
			"cast_point"				"0.0"
			"channel_duration"			"1"
			"shield_amount"				"400"
			"damage"					"300 375 450 525 600"
			"root_dur"					"0.8 1 1.2 1.4 1.6"
			"mana"						"200 250 300 350 400"
			"arondite_duration"			"1.5"
			"shield_damage_decrease_flat_value"						"300 375 450 525 600"
		}
	}

	//=================================================================================================================
	// Lancelot : Blessing of Fairy
	//=================================================================================================================
	"lancelot_blessing_of_fairy"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/lancelot/lancelot_blessing_of_fairy"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityTextureName"			"custom/lancelot_bless_of_fairy"
		"AbilityCooldown"				"70"
		"MaxLevel"						"1"
		
		"AbilityValues"
        {
            "damage_threshold" "500"
            "duration" "3.5"
            "magres" "80"
            "heal" "500"
        }
		
	}

	//=================================================================================================================
	// Lancelot : Caliburn
	//=================================================================================================================

	//=================================================================================================================
	// Lancelot : Vortigern
	//=================================================================================================================
	"lancelot_vortigern"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/lancelot/lancelot_vortigern"
		"MaxLevel"						"5"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/saber_alter_vortigern"
		"AbilityCastAnimation" 			"ACT_DOTA_OVERRIDE_ABILITY_1"
		"AnimationPlaybackRate" 		"1"
		
		"precache"
		{
			"particle"	"particles/units/heroes/hero_magnataur/magnataur_shockwave.vpcf"
			"particle"	"particles/custom/saber_alter/saber_alter_vortigern_line.vpcf"
		}
		
		"AbilityCastPoint"				"0.1"
		"AbilityCooldown"				"27"
		"AbilityManaCost"				"250"
		"AbilityCastRange"				"600"
		
		"AbilityValues"
        {
            "radius" "600"
            "damage" "300 375 450 525 600"
            "low_end" "80"
            "high_end" "120"
            "stun_duration" "0.3"
        }
		

		
	}


	//=================================================================================================================
	// Lancer : Gae Bolg - The Spear of Impaling Barbed Death
	//=================================================================================================================
	"lancelot_gae_bolg"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/lancelot/lancelot_gae_bolg"
		"MaxLevel"						"5"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_CREEP"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/lancelot_gae_bolg"
		//"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_4"
		"AbilityCastAnimation"			"ACT_DOTA_OVERRIDE_ABILITY_2"
		"AnimationPlaybackRate" 		"2.5"
		
		"precache"
		{
			"particle"		"particles/units/heroes/hero_chaos_knight/chaos_knight_reality_rift.vpcf"
			"particle"		"particles/custom/screen_red_splash.vpcf"
			"particle"		"particles/custom/lancer/lancer_culling_blade_kill.vpcf"
			"particle"		"particles/custom/lancer/lancer_heart_break_txt.vpcf"
			"particle"		"particles/custom/lancer/lancer_heart_break.vpcf"
			"particle"		"particles/items_fx/dagon.vpcf"
			"particle"		"particles/generic_gameplay/screen_blood_splatter.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_lion.vsndevts"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"156"
		"AbilityCastRangeBuffer"		"150"
		"AbilityCastPoint"				"0.9"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"40.0"

		// Damage.
		//-------------------------------------------------------------------------------------------------------------
		"AbilityDamage"					"208 260 312 364 416"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"250"
		
		"AbilityValues"
        {
            "damage" "208 260 312 364 416"
            "heartbreak_threshold" "160 200 240 280 320"
        }
		
	}


	//===================================================
	// Lancelot : Nine Lives
	//===================================================
	"lancelot_nine_lives"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/lancelot/lancelot_nine_lives"
		"MaxLevel"						"5"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/lancelot_nine_lives"
		"AbilityCastAnimation" 			"ACT_DOTA_ITEM_PICKUP"
		"AOERadius"						"%radius"
		
		"precache"
		{
			"particle"	"particles/custom/berserker/nine_lives/hit.vpcf"
			"particle"	"particles/custom/berserker/nine_lives/last_hit.vpcf"
			"particle"		"particles/econ/items/earthshaker/egteam_set/hero_earthshaker_egset/earthshaker_echoslam_start_magma_low_egset.vpcf"
			"particle"		"particles/units/heroes/hero_earthshaker/earthshaker_echoslam_start_f_fallback_low.vpcf"
			"particle"	"particles/econ/items/earthshaker/egteam_set/hero_earthshaker_egset/earthshaker_echoslam_start_magma_cracks_egset.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_earth_spirit.vsndevts"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_ogre_magi.vsndevts"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"700"
		"AbilityCastPoint"				"0.1"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"50.0"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"250"
		
		"AbilityValues"
        {
            "radius" "350"
            "radius_lasthit" "500"
            "damage" "30 35 40 45 50"
            "damage_lasthit" "300 350 400 450 500"
            "stun_duration" "1.0"
            "range" "700"
        }
		
	}

	//=====================================
	// Lancelot : Rule Breaker
	//=====================================

	//=====================================
	// Lancelot : Tsubame Gaeshi
	//=====================================
	"lancelot_tsubame_gaeshi"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/lancelot/lancelot_tsubame_gaeshi"
		"MaxLevel"						"5"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PURE"
		"AbilityTextureName"			"custom/lancelot_tsubame_gaeshi"
		"AbilityUnitTargetFlags"		"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityCastAnimation" 			"ACT_DOTA_OVERRIDE_ABILITY_4"
		"AnimationPlaybackRate" 		"1.5"
		
		"AbilityCastPoint"				"0.6"
		"AbilityCastRange"				"200"
		"AbilityCastRangeBuffer"		"100"
		"AbilityCooldown"				"50"
		"AbilityManaCost"				"250"
		
		"precache"
		{
			"particle"		"particles/units/heroes/hero_axe/axe_counterhelix_unused.vpcf"
			"particle"		"particles/custom/false_assassin/fa_tsubame_gaeshi_first_slash.vpcf"
			"particle"		"particles/custom/false_assassin/fa_tsubame_gaeshi_second_slash.vpcf"
			"particle"		"particles/custom/false_assassin/fa_tsubame_gaeshi_third_slash.vpcf"
			"particle"		"particles/custom/false_assassin/tsubame_gaeshi/tsubame_gaeshi_windup_indicator.vpcf"
		}

		"AbilityValues"
        {
            "damage" "150 175 200 225 250"
            "lasthit_damage" "300 350 400 450 500"
            //"stun_duration" "1.5"
            "global_cooldown" "45 43 41 39 37"
            "cast_point"			"0.6"
        }



	}


	//=======================================
	// Lancelot Attribute : Improve Eternal Arms Mastership
	//=======================================
	"lancelot_attribute_improve_eternal"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/lancelot/lancelot_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/lancelot_attribute_improve_eternal"		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"10"

		"precache"
		{
			"particle"		"particles/units/heroes/hero_abaddon/abaddon_death_coil_explosion.vpcf"
		}

		"AbilityValues"
        {
            "active_duration" "5"
            "crit_chance" "20"
            "crit_damage" "200"
        }
	}

	//=======================================
	// Lancelot Attribute : Blessing of Fairy
	//=======================================
	"lancelot_attribute_blessing_of_fairy"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/lancelot/lancelot_attribute_blessing_of_fairy"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/lancelot_bless_of_fairy"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"11"

		"precache"
		{
		}

		"AbilityValues"
        {
            "health_threshold" "500"
            "magic_immune_duration" "3.5"
            "healing" "500"
            "magres" "80"
        }
		
	}

	//=======================================
	// Lancelot Attribute : Knight of Honor
	//=======================================

	//=======================================
	// Lancelot Attribute : Eternal Flame
	//=======================================
	"lancelot_attribute_eternal_flame"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/lancelot/lancelot_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/lancelot_attribute_eternal_flame"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"8"

		"precache"
		{
		}

		"AbilityValues"
        {
            "armor_shred" "1"
            "duration" "5"
            "root_dur" "0.4"
        }
	}

	//=======================================
	// Lancelot Attribute : Improve owner
	//=======================================
	"lancelot_attribute_knight_of_owner"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/lancelot/lancelot_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/lancelot/lancelot_5sa"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"12"

		"precache"
		{
		}

		"AbilityValues"
        {
            "armor_shred" "1"
            "duration" "5"
            "root_dur" "0.4"
        }
	}


	//=======================================
	// Lancelot Attribute : Knight of the Lake
	//=======================================
	"lancelot_attribute_kotl"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/lancelot/lancelot_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/lancelot_knight_of_the_lake"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"12"

		"precache"
		{
		}

		"AbilityValues"
        {
            "magic_immune_dur" "1.25"
            "mana_cost" "30"
        }
	}

	//=======================================
	// Lancelot Attribute : Total Assault
	//=======================================

	//====================================
	// Lancelot : Nuke
	//====================================

	// [restored] возвращён после ошибочной чистки
	// [restored] возвращён после ошибочной чистки
}