"DOTAAbilities"
{
	//========================================
	// False Assassin : Windblade
	//========================================
	
	//========================================
	// False Assassin : Heart of Harmony
	//========================================
	
	//========================================
	// False Assassin : Illusory Wanderer
	//========================================


	//========================================
	// False Assassin : Illusion Passive
	//========================================

	// [restored] возвращён после ошибочной чистки
	// [restored] возвращён после ошибочной чистки
	// [restored] возвращён после ошибочной чистки
	"false_assassin_illusion_passive"
	{
		"BaseClass"						"ability_datadriven"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityTextureName"			"custom/false_assassin_illusion"
		"precache"
		{
			"particle"					"sounds/weapons/hero/juggernaut/attack03.vsnd"
		}

		"Modifiers"
		{
			"modifier_fa_death_checker"
			{
				"OnDeath"
				{
					"RunScript"
					{
						"ScriptFile"		"fa_ability"
						"Function"			"OnFADeath"
					}
				}
			}
			"modifier_psuedo_omnislash"
			{
				"Passive"					"1"
				"AllowIllusionDuplicate"	"1"
				"OnAttackLanded"
				{
					"RunScript"
					{
						"ScriptFile"		"fa_ability"
						"Function"			"TPOnAttack"
					}
				}
				
				"OnDestroy"
				{
					"RunScript"
					{
						"ScriptFile"		"fa_ability"
						"Function"			"OnIWDestroy"
					}
				}
			}
		}
	}
}