"DOTAAbilities"
{
	//========================================
	// False Assassin : Gate Keeper
	//========================================
	"sasaki_gatekeeper"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/sasaki/sasaki_gatekeeper"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityTextureName"			"custom/false_assassin_gate_keeper"
		"AbilityCastAnimation" 			"ACT_DOTA_ITEM_PICKUP"
		"AnimationPlaybackRate" 		"1.0"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"

		"precache"
		{
			"particle"					"particles/units/heroes/hero_razor/razor_ambient_g.vpcf"
			"particle"					"particles/units/heroes/hero_brewmaster/brewmaster_primal_split_storm_image.vpcf"
			"particle"					"particles/units/heroes/hero_zuus/zuus_thundergods_wrath_start_f.vpcf"
			"particle"					"particles/zlodemon/zlodemon_overhead_eye.vpcf"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_templar_assassin.vsndevts"
		}
		

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"15 14 13 12 11"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"0"
		
		"AbilityValues"
		{
			"leash_range"			"1500"
			"bonus_damage"			"30 37.5 45 52.2 60"
			"bonus_armor"			"2 2.5 3 3.5 4"
			"bonus_mr"				"6 7 8 9 10"
			"bonus_regen"			"20 25 30 35 40"
			"duration"				"8"
		}
	}
}