
#base "sasaki_gatekeeper.kv"
#base "sasaki_heart_of_harmony.kv"
#base "sasaki_tsubame.kv"
#base "sasaki_quickdraw.kv"
#base "sasaki_windblade.kv"

"DOTAAbilities"
{
	//=================================================================================================================
	// False Assassin : Mind's Eye
	//=================================================================================================================
	"false_assassin_minds_eye"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/sasaki/false_assassin_minds_eye"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityTextureName"			"custom/false_assassin_minds_eye"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PURE"
		"MaxLevel"						"2"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"precache"
		{
			"particle"		"particles/units/heroes/hero_juggernaut/jugg_crit_blur_impact.vpcf"
		}
		
		"AbilityValues"
        {
            "agi_ratio" "0.35 0.7"
            "agi_ratio_revoked" "0.6 1.2"
        }
		
		
	}

	//========================================
	// False Assassin : Gate Keeper
	//========================================
	"false_assassin_gate_keeper"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/sasaki/false_assassin_gate_keeper"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityTextureName"			"custom/false_assassin_gate_keeper"
		"AbilityCastAnimation" 			"ACT_DOTA_ITEM_PICKUP"
		"AnimationPlaybackRate" 		"1.0"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"

		"precache"
		{
			"particle"					"particles/units/heroes/hero_razor/razor_ambient_g.vpcf"
			"particle"					"particles/units/heroes/hero_brewmaster/brewmaster_primal_split_storm_image.vpcf"
			"particle"					"particles/units/heroes/hero_zuus/zuus_thundergods_wrath_start_f.vpcf"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_templar_assassin.vsndevts"

		}
		

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"17"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"0"
		
		"AbilityValues"
        {
            "bonus_hp_regen" "50 60 70 80 90"
            "bonus_armor" "3 6 9 12 15"
            "movespeed_decrease" "-20 -15 -10 -5 0"
            "bonus_sight" "300"
            "duration" "5.0"
            "mana_regen" "20"
        }
		
		
		
		
	}

	//=====================================
	// False Assassin : Quickdraw
	//=====================================
	"false_assassin_quickdraw"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/false_assassin_quickdraw"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1.0"

		"precache"
		{
			"particle"					"particles/custom/false_assassin/fa_quickdraw.vpcf"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_phantom_lancer.vsndevts"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"750"
		"AbilityCastPoint"				"0.1"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"45"

		"AbilityValues"
        {
            "base_damage" "500"
            "agi_ratio" "13"
        }
		
		"OnSpellStart"
		{
			"RunScript"
			{
			 	"ScriptFile"		"fa_ability"
			 	"Function"			"OnQuickdrawStart"
			}
			"ApplyModifier"
			{
				"ModifierName"		"modifier_qd_anim"
				"Target"			"CASTER"
			}
		}

		"OnProjectileHitUnit"
		{
			"DeleteOnHit"		"false"
			"RunScript"
			{
			 	"ScriptFile"	"fa_ability"
			 	"Function"		"OnQuickdrawHit"
			}
		}

		"Modifiers"
		{
			"modifier_quickdraw_cooldown"
			{
				"IsDebuff"			"1"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_quickdraw_baseattack_reduction"
			{
				"Duration"	"0.5"
				"Properties"
				{
					"MODIFIER_PROPERTY_BASEDAMAGEOUTGOING_PERCENTAGE"	"-100"
				}
			}
			"modifier_qd_anim"
			{
				"Duration"	"0.5"
				"IsHidden"	"1"
				"OverrideAnimation"     "ACT_DOTA_CAST_ABILITY_1"
		
				"Properties"
				{
					"MODIFIER_PROPERTY_OVERRIDE_ANIMATION_RATE"		"1"
				}
			}
		}
	}
	
	//========================================
	// False Assassin : Windblade
	//========================================
	
	//========================================
	// False Assassin : Heart of Harmony
	//========================================
	"false_assassin_heart_of_harmony"
	{
		"BaseClass"						"ability_datadriven"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityTextureName"			"custom/false_assassin_heart_of_harmony"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PHYSICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_ITEM_PICKUP"
		"AnimationPlaybackRate" 		"1.0"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"

		"precache"
		{
			"particle"					"particles/econ/items/abaddon/abaddon_alliance/abaddon_aphotic_shield_alliance.vpcf"
			"particle"					"particles\units\heroes\hero_pugna\pugna_decrepify.vpcf"	
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_abaddon.vsndevts"
		}

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastPoint"				"0.1"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"18"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"0"
		
		"AbilityValues"
        {
            "duration" "3.0"
            "threshold" "85 65 55 45 35"
            "bonus_mr" "-30 -40 -50 -60 -70"
            "attack_count" "4 4 5 5 6"
            "stun_duration" "1.1 1.2 1.3 1.4 1.5"
            "gcd" "15"
        }
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"		"fa_ability"
				"Function"			"OnHeartStart"
				"GCD"				"%gcd"
			}
		}
		
		"OnUpgrade"
		{
			"RunScript"
			{
				"ScriptFile"		"fa_ability"
				"Function"			"OnHeartLevelUp"
				"ArmorPen"			"%armor_pen"
			}
		}		
		
		"Modifiers"
		{
			"modifier_heart_of_harmony"
			{
				"Duration"		"%duration"
				
				"EffectName"		"particles/units/heroes/hero_razor/razor_ambient_g.vpcf"
				"EffectAttachType"	"follow_origin"
				"OnCreated"
				{
					"RunScript"
					{
						"ScriptFile"		"fa_ability"
						"Function"			"GKParticleStart"
					}
				}
				
				"OnDestroy"
				{
					"RunScript"
					{
						"ScriptFile"		"fa_ability"
						"Function"			"GKParticleDestroy"
					}
				}				
				"OnTakeDamage"
				{
					"RunScript"
					{
						"ScriptFile"		"fa_ability"
						"Function"			"OnHeartDamageTaken"
						"DamageTaken"		"%attack_damage"
						"Threshold"			"%threshold"
						"StunDuration"		"%stun_duration"
						"AttackCount"		"%attack_count"
					}
				}				
				"Properties"
				{
					"MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE"	"%bonus_mr"
				}
			}

			"modifier_heart_of_harmony_resistance_linger"
			{
				"Duration"		"0.5"	
				"IsHidden"		"1"		
				"Properties"
				{
					"MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE"	"%bonus_mr"
				}
			}

			"modifier_heart_of_harmony_movespeed_bonus"
			{
				"EffectName"			"particles/units/heroes/hero_dark_seer/dark_seer_surge.vpcf"
				"EffectAttachType"		"follow_origin"	
				"Duration"				"3.0"
				"Properties"
				{
					"MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE"	"300"
				}

			}
			"modifier_heart_of_harmony_invisible"
			{
				"EffectName"				"particles\units\heroes\hero_pugna\pugna_decrepify.vpcf"	
				"EffectAttachType"			"follow_overhead"
				"Duration"					"%duration"
				"IsHidden"					"1"
				"States"
			    {
				    "MODIFIER_STATE_INVISIBLE" "MODIFIER_STATE_VALUE_ENABLED"
				    "MODIFIER_STATE_NO_UNIT_COLLISION" "MODIFIER_STATE_VALUE_ENABLED"
			    }
				"OnAbilityExecuted"
				{
					"RunScript"
					{
						"ScriptFile"		"fa_ability"
						"Function"			"OnInvisibilityBroken"
					}								
				}
				"OnAttackStart"
				{
					"RunScript"
					{
						"ScriptFile"		"fa_ability"
						"Function"			"OnInvisibilityBroken"
					}
				}
			}
		}
	}

	//=====================================
	// False Assassin : Presence Concealment
	//=====================================
	"false_assassin_presence_concealment"
	{
		"BaseClass"          			    "ability_lua"
		"ScriptFile"						"abilities/sasaki/false_assassin_presence_concealment"
		"AbilityTextureName"           		"custom/false_assassin_attribute_vitrification"
		"AbilityBehavior"					"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityCastPoint"					"0.2"
		"AbilityCastAnimation" 				"ACT_DOTA_IDLE"
		"AnimationPlaybackRate" 			"1.0"

		"MaxLevel"			"1"
		"AbilityCooldown"	"7"
		"precache"
		{
			"particle"		"particles\units\heroes\hero_pugna\pugna_decrepify.vpcf"
			
		}
		"AbilityValues"
        {
            "duration" "3"
        }
	}
	

	//========================================
	// False Assassin : Tsubame Mai
	//========================================
	"false_assassin_tsubame_mai"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/sasaki/false_assassin_tsubame_mai"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityTextureName"			"custom/false_assassin_tsubame_mai"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PURE"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1.0"
		"MaxLevel"						"1"
		"precache"
		{
			"particle"					"particles/custom/false_assassin/fa_illusory_wanderer_sword_glow.vpcf"
			"particle"					"particles/custom/archer/archer_overedge_slash.vpcf"
			"particle"					"particles/units/heroes/hero_razor/razor_ambient_g.vpcf"
			"particle"					"particles/units/heroes/hero_zuus/zuus_thundergods_wrath_start_f.vpcf"
			"particle"					"particles/units/heroes/hero_brewmaster/brewmaster_primal_split_storm_image.vpcf"
			"particle"		"particles/units/heroes/hero_juggernaut/juggernaut_omni_dash.vpcf"
			"particle"		"particles/units/heroes/hero_juggernaut/juggernaut_omni_slash_tgt.vpcf"
			"particle"		"particles/units/heroes/hero_juggernaut/juggernaut_omni_slash_trail.vpcf"
		}

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastPoint"				"0.0"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"82"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"0"
		
		"AbilityValues"
        {
            "duration" "3.1"
            "threshold" "200"
            "slash_amount" "3"
            "slash_damage_percentage" "50"
        }
	}
	

	//=====================================
	// False Assassin : Tsubame Gaeshi
	//=====================================

	//=======================================
	// FA Attribute : Ganryu
	//=======================================
	"false_assassin_attribute_ganryu"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/sasaki/false_assassin_attribute_ganryu"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/false_assassin_attribute_ganryu"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"17"

		"precache"
		{
		}

		"AbilityValues"
        {
            "slash_reduc" "0.2"
            "minor_slash_dmg" "35"
            "final_slash_dmg" "70"
            "armor_reduc" "33"
        }
		
	}
	//=======================================
	// FA Attribute : Eye of Serenity
	//=======================================
	"false_assassin_attribute_eye_of_serenity"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/sasaki/false_assassin_attribute_eye_of_serenity"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/false_assassin_attribute_eye_of_serenity"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"8"

		"precache"
		{
		}

		"AbilityValues"
        {
            "vision_duration" "3.0"
            "vision_cd" "10.0"
        }
		
	}

	//=======================================
	// FA Attribute : Quickdraw
	//=======================================
	"false_assassin_attribute_quickdraw"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/sasaki/false_assassin_attribute_quickdraw"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/false_assassin_attribute_quickdraw"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PHYSICAL"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"12"

		"precache"
		{
		}

		"AbilityValues"
        {
            "base_damage" "500"
            "atk_ratio" "100"
            "focus_attacks" "2"
            "focus_cdr" "50"
            "exhausted_duration" "8"
        }
		
	}

	//=======================================
	// FA Attribute : Vitrification
	//=======================================
	"false_assassin_attribute_vitrification"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/sasaki/false_assassin_attribute_vitrification"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/false_assassin_attribute_vitrification"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"7"

		"precache"
		{
		}

		"AbilityValues"
        {
        }
		
	}
	//=======================================
	// FA Attribute : Improve Mind's Eye
	//=======================================
	"false_assassin_attribute_improve_minds_eye"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/sasaki/false_assassin_attribute_improve_minds_eye"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/false_assassin_attribute_improve_minds_eye"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"6"

		"precache"
		{
		}

		"AbilityValues"
        {
            "agi_ratio" "0.7"
            "agi_ratio_revoked" "1.2"
            "attack_mana" "10"
        }
		
	}	
}