"DOTAAbilities"
{
	//=======================================
	// Berserker - Roar
	//=======================================
	"atalanta_roar"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_roar"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL" 
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_roar"

		"AbilityCastRange"				"600 650 700 750 800"
		
		"AbilityCastPoint"				"0.3"
		"AbilityCooldown"				"15 14 13 12 11"
		"AbilityManaCost"				"100"

		"AbilityValues"
        {
            "duration" "2 2.5 3 3.5 4"
            "ms_slow" "30 35 40 45 50"
            "distance" "600 650 700 750 800"
            "width" "200"
            "base_stacks" "8 10 12 14 16"
            "base_damage" "200 250 300 350 400"
            "echo_damage" "50"
            "as_slow" "50 70 90 110 130"
            "cast_range" "450"
            "duration_locked" "1 1.25 1.5 1.75 2"
        }
	}

	//=======================================
	// Berserker - Attack of the Beast
	//=======================================

	"atalanta_ora"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_ora"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_5"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_ora"
		"AbilityCastPoint"				"0"

		"AbilityCooldown"				"22 21 20 19 18"

		"AbilityManaCost"				"200"
		
		"AbilityValues"
        {
            "radius" "200"
            "width" "50"
            "total_damage" "-50"
            "duration" "6"
            "reduce_damage" "-50"
            "attack_rate" "1.0"
            "base_damage" "40 50 60 70 80"
            "base_attack_count" "0"
            "as_bonus" "100 125 150 175 200"
            "attack_range_bonus" "50"
        }
	}

	//=======================================
	// Berserker - Cursed Furiocity
	//=======================================

	"atalanta_pull"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_pull"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_5"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_ora"
		"AbilityCastPoint"				"0.1"

		"AbilityCooldown"				"22 21 20 19 18"

		"AbilityManaCost"				"200"
		
		"AbilityValues"
        {
            "radius" "600 650 700 750 800"
            "slow_dur" "2.5"
            "damage" "200 250 300 350 400"
            "curse_stacks" "2 4 6 8 10"
            "ms_slow" "30 35 40 45 50"
            "as_slow" "1.2 1.3 1.4 1.5 1.6"
        }
	}

	//=======================================
	// Berserker - Crossing Arcadia
	//=======================================

	"atalanta_jump"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_jump"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_jump"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"2.0"
		
		"AOERadius"						"%radius"
		"AbilityCastRange"				"1500"
		"AbilityCastPoint"				"0.2"
		"AbilityManaCost"				"400"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"26 24 22 20 18"

		"AbilityValues"
        {
            "speed" "1000"
            "fly_duration" "0.8"
            "max_height" "750"
            "damage" "400 500 600 700 800"
            "radius" "400"
            "curse_stacks" "20 25 30 35 40"
            "stun_duration" "0.7 1.0 1.4 1.7 2.0"
            "flame_duration" "1.5 2.0 2.5 3.0 3.5"
        }		
	}

	//=======================================
	// Berserker - Curse
	//=======================================

	"atalanta_curse"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_curse"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_curse"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"

		"AbilityCooldown"				"30"
		
		"AbilityValues"
        {
            "duration" "10"
            "amplify_per_stack" "0.3"
            "detonate_damage" "5"
        }
	}

	//=======================================
	// Berserker - Tauropolos Alter
	//=======================================

	"atalanta_tauropolos_alter"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_tauropolos_alter"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityType"					"DOTA_ABILITY_TYPE_ULTIMATE"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_tauropolos"
		"AnimationPlaybackRate" 		"1.0"
		
		"AbilityCastRange"				"500"
		"AbilityCastPoint"				"1.0"
		"AbilityManaCost"				"800"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"38 36 34 32 30"

		"AbilityValues"
        {
            "damage" "90 110 130 150 170"
            "duration" "7"
            "min_dist" "10"
            "max_dist" "700"
            "explosion_radius" "250"
            "curse_stacks" "10"
            "armor_bonus" "8 10 12 14 16"
            "mr_bonus" "8 10 12 14 16"
        }		
	}

	"atalanta_tauropolos_alter_stop"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_tauropolos_alter"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityType"					"DOTA_ABILITY_TYPE_ULTIMATE"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_tauropolos"
		"AnimationPlaybackRate" 		"1.0"
		
		"AbilityCastPoint"				"0"
		"AbilityManaCost"				"0"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"0"

		"AbilityValues"
        {
        }		
	}

	//=======================================
	// Combo - Tauropolos Skia Thermokrasia
	//=======================================

	"atalanta_skia"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_skia"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_HIDDEN | DOTA_ABILITY_BEHAVIOR_CHANNELLED | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation"			"ACT_DOTA_CAST_ABILITY_6"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_skia"
		"AbilityCastPoint"				"0.1"
		"AbilityChannelTime"			"0.01"

		"AbilityCooldown"				"180"
		"AbilityCastRange"				"6000"	
		"AbilityManaCost"				"800"
		
		"AbilityValues"
        {
            "damage" "2000"
            "curse_stacks" "50"
            "radius" "900"
            "fly_duration" "3.25"
        }
	}

	"atalanta_evolution_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_attr1"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"14"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
            "radius" "300"
        }		
	}
	"atalanta_tornado_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_attr2"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"12"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
            "arcadia_pull" "300"
            "skia_pull" "500"
            "pull_pull" "300"
        }		
	}
	"atalanta_vision_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_vision"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"13"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
            "stack_damage" "2.5"
        }		
	}
	"atalanta_moon_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_moon"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"17"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
            "roar_damage" "50"
            "tauropolos_curse" "5"
            "percent" "0.1"
            "explosion" "5"
        }		
	}
}