#base "astolfo_trap_of_argalia.kv"
#base "astolfo_monstrous_strength_passive.kv"

"DOTAAbilities"
{
	"astolfo_deafening_blast_attribute"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/astolfo/astolfo_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/astolfo/deafening_blast"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"13"

		"precache"
		{
		}

		"AbilityValues"
        {
            "area_of_effect" "500"
            "damage" "350"
            "regen" "500"
        }
	}


	//=======================================
	// Astolfo Passive: Casa Di Logistilla
	//=======================================
	"astolfo_casa_di_logistilla"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/astolfo/astolfo_casa_di_logistilla"
		"AbilityTextureName"			"custom/astolfo_casa_di_logistilla"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"MaxLevel"						"1"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityCooldown"				"60"
		"AbilityManaCost"				"0"

		"precache"
		{	
			"particle"		"particles/units/heroes/hero_dazzle/dazzle_weave_circle_ray.vpcf"
			"particle"		"particles/zlodemon/astolfo_jopa_shield.vpcf"
		}

		"AbilityValues"
        {
            "passive_mr" "10"
            "active_mr" "75"
            "active_duration" "3.5"
        }

	}

	//=======================================
	// Astolfo: Hipogriff: Vanish
	//=======================================
	"astolfo_hippogriff_vanish"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/astolfo/astolfo_hippogriff_vanish"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"25"
		"AbilityTextureName"			"custom/astolfo_hippogriff_vanish"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_AUTOCAST"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO"

		"AbilityCooldown"				"25"
		"AbilityManaCost"				"100"
		"AbilityCastRange"				"800"
		"AbilityCastRangeBuffer"		"100"
		"AbilityCastPoint"				"0.3"

		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1.6"

		"precache"
		{
			"particle"		"particles/custom/astolfo/astolfo_hippogriff_vanish.vpcf"
			"particle"		"particles/units/heroes/hero_shadow_demon/shadow_demon_disruption.vpcf"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_mirana.vsndevts"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_oracle.vsndevts"
		}
		"AbilityValues"
        {
            "cast_delay" "0.3"
            "damage" "400"
            "banish_duration" "0.75"
        }



	}

	//=======================================
	// Astolfo: Down with a Touch!
	//=======================================
	"astolfo_down_with_a_touch"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/astolfo/astolfo_down_with_a_touch"
		"MaxLevel"						"5"
		"AbilityTextureName"			"custom/astolfo/astolfo_down"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"

		"AbilityCooldown"				"15 14 13 12 11"
		"AbilityManaCost"				"100"
		"AbilityCastRange"				"500"
		"AbilityCastPoint"				"0.25"

		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"4.0"


		"precache"
		{
			"particle"		"particles/custom/astolfo/astolfo_down_with_a_touch_projectile.vpcf"	
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_sniper.vsndevts"
		}

		"AbilityValues"
        {
            "range" "500"
            "attack_amount" "4"
            "damage" "70 90 110 130 150"
            "slow" "-30 -40 -50 -60 -70"
            "slow_duration" "3"
            "lock_duration" "0.6 0.7 0.8 0.9 1"
            "slow_tier2" "-15 -20 -25 -30 -35"
            "slow_tier3" "-7.5 -10 -12.5 -15 -17.5"
        }



	}

	//=======================================
	// Astolfo: La black Luna
	//=======================================
	"astolfo_la_black_luna"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/astolfo/astolfo_la_black_luna"
		"MaxLevel"						"5"
		"AbilityTextureName"			"custom/astolfo_la_black_luna"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_CHANNELLED | DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_ROT"
		"AnimationPlaybackRate" 		"1.0"
		
		"AbilityCastPoint"				"0.5"
		"AbilityChannelTime"			"2.1"		
		"AbilityCastRange"				"1000"
		"AbilityCooldown"				"40"
		"AbilityManaCost"				"400"


		"precache"
		{
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_silencer.vsndevts"
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_legion_commander.vsndevts"
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_venomancer.vsndevts"
			"particle"			"particles/custom/astolfo/la_black_luna/la_black_luna_shockwave.vpcf"
		}

		"AbilityValues"
        {
            "radius" "1000"
            "slow_amount" "-40 -45 -50 -55 -60"
            "damage_radius" "700"
            "damage" "160 200 240 280 320"
            "silence_radius" "700"
            "slow_amount1" "-99"
            "slow_amount2" "-99"
        }


	}

	//=======================================
	// Astolfo: Hipogriff: Raid
	//=======================================
	"astolfo_hippogriff_raid"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/astolfo/astolfo_hippogriff_raid"
		"MaxLevel"						"5"
		"AbilityTextureName"			"custom/astolfo_hippogriff_raid"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AOERadius"						"%radius"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityType"					"ABILITY_TYPE_ULTIMATE"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"

		"AbilityCooldown"				"28"
		"AbilityManaCost"				"800"
		"AbilityCastRange"				"2000"
		"AbilityCastPoint"				"0.5"

		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"0.75"

		"precache"
		{
			"particle"			"particles/custom/astolfo/raid_hippogriff.vpcf"
			"particle"			"particles/custom/astolfo/astolfo_hippogriff_raid_flyer.vpcf"
			"particle"			"particles/custom/astolfo/astolfo_ground_mark_flex.vpcf"
			"particle"			"particles/custom/astolfo/hippogriff_raid/astolfo_hippogriff_raid_first_impact.vpcf"
			"particle"			"particles/custom/astolfo/hippogriff_raid/astolfo_hippogriff_raid_second_impact.vpcf"
			"particle"			"particles/custom/astolfo/hippogriff_raid/astolfo_hippogriff_raid_ascend.vpcf"
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_phoenix.vsndevts"
		}
		"AbilityValues"
        {
            "max_range" "2000"
            "cast_delay" "0.5"
            "reveal_delay" "2.0"
            "total_delay" "4.0"
            "radius" "600"
            "first_impact_damage" "500 550 600 650 700"
            "first_impact_stun_duration" "2"
            "second_impact_damage" "400 500 600 700 800"
            "attribute_bonus_range" "500"
        }
	}

	//=======================================
	// Astolfo: Hipogriff: Ride
	//=======================================
	"astolfo_hippogriff_ride"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/astolfo/astolfo_hippogriff_ride"
		"AbilityTextureName"			"custom/astolfo_hippogriff_ride"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		// "AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		// "AnimationPlaybackRate" 		"0.5"
		"MaxLevel"						"1"
		"RequiredLevel"					"24"
		"LevelsBetweenUpgrades"			"1"


		"AbilityCooldown"				"180"
		"AbilityManaCost"				"600"
		"AbilityCastRange"				"2700"

		"LinkedAbilities"				"astolfo_hippogriff_rush"

		"precache"
		{
			"particle"				"particles/custom/astolfo/astolfo_ground_mark_smile.vpcf"
			"particle"				"particles/custom/astolfo/hippogriff_ride/astolfo_hippogriff_ride_thunder.vpcf"
			"particle"				"particles/custom/astolfo/hippogriff_ride/astolfo_hippogriff_ride_aoe_indicator.vpcf"
			"particle"				"particles/custom/astolfo/hippogriff_ride/astolfo_hippogriff_rush_portal.vpcf"
			"particle"				"particles/custom/astolfo/astolfo_ground_mark_flex_10sec.vpcf"
			"particle"				"particles/econ/items/kunkka/divine_anchor/hero_kunkka_dafx_skills/kunkka_spell_torrent_bubbles_swirl_fxset.vpcf"
		}
		"AbilityValues"
        {
            "ascend_delay" "2.0"
            "duration" "8.0"
            "max_range" "2700"
            "linear_range" "1000"
            "damage" "600"
        }



	}

	//=======================================
	// Astolfo: Hipogriff: Rush
	//=======================================
	"astolfo_hippogriff_rush"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"                    "astolfo/astolfo_hippogriff_ride.lua"
		"AbilityTextureName"			"custom/astolfo_hippogriff_ride"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_HIDDEN | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING | DOTA_ABILITY_BEHAVIOR_UNRESTRICTED | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"MaxLevel"						"1"
		"RequiredLevel"					"24"
		"LevelsBetweenUpgrades"			"1"


		"AbilityCooldown"				"0.75"
		"AbilityManaCost"				"0"
		"AbilityCastRange"				"2700"
		//"VectorTarget"                  "1"

		"precache"
		{
		}
		"AbilityValues"
        {
            "ascend_delay" "2.0"
            "duration" "8.0"
            "max_range" "2700"
            "linear_range" "1000"
            "damage" "600"
            "cooldown" "0.75"
        }

		"OnSpellStart"
		{
		}

	}



	//=================================================================================================================
	// Astolfo : Down with a Touch Passive
	//=================================================================================================================



	//=================================================================================================================
	// Astolfo : Monstrous Strength Passive
	//=================================================================================================================
	"astolfo_monstrous_strength"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/astolfo/astolfo_monstrous_strength"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityTextureName"			""
		"MaxLevel"						"1"
		
		"AbilityValues"
        {
        }
		
	}

	//=================================================================================================================
	// Astolfo : Independent Action Passive
	//=================================================================================================================
	"astolfo_independent_action"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/astolfo/astolfo_independent_action"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityTextureName"			""
		"MaxLevel"						"1"
		
		
	}

	//=======================================
	// Astolfo Attribute: Riding
	//=======================================
	"astolfo_attribute_riding"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/astolfo/astolfo_attribute_riding"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/astolfo_attribute_riding"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"14"

		"precache"
		{
		}

		"AbilityValues"
        {
            "vanish_stun_duration" "0.5"
            "raid_first_impact_damage" "10"
            "raid_second_impact_radius" "100"
        }
		
	}


	//=======================================
	// Astolfo Attribute: Monstrous Strength
	//=======================================
	"astolfo_attribute_monstrous_strength"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/astolfo/astolfo_attribute_monstrous_strength"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/astolfo_attribute_monstrous_strength"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"10"

		"precache"
		{
		}

		"AbilityValues"
        {
            "base_damage" "35"
            "damage_pct" "8"
        }
		
	}

	//=======================================
	// Astolfo Attribute: Independent Action
	//=======================================
	"astolfo_attribute_independent_action"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/astolfo/astolfo_attribute_independent_action"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/astolfo_attribute_independent_action"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"13"

		"precache"
		{
		}

		"AbilityValues"
        {
            "health_regen" "0.5"
            "mana_regen" "0.8"
            "health_regen_boosted" "1.5"
            "mana_regen_boosted" "3"
        }
		
	}

	//=======================================
	// Astolfo Attribute: Sanity
	//=======================================
	"astolfo_attribute_sanity"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/astolfo/astolfo_attribute_sanity"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/astolfo_attribute_sanity"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"12"

		"precache"
		{
		}

		"AbilityValues"
        {
            "bash_damage" "100"
            "bash_duration" "0.75"
            "critical_damage" "200"
            "evasion_duration" "1.0"
        }
		
	}
	//=======================================
	// Astolfo: Hipogriff: Tornado
	//=======================================

	// [restored] возвращён после ошибочной чистки
}