"""Generate heroes.py from the actual game files.

Each Fate hero is a .kv under scripts/npc/heroes/ that `override_hero`s a base
Dota hero. The name shown on the scoreboard is that base hero's localized string
in resource/addon_english.txt (e.g. npc_dota_hero_nevermore -> "Demon king
Nobunaga", npc_dota_hero_gyrocopter -> "Oda Nobunaga").

Run from the bot folder:
    python gen_heroes.py

It reads the addon (the parent folder of this bot) and rewrites heroes.py with
the exact, current roster. Re-run it whenever heroes are added/renamed.
"""

import os
import re
import sys

# Windows consoles default to a legacy codepage that can't print ō/é etc.
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

BOT_DIR = os.path.dirname(os.path.abspath(__file__))
ADDON_ROOT = os.path.dirname(BOT_DIR)
NPC_DIR = os.path.join(ADDON_ROOT, "scripts", "npc")
HEROES_DIR = os.path.join(NPC_DIR, "heroes")
HEROES_CUSTOM = os.path.join(NPC_DIR, "npc_heroes_custom.txt")
LOC_FILE = os.path.join(ADDON_ROOT, "resource", "addon_english.txt")
LOC_FILE_CN = os.path.join(ADDON_ROOT, "resource", "addon_schinese.txt")

UNIT_RE = re.compile(r'"(npc_dota_hero_[a-z0-9_]+)"')
OVERRIDE_RE = re.compile(r'override_hero"\s+"(npc_dota_hero_[a-z0-9_]+)"')
LOC_RE = re.compile(r'"(npc_dota_hero_[a-z0-9_]+)"\s+"([^"]+)"')


def read(path):
    # game files vary: english is utf-8(-sig), schinese is utf-16. Try both.
    for enc in ("utf-8-sig", "utf-16"):
        try:
            with open(path, "r", encoding=enc) as f:
                text = f.read()
            if "\x00" not in text:           # utf-16 read as utf-8 leaves NULs
                return text
        except (UnicodeError, UnicodeDecodeError):
            continue
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return f.read()


def active_kv_files():
    """The .kv files actually #base-included by npc_heroes_custom.txt."""
    text = read(HEROES_CUSTOM)
    files = re.findall(r'#base\s+"(heroes/npc_fate_hero_[a-z0-9_]+\.kv)"', text)
    return [os.path.join(NPC_DIR, f.replace("/", os.sep)) for f in files]


def load_localization(path):
    loc = {}
    for line in read(path).splitlines():
        m = LOC_RE.search(line)
        if m and m.group(1) not in loc:  # keep first (the hero name entry)
            loc[m.group(1)] = m.group(2).strip()
    return loc


def parse_kv(path):
    text = read(path)
    units = UNIT_RE.findall(text)
    unit = units[0] if units else None
    om = OVERRIDE_RE.search(text)
    override = om.group(1) if om else None
    return unit, override


def main():
    loc = load_localization(LOC_FILE)
    loc_cn = load_localization(LOC_FILE_CN) if os.path.exists(LOC_FILE_CN) else {}
    kv_files = active_kv_files()
    if not kv_files:
        # fall back to every kv in the folder
        kv_files = [os.path.join(HEROES_DIR, f) for f in os.listdir(HEROES_DIR)
                    if f.endswith(".kv")]

    rows = []      # (display_name, kv_basename, base_hero)
    cn_pairs = []  # (chinese_name, english_name)
    seen = set()
    missing = []
    for path in sorted(kv_files):
        if not os.path.exists(path):
            continue
        unit, override = parse_kv(path)
        base = override or unit
        name = loc.get(unit) or loc.get(override)
        kv = os.path.basename(path)
        if not name:
            missing.append(kv)
            continue
        if name not in seen:
            seen.add(name)
            rows.append((name, kv, base))
            cn = loc_cn.get(unit) or loc_cn.get(override)
            if cn:
                cn_pairs.append((cn, name))

    rows.sort(key=lambda r: r[0].lower())
    cn_pairs.sort(key=lambda r: r[1].lower())

    out = ['"""Known hero (Servant) display names — AUTO-GENERATED.',
           "",
           "Generated by gen_heroes.py from the game's scripts/npc/heroes/*.kv",
           "(override_hero) + resource/addon_english.txt (display names). These are",
           "the exact strings that appear on the end-of-round scoreboard.",
           "",
           "Re-run `python gen_heroes.py` after adding/renaming heroes. Edit ALIASES",
           "below (preserved-ish) for OCR spelling variants if you ever need them.",
           '"""',
           "",
           "HEROES = ["]
    for name, kv, base in rows:
        out.append(f'    {name!r},  # {kv} -> {base}')
    out.append("]")
    out.append("")
    out.append("# Map a variant spelling (lowercased) -> canonical name above.")
    out.append("ALIASES = {")
    out.append("}")
    out.append("")
    out.append("# Chinese (Fate) scoreboard names -> canonical English, from")
    out.append("# resource/addon_schinese.txt. Lets the bot read zh-localized boards.")
    out.append("CHINESE = {")
    for cn, name in cn_pairs:
        out.append(f"    {cn!r}: {name!r},")
    out.append("}")
    out.append("")

    target = os.path.join(BOT_DIR, "heroes.py")
    with open(target, "w", encoding="utf-8") as f:
        f.write("\n".join(out))

    print(f"Wrote {target} with {len(rows)} heroes ({len(cn_pairs)} with Chinese names).")
    if missing:
        print(f"\n{len(missing)} kv file(s) had no display name in localization "
              f"(skipped): {', '.join(missing)}")
    print("\nRoster:")
    for name, kv, base in rows:
        print(f"  {name:<24} ({kv})")


if __name__ == "__main__":
    main()
