"""Known hero (Servant) display names — AUTO-GENERATED.

Generated by gen_heroes.py from the game's scripts/npc/heroes/*.kv
(override_hero) + resource/addon_english.txt (display names). These are
the exact strings that appear on the end-of-round scoreboard.

Re-run `python gen_heroes.py` after adding/renaming heroes. Edit ALIASES
below (preserved-ish) for OCR spelling variants if you ever need them.
"""

HEROES = [
    'Altera',  # npc_fate_hero_altera.kv -> npc_dota_hero_faceless_void
    'Angra Mainyu',  # npc_fate_hero_avenger.kv -> npc_dota_hero_vengefulspirit
    'Aozaki Aoko',  # npc_fate_hero_aoko.kv -> npc_dota_hero_ogre_magi
    'Arash',  # npc_fate_hero_arash.kv -> npc_dota_hero_clinkz
    'Arcueid',  # npc_fate_hero_arcueid.kv -> npc_dota_hero_tiny
    'Arturia (Alter)',  # npc_fate_hero_arturia_alter.kv -> npc_dota_hero_spectre
    'Arturia Pendragon',  # npc_fate_hero_arturia.kv -> npc_dota_hero_legion_commander
    'Astolfo',  # npc_fate_hero_astolfo.kv -> npc_dota_hero_queenofpain
    'Atalanta',  # npc_fate_hero_atalanta.kv -> npc_dota_hero_drow_ranger
    'Atalanta Alter',  # npc_fate_hero_atalanta_alter.kv -> npc_dota_hero_ursa
    'Chloe von Einzbern',  # npc_fate_hero_chloe.kv -> npc_dota_hero_naga_siren
    'Cu Chulainn',  # npc_fate_hero_cu_chulain.kv -> npc_dota_hero_phantom_lancer
    'Demon king Nobunaga',  # npc_fate_hero_demon_king_nobunaga.kv -> npc_dota_hero_nevermore
    'Diarmuid',  # npc_fate_hero_diarmuid.kv -> npc_dota_hero_huskar
    'Edmond Dantes',  # npc_fate_hero_edmon.kv -> npc_dota_hero_treant
    'EMIYA',  # npc_fate_hero_emiya.kv -> npc_dota_hero_ember_spirit
    'Gawain',  # npc_fate_hero_gawain.kv -> npc_dota_hero_omniknight
    'Gilgamesh',  # npc_fate_hero_gilgamesh.kv -> npc_dota_hero_skywrath_mage
    'Gilles de Rais',  # npc_fate_hero_gilles.kv -> npc_dota_hero_shadow_shaman
    'Hassan-i-Sabbah',  # npc_fate_hero_true_assassin.kv -> npc_dota_hero_bounty_hunter
    'Heracles',  # npc_fate_hero_heracles.kv -> npc_dota_hero_doom_bringer
    'Hijikata Toshizo',  # npc_fate_hero_hijikata.kv -> npc_dota_hero_spirit_breaker
    'Iskandar',  # npc_fate_hero_iskandar.kv -> npc_dota_hero_chen
    'Jack The Ripper',  # npc_fate_hero_jtr.kv -> npc_dota_hero_riki
    "Jeanne d'Arc",  # npc_fate_hero_jeanne.kv -> npc_dota_hero_mirana
    "Jeanne d'Arc Alter",  # npc_fate_hero_jeanne_alter.kv -> npc_dota_hero_razor
    'Karna',  # npc_fate_hero_karna.kv -> npc_dota_hero_beastmaster
    'King Hassan',  # npc_fate_hero_kinghassan.kv -> npc_dota_hero_skeleton_king
    'Lancelot',  # npc_fate_hero_lancelot.kv -> npc_dota_hero_sven
    'Leonidas I',  # npc_fate_hero_leonidas.kv -> npc_dota_hero_venomancer
    'Li Shuwen',  # npc_fate_hero_li_shuwen.kv -> npc_dota_hero_bloodseeker
    'Lu Bu',  # npc_fate_hero_lu_bu.kv -> npc_dota_hero_centaur
    'Medea',  # npc_fate_hero_medea.kv -> npc_dota_hero_crystal_maiden
    'Medusa',  # npc_fate_hero_medusa.kv -> npc_dota_hero_templar_assassin
    'Merlin',  # npc_fate_hero_merlin.kv -> npc_dota_hero_puck
    'Mordred',  # npc_fate_hero_mordred.kv -> npc_dota_hero_abaddon
    'Muramasa',  # npc_fate_hero_muramasa.kv -> npc_dota_hero_magnataur
    'Nanaya Shiki',  # npc_fate_hero_nanaya.kv -> npc_dota_hero_night_stalker
    'Nero Claudius',  # npc_fate_hero_nero.kv -> npc_dota_hero_lina
    'Nursery Rhyme',  # npc_fate_hero_nursery_rhyme.kv -> npc_dota_hero_windrunner
    'Oda Nobunaga',  # npc_fate_hero_nobu.kv -> npc_dota_hero_gyrocopter
    'Okada Izo',  # npc_fate_hero_okada.kv -> npc_dota_hero_troll_warlord
    'Okita Souji',  # npc_fate_hero_okita.kv -> npc_dota_hero_dark_willow
    'Ozymandias',  # npc_fate_hero_ozy.kv -> npc_dota_hero_phoenix
    'Robin Hood',  # npc_fate_hero_robin.kv -> npc_dota_hero_sniper
    'Saitō Hajime',  # npc_fate_hero_saito.kv -> npc_dota_hero_terrorblade
    'Sasaki Kojiro',  # npc_fate_hero_sasaki.kv -> npc_dota_hero_juggernaut
    'Scathach',  # npc_fate_hero_scathach.kv -> npc_dota_hero_monkey_king
    'Shiki Ryougi',  # npc_fate_hero_ryougi.kv -> npc_dota_hero_phantom_assassin
    'Tamamo no Mae',  # npc_fate_hero_tamamo.kv -> npc_dota_hero_enchantress
    'Vlad III',  # npc_fate_hero_vlad.kv -> npc_dota_hero_tidehunter
]

# Map a variant spelling (lowercased) -> canonical name above.
ALIASES = {
}

# Chinese (Fate) scoreboard names -> canonical English, from
# resource/addon_schinese.txt. Lets the bot read zh-localized boards.
CHINESE = {
    '阿蒂拉': 'Altera',
    '安哥拉曼纽': 'Angra Mainyu',
    '苍崎青子': 'Aozaki Aoko',
    '阿拉什': 'Arash',
    '爱尔奎特': 'Arcueid',
    '阿尔托莉雅·潘德拉贡〔Alter〕': 'Arturia (Alter)',
    '阿尔托莉雅·潘德拉贡': 'Arturia Pendragon',
    '阿斯托尔福': 'Astolfo',
    '阿塔兰忒': 'Atalanta',
    '阿塔兰忒Alter': 'Atalanta Alter',
    '克洛伊·冯·艾因兹贝伦': 'Chloe von Einzbern',
    '库·丘林': 'Cu Chulainn',
    '魔王信长': 'Demon king Nobunaga',
    '迪尔姆德': 'Diarmuid',
    '爱德蒙·唐泰斯': 'Edmond Dantes',
    '卫宫': 'EMIYA',
    '高文': 'Gawain',
    '吉尔伽美什': 'Gilgamesh',
    '吉尔·德·雷': 'Gilles de Rais',
    '哈桑·萨巴赫': 'Hassan-i-Sabbah',
    '赫拉克勒斯': 'Heracles',
    '土方岁三': 'Hijikata Toshizo',
    '伊斯坎达尔': 'Iskandar',
    '开膛手杰克': 'Jack The Ripper',
    '贞德': "Jeanne d'Arc",
    '贞德〔Alter〕': "Jeanne d'Arc Alter",
    '迦尔纳': 'Karna',
    '山中老人': 'King Hassan',
    '兰斯洛特': 'Lancelot',
    '列奥尼达一世': 'Leonidas I',
    '李书文': 'Li Shuwen',
    '吕布': 'Lu Bu',
    '美狄亚': 'Medea',
    '美杜莎': 'Medusa',
    '梅林': 'Merlin',
    '莫德雷德': 'Mordred',
    '村正': 'Muramasa',
    '七夜志贵': 'Nanaya Shiki',
    '尼禄·克劳狄乌斯': 'Nero Claudius',
    '童谣': 'Nursery Rhyme',
    '织田信长': 'Oda Nobunaga',
    '冈田以藏': 'Okada Izo',
    '冲田总司': 'Okita Souji',
    '奥兹曼迪亚斯': 'Ozymandias',
    '罗宾汉': 'Robin Hood',
    '斋藤一': 'Saitō Hajime',
    '佐佐木小次郎': 'Sasaki Kojiro',
    '斯卡哈': 'Scathach',
    '两仪式': 'Shiki Ryougi',
    '玉藻前': 'Tamamo no Mae',
    '弗拉德三世': 'Vlad III',
}
