"DOTAAbilities"
{
	//=======================================★★★★★
	// Artoria: Invisible Air (Q)
	//=======================================★★★★★
	"artoria_invisible_air"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/artoria/artoria_invisible_air"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"AbilityTextureName"			"custom/saber_invisible_air"
		
		"AbilityType"					"DOTA_ABILITY_TYPE_BASIC"
		
		// Ability Stats		//------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"600 650 700 750 800"
		"AbilityCastRangeBuffer"		"100"
		"AbilityCastPoint"				"0.2"
		"AbilityCooldown"				"5"
		"AbilityManaCost"				"100"
		
		// Precache		//------------------------------------------------------------------------------------------------------------
		"precache"
		{
			"particle"				"particles/econ/items/windrunner/windrunner_cape_sparrowhawk/windrunner_windrun_blur_sparrowhawk.vpcf"
			"particle"				"particles/custom/saber/saber_invisible_air_trail.vpcf"
			"particle"				"particles/units/heroes/hero_invoker/invoker_tornado_trail.vpcf"
			"particle"				"particles/units/heroes/hero_invoker/invoker_tornado_base.vpcf"
			"particle"				"particles/custom/artoria/artoria_wind_blow.vpcf"
			"particle"				"particles/custom/artoria/invisible_air/artoria_invisible_air.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_windrunner.vsndevts"
		}
		
		// Ability Special		//------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "damage" "200 250 300 350 400"
            "speed" "700"
            "range" "600 650 700 750 800"
            "bonus_damage" "10 20 30 40 50"
            "wind_speed" "1500.0"
            "vision_radius" "500"
            "vision_duration" "2.0"
        }
	}
}