"DOTAAbilities"
{
	//=======================================★★★★★
	// Artoria: Instinct (F, Activatable Passive)
	//=======================================★★★★★
	"artoria_instinct"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/artoria/artoria_instinct"
		"MaxLevel"						"1"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityTextureName"			"custom/saber_instinct"

		"AbilityCooldown"				"20"
		
		// Precache		//------------------------------------------------------------------------------------------------------------
		"precache"
		{
			"particle"			"particles/custom/enkidu/enkiduenergyblades.vpcf"
		}
		
		// Ability Special		//------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "evasion_rate" "15"
        }
	}
}