"DOTAAbilities"
{
	//=================================================================================================================
	// Assassin(Extra) : Fierce Tiger Strike(first strike)
	//=================================================================================================================
	"lishuwen_tiger_strike"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/lishuwen/lishuwen_tiger_strike"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING| DOTA_ABILITY_BEHAVIOR_AUTOCAST"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PHYSICAL"
		"AbilityTextureName"			"custom/lishuwen_fierce_tiger_strike"
		"AbilityCastAnimation" 			"ACT_DOTA_ATTACK"
		"AnimationPlaybackRate" 		"1.0"
		"precache"
		{
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_earthshaker.vsndevts"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_juggernaut.vsndevts"
			"particle"		"particles/econ/items/earthshaker/egteam_set/hero_earthshaker_egset/earthshaker_echoslam_start_fallback_low_egset.vpcf"
			"particle"		"particles/econ/items/juggernaut/jugg_arcana/juggernaut_arcana_v2_crit_tgt.vpcf"
			"particle"		"particles/units/heroes/hero_earthshaker/earthshaker_echoslam_start_f_fallback_low.vpcf"
			"particle"		"particles/units/heroes/hero_ember_spirit/ember_spirit_sleightoffist_trail.vpcf"
			"particle"		"particles/units/heroes/hero_phantom_assassin/phantom_assassin_crit_impact.vpcf"
			"particle"		"particles/custom/lishuwen/lishuwen_first_hit.vpcf"
			"particle"		"particles/custom/lishuwen/lishuwen_second_hit.vpcf"
			"particle"		"particles/custom/lishuwen/lishuwen_third_hit.vpcf"
			"particle"		"particles/custom/lishuwen/lishuwen_no_second_strike_hit.vpcf"
		}
		
		// Ability stats
		//-------------------------------------------------------------------------------------------------------------
		//"AbilityCastRange"			"700"
		"AbilityCastRangeBuffer"		"100"
		//"AbilityCastPoint"				"0.3"
		"AbilityCooldown"				"23"
		"AbilityManaCost"				"200"
		
		// Ability special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "damage_1" "300 375 450 525 600"
            "slow_amount" "-55"
            "slow_duration" "2.0 2.0 2.5 2.5 3.0"
            "damage_2" "300 350 400 450 500"
            "stun_duration" "0.4"
            "damage_3_magical" "300 350 400 450 500"
            "damage_2_physical" "25"
            "window_duration" "2"
            "regen_amount" "50"
            "regen_duration" "4.0"
            "strike_1_range" "500"
            "strike_2_range" "400"
            "reduced_cooldown" "18"
            "furious_chain_cooldown" "5"
            "chain_switch_penalty" "0.75"
            "chain_bonus_multiplier" "1.25"
            "strength_ratio" "0.33"
            "critical_chance" "25"
            "crit_multiplier" "200"
            "losthealth_multiplier" "1.0"
            "sa_attack_speed" "150"
            "damage_bers_physical" "60"
        }
	}
}