"DOTAAbilities"
{
	//=================================================================================================================
	// Assassin(Extra) : No Second Strike
	//=================================================================================================================
	"lishuwen_no_second_strike"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/lishuwen/lishuwen_no_second_strike"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitTargetFlags"		"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PURE"
		"AbilityType"					"ABILITY_TYPE_ULTIMATE"
		"AbilityTextureName"			"custom/lishuwen_no_second_strike"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_4"
		"AnimationPlaybackRate" 		"0.35"
		"precache"
		{
			"particle"			"particles/custom/lishuwen/lishuwen_no_second_strike_windup.vpcf"
			"particle"			"particles/units/heroes/hero_earthshaker/earthshaker_echoslam_start_fallback_mid.vpcf"
			"particle"			"particles/custom/lishuwen/lishuwen_no_second_strike_hit.vpcf"
			"particle"			"particles/custom/lishuwen/lishuwen_no_second_strike_windup.vpcf"
			"particle"			"particles/custom_game/heroes/saitama/saitama_windup.vpcf"
			"particle"			"particles/custom_game/heroes/kenshiro/kenshiro_ganzan_hit/kenshiro_ganzan_hit_j.vpcf"
			"particle"			"particles/zlodemon/shuwen_jopa_1.vpcf"
			"particle"			"particles/zlodemon/shuwen_jopa_2.vpcf"
			"particle"			"particles/li_shuwen/li_shuwen_stacks.vpcf"
			"particle"			"particles/li_shuwen/li_shuwen_stacks_jopa.vpcf"
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_nyx_assassin.vsndevts"
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_bloodseeker.vsndevts"
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_spirit_breaker.vsndevts"
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_oracle.vsndevts"
		}
		
		// Ability stats
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"700"
		"AbilityCastRangeBuffer"		"300"
		"AbilityCastPoint"				"0.55"
		"AbilityCooldown"				"22"
		"AbilityManaCost"				"800"
		
		// Ability special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "cast_delay" "0.55"
            "initial_damage" "300 350 400 450 500"
            "stun_duration" "0.5"
            "revoke_duration" "2.00"
            "shock_damage" "300 350 400 450 500"
            "attribute_stun_duration" "1.0"
            "attribute_revoke_duration" "2.00"
            "attribute_kb_distance" "250"
            "stacks_duration" "15"
            "damage_per_nss_stack" "12"
            "sa_bonus_damage_per_stack" "8"
            "magical_damage_reduction_1" "20"
            "magical_damage_reduction_2" "40"
            "slow_power" "30"
            "heal_reduction_1" "40"
            "heal_reduction_2" "60"
            "mr_reduction" "15"
            "armor_reduction" "10"
        }
	}
}