"DOTAAbilities"
{
	//=================================================================================================================
	// Assassin(Extra) : Presence Concealment
	//=================================================================================================================
	"lishuwen_presence_concealment"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/lishuwen/lishuwen_presence_concealment"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityTextureName"			"custom/lishuwen_concealment"
		"AbilityCastAnimation" 			"ACT_DOTA_ALCHEMIST_CHEMICAL_RAGE_START"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AnimationPlaybackRate" 		"1.2"

		"precache"
		{
			"particle"			"particles/units/heroes/hero_pugna/pugna_decrepify.vpcf"
			"particle"			"particles/units/heroes/hero_dark_seer/dark_seer_surge.vpcf"
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_phantom_lancer.vsndevts"
		}
		
		// Cast
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastPoint"				"0.2"
		"AbilityCooldown"				"14"
		"AbilityManaCost"				"100"
		
		// Ability Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "cast_delay" "0.2"
            "health_regen" "3.0 3.5 4.0 4.5 5.0"
            "mana_regen" "3.0 3.5 4.0 4.5 5.0"
            "break_delay" "2.0"
            "bonus_damage" "30 37.5 45 52.5 60"
            "number_attacks" "5"
            "atk_buff_duration" "5.0"
        }
	}
}