"DOTAAbilities"
{
	//=================================================================================================================
	// Assassin(Extra) : Berserk
	//=================================================================================================================
	"lishuwen_berserk"
	{
		"BaseClass"						"ability_datadriven"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/lishuwen_berserk"
		"MaxLevel"						"1"
		"AbilityCooldown"				"45"
		"precache"
		{
			"particle"		"particles/prototype_fx/item_linkens_buff.vpcf"
			"particle"		"particles/custom/abaddon_death_coil_explosion.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_abaddon.vsndevts"
			"particle"		"particles/units/heroes/hero_spectre/spectre_ambient.vpcf"
		}
		
		"AbilityValues"
        {
            "duration" "8"
            "strbonus" "20"
            "dmg_ratio" "1.5"
        }
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"		"lishuwen_ability"
				"Function"			"OnBerserkStart"
				"Duration"			"%duration"
			}
		}
		
		"Modifiers"
		{
			"modifier_lishuwen_berserk"
			{
				"Duration"		"%duration"
				"EffectName"		"particles/units/heroes/hero_spectre/spectre_ambient.vpcf"
				"EffectAttachType"	"follow_origin"
				"Properties"
				{
					"MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE"	"100"
				}				
			}
		}
	}

	//=================================================================================================================
	// Assassin(Extra) : Presence Concealment
	//=================================================================================================================

	//=================================================================================================================
	// Assassin(Extra) : Cosmic Orbit
	//=================================================================================================================
	"lishuwen_cosmic_orbit"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityTextureName"			"custom/lishuwen_cosmic_orbit"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1"
		"precache"
		{
			"particle"					"particles/custom/generic/fate_red_shield.vpcf"
			"particle"					"particles/items2_fx/satanic_buff.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_sven.vsndevts"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_nightstalker.vsndevts"
		}
		
		// Cast
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastPoint"				"0.5"
		"AbilityCooldown"				"27 24 21 18 15"
		"AbilityManaCost"				"200"
		
		// Ability Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "resist_duration" "0.1 0.2 0.3 0.4 0.5"
            "mr_bonus" "50"
            "armor_bonus" "30"
            "active_bonus_aspd" "15 30 45 60 75"
            "active_bonus_ms" "15"
            "active_duration" "8"
        }
		// Data driven
		//-------------------------------------------------------------------------------------------------------------
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"lishuwen_ability"
				"Function"		"OnCosmicOrbitStart"
			}
		}
				
		"Modifiers"
		{
			"modifier_lishuwen_cosmic_orbit_passive"
			{
				"Passive"		"1"
				"IsHidden"		"1"
				"OnAttackLanded"
				{
					"RunScript"
					{
						"ScriptFile"	"lishuwen_ability"
						"Function"		"OnCosmicOrbitAttackLanded"
					}					
				}
			}
			"modifier_lishuwen_cosmic_orbit"
			{	
				"EffectName" "particles/items2_fx/satanic_buff.vpcf"
	            "EffectAttachType" "follow_origin"	
				"Duration"			"%active_duration"
				"Properties"
				{
					"MODIFIER_PROPERTY_ATTACKSPEED_BONUS_CONSTANT"	"%active_bonus_aspd"
					"MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE"	"%active_bonus_ms"
				}							
			}
			"modifier_lishuwen_cosmic_orbit_momentary_resistance"
			{
				"EffectName"	"particles/custom/generic/fate_red_shield.vpcf"
				"EffectAttachType"	"follow_origin"
				"Duration"			"%resist_duration"
				"Properties"
				{
					"MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BONUS"	"%mr_bonus"
					"MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS"     	"%armor_bonus"
				}				
			}
			"modifier_lishuwen_cosmic_orbit_silence_cooldown"
			{
				"Duration"		"3.0"
				"IsDebuff"		"1"
				"IsHidden"		"0"
			}
		}
	}
	
	//=================================================================================================================
	// Assassin(Extra) : Fierce Tiger Strike(first strike)
	//=================================================================================================================

	//=================================================================================================================
	// Assassin(Extra) : Fierce Tiger Strike(second strike)
	//=================================================================================================================

	//=================================================================================================================
	// Assassin(Extra) : Fierce Tiger Strike(third strike)
	//=================================================================================================================

	//=================================================================================================================
	// Assassin(Extra) : No Second Strike
	//=================================================================================================================
	"lishuwen_no_second_strike"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitTargetFlags"		"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityType"					"ABILITY_TYPE_ULTIMATE"
		"AbilityTextureName"			"custom/lishuwen_no_second_strike"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_4"
		"AnimationPlaybackRate" 		"0.5"
		"precache"
		{
			"particle"			"particles/units/heroes/hero_bloodseeker/bloodseeker_rupture.vpcf"		
			"particle"			"particles/units/heroes/hero_nyx_assassin/nyx_assassin_mana_burn.vpcf"
			"particle"			"particles/custom/lishuwen/lishuwen_no_second_strike_windup.vpcf"
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_nyx_assassin.vsndevts"
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_bloodseeker.vsndevts"
		}
		
		// Ability stats
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"150"
		"AbilityCastRangeBuffer"		"100"
		"AbilityCastPoint"				"0.75"
		"AbilityCooldown"				"30"
		"AbilityManaCost"				"800"
		
		// Ability special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "cast_delay" "0.75"
            "initial_damage" "650 700 750 800 850"
            "stun_duration" "0.7"
            "open_wound_duration" "3.0"
            "open_wound_damage" "60 75 90 105 120"
            "open_wound_stun_duration" "0.6"
            "silence_duration" "3.0"
        }

		"OnAbilityPhaseStart"
		{
			"RunScript"
			{
				"ScriptFile"			"lishuwen_ability"
				"Function"				"OnNSSCastStart"
				"CastDelay"				"%cast_delay"
			}
		}
		
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"			"lishuwen_ability"
				"Function"				"OnNSSStart"
				"Damage"				"%initial_damage"
				"StunDuration"			"%stun_duration"
				"SilenceDuration"		"%silence_duration"
				"ProcDamage"			"%open_wound_damage"
				"ProcStunDuration"		"%open_wound_stun_duration"
			}
		}
	
		
		"Modifiers"
		{
			"modifier_no_second_strike_delay_indicator"
			{
		        "EffectName"    "particles/units/heroes/hero_bloodseeker/bloodseeker_rupture.vpcf"
		        "EffectAttachType"  "follow_origin"
				"Duration"		"%open_wound_duration"
				"IsDebuff"		"1"
				"OnTakeDamage"
				{
					"RunScript"
					{
						"ScriptFile"	"lishuwen_ability"
						"Function"		"OnNSSTakeDamage"
						"DamageTaken"	"%attack_damage"	
						"ProcDamage"			"%open_wound_damage"
						"ProcStunDuration"		"%open_wound_stun_duration"
					}
				}
				"OnDestroy"
				{
					"RunScript"
					{
						"ScriptFile"		"lishuwen_ability"
						"Function"			"OnNSSDelayFinished"
						//"DelayedDamagePercentage"	"%delayed_damage_percentage"
						//"DelayedStunDuration"		"%delayed_stun_duration"
					}
				}
			}

			"modifier_no_second_strike_anim"
			{
				"IsHidden"			"1"
				"Duration"			"0.5"
				"OverrideAnimation"		"ACT_DOTA_CAST_ABILITY_4_END"
				"Properties"
				{
					"MODIFIER_PROPERTY_OVERRIDE_ANIMATION_RATE"		"2.0"
				}
			}	
		}
	}

	// [restored] возвращён после ошибочной чистки
	// [restored] возвращён после ошибочной чистки
	// [restored] возвращён после ошибочной чистки
	// [restored] возвращён после ошибочной чистки
}