"DOTAAbilities"
{
	//=======================================
	// Archer Attribute : Eagle Eye
	//=======================================

	//=======================================
	// Archer Attribute : Hrunting
	//=======================================
	//=======================================
	// Archer Attribute : Shroud of Martin
	//=======================================

	//=======================================
	// Archer Attribute : Improve Projection
	//=======================================

	//=======================================
	// Archer Attribute : Kanshou Bakuya Overedge
	//=======================================
	
	//=======================================
	// Archer : Rho Aias
	//=======================================

	
	//=================================================================================================================
	// Archer : Clairvoyance
	//=================================================================================================================
	"archer_5th_clairvoyance"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"2"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityTextureName"			"custom/archer_5th_clairvoyance"
		"AOERadius"						"%radius"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"1.0"
		"precache"
		{
			"particle"					"particles/custom/archer/archer_clairvoyance_dust.vpcf"
			"particle"					"particles/custom/archer/archer_clairvoyance_circle.vpcf"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_keeper_of_the_light.vsndevts"

		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"99999"
		"AbilityCastPoint"				"0.3"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"22.0 14.0"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"100"
		
		"AbilityValues"
        {
            "radius" "700 900"
            "range" "99999"
            "duration" "9.0"
        }
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"    		"archer_ability"
				"Function"      		"FarSightVision"
				"Radius"				"%radius"
				"Target"				"POINT"
				"Duration"				"%duration"
			}
		}
	}
	
	

	//=================================================================================================================
	// Archer : Kanshou Bakuya
	//=================================================================================================================

	//=================================================================================================================
	// Archer : Crane Wings
	//=================================================================================================================

	//=================================================================================================================
	// Archer : Unlimited Blade Works
	//=================================================================================================================
	"archer_5th_ubw"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/archer_5th_ubw"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_4"
		"AbilityType"					"ABILITY_TYPE_ULTIMATE"
		"AnimationPlaybackRate" 		"1.0"
		
		"precache"
		{
			"particle"					"particles/units/heroes/hero_phantom_assassin/phantom_assassin_stifling_dagger.vpcf"
			"particle"					"particles/custom/archer/archer_ubw_ring.vpcf"
			"particle"					"particles/custom/archer/ubw/firering.vpcf"
			"particle"					"particles/custom/archer/ubw/entrance_flash.vpcf"
			"particle"					"particles/custom/archer/ubw/exit_flash.vpcf"
			"model"						"models/items/skeleton_king/weapon_shattered/weapon_shattered.vmdl"
		}
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"10"
		"AbilityManaCost"				"0"
		"AbilityCastRange"				"1150"
		
		"AbilityValues"
        {
            "cast_delay" "2.0"
            "radius" "1150"
            "duration" "12.0"
            "damage" "20 30 40 50 60"
        }

		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"archer_ability"
				"Function"		"OnUBWCastStart"
				"Radius"		"%radius"
			}
		}
		"OnUpgrade"
		{
			"RunScript"
			{
				"ScriptFile"		"archer_ability"
				"Function"			"OnUBWLevelUp"
			}
		}		
		
		"OnRespawn"
		{
			"RunScript"
			{
				"ScriptFile"	"archer_ability"
				"Function"		"OnUBWDeath"
			}
		}

		"OnProjectileHitUnit"
		{
			"RunScript"
			{
				"ScriptFile"	"archer_ability"
				"Function"		"OnUBWWeaponHit"
				"Damage"		"%damage"
			}
		}		
			
		"Modifiers"
		{
			"modifier_ubw_freeze"
			{
				"Duration"		"2.0"
				"IsHidden"		"1"
				"OverrideAnimation"		"ACT_DOTA_CAST_ABILITY_4"
				"Duration"				"2.0"
			}

			"modifier_ubw_death_checker"
			{
				"OnCreated"
				{
					"AttachEffect"
					{
						"Target"			"TARGET"
						"EffectName"		"particles/custom/archer/archer_ubw_ring.vpcf"
						"EffectAttachType"	"start_at_origin"
						"EffectRadius"		"%radius"
					}
				}
			
				"Duration"	"12.0"
				"OnDestroy"
				{
					"RemoveModifier"
					{
						"ModifierName"		"modifier_ubw_death_checker"
						"Target"			"CASTER"
					}
					"RemoveModifier"
					{
						"ModifierName"		"modifier_shroud_of_martin_str_bonus"
						"Target"			"CASTER"
					}
					"RunScript"
					{
						"ScriptFile"	"archer_ability"
						"Function"		"OnUBWDeath"
					}
				}
			}

			"modifier_shroud_of_martin_str_bonus"
			{
				"IsHidden"		"1"
				"Duration"		"12.0"
				"Properties"
				{
					"MODIFIER_PROPERTY_STATS_STRENGTH_BONUS"	"20"
				}
			}
		}
	}

	//=====================================
	// Archer : Sword Barrage - Retreat Shot
	//=====================================

	//=====================================
	// Archer : Sword Barrage - Confine
	//=====================================

	//=====================================
	// Archer : Sword Barrage - Bombard
	//=====================================

	//=================================================================================================================
	// Archer : Arrow Rain
	//=================================================================================================================
	"archer_5th_arrow_rain"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/archer_5th_arrow_rain"
		
		"precache"
		{
			"particle"			"particles/units/heroes/hero_sven/sven_storm_bolt_projectile_explosion.vpcf"
			"particle"			"particles/units/heroes/hero_clinkz/clinkz_searing_arrow.vpcf"
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_drowranger.vsndevts"
			"particle"			"particles/units/heroes/hero_gyrocopter/gyro_guided_missile_explosion.vpcf"
			"particle"			"particles/custom/archer/archer_arrow_rain_model.vpcf"
			"particle"			"particles/custom/archer/archer_sword_barrage_impact_circle.vpcf"
			"particle"			"particles/custom/screen_brown_splash.vpcf"
		}
		
		"AbilityCastPoint"				"0.1"
		"AbilityCooldown"				"180"
		"AbilityManaCost"				"400"
		
		"AbilityValues"
        {
            "arrow_amount" "100"
            "arrow_damage" "175"
            "bp_shot_amount" "5"
            "bp_shot_damage" "66"
        }
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"archer_ability"
				"Function"		"OnRainStart"
				"Damage"		"%arrow_damage"
			}
		}

		"OnProjectileHitUnit"
		{
			"RunScript"
			{
				"ScriptFile"    "archer_ability"
				"Function"      "OnArrowRainBPHit"
			}
			"FireSound"
			{
				"EffectName"	"Hero_Sven.StormBoltImpact"
			}
		}
			
		"Modifiers"
		{
			"modifier_arrow_rain_cooldown"
			{
				"IsDebuff"	"1"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_arrow_rain_anim"
			{
				"Duration"	"1.0"
				"IsHidden"	"0"
				"OverrideAnimation"     "ACT_DOTA_CAST_ABILITY_2"			
				"Properties"
				{
					"MODIFIER_PROPERTY_OVERRIDE_ANIMATION_RATE"		"3"
				}
			}
		}
	}
	
	//=================================================================================================================
	// Archer : Hrunting
	//=================================================================================================================

	//===================================================
	// Archer : Nine Lives
	//===================================================

	//=================================================================================================================
	// Archer : Broken Phantasm
	//=================================================================================================================
	
	//=====================================
	// Archer : Rule Breaker
	//=====================================

	//=======================================
	// Archer Attribute : Improve Projection
	//=======================================

	// [restored] возвращён после ошибочной чистки
}