#base "gilgamesh_enkidu.kv"
#base "gilgamesh_sword_rain.kv"

"DOTAAbilities"
{
	//=================================================================================================================
	// Gilgamesh : Golden Rule
	//=================================================================================================================
	"gilgamesh_golden_rule"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/gilgamesh/gilgamesh_golden_rule"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityTextureName"			"custom/gilgamesh_golden_rule"
		"MaxLevel"						"2"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		
		"AbilityValues"
        {
            "gold_gain" "15 30"
        }
		
	}		

	//=====================================
	// Gilgamesh : Attack passive
	//=====================================
	"gilgamesh_attack_passive"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilgamesh/gilgamesh_attack_passive"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_HIDDEN|DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/gilgamesh/gilgamesh_sword_barrage"
		
		"precache"
		{
			"particle"					"particles/gilgamesh/gob.vpcf"
			"particle"					"particles/gilgamesh/gil_target_gob_projectile.vpcf"
			"particle"					"particles/gilgamesh/gob_hit.vpcf"
		}
		 
		"AbilityValues"
        {
            "cast_delay" "0.3"
            "cast_range" "850"
        }
		
		 
	}

	//=====================================
	// Gilgamesh : Sword barrage
	//=====================================
	"gilgamesh_sword_barrage"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilgamesh/gilgamesh_sword_barrage"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET|DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetFlags"		"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PHYSICAL"
		"AbilityTextureName"			"custom/gilgamesh/gilgamesh_sword_barrage"
		
		"AbilityCastPoint"				"0.1"
		"AbilityCastRange"				"1000"
		"AbilityCastRangeBuffer"		"150"
		"AbilityCooldown"				"4"
		"AbilityManaCost"				"100"
		"AbilityCastAnimation"			"ACT_DOTA_CAST_ABILITY_2"
		"AnimationPlaybackRate" 		"0.9"

		"precache"
		{
			"particle"					"particles/gilgamesh/gob.vpcf"
			"particle"					"particles/gilgamesh/gil_target_gob_projectile.vpcf"
			"particle"					"particles/gilgamesh/gob_hit.vpcf"
		}
		
		 
		"AbilityValues"
        {
            "cast_delay" "0.3"
            "cast_range" "1000"
            "damage" "60 75 90 105 120"
            "root_duration" "0.3"
            "lock_duration" "0.3"
            "radius" "100"
            "strike_amount" "5"
        }
		
		 
	}
	//=====================================
	// Gilgamesh : Gate of Babylon
	//=====================================
	"gilgamesh_gate_of_babylon"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilgamesh/gilgamesh_gate_of_babylon"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT|DOTA_ABILITY_BEHAVIOR_AUTOCAST"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PHYSICAL"
		"AbilityTextureName"			"custom/gilgamesh_gate_of_babylon"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_4"
		"AnimationPlaybackRate" 		"10.0"

		"precache"
		{
			"particle"		"particles/gilgamesh/gob_weapon.vpcf"
			"particle"		"particles/gilgamesh/gob.vpcf"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_juggernaut.vsndevts"
			"particle"		"particles/custom_game/heroes/gilgamesh/gilgamesh_enlarge_gate_hit/gilgamesh_enlarge_gate_hit.vpcf"
			"particle"		"particles/gilgamesh/gob_weapon_longer.vpcf"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"1000"
		"AbilityCastPoint"				"0.3"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"30"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"400"
		
		"AbilityValues"
        {
            "damage" "20 25 30 35 40"
            "radius" "100"
            "duration" "5"
            "range" "1000"
        }
		
		 
	}
	//=====================================
	// Gilgamesh : Enuma Elish
	//=====================================
	"gilgamesh_enuma_elish"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilgamesh/enuma_elish"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_CHANNELLED"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation"			"ACT_DOTA_IDLE"
		"AbilityTextureName"			"custom/gilgamesh_enuma_elish"

		"precache"
			{
			"particle"		"particles/custom/gilgamesh/gilgamesh_enuma_elish_charge_wave.vpcf"
			"particle"		"particles/units/heroes/hero_keeper_of_the_light/keeper_of_the_light_illuminate_impact.vpcf"
			"particle"		"particles/custom/gilgamesh/enuma_elish/projectile.vpcf"			
			"particle"		"particles/custom/gilgamesh/enuma_elish/charging_sparkles.vpcf"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_weaver.vsndevts"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_dark_seer.vsndevts"
			}
			
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"1700"
		"AbilityCastPoint"				"0.2"
		"AbilityChannelTime"      		"4.05"

		// Time
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"47.0"


		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"800"

		// AbilitySpecial
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "activation" "1.5"
            "radius" "250"
            "end_radius" "250"
            "range" "1700"
            "speed" "1000"
            "damage" "1000 1250 1500 1750 2000"
            "endcast_pause" "1.0"
            "endradius_charge_start" "10"
            "endradius_charge_end" "50"
            "endradius_total" "500"
            "damage_charge_start" "7.5"
            "damage_charge_end" "37.5"
            "damage_total" "400 550 700 850 1000"
            "add1_charge_start" "22.5"
            "add1_charge_end" "37.5"
            "damagemax" "1600 2125 2550 2975 3500"
            "endradiusmax" "625"
        }
	}
	//=====================================
	// Gilgamesh : Enuma Elish ACTIVATE
	//=====================================
	"gilgamesh_enuma_elish_activate"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilgamesh/enuma_elish"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/gilgamesh_enuma_elish"

		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"1"
		"AbilityManaCost"				"0"

		"precache"
		{
		}

		"AbilityValues"
        {
        }
	}	
	
	//=====================================
	// Gilgamesh : MAX Enuma Elish
	//=====================================
	"gilgamesh_max_enuma_elish"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/gilgamesh/gilgamesh_max_enuma_elish"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PURE"
		"AbilityCastAnimation" 			"ACT_DOTA_IDLE"
		"AnimationPlaybackRate" 		"1.0"

		"AbilityTextureName"			"custom/gilgamesh_max_enuma_elish"
		"precache"
		{
			"particle"		"particles/units/heroes/hero_dragon_knight/dragon_knight_breathe_fire.vpcf"
			"particle"		"particles/custom/screen_scarlet_splash.vpcf"
			"particle"		"particles/custom/gilgamesh/enuma_elish.vpcf"
			"particle"		"particles/custom/gilgamesh/gilgamesh_enuma_elish_charge.vpcf"
			"particle"		"particles/units/heroes/hero_keeper_of_the_light/keeper_of_the_light_illuminate_impact.vpcf"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"2500"
		"AbilityCastPoint"				"0.2"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"160"


		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"800"
		
		"AbilityValues"
        {
            "cast_delay" "4.25"
            "damage" "2500"
            "start_radius" "250"
            "end_radius" "500"
            "radius" "2500"
            "speed" "2800"
        }
		
		
		

	}

	//=======================================
	// Gilgamesh Attribute : Improve Golden Rule
	//=======================================
	"gilgamesh_attribute_improve_golden_rule"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/gilgamesh/gilgamesh_attribute_improve_golden_rule"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/gilgamesh_attribute_improve_golden_rule"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"10"

		"precache"
		{
		}

		"AbilityValues"
        {
            "bounty_bonus" "50"
        }

	}
	//=======================================
	// Gilgamesh Attribute : Power of Sumer
	//=======================================
	"gilgamesh_attribute_power_of_sumer"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/gilgamesh/gilgamesh_attribute_power_of_sumer"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/gilgamesh_attribute_power_of_sumer"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"14"

		"precache"
		{
		}

		"AbilityValues"
        {
            "dmg_ratio" "20"
            "dmg_ratio_q" "25"
        }
		
	}

	//=======================================
	// Gilgamesh Attribute : Chains of heaven
	//=======================================
	"gilgamesh_attribute_chains_of_heaven"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilgamesh/gilgamesh_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/gilgamesh/chains_of_heaven"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"10"

		"precache"
		{
		}

		"AbilityValues"
        {
            "amount_of_swords" "8"
            "sword_damage" "100"
            "bonus_duration" "1"
        }
	}

	//=======================================
	// Gilgamesh Attribute : Rain of Swords
	//=======================================
	"gilgamesh_attribute_rain_of_swords"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilgamesh/gilgamesh_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/gilgamesh/rain_of_swords"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"11"

		"precache"
		{
		}

		"AbilityValues"
        {
            "bonus_damage" "50"
            "bonus_aoe" "50"
            "reset_timer" "5"
            "max_stack" "5"
        }
	}

	"gilgamesh_rain_of_swords_passive"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gilgamesh/gilgamesh_passives"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/gilgamesh/rain_of_swords"
		
		"precache"
		{
		}

		"AbilityValues"
        {
        }
	}

	//=======================================
	// Gilgamesh Attribute : Sword of Creation
	//=======================================
	"gilgamesh_attribute_sword_of_creation"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/gilgamesh/gilgamesh_attribute_sword_of_creation"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/gilgamesh_attribute_sword_of_creation"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"12"

		"precache"
		{
		}

		"AbilityValues"
        {
            "enuma_range" "150"
            "enuma_radius" "250"
            "max_enuma_damage" "3500"
            "max_enuma_radius" "750"
        }
		
	}
}
