"DOTAAbilities"
{
	//=================================================================================================================
	// Gawain : Heat
	//=================================================================================================================
	"gawain_heat"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/gawain/gawain_heat"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/gawain_heat"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1.0"
		
		"precache"
		{
			"particle"					"particles/units/heroes/hero_invoker/invoker_sun_strike_beam.vpcf"
			"particle"					"particles/units/heroes/hero_phoenix/phoenix_fire_spirit_ground.vpcf"
			"particle"					"particles/units/heroes/hero_invoker/invoker_sun_strike_sparks.vpcf"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_invoker.vsndevts"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_ember_spirit.vsndevts"
			"particle"					"particles/units/heroes/hero_ember_spirit/ember_spirit_flameguard.vpcf"
		}
		
		"AbilityCooldown"				"16"
		"AbilityManaCost"				"100"
		
		"AbilityValues"
        {
            "burn_damage" "65 80 95 110 125"
            "attack_speed" "65 80 95 110 125"
            "stack_damage" "5 6.25 7.5 8.75 10"
            "stack_damage_max" "50 62.5 75 87.5 100"
            "duration" "9"
            "radius" "500"
        }
	}	
}