"DOTAAbilities"
{	
	//=================================================================================================================
	// Gawain : Heat
	//=================================================================================================================

	//=================================================================================================================
	// Gawain : Blade of the Devoted
	//=================================================================================================================
	"gawain_blade_of_the_devoted"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/gawain/gawain_blade_of_the_devoted"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityTextureName"			"custom/gawain_blade_of_the_devoted"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1.0"
		
		"precache"
		{
			"particle"					"particles/units/heroes/hero_invoker/invoker_sun_strike_beam.vpcf"
			"particle"					"particles/units/heroes/hero_phoenix/phoenix_fire_spirit_ground.vpcf"
			"particle"					"particles/units/heroes/hero_invoker/invoker_sun_strike_sparks.vpcf"
			"particle"					"particles/units/heroes/hero_doom_bringer/doom_infernal_blade_debuff.vpcf"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_invoker.vsndevts"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_ember_spirit.vsndevts"
		}
		
		"AbilityCooldown"				"17 17 17 17 17"
		"AbilityManaCost"				"200"
		
		"AbilityValues"
        {
            "damage" "360 428 495 562 630"
            "bonus_speed" "20 25 30 35 40"
        }


	}



	//=================================================================================================================
	// Gawain : Solar Embodiment
	//=================================================================================================================

	
	//=================================================================================================================
	// Gawain : Blessing of Fairy
	//=================================================================================================================
	"gawain_blessing_of_fairy"
	{
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityTextureName"			"custom/gawain_blessing_of_fairy"
		"AbilityCooldown"				"60"

		"precache"
		{
			"particle"	"particles/items_fx/aegis_timer.vpcf"

		}
		
		"OnSpellStart"
		{
			"ApplyModifier"
			{
				"ModifierName"	"modifier_gawain_revive"
				"Target"		"CASTER"
			}
		}

		"Modifiers"
		{
			"modifier_gawain_revive"
			{
				"Passive"	"1"
				"IsHidden"	"1"
				"OnTakeDamage"
				{
					"RunScript"
					{
						"ScriptFile"	"gawain_ability"
						"Function"	"OnFairyDamageTaken"
						"DamageTaken"	"%attack_damage"
					}
				}
			}
			"modifier_gawain_blessing_cooldown"
			{
				"IsDebuff"	"1"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}

		}
	}

	//=================================================================================================================
	// Gawain : Invigorating Ray
	//=================================================================================================================

	//=================================================================================================================
	// Gawain : Blade of the Devoted
	//=================================================================================================================
	"gawain_blade_of_the_devoted"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityTextureName"			"custom/gawain_blade_of_the_devoted"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1.0"
		
		"precache"
		{
			"particle"			"particles/units/heroes/hero_invoker/invoker_sun_strike_beam.vpcf"
			"particle"			"particles/units/heroes/hero_phoenix/phoenix_fire_spirit_ground.vpcf"
			"particle"			"particles/units/heroes/hero_invoker/invoker_sun_strike_sparks.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_invoker.vsndevts"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_ember_spirit.vsndevts"
		}
		
		"AbilityCooldown"				"15 14 13 12 11"
		"AbilityManaCost"				"200"
		
		"AbilityValues"
        {
            "heal_amount" "350 425 500 575 650"
            "bonus_speed" "10 15 20 25 30"
        }

		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"gawain_ability"
				"Function"		"OnDevoteStart"
			}
		}

		"OnRespawn"
		{
		}

		"Modifiers"
		{
			"modifier_blade_of_the_devoted"
			{
				"Duration"		"5"
				"OnAttackStart"
				{
					"ApplyModifier"
					{
						"ModifierName"		"modifier_blade_of_the_devoted_anim"
						"Target"			"CASTER"
						"Flags" "DOTA_UNIT_TARGET_FLAG_INVULNERABLE"
					}
				}
				"OnAttackLanded"
				{
					"RunScript"
					{
						"ScriptFile"		"gawain_ability"
						"Function"			"OnDevoteHit"
						"Damage"			"%heal_amount"
					}
				}			
				"Properties"
				{
					"MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE"	"%bonus_speed"
				}	
			}
			"modifier_blade_of_the_devoted_eclispe"
			{
				"Duration"		"3.0"
				"OnAttackLanded"
				{
					"RunScript"
					{
						"ScriptFile"		"gawain_ability"
						"Function"			"OnDevoteConsecutiveHit"
					}
				}	
			}

			"modifier_blade_of_the_devoted_ally_deniable"
			{
				"Duration"		"1.0"
				"IsHidden"		"1"
				"States"
				{
					"MODIFIER_STATE_SPECIALLY_DENIABLE" "MODIFIER_STATE_VALUE_ENABLED"
				}			
			}
			"modifier_blade_of_the_devoted_anim"
			{
				"OverrideAnimation"     "ACT_DOTA_ATTACK_EVENT"	
				"Duration"			"0.5"
				"IsHidden"			"1"
				"Properties"
				{
					"MODIFIER_PROPERTY_OVERRIDE_ANIMATION_RATE"		"1.5"
				}
			}
			"modifier_max_mana_burst_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/saber_alter_max_mana_burst"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_delusional_illusion_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/true_assassin_combo"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_max_excalibur_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/saber_max_excalibur"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_wesen_gae_bolg_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/lancer_5th_wesen_gae_bolg"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_arrow_rain_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/archer_5th_arrow_rain"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_bellerophon_2_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/rider_5th_bellerophon_2"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_hecatic_graea_powered_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/caster_5th_hecatic_graea_powered"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_tsubame_mai_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/false_assassin_tsubame_mai"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_madmans_roar_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/berserker_5th_madmans_roar"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_max_enuma_elish_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/gilgamesh_max_enuma_elish"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_endless_loop_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/avenger_endless_loop"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_rampant_warrior_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/diarmuid_rampant_warrior"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_nuke_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/lancelot_nuke"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_larret_de_mort_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/gille_larret_de_mort"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_annihilate_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/iskander_annihilate"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_fiery_finale_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/nero_fiery_finale"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_polygamist_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/tamamo_kick"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_raging_dragon_strike_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/lishuwen_raging_dragon_strike"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_la_pucelle_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/jeanne_la_pucelle"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_hippogriff_ride_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/astolfo_hippogriff_ride"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}			
			"modifier_instinct_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/saber_instinct"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_strike_air_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/saber_attribute_strike_air"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_battle_continuation_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/lancer_5th_battle_continuation"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_hrunting_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/archer_5th_hrunting"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_overedge_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/archer_5th_overedge"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_blood_mark_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/avenger_blood_mark"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_quickdraw_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/false_assassin_quickdraw"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_mystic_shackle_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/wisp_tether"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_eternal_arms_mastership_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/lancelot_arms_mastership"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_story_for_someones_sake_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/nursery_rhyme_story_for_somebodys_sake"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_phoebus_catastrophe_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/atalanta_phoebus_catastrophe"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_golden_apple_cooldown"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/atalanta_golden_apple"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_lord_of_execution_cd"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/vlad_combo"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_protection_of_faith_proc_cd"
			{
				"IsDebuff"	"1"
				"TextureName"	"custom/vlad_protection_of_faith"
				"Attributes"		"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
		}
	}


	//=================================================================================================================
	// Gawain : Excalibur Galatine
	//=================================================================================================================
	"gawain_excalibur_galatine"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/gawain_excalibur_galatine"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_2"
		"AnimationPlaybackRate" 		"1.0"
		"AOERadius"						"%radius"

		
		"precache"
		{
			"particle"		"particles/units/heroes/hero_keeper_of_the_light/keeper_cast01.vpcf"
			"particle"		"particles/units/heroes/hero_lina/lina_spell_light_strike_array.vpcf"
			"particle"		"particles/custom/gawain/gawain_excalibur_galatine_orb.vpcf"
			"particle"		"particles/units/heroes/hero_ember_spirit/ember_spirit_hit.vpcf"
			"particle"		"particles/custom/saber_excalibur_circle.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_lina.vsndevts"
		}
		
		"AbilityCastPoint"				"0.15"
		"AbilityCooldown"				"36"
		"AbilityManaCost"				"400"
		"AbilityCastRange"				"1500"
		
		"AbilityValues"
        {
            "cast_delay" "1.75"
            "damage" "700 900 1100 1300 1500"
            "radius" "550"
        }
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"    "gawain_ability"
				"Function"      "OnGalatineStart"
				"Target"		"POINT"
				"Damage"		"%damage"
				"Radius"		"%radius"
			}
			"ApplyModifier"
			{
				"ModifierName"	"modifier_excalibur_galatine_vfx"
				"Target"		"CASTER"
			}
		}
		
		"Modifiers"
		{		
			"modifier_excalibur_galatine_vfx"
			{
				"Duration"		"1.75"
				"OnCreated"
				{
					"AttachEffect"
					{
						"Target"			"TARGET"
						"EffectName"		"particles/custom/saber_excalibur_circle.vpcf"
						"EffectAttachType"	"follow_origin"
						"EffectRadius"		"400"
					}
				}
			}
			"modifier_excalibur_galatine_anim"
			{
				"OverrideAnimation"     "ACT_DOTA_CAST_ABILITY_2"	
				"Duration"			"1.5"
				"IsHidden"			"1"
				"Properties"
				{
					"MODIFIER_PROPERTY_OVERRIDE_ANIMATION_RATE"		"0.7"
				}
			}
		}
	}



	//=======================================
	// Gawain : Detonate Excalibur Galatine
	//=======================================
	"gawain_excalibur_galatine_detonate"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/gawain_excalibur_galatine"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"5"
		"AbilityManaCost"				"0"

		"precache"
		{
		}

		"AbilityValues"
        {
        }
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"gawain_ability"
				"Function"		"OnGalatineDetonate"
			}
		}
	}
	//=================================================================================================================
	// Gawain : Sun's Embrace
	//=================================================================================================================



	//=======================================
	// Gawain : Divine Meltdown
	//=======================================
	//=================================================================================================================
	// Gawain : Supernova
	//=================================================================================================================

	//=======================================
	// Gawain Attribute : Dawnbringer
	//=======================================

	//=======================================
	// Gawain Attribute : Blessing of Fairy
	//=======================================
	"gawain_attribute_blessing_of_fairy"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/gawain_attribute_blessing_of_fairy"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"15"

		"precache"
		{
		}

		"AbilityValues"
        {
        }
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"gawain_ability"
				"Function"		"OnFairyAcquired"
			}
		}

		"Modifiers"
		{

		}
	}

	//=======================================
	// Gawain Attribute : Divine Meltdown
	//=======================================

	//=======================================
	// Gawain Attribute : Sunlight
	//=======================================

	//=======================================
	// Gawain Attribute : Eclipse
	//=======================================

	// [restored] возвращён после ошибочной чистки
	// [restored] возвращён после ошибочной чистки
	// [restored] возвращён после ошибочной чистки
	// [restored] возвращён после ошибочной чистки
	// [restored] возвращён после ошибочной чистки
}