#base "medea_hecatic_graea.kv"

"DOTAAbilities"
{
	//=================================================================================================================
	// medea blink (spellbook ability)
	//=================================================================================================================
	"medea_blink"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/medea/medea_blink"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_IMMEDIATE|DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"antimage_blink"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1.0"
		"MaxLevel"						"5"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityManaCost"				"100"
		"AbilityCooldown"				"11"
		"AbilityCastPoint"				"0.0"
		
		"AbilityValues"
		{
			"cast_point"			"0.0"
			"base_dist"				"500 575 650 725 800"		
		}
	}
	//=======================================
	// Caster : Item Construction
	//=======================================
	"caster_5th_item_construction"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/medea/caster_5th_item_construction"
		"MaxLevel"						"3"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityTextureName"			"custom/caster_5th_item_construction"
		"AbilityCastAnimation" 			"ACT_DOTA_ATTACK"
		"AnimationPlaybackRate" 		"1.0"
		
		"AbilityCastPoint"				"0.3"
		"AbilityCooldown"				"60"
		"AbilityManaCost"				"100"

		"precache"
		{
		}

		"AbilityValues"
        {
            "b_a_s_chance" "45 30 25"
            "b_a_s_chance_near_workshop" "33 33 34"
        }
		
	}

	//=====================================
	// Caster : Territory Creation
	//=====================================
	"caster_5th_territory_creation"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/medea/caster_5th_territory_creation"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityTextureName"			"custom/caster_5th_territory_creation"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"2.0"
		"precache"
		{
			"model"			"models/props_structures/tower_good.vmdl"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_rubick.vsndevts"
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_lion.vsndevts"
			"particle"			"particles/units/heroes/hero_lion/lion_spell_mana_drain.vpcf"
			"particle"					"particles/units/heroes/hero_jakiro/jakiro_dual_breath_ice.vpcf"
			"particle"				"particles/units/heroes/hero_crystalmaiden/maiden_crystal_nova.vpcf"
			"particle"				"particles/units/heroes/hero_crystalmaiden/maiden_frostbite_buff.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_obsidian_destroyer.vsndevts"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_jakiro.vsndevts"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_crystalmaiden.vsndevts"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_ancient_apparition.vsndevts"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"200"
		"AbilityCastPoint"				"0.3"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"40"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"400"
		
		"AbilityValues"
        {
            "workshop_health" "10000"
        }
		

	}

	//=====================================
	// Caster : Mana Drain
	//=====================================
	"caster_5th_mana_drain"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/medea/caster_5th_mana_drain"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_CHANNELLED"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_BOTH"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityTextureName"			"lion_mana_drain"
		"AbilityCastRange"				"2000"
		"AbilityCastPoint"				"0.01"
		"AbilityCooldown"				"30"
		"AbilityManaCost"				"0"
		"AbilityChannelTime"			"5.0"

		"precache"
		{
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_lion.vsndevts"
			"particle"			"particles/units/heroes/hero_lion/lion_spell_mana_drain.vpcf"
		}

		"AbilityValues"
        {
            "duration" "5.0"
            "mana_per_second" "40"
            "break_distance" "2500"
            "tick_interval" "0.25"
            "int_ratio" "0.8"
        }



	}

	//=======================================
	// Caster : Territory Explosion
	//=======================================
	"caster_5th_territory_explosion"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/medea/caster_5th_territory_explosion"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityTextureName"			"custom/caster_territory_explosion"
		"AbilityCastPoint"				"0.70"
		"AbilityCooldown"				"0"
		"AbilityManaCost"				"100"

		"precache"
		{
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_obsidian_destroyer.vsndevts"
			"particle"				"particles/units/heroes/hero_obsidian_destroyer/obsidian_destroyer_sanity_eclipse_area.vpcf"
			"particle"				"particles/custom/caster/workshop_explosion.vpcf"
		}

		"AbilityValues"
        {
            "cast_delay" "0.7"
        }
		

	}

	//=======================================
	// Caster : Mobilize
	//=======================================
	"caster_5th_mobilize"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/medea/caster_5th_mobilize"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityTextureName"			"custom/caster_mobilize"
		"AbilityCastPoint"				"1.6"
		"AbilityCooldown"				"0"
		"AbilityManaCost"				"0"

		"precache"
		{
		}

		"AbilityValues"
        {
        }
		

	}
	//=======================================
	// Caster : Immobilize
	//=======================================
	"caster_5th_immobilize"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/medea/caster_5th_immobilize"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/caster_immobilize"
		"AbilityCastPoint"				"1.6"
		"AbilityCooldown"				"0"
		"AbilityManaCost"				"0"

		"precache"
		{
		}

		"AbilityValues"
        {
        }
		

	}

	//=====================================
	// Caster : Dimensional Jump
	//=====================================
	"caster_5th_dimensional_jump"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/caster/territory_dimensional_jump"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"phantom_assassin_phantom_strike"
		"MaxLevel"						"1"

		"precache"
		{
		}

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"9999"
		"AbilityCastPoint"				"0.15"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"5"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"150"
		
	    "AbilityValues"
        {
            "distance" "1000"
        }
	}


	//=====================================
	// Caster : Recall
	//=====================================
	"caster_5th_recall"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/medea/caster_5th_recall"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityTextureName"			"keeper_of_the_light_recall"


		"AbilityCooldown"				"60"
		"AbilityManaCost"				"100"
		
		"precache"
		{
            "particle"          "particles/custom/caster/caster_recall_out.vpcf"
            "particle"          "particles/units/heroes/hero_wisp/wisp_relocate_teleport.vpcf"
            "particle"          "particles/units/heroes/hero_wisp/wisp_relocate_channel.vpcf"
		}

		"AbilityValues"
        {
        }


	}


	//================================================
	// Spooky Scary Skeleton Passive
	//================================================
	"caster_5th_skeleton_passive"
	{
		"AbilityBehavior" 		"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"BaseClass" 					"ability_lua"
		"ScriptFile" 					"abilities/medea/caster_5th_skeleton_passive"
		"AbilityTextureName"            "rubick_empty1"
		"MaxLevel"                      "1"


	}

	//================================================
	// Spooky Scary Skeleton Bash
	//================================================
	"caster_5th_skeleton_bash"
	{
		"AbilityBehavior" 		"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"BaseClass" 					"ability_lua"
		"ScriptFile" 					"abilities/medea/caster_5th_skeleton_bash"
		"AbilityTextureName"            "rubick_empty1"
		"MaxLevel"                      "1"

		"AbilityValues"
        {
            "bash_chance" "100"
            "bash_duration" "0.8"
        }

	}

	//================================================
	// Dragon Chilling Breath
	//================================================
	"caster_5th_dragon_chilling_breath"
	{
		"AbilityBehavior" 		"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"BaseClass" 					"ability_lua"
		"ScriptFile" 					"abilities/medea/caster_5th_dragon_chilling_breath"
		"AbilityTextureName"            "winter_wyvern_arctic_burn"
		"MaxLevel"                      "1"

		"AbilityValues"
        {
            "slow" "-50"
            "duration" "1"
        }

	}

	//================================================
	// Dragon Frost Bite
	//================================================
	"caster_5th_dragon_frostbite"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/medea/caster_5th_dragon_frostbite"
		"MaxLevel"						"8"
		"RequiredLevel"					"25"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"winter_wyvern_cold_embrace"
		"AbilityCastAnimation" 			"ACT_DOTA_ATTACK"
		"AnimationPlaybackRate" 		"1.3"
		
		"precache"
		{
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"900"
		"AbilityCastPoint"				"0.5"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"30.0"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"100"
		
		"AbilityValues"
        {
            "delay" "0.5"
            "radius" "300"
            "total_duration" "1.0"
            "damage" "500 550 600 650 700 750 800 850"
        }


		
	}

	//================================================
	// Dragon Arcane Wrath
	//================================================
	"caster_5th_dragon_arcane_wrath"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"8"
		"RequiredLevel"					"25"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_CREEP"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"crystal_maiden_crystal_nova"
		"AbilityCastAnimation" 			"ACT_DOTA_ATTACK"
		"AnimationPlaybackRate" 		"0.55"
		"AOERadius"						"%radius"
		"precache"
		{
			"particle"		"particles/units/heroes/hero_obsidian_destroyer/obsidian_destroyer_sanity_eclipse_area.vpcf"
			"particle"		"particles/econ/items/crystal_maiden/crystal_maiden_maiden_of_icewrack/maiden_freezing_field_casterribbons_arcana1.vpcf"
		}
		"IsCastableWhileHidden"			"1"
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"1350"
		"AbilityCastPoint"				"2.0"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"60.0"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"300"
		
		"AbilityValues"
        {
            "delay" "2.0"
            "damage" "400 500 600 700 800 900 1000 1100"
            "radius" "450"
            "stun_duration" "1.75"
        }
		
		"OnAbilityPhaseStart"
		{
			"RunScript"
			{
				"ScriptFile"	"caster_ability"
				"Function"		"OnArcaneWrathCast"
			}
		}

		"OnSpellStart"
		{
			"RunScript"
			{
			 	"ScriptFile"	"caster_ability"
			 	"Function"		"OnArcaneWrathStart"
			 	"Target"		"POINT"
			 	"Radius"		"%radius"
			 	"StunDuration"	"%stun_duration"
			 	"Damage"		"%damage"
			}
			"FireEffect"
			{
				"TargetPoint"			"POINT"
				"EffectName"			"particles/units/heroes/hero_crystalmaiden/maiden_crystal_nova.vpcf"
				"EffectAttachType"		"world_origin"
				"ControlPoints"
				{
					"01"				"%radius 2 %radius*3"
				}
			}
		}
		
		"Modifiers"
		{
		}
	}


	//=======================================
	// Caster : Argos
	//=======================================
	"medea_argos"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/medea/medea_argos"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityTextureName"			"custom/caster_5th_argos"
		"AbilityCastPoint"				"0.3"
		"AbilityCooldown"				"10"
		"AbilityManaCost"				"100"
		"AbilityCastAnimation" 			"ACT_DOTA_ATTACK"
		"AnimationPlaybackRate" 		"1.0"

		"precache"
		{
			"particle"	"particles/units/heroes/hero_medusa/medusa_mana_shield.vpcf"
			"particle"	"particles/custom/caster/caster_argos_durability.vpcf"
			"particle"	"particles/zlodemon/medea_base_attack.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_medusa.vsndevts"
		}

		"AbilityValues"
        {
            "shield_amount" "80 160 240 320 400"
            "max_shield" "160 320 480 640 800"
            "armor_duration" "3.0"
            "armor" "4"
        }
		
		// "OnSpellStart"
		// {
		// 	"RunScript"
		// 	{
		// 		"ScriptFile"	"caster_ability"
		// 		"Function"		"OnArgosStart"
		// 		"ShieldAmount"	"%shield_amount"
		// 		"MaxShield"		"%max_shield"
		// 	}
		// 	"FireSound"
		// 	{
		// 		"EffectName"	"Hero_Medusa.ManaShield.On" 
		// 		"Target"		"CASTER"
		// 	}
		// }

		

		// "Modifiers"
		// {
		// 	"modifier_argos_shield"
		// 	{
		// 		"IsDebuff"		"false"
		// 		"IsPurgable"	"false"
		// 		"OnTakeDamage"
		// 		{
		// 			"RunScript"
		// 			{
		// 				"ScriptFile"	"caster_ability"
		// 				"Function"		"OnArgosDamaged"
		// 				"DamageTaken"	"%attack_damage"		
		// 			}
		// 		}
		// 		"EffectName"	"particles/units/heroes/hero_medusa/medusa_mana_shield.vpcf"
		// 		"EffectAttachType"	"follow_origin"
		// 	}
		// 	"modifier_argos_armor"
		// 	{
		// 		"IsDebuff"		"false"
		// 		"IsPurgable"	"false"
		// 		"Duration"      "%armor_duration"
		// 		"Properties"
		// 		{
		// 			"MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS"	"%armor"
		// 		}
		// 	}
		// }
	}

	//=======================================
	// Caster : Ancient Magic
	//=======================================
	"caster_5th_ancient_magic"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/medea/caster_5th_ancient_magic"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL | DOTA_ABILITY_BEHAVIOR_TOGGLE"
		"AbilityTextureName"			"custom/caster_5th_ancient_magic"

		"LinkedAbilities"				"caster_5th_wall_of_flame caster_5th_silence caster_5th_divine_words medea_blink caster_5th_sacrifice"		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"0"
		"AbilityManaCost"				"0"

		"precache"
		{
		}

		"AbilityValues"
        {
        }
		
	}

	//=======================================
	// Caster : Wall of Flame
	//=======================================
	"caster_5th_wall_of_flame"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/medea/caster_5th_wall_of_flame"
		"MaxLevel"						"5"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"dragon_knight_breathe_fire"
		"AbilityCastPoint"				"0.01"
		"AbilityCooldown"				"7"
		"AbilityManaCost"				"200"
		"AbilityCastAnimation" 			"ACT_DOTA_ATTACK"
		"AnimationPlaybackRate" 		"1.0"
        "IsCastableWhileHidden"         "1"

		"precache"
		{
			"particle"	"particles/units/heroes/hero_ember_spirit/ember_spirit_hit_fire.vpcf"
			"particle"	"particles/units/heroes/hero_dragon_knight/dragon_knight_breathe_fire.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_ember_spirit.vsndevts"
		}

		"AbilityValues"
        {
            "pushback" "500 600 700 800 900"
            "damage" "100 130 160 190 220"
            "radius" "300"
        }
		
	}

	//=====================================
	// Caster : Silence
	//=====================================
	"caster_5th_silence"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/medea/caster_5th_silence"
		"MaxLevel"						"5"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityTextureName"			"death_prophet_silence"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"2.0"
		"AOERadius"						"%radius"
        "IsCastableWhileHidden"         "1"
		"precache"
		{
			"particle"				"particles/units/heroes/hero_death_prophet/death_prophet_silence.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_death_prophet.vsndevts"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"750"
		"AbilityCastPoint"				"0.3"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"16"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"200"
		
		"AbilityValues"
        {
            "duration" "1.4 1.8 2.2 2.6 3.0"
            "radius" "250"
        }
		
	}

	//=====================================
	// Caster : High-Speed Divine Words
	//=====================================
	"caster_5th_divine_words"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/medea/caster_5th_divine_words"
		"MaxLevel"						"5"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"invoker_sun_strike"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"2.0"
		"AOERadius"						"%radius"
        "IsCastableWhileHidden"         "1"
		"precache"
		{
			"particle"		"particles/units/heroes/hero_luna/luna_lucent_beam.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_luna.vsndevts"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"700"
		"AbilityCastPoint"				"0.2"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"7"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"200"
		
		"AbilityValues"
        {
            "radius" "325"
            "damage" "150 175 200 225 250"
        }
		
	}

	//=======================================
	// Caster : Sacrifice
	//=======================================
	"caster_5th_sacrifice"
	{
		"BaseClass"             		"ability_lua"
		"ScriptFile"             		"abilities/medea/caster_5th_sacrifice"
		"AbilityTextureName"			"omniknight_guardian_angel"
		"MaxLevel"						"5"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN | DOTA_ABILITY_BEHAVIOR_CHANNELLED"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_FRIENDLY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityCastPoint"				"0.3"
		"AbilityCooldown"				"40"
		"AbilityManaCost"				"600"
		"AbilityCastRange"				"600 675 750 825 900"
		"AbilityChannelTime"			"10.0"	
		"AbilityCastAnimation" 			"ACT_DOTA_IDLE"
		"AnimationPlaybackRate" 		"2.0"


		"precache"
		{
			"particle"	"particles/units/heroes/hero_warlock/warlock_shadow_word_buff.vpcf"
			"particle"  "particles/status_fx/status_effect_guardian_angel.vpcf"
			"particle"	"particles/units/heroes/hero_omniknight/omniknight_guardian_angel_buff_j.vpcf"
			"particle"	"particles/custom/caster/sacrifice/caster_sacrifice_indicator.vpcf"
			"soundfile" "soundevents/game_sounds_heroes/game_sounds_shadowshaman.vsndevts"
			"soundfile"	"soundevents/game_sounds_heroes/game_sounds_witchdoctor.vsndevts"
		}
		
		"AbilityValues"
        {
            "duration" "10.0"
            "radius" "600 675 750 825 900"
        }



	}

	//=====================================
	// Caster : Mana Transfer
	//=====================================

	"caster_5th_close_spellbook"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/medea/caster_5th_close_spellbook"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"silencer_last_word"
		
		"AbilityCastPoint"				"0.0"

	}

	//=====================================
	// Caster : Rule Breaker
	//=====================================
	"caster_5th_rule_breaker"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/medea/caster_5th_rule_breaker"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityTextureName"			"custom/caster_5th_rule_breaker"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"2.2"
		"AbilityCastPoint"				"0.3"
		"AbilityCastRange"				"350"
		"AbilityCastRangeBuffer"		"200"
		"AbilityCooldown"				"35"
		"AbilityManaCost"				"400"
        "IsCastableWhileHidden"         "1"
		
		"precache"
		{
			"particle"		"particles/units/heroes/hero_pugna/pugna_decrepify.vpcf"
			"particle"		"particles/units/heroes/hero_dazzle/dazzle_weave.vpcf"
			"particle"		"particles/units/heroes/hero_doom_bringer/doom_bringer_doom.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_silencer.vsndevts"
		}

		"AbilityValues"
        {
            "delay" "0.3"
            "stun_duration" "1.0 1.0 1.25 1.25 1.5"
            "duration" "1 1.25 1.5 1.75 2"
        }


	}

	//====================================
	// Caster : Hecatic Graea
	//====================================


	//====================================
	// Caster : Hecatic Graea Powered
	//====================================

	//=======================================
	// Caster Attribute : Improve Territory Creation
	//=======================================
	"caster_5th_attribute_improve_territory_creation"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/medea/caster_5th_attribute_improve_territory_creation"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/caster_5th_attribute_improve_territory_creation"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"13"

		"precache"
		{
		}

		"AbilityValues"
        {
            "workshop_health" "2000"
            "workshop_mregen" "50"
            "explosion_bonus_damage" "300"
            "workshop_mana" "1500"
        }
		
	}

	//=======================================
	// Caster Attribute : Improve Argos
	//=======================================
	"caster_5th_attribute_improve_argos"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/medea/caster_5th_attribute_improve_argos"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/caster_5th_attribute_improve_argos"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"8"

		"precache"
		{
		}

		"AbilityValues"
        {
            "bonus_durability" "150"
            "bonus_charge" "100"
            "armor_duration" "3"
            "armor" "25"
        }
		
	}
	
	//=======================================
	// Caster Attribute : Witchcraft
	//=======================================
	"caster_5th_attribute_improve_hecatic_graea"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/medea/caster_5th_attribute_improve_hecatic_graea"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/caster_hecatic_graea_attr"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"14"

		"precache"
		{
		}

		"AbilityValues"
        {
            "bonus_ray" "3"
            "bonus_damage" "300"
            "int_ratio" "1.5"
        }
		
	}

	//=======================================
	// Caster Attribute : Dagger of Treachery
	//=======================================
	"caster_5th_attribute_dagger_of_treachery"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"						"abilities/medea/caster_5th_attribute_dagger_of_treachery"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/caster_5th_attribute_dagger_of_treachery"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"11"

		"precache"
		{
		}

		"AbilityValues"
        {
            "cd_reduction" "10.0"
            "revoke_duration" "5.0"
            "mana_steal_amount" "1"
        }
		
	}
	

	// [restored] возвращён после ошибочной чистки
	// [restored] возвращён после ошибочной чистки
}