//#base "medusa_breaker_gorgon.kv"
//#base "medusa_nail_pull.kv"
#base "medusa_riding_passive.kv"

"DOTAAbilities"
{
	//=================================================================================================================
	// Rider : Bloodfort Andromeda
	//=================================================================================================================
	"rider_5th_bloodfort_andromeda"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/medusa/rider_5th_bloodfort_andromeda"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_AOE "
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/medusa/medusa_bloodfort"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"1.0"

		"precache"
		{
			"particle"					"particles/custom/rider/rider_bloodfort_andromeda_sphere.vpcf"
			"particle"					"particles/units/heroes/hero_warlock/warlock_upheaval.vpcf"
		}

		"AbilityCastPoint"				"0.8"
		"AbilityCooldown"				"28"
		"AbilityManaCost"				"400"

		"AbilityValues"
		{
			"delay" "0.8"
			"radius" "1100"
			"slow" "-20"
			"duration" "6.0"
			"damage" "120 165 210 255 300"
			"absorb" "30 37.5 45 52.5 60"
			"bleed_damage" "40"
			"bleed_absorb" "16.6"
		}
	}

		//=======================================
	// Rider Attribute : Seal
	//=======================================

		//=======================================
	// Rider Attribute : Monstrous Strength
	//=======================================
	"imba_pudge_meat_hook"
	{
		"BaseClass"             		"ability_lua"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"

		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"

		"AbilityTextureName"			"custom/rider_5th_nail_swing"
		"ScriptFile"					"abilities/medusa/medusa_hook.lua"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastPoint"				"0.3"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"30 26 22 18 14"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"100" 

		// Precache
		//-------------------------------------------------------------------------------------------------------------
		"precache"
		{
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_pudge.vsndevts"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_bloodseeker.vsndevts"
			"particle"					"particles/units/heroes/hero_bloodseeker/bloodseeker_rupture.vpcf"
			"particle"					"particles/units/heroes/hero_pudge/pudge_meathook_chain.vpcf"
			"particle"					"particles/units/heroes/hero_pudge/pudge_meathook_impact.vpcf"			
		}

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "base_speed" "3000"
            "base_range" "1600 1800 2000 2200 2400"
            "base_damage" "200 275 350 425 500"
            "hook_width" "100"
            "vision_radius" "550"
            "vision_duration" "4"
            "cooldown_cap_scepter" "3.0"
            "enemy_disable_linger" "0.2"
            "number_of_hooks" "1"
            "max_targets" "1"
            "hook_stacks" "8 16 24 32"
        }
	}

	//=================================================================================================================
	// Medusa: Nail Hook
	//=================================================================================================================
	"medusa_nail_hook"
	{
		"BaseClass"             		"ability_lua"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"

		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"

		"AbilityTextureName"			"custom/medusa/medusa_nail_hook"
		"ScriptFile"					"abilities/medusa/medusa_nail_hook.lua"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastPoint"				"0.0"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"14 13 12 11 10"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"100"

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "speed" "3000"
            "range" "900"
            "damage" "200 250 300 350 400"
            "fly_speed" "3000"
            "reduced_cooldown" "1"
        }
	}
	//=================================================================================================================
	// Medusa: Chain Assault
	//=================================================================================================================
	"medusa_chain_assault"
	{
		"BaseClass"             		"ability_lua"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"SpellImmunityType"				"SPELL_IMMUNITY_ENEMIES_NO"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"

		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"

		"AbilityTextureName"			"custom/medusa/medusa_chain_assault"
		"ScriptFile"					"abilities/medusa/medusa_chain_assault.lua"

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastPoint"				"0.3"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"15 13 11 9 7"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"200"

		// Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "speed" "3000"
            "range" "1000"
            "damage" "200 250 300 350 400"
            "fly_speed" "3000"
            "width" "75"
            "collide_stun_duration" "0.6 0.75 0.9 1.05 1.2"
        }
	}
	//=================================================================================================================
	// Medusa: Breaker Gorgon
	//=================================================================================================================
	"medusa_breaker"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/medusa/medusa_breaker"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityTextureName"			"custom/medusa/medusa_breaker"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_4"
		"AnimationPlaybackRate" 		"1.0"
		"MaxLevel"						"2"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"25"
		"AbilityManaCost"				"200"
		"AbilityCooldown"				"20 15"
		"AbilityCastPoint"				"0.2"
		//"AbilityChannelTime"            "3.0"
		
		"AbilityValues"
        {
            "slow_duration" "2.0 4.0"
            "radius" "500"
            "damage" "200 300"
            "angle" "140"
            "turn_rate" "90"
            "ms_slow" "80"
            "stun_duration" "1 1.5"
            "window_duration" "1.5 2.0"
            "stack_count" "1"
            "break_cap" "700"
            "break_damage" "15 25"
        }
	}
	//=================================================================================================================
	// Medusa: Gorgon Rush
	//=================================================================================================================
	"medusa_gorgon_rush"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/medusa/medusa_gorgon_rush"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_HIDDEN | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES"
		"AbilityTextureName"			"custom/medusa/medusa_gorgon_rush"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_7"
		"AnimationPlaybackRate" 		"2.0"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"25"
		"AbilityManaCost"				"200"
		"AbilityCooldown"				"15"
		"AbilityCastPoint"				"0.5"
		//"AbilityChannelTime"            "3.0"
		
		"AbilityValues"
        {
            "range" "1500"
            "radius" "500"
            "damage" "700"
            "speed" "6000"
            "damage_per_agi" "1.5"
        }
	}
	//=================================================================================================================
	// Medusa: Monstrous Strength
	//=================================================================================================================
	"medusa_monstrous_strength"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/medusa/medusa_monstrous_strength"
		"MaxLevel"						"1"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"25"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_FRIENDLY" 
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/medusa/medusa_monstrous"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_5"
		"AnimationPlaybackRate" 		"1.0"

		"precache"
		{	
			"particle"			"particles/medusa/medusa_monstrous_ambient.vpcf"
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_sven.vsndevts"
		}

		"AbilityCastPoint"				"0.4"
		"AbilityCooldown"				"40"
		"AbilityManaCost"				"100"
		
		"AbilityValues"
        {
            "disarm_duration" "0.5"
            "duration" "8"
            "health_percent" "2.5"
            "as_bonus" "80"
            "str_bonus" "20"
            "base_damage" "35"
        }
	}
	//=================================================================================================================
	// Medusa : Bellerophon
	//=================================================================================================================
	"medusa_bellerophon"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/medusa/medusa_bellerophon"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_VECTOR_TARGETING | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/rider_5th_bellerophon"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_6"
		"AbilityType"					"ABILITY_TYPE_ULTIMATE"
		"AnimationPlaybackRate" 		"2.0"
		"AOERadius"						"%radius"
		
		"precache"
		{
			"particle"				"particles/medusa/medusa_trail_test_3.vpcf"
			"particle"				"particles/medusa/medusa_surge_trail.vpcf"
			"particle"				"particles/vector_target/vector_target_range_finder_line.vpcf"
			"particle"				"particles/ui_mouseactions/range_finder_cone.vpcf"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		//"AbilityCastRange"				"2000"
		"AbilityCastPoint"				"0.35"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"30.0"


		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"800"
		
		"AbilityValues"
        {
            "delay" "0.4"
            "damage" "900 1075 1250 1425 1600"
            "radius" "350"
            "cast_range" "2000"
            "stun_duration" "1.25"
            "vector_range" "900"
            "attribute_range" "500"
            "riding_damage" "100"
            "agility_multiplier" "3.5"
        }
	}
	//=================================================================================================================
	// Medusa : Bellerophon II
	//=================================================================================================================
	"medusa_bellerophon_2"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/medusa/medusa_bellerophon_2"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/medusa/medusa_bellerophon_2"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AbilityType"					"ABILITY_TYPE_ULTIMATE"
		"AnimationPlaybackRate" 		"1.0"
		"AOERadius"						"%radius"
		
		"precache"
		{
			"particle"				"particles/custom/rider/rider_bellerophon_1.vpcf"
			"particle"				"particles/custom/rider/rider_bellerophon_1_alternate.vpcf"
			"particle"				"particles/custom/rider/rider_bellerophon_1_impact.vpcf"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"4080"
		"AbilityCastPoint"				"1.5"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"150.0"


		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"800"
		
		"AbilityValues"
        {
            "delay" "3"
            "damage" "2500"
            "radius" "650"
            "range" "4080"
            "stun_duration" "1.5"
            "riding_damage" "500"
            "agility_multiplier" "5"
        }
	}
	//=================================================================================================================
	// Medusa: Attributes
	//=================================================================================================================
	"medusa_seal_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/medusa/medusa_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/medusa/medusa_seal"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"9"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
        }		
	}
	"medusa_monstrous_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/medusa/medusa_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/medusa/medusa_monstrous"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"10"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
            "disarm_duration" "0.5"
            "duration" "8"
            "health_percent" "2"
            "as_bonus" "80"
            "str_bonus" "20"
            "base_damage" "35"
        }
	}
	"medusa_chain_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/medusa/medusa_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/medusa/medusa_chain_mastery_2"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"9"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
            "duration" "7"
            "damage" "30"
            "bleed_damage" "30"
            "bleed_absorb" "20"
        }		
	}
	"medusa_gorgon_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/medusa/medusa_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/medusa/medusa_gorgon_rush"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"10"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
            "range" "1500"
            "radius" "500"
            "damage" "700"
            "speed" "6000"
            "damage_per_agi" "1.5"
        }		
	}
	"medusa_riding_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/medusa/medusa_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/rider_5th_attribute_riding"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"16"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
            "belle_damage" "3.5"
            "belle_2_damage" "5"
            "bonus_belle_damage" "100"
            "bonus_belle2_damage" "500"
            "attribute_range" "100"
        }		
	}
}