"DOTAHeroes"
{
	//=================================================================================================================
	//	HIJIKATA TOSHIZO ( LUKE FROM ERBS)
	//=================================================================================================================
	"npc_dota_hero_hijikata"
	{
		"override_hero"			"npc_dota_hero_spirit_breaker"
		"DisableWearables" 			"1"
		"Model"					"models/hijikata/hijikata_0_14_idle.vmdl"
		//"Model"					"models/development/invisiblebox.vmdl"
		"AbilityLayout"			"6"
		//"HeroID"					"118"
		"DrawParticlesWhileHidden" "1"
		"ModelScale"			"1.3"
		

		"Ability1"				"hijikata_dash"
		"Ability2"				"hijikata_demon"
		"Ability3"				"hijikata_duel"
		"Ability4"				"hijikata_madness"
		"Ability5"				"hijikata_laws"
		"Ability6"				"hijikata_ult"
		"Ability7"				"hijikata_dash_recast"
		"Ability8"				"hero_base_stats_bonus"
		"Ability9"				"presence_detection_passive"
		"Ability10"				"attribute_bonus_custom"
		"Ability11"				"hijikata_combo"
		"Ability12"				"hijikata_target_dash"
		"Ability13"				"hijikata_knockup"
		"Ability14"				"hijikata_fierce_journey"

		"Combo"						"hijikata_combo"
		"AttributeNumber"			"4"
		"Attribute1"				"hijikata_shinsengumi_attribute"
		"Attribute2"				"hijikata_battle_continuation_attribute"
		"Attribute3"				"hijikata_eternal_madness_attribute"
		"Attribute4"				"hijikata_tactics_attribute"
		//"Attribute5"				"saito_mastery_attribute"

		"StatusHealth"					"1000"
		"StatusHealthRegen"				"6.0"
		"StatusMana"					"1000"
		"StatusManaRegen"				"5.0"
		
		"ArmorPhysical"					"2"
		"MagicalResistance"				"4"
		
		"AttackCapabilities"			"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"				"60"
		"AttackDamageMax"				"60"
		"AttackRate"					"0.9"
		"AttackAcquisitionRange"		"550"
		"AttackRange"					"175"
		"HealthBarOffset"				"260" 

		"AttributePrimary"				"DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength"			"0"
		"AttributeStrengthGain"			"2.1"
		"AttributeBaseAgility"			"0"
		"AttributeAgilityGain"			"2.0"
		"AttributeBaseIntelligence"		"0"
		"AttributeIntelligenceGain"		"1.9"
		
		"MovementSpeed"					"370"
		"MovementTurnRate"				"0.8"

		"VisionDaytimeRange"			"1050"
		"VisionNighttimeRange"			"1050"

	}
}