"DOTAHeroes"
{
	//=================================================================================================================
	//	Ruler - Jeanne d'Arc
	//=================================================================================================================
	"npc_dota_hero_jeanne_alter"
	{
		"override_hero"				"npc_dota_hero_razor"
		"DisableWearables" 			"1"
		"Model"						"models/updated_by_seva_and_hudozhestvenniy_film_spizdili/jeanne_alter/jeanne_alter.vmdl"
		"ModelScale"				"1.1"
		"LoadoutScale"        "1.1"
        "SpectatorLoadoutScale"   		"1.1"
		//"HeroID"					"121"
		"DrawParticlesWhileHidden" "1"
		"Skins"
		{
			"skin_1"
			{
				"loc_name"			"jalter_1"
				"model"				"models/zlodemon/alter_jaba/jeanne_alter.vmdl"
			}
		}
		"AbilityLayout"				"6"
		"Ability1"					"jeanne_curse" //"jeanne_flag_swing"
		"Ability2"					"jeanne_trail"
		"Ability3"					"jeanne_jump"
		"Ability4"					"jeanne_witch"
		"Ability5"					"jeanne_mana"
		"Ability6"					"jeanne_lagron"
		//"Ability6"					"jeanne_flag"
		"Ability7"					"jeanne_lagron_combo"
		"Ability8"					"jeanne_identity_discernment"
		"Ability9"					"hero_base_stats_bonus"
		"Ability10"					"jeanne_trail_reactivate"
		"Ability15"					"presence_detection_passive"
		"Ability16"					"attribute_bonus_custom"

		"Combo"						"jeanne_lagron_combo"
		"AttributeNumber"			"4"
		"Attribute1"				"jeanne_oblivion_attribute"
		"Attribute2"				"jeanne_ephemeral_attribute"
		"Attribute3"				"jeanne_dragon_attribute"
		"Attribute4"				"jeanne_cursed_ground_attribute"
		"Attribute5"				"jeanne_avenger_attribute"
		
		"StatusHealth"					"1100"
		"StatusHealthRegen"				"5"
		"StatusMana"					"1000"
		"StatusManaRegen"				"5.0"
		
		"ArmorPhysical"					"4"
		"MagicalResistance"				"35"
		
		"AttackCapabilities"			"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"				"57"
		"AttackDamageMax"				"63"
		"AttackRate"					"1.7"
		"AttackAcquisitionRange"		"800"
		"AttackRange"					"200"

		
		
		"AttributePrimary"				"DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength"			"0"
		"AttributeStrengthGain"			"2.5"
		"AttributeBaseAgility"			"0"
		"AttributeAgilityGain"			"2.0"
		"AttributeBaseIntelligence"		"0"
		"AttributeIntelligenceGain"		"2.0"
		
		"MovementCapabilities"			"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"					"375"
		"MovementTurnRate"				"0.8"
		
		"VisionDaytimeRange"			"1000"
		"VisionNighttimeRange"			"1000"
	}
}