"DOTAHeroes"
{
	//=================================================================================================================
	//	Black Rider(Apoc.) - Astolfo
	//=================================================================================================================
	"npc_dota_hero_astolfo"
	{
		"override_hero"				"npc_dota_hero_queenofpain"
		"DisableWearables" 			"1"
		"Model"						"models/astolfo/extella/astolfo.vmdl"
		"ModelScale"				"1.3"
		"LoadoutScale"              "1.3"
        "SpectatorLoadoutScale"     "1.3"
		"DrawParticlesWhileHidden" "1"
		"Skins"
		{
			"skin_1"
			{
				"loc_name"			"astolfo_1"
				"model"				"models/astolfo/astolfo_trifas.vmdl"
			}
			"skin_2"
			{
				"loc_name"			"astolfo_2"
				"model"				"models/astolfo/extella/astolfo_swimsuit.vmdl"
			}
		}
		"AbilityLayout"				"6"
		"Ability1"					"astolfo_down_with_a_touch"
		"Ability2"					"astolfo_trap_of_argalia"
		"Ability3"					"astolfo_la_black_luna"
		"Ability4"					"astolfo_hippogriff_vanish"
		"Ability5"					"astolfo_casa_di_logistilla"
		"Ability6"					"astolfo_hippogriff_raid"
		//"Ability6"					"astolfo_tornado"
		"Ability7"					"astolfo_hippogriff_ride"
		"Ability8"					"astolfo_hippogriff_rush"
		"Ability9"					"astolfo_monstrous_strength_passive"
		"Ability10"					"hero_base_stats_bonus"
		"Ability15"					"presence_detection_passive"
		"Ability16"					"attribute_bonus_custom"

		"Combo"						"astolfo_hippogriff_ride"
		"AttributeNumber"			"5"
		"Attribute1"				"astolfo_attribute_riding"
		"Attribute2"				"astolfo_attribute_monstrous_strength"
		"Attribute3"				"astolfo_attribute_independent_action"
		"Attribute4"				"astolfo_attribute_sanity"
		"Attribute5"				"astolfo_deafening_blast_attribute"
		
		"StatusHealth"					"1200"
		"StatusHealthRegen"				"5"
		"StatusMana"					"1000"
		"StatusManaRegen"				"6.0"
		
		"ArmorPhysical"					"4"
		"MagicalResistance"				"20"
		
		"AttackCapabilities"			"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"				"43"
		"AttackDamageMax"				"47"
		"AttackRate"					"1.7"
		"AttackAcquisitionRange"		"500"
		"AttackRange"					"150"

		
		
		"AttributePrimary"				"DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength"			"0"
		"AttributeStrengthGain"			"1.7"
		"AttributeBaseAgility"			"0"
		"AttributeAgilityGain"			"3.4"
		"AttributeBaseIntelligence"		"0"
		"AttributeIntelligenceGain"		"2.2"
		
		"MovementCapabilities"			"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"					"390"
		"MovementTurnRate"				"0.8"
		
		"VisionDaytimeRange"			"1000"
		"VisionNighttimeRange"			"1000"
	}
}