"DOTAHeroes"
{
	//=================================================================================================================
	//	Karna
	//=================================================================================================================
	"npc_dota_hero_karna"
	{
		"override_hero"			"npc_dota_hero_beastmaster"
		"DisableWearables" 		"1"
		"Model"					"models/karna/karna_new.vmdl"
		//"Model"				"models/development/invisiblebox.vmdl"
		"ModelScale"			"1.1"
			"LoadoutScale"        "1.1"
        "SpectatorLoadoutScale"   		"1.1"
		"DrawParticlesWhileHidden" "1"

		"AbilityLayout"			"6"
		"Ability1"				"karna_spin"
		"Ability2"				"karna_slashes"
		"Ability3"				"karna_buff_melee"
		"Ability4"				"fate_empty1"
		"Ability5"				"karna_armor"
		"Ability6"				"karna_jump"
		"Ability7"				"karna_combo_vasavi_new"
		"Ability8"				"karna_divinity_proxy"
		"Ability9"				"karna_discern_poor"
		"Ability10"				"karna_spin_2"	
		"Ability11"				"karna_recast_dash"
		"Ability12"				"karna_upper_slash"			
		"Ability13"				"karna_push"	
		"Ability14"				"karna_brahmastra_new"	
		"Ability15"				"karna_brahmastra_kundala_new"	
		"Ability16"				"karna_brahmastra_kundala_retrieve"	
		"Ability17"				"karna_spears_barrage"	
		"Ability18"				"presence_detection_passive"
		"Ability19"				"attribute_bonus_custom"
		"Ability20"				"hero_base_stats_bonus"

		"Combo"						"karna_combo_vasavi_new"
		"AttributeNumber"			"5"
		"Attribute1"				"karna_poor_attribute"
		"Attribute2"				"karna_ucm_attribute"
		"Attribute3"				"karna_indra_attribute"
		"Attribute4"				"karna_divinity_attribute"
		"Attribute5"				"karna_mana_burst_attribute"


		"StatusHealth"					"800"
		"StatusHealthRegen"				"8"
		"StatusMana"					"1000"
		"StatusManaRegen"				"5"

		"ArmorPhysical"					"4"
		"MagicalResistance"				"5"

		"AttackCapabilities"			"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackRange"					"350"
		"AttackDamageMin"				"53"
		"AttackDamageMax"				"69"
		"AttackRate"					"1.7"
		"AttackAcquisitionRange"		"600"
		"AttackAnimationPoint"			"0.2"


		"AttributePrimary"				"DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength"			"0"
		"AttributeStrengthGain"			"1.5"
		"AttributeBaseAgility"			"0"
		"AttributeAgilityGain"			"2.0"
		"AttributeBaseIntelligence"		"0"
		"AttributeIntelligenceGain"		"2.5"

		"MovementSpeed"					"375"
		"MovementTurnRate"				"0.8"

		"VisionDaytimeRange"			"1000"
		"VisionNighttimeRange"			"1000"
	}
}