"DOTAHeroes"
{
	//=================================================================================================================
	//	Okada izo
	//=================================================================================================================
	"npc_dota_hero_okada"
	{
		"override_hero"			"npc_dota_hero_troll_warlord"
		"DisableWearables" 			"1"
		"Model"					"models/hijikata/hijikata_0_14_idle.vmdl"
		//"Model"					"models/development/invisiblebox.vmdl"
		"AbilityLayout"			"6"
		//"HeroID"					"118"
		"DrawParticlesWhileHidden" "1"
		"ModelScale"			"1.1"
		

		"Ability1"				"okada_reduced_earth"
		"Ability2"				"okada_flashblade"
		"Ability3"				"okada_chest"
		"Ability4"				"okada_manslayer"
		"Ability5"				"hijikata_laws"
		"Ability6"				"hijikata_ult"
		"Ability7"				"hijikata_dash_recast"
		"Ability8"				"hero_base_stats_bonus"
		"Ability9"				"presence_detection_passive"
		"Ability10"				"attribute_bonus_custom"
		"Ability11"				"hijikata_combo"
		"Ability12"				"hijikata_target_dash"
		"Ability13"				"hijikata_knockup"
		"Ability14"				"hijikata_fierce_journey"
		"Ability15"				"hijikata_duel_recast"
		"Combo"						"hijikata_combo"
		"AttributeNumber"			"5"
		"Attribute1"				"okada_sa_1"
		"Attribute2"				"okada_sa_2"
		"Attribute3"				"okada_sa_3"
		"Attribute4"				"okada_sa_4"
		"Attribute5"				"okada_sa_5"

		"StatusHealth"					"1100"
		"StatusHealthRegen"				"6.0"
		"StatusMana"					"1000"
		"StatusManaRegen"				"5.0"
		
		"ArmorPhysical"					"11"
		"MagicalResistance"				"10"
		
		"AttackCapabilities"			"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"				"60"
		"AttackDamageMax"				"60"
		"AttackRate"					"1.5"
		"AttackAcquisitionRange"		"550"
		"AttackRange"					"225"
		"HealthBarOffset"				"260" 

		"AttributePrimary"				"DOTA_ATTRIBUTE_AGILITY"
		"AttributeBaseStrength"			"0"
		"AttributeStrengthGain"			"1.8"
		"AttributeBaseAgility"			"0"
		"AttributeAgilityGain"			"2.5"
		"AttributeBaseIntelligence"		"0"
		"AttributeIntelligenceGain"		"1.5"
		
		"MovementSpeed"					"390"
		"MovementTurnRate"				"0.8"

		"VisionDaytimeRange"			"1050"
		"VisionNighttimeRange"			"1050"

	}
}