"DOTAHeroes"
{
	//=================================================================================================================
	//	Assassin(Grand) - Old Man from the Mountian
	//=================================================================================================================
	"npc_dota_hero_kinghassan"
	{
		"override_hero"			"npc_dota_hero_skeleton_king"
		"DisableWearables" 			"1"
		"Model"					"models/updated_by_seva_and_hudozhestvenniy_film_spizdili/kinghassan/kinghassan_unanim.vmdl"
		//"Model"				"models/development/invisiblebox.vmdl"
		"ModelScale"			"6.0"
		"LoadoutScale"       "6.0"
        "SpectatorLoadoutScale"   		"6.0"
		"DrawParticlesWhileHidden" "1"

		"AbilityLayout"			"6"
		"Ability1"				"khsn_ambush"
		"Ability2"				"khsn_mde"
		"Ability3"				"khsn_slash"
		"Ability4"				"khsn_grab"
		"Ability5"				"khsn_bc"
		"Ability6"				"khsn_aoe_flame"
		"Ability7"				"khsn_combo"
		"Ability8"				"khsn_combo_arena"
		"Ability9"				"khsn_presence"
		"Ability10"				"presence_detection_passive"
		"Ability11"				"attribute_bonus_custom"
		"Ability12"				"hero_base_stats_bonus"
		"Ability13"				"khsn_combo_arena_recast"
		"Ability14"				"khsn_azrael"


		"Combo"					"khsn_combo_arena"
		"AttributeNumber"			"5"
		"Attribute1"				"khsn_boundary_attribute"
		"Attribute2"				"khsn_bc_attribute"
		"Attribute3"				"khsn_presence_attribute"
		"Attribute4"				"khsn_flame_attribute"
		"Attribute5"				"khsn_azrael_attribute"


		"StatusHealth"					"1400"
		"StatusHealthRegen"				"7"
		"StatusMana"					"1000"
		"StatusManaRegen"				"5"

		"ArmorPhysical"					"1"
		"MagicalResistance"				"30"

		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackRange"					"215"
		"AttackDamageMin"				"90"
		"AttackDamageMax"				"90"
		"AttackRate"					"1.5"
		"AttackAcquisitionRange"		"520"
		//"AttackAnimationPoint"		"0.3"


		"AttributePrimary"				"DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength"			"0"
		"AttributeStrengthGain"			"3.2"
		"AttributeBaseAgility"			"0"
		"AttributeAgilityGain"			"2.0"
		"AttributeBaseIntelligence"		"0"
		"AttributeIntelligenceGain"		"1.5"

		"HealthBarOffset"				"350" 

		"MovementSpeed"					"370"
		"MovementTurnRate"				"0.8"

		"VisionDaytimeRange"			"1000"
		"VisionNighttimeRange"			"1000"
	}
}