"DOTAHeroes"
{
	//=================================================================================================================
	//	Berserker(5th) - Hercules 
	//=================================================================================================================
	"npc_dota_hero_berserker_5th"
	{
		"override_hero"			"npc_dota_hero_doom_bringer"
		"DisableWearables" 			"1"
		"Model"					"models/zlodemon/heracles.vmdl"//"models/berserker/berserker.vmdl"
		"ModelScale"			"1.3"
		"Skins"
		{
			"skin_1"
			{
				"loc_name"			"herc_1"
				"model"				"models/zlodemon/heracles_arbuz.vmdl"
			}
			"skin_2"
			{
				"loc_name"			"herc_2"
				"model"				"models/barbatos/barbatos.vmdl"
			}


		}
		"LoadoutScale"        "1.3"
        "SpectatorLoadoutScale"   		"1.3"
		//"SoundSet"						""
		"IdleSoundLoop"					""
		//"Model"					"models/development/invisiblebox.vmdl"
		//"HeroID"					"116"
		"DrawParticlesWhileHidden" "1"

		"AbilityLayout"			"6"
		"Ability1"				"heracles_fissure"
		"Ability2"				"heracles_courage"			//"berserker_5th_courage"
		"Ability3"				"pepeg_jump"			//"berserker_5th_berserk"
		"Ability4"				"heracles_berserk"
		"Ability5"				"pepeg_divinity"
		"Ability6"				"heracles_nine_lives"
		"Ability7"				"berserker_5th_madmans_roar"
		"Ability8"				"berserker_5th_berserk_attribute_passive"
		"Ability9"				"berserker_5th_god_hand"
		"Ability10"				"berserker_5th_reincarnation"
		"Ability11"				"presence_detection_passive"
		"Ability12"				"attribute_bonus_custom"
		"Ability13"				"hero_base_stats_bonus"
		"Ability14"				"heracles_mad_enhancement_passive"
		"Ability15"				"pepeg_combo_final_gachi"

		"Combo"						"berserker_5th_madmans_roar"
		"AttributeNumber"			"5"
		"Attribute1"				"berserker_5th_attribute_improve_divinity"
		"Attribute2"				"berserker_5th_attribute_berserk"
		"Attribute3"				"berserker_5th_attribute_god_hand"
		"Attribute4"				"berserker_5th_attribute_reincarnation"
		"Attribute5"				"heracles_mad_enhancement_attribute"

		"StatusHealth"					"1400"
		"StatusHealthRegen"				"15"
		"StatusMana"					"1000"
		"StatusManaRegen"				"5"
		
		"ArmorPhysical"					"1"
		"MagicalResistance"				"30"
		
		"AttackCapabilities"			"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackRange"					"200"
		"AttackDamageMin"				"100"
		"AttackDamageMax"				"100"
		"AttackRate"					"1.5"
		"HealthBarOffset"				"260" 

		"AttributePrimary"				"DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength"			"0"
		"AttributeStrengthGain"			"3"
		"AttributeBaseAgility"			"0"
		"AttributeAgilityGain"			"3"
		"AttributeBaseIntelligence"		"0"
		"AttributeIntelligenceGain"		"1.0"
		
		"MovementSpeed"					"370"
		"MovementTurnRate"				"0.8"

		"VisionDaytimeRange"			"1000"
		"VisionNighttimeRange"			"1000"
	}
}