"DOTAHeroes"
{
	//=================================================================================================================
	//	Demon king Nobunaga
	//=================================================================================================================
	"npc_dota_hero_demon_king_nobunaga"
	{
		"override_hero"			"npc_dota_hero_nevermore"
		"DisableWearables" 			"1"
		"Model"					"models/maounobu/maounobu.vmdl"
		//"Model"					"models/maounobu/maounobu.vmdl"
		"AbilityLayout"			"6"
		"DrawParticlesWhileHidden" "1"
		"ModelScale"			"1.6"
		"LoadoutScale"         	"1.6"
        "SpectatorLoadoutScale"   		"1.6"
		"DrawParticlesWhileHidden" "1"
		

		"Ability1"				"demon_king_beam"
		"Ability2"				"demon_king_extermination"
		"Ability3"				"demon_king_blink"
		"Ability4"				"demon_king_release"
		"Ability5"				"demon_king_combo"
		"Ability6"				"demon_king_breath"
		"Ability7"				"demon_king_combo_recast"
		"Ability8"				"hero_base_stats_bonus"
		"Ability9"				"presence_detection_passive"
		"Ability10"				"attribute_bonus_custom"

		"Combo"						"demon_king_combo"
		"AttributeNumber"			"5"
		"Attribute1"				"demon_king_attribute_1"
		"Attribute2"				"demon_king_attribute_2"
		"Attribute3"				"demon_king_attribute_3"
		"Attribute4"				"demon_king_attribute_4"
		"Attribute5"				"demon_king_attribute_5"

		"StatusHealth"					"1100"
		"StatusHealthRegen"				"6.0"
		"StatusMana"					"1000"
		"StatusManaRegen"				"5.0"
		
		"ArmorPhysical"					"2"
		"MagicalResistance"				"5"
		
		"AttackCapabilities"			"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"				"57"
		"AttackDamageMax"				"58"
		"AttackRate"					"0.9"
		"AttackAcquisitionRange"		"550"
		"AttackRange"					"175"

		"AttributePrimary"				"DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength"			"0"
		"AttributeStrengthGain"			"1.7"
		"AttributeBaseAgility"			"0"
		"AttributeAgilityGain"			"2.7"
		"AttributeBaseIntelligence"		"0"
		"AttributeIntelligenceGain"		"2.2"
		
		"MovementSpeed"					"400"
		"MovementTurnRate"				"0.8"

		"VisionDaytimeRange"			"1050"
		"VisionNighttimeRange"			"1050"

	}
}