"DOTAHeroes"
{
	//=================================================================================================================
	//	Okada izo
	//=================================================================================================================
	"npc_dota_hero_ozy"
	{
		"override_hero"			"npc_dota_hero_phoenix"
		"DisableWearables" 			"1"
		"Model"					"models/ozy/ozy.vmdl"
		//"Model"					"models/development/invisiblebox.vmdl"
		"AbilityLayout"			"6"
		//"HeroID"					"118"
		"DrawParticlesWhileHidden" "1"
		"ModelScale"			"1.3"
		

		"Ability1"				"ozy_light_chacram"
		"Ability2"				"ozy_protection_of_sun_god"
		"Ability3"				"ozy_light_pillar"
		"Ability4"				"ozy_spawn_boat"
		"Ability5"				"ozy_mystic_eyes"
		"Ability6"				"ozy_spawn_piramid"
		"Ability7"				"okada_combo"
		"Ability8"				"ozy_light_chacram_recast"
		"Ability9"				"hero_base_stats_bonus"
		"Ability10"				"presence_detection_passive"
		"Ability11"				"attribute_bonus_custom"
		"Combo"						"okada_combo"
		"AttributeNumber"			"4"
		"Attribute1"				"ozy_sa_1"
		"Attribute2"				"ozy_sa_2"
		"Attribute3"				"ozy_sa_3"
		"Attribute4"				"ozy_sa_4"
		//"Attribute5"				""

		"StatusHealth"					"1100"
		"StatusHealthRegen"				"6.0"
		"StatusMana"					"1000"
		"StatusManaRegen"				"5.0"
		
		"ArmorPhysical"					"11"
		"MagicalResistance"				"10"
		
		"AttackCapabilities"			"DOTA_UNIT_CAP_RANGED_ATTACK"
		"AttackDamageMin"				"60"
		"AttackDamageMax"				"60"
		"AttackRate"					"1.5"
		"AttackAcquisitionRange"		"800"
		"AttackRange"					"700"
		"HealthBarOffset"				"260" 

		"AttributePrimary"				"DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength"			"0"
		"AttributeStrengthGain"			"2.2"
		"AttributeBaseAgility"			"0"
		"AttributeAgilityGain"			"1.6"
		"AttributeBaseIntelligence"		"0"
		"AttributeIntelligenceGain"		"2.8"
		
		"MovementSpeed"					"340"
		"MovementTurnRate"				"0.8"

		"VisionDaytimeRange"			"1000"
		"VisionNighttimeRange"			"1000"

	}
}