"DOTAHeroes"
{
	//=================================================================================================================
	//	Kama
	//=================================================================================================================
	"npc_fate_hero_kama"
	{
		"override_hero"				"npc_dota_hero_enigma"
		"DisableWearables"			"1"
		"Model"						"models\maounobu\maounobu.vmdl"
		"ModelScale"				"1.0"
		"DrawParticlesWhileHidden"	"1"
		"GameSoundsFile"			"soundevents/hero_kama.vsndevts"
		"SoundSet"					"Hero_Kama"

		"AbilityLayout"				"6"
		"Ability1"				"kama_q"		// Q
		"Ability2"				"kama_w"		// W
		"Ability3"				"kama_e"		// E
		"Ability4"				"kama_d"		// D
		"Ability5"				"kama_f"		// F
		"Ability6"				"kama_r"		// R
		"Ability7"				"hero_base_stats_bonus"
		"Ability8"				"presence_detection_passive"
		"Ability9"				"attribute_bonus_custom"
		"Ability10"				"kama_combo"		// Combo
		"Combo"						"kama_combo"
		"AttributeNumber"			"4"
		"Attribute1"				"kama_sa_1"
		"Attribute2"				"kama_sa_2"
		"Attribute3"				"kama_sa_3"
		"Attribute4"				"kama_sa_4"

		"StatusHealth"				"1200"
		"StatusHealthRegen"			"6.0"
		"StatusMana"				"1000"
		"StatusManaRegen"			"4.0"

		"ArmorPhysical"				"2"
		"MagicalResistance"			"25"

		"AttackCapabilities"		"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"			"70"
		"AttackDamageMax"			"70"
		"AttackRate"				"1.7"
		"AttackAcquisitionRange"	"600"
		"AttackRange"				"150"
		"HealthBarOffset"			"220"

		"AttributePrimary"			"DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength"		"0"
		"AttributeStrengthGain"		"3.0"
		"AttributeBaseAgility"		"0"
		"AttributeAgilityGain"		"2.0"
		"AttributeBaseIntelligence"	"0"
		"AttributeIntelligenceGain"	"2.0"

		"MovementCapabilities"		"DOTA_UNIT_CAP_MOVE_GROUND"
		"MovementSpeed"				"330"
		"MovementTurnRate"			"0.7"

		"VisionDaytimeRange"		"1000"
		"VisionNighttimeRange"		"1000"
	}
}
