"DOTAHeroes"
{
	//=======================================================================================================
	//	Saber - Saitō Hajime
	//=======================================================================================================
	"npc_dota_hero_saito"
	{
		//---------------------------------------------------------------------------------------------------
		//	General
		//---------------------------------------------------------------------------------------------------

		"override_hero"					"npc_dota_hero_terrorblade"

		"Model"							"models/heroes/saito_2/saito_2_mdoc.vmdl"
		"ModelScale"					"1.0"
		"Skins"
		{
			"skin_1"
			{
				"loc_name"			"saito_haori"
				"model"				"models/heroes/saito_1/saito_1_mdoc.vmdl"
			}
		}
		"precache"
		{
			"model"						"models/heroes/saito_1/saito_1_mdoc.vmdl"		//SaberSaitōHajimeStage3
			"model"						"models/heroes/saito_2/saito_2_mdoc.vmdl"		//SaberSaitōHajimeStage1
		}

		//"HeroID"						"118"

		"DisableWearables"				"1"
		"DrawParticlesWhileHidden"		"1"

		//---------------------------------------------------------------------------------------------------
		//	Abilities
		//---------------------------------------------------------------------------------------------------

		"AbilityLayout"					"6"

		"Ability1"						"saito_flashblade"
		"Ability2"						"saito_steelwing"
		"Ability3"						"saito_shadowslash"

		"Ability4"						"saito_mind_eye"
		"Ability5"						"saito_fds"

		"Ability6"						"saito_formless_invis"
		"Ability7"						"saito_formlessness_new"

		"Ability8"						"saito_step"
		"Ability9"						"saito_storm"
		"Ability10"						"saito_vortex"

		"Ability11"						"saito_jce"
		"Ability12"						"saito_blast"

		"Ability13"						"presence_detection_passive"
		"Ability14"						"attribute_bonus_custom"
		"Ability15"						"hero_base_stats_bonus"

		"Combo"							"saito_jce"

		"AttributeNumber"				"5"

		"Attribute1"					"saito_attribute_freedom"
		"Attribute2"					"saito_attribute_sword"
		"Attribute3"					"saito_attribute_memoir"
		"Attribute4"					"saito_attribute_freestyle"
		"Attribute5"					"saito_attribute_kunishige"

		//---------------------------------------------------------------------------------------------------
		//	Roles
		//---------------------------------------------------------------------------------------------------

		"ManaCost"						"20"
		"NP"							"3"
		"Difficult"						"5"
		"SType"							"burst,control,mobility"
		"Trait"							"shinsengumi"

		//---------------------------------------------------------------------------------------------------
		//	Stats
		//---------------------------------------------------------------------------------------------------

		"HealthBarOffset"				"200"

		"StatusHealth"					"1000"
		"StatusHealthRegen"				"5.0"
		"StatusMana"					"1000"
		"StatusManaRegen"				"5.0"

		//---------------------------------------------------------------------------------------------------
		//	Defense
		//---------------------------------------------------------------------------------------------------

		"ArmorPhysical"					"7"
		"MagicalResistance"				"10"

		//---------------------------------------------------------------------------------------------------
		//	Attack
		//---------------------------------------------------------------------------------------------------

		"AttackCapabilities"			"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackDamageMin"				"42"
		"AttackDamageMax"				"48"
		"AttackAnimationPoint"			"0.500000"
		"AttackRate"					"1.7"
		"AttackAcquisitionRange"		"600"
		"AttackRange"					"150"

		//---------------------------------------------------------------------------------------------------
		//	Attributes
		//---------------------------------------------------------------------------------------------------

		"AttributePrimary"				"DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength"			"0"
		"AttributeStrengthGain"			"2.2"
		"AttributeBaseAgility"			"0"
		"AttributeAgilityGain"			"2.5"
		"AttributeBaseIntelligence"		"0"
		"AttributeIntelligenceGain"		"2.8"

		//---------------------------------------------------------------------------------------------------
		//	Mobility
		//---------------------------------------------------------------------------------------------------

		"MovementSpeed"					"365"
		"MovementTurnRate"				"0.8"

		//---------------------------------------------------------------------------------------------------
		//	Vision
		//---------------------------------------------------------------------------------------------------

		"VisionDaytimeRange"			"1000"
		"VisionNighttimeRange"			"1000"

		//---------------------------------------------------------------------------------------------------
		//	Automatic files pre-caching, to avoid bugs when files are not pre-cached in Lua custom files.
		//---------------------------------------------------------------------------------------------------

		"SoundSet"						"Hero_Saito"
		"GameSoundsFile"				"soundevents/heroes/saito.vsndevts"
		"VoiceFile"						"soundevents/voscripts/game_sounds_vo_terrorblade.vsndevts"
		"particle_folder"				"particles/heroes/saito"
	}
}