"DOTAHeroes"
{
	//=================================================================================================================
	//	Aozaki Aoko
	//=================================================================================================================
	"npc_dota_hero_aoko"
	{
		"override_hero"			"npc_dota_hero_ogre_magi"
		"DisableWearables" 			"1"
		"Model"					"models/updated_by_seva_and_hudozhestvenniy_film_spizdili/aoko/aoko.vmdl"
		"ModelScale"			"1.0"
		"LoadoutScale"        "1.0"
        "SpectatorLoadoutScale"   		"1.0"
		//"SoundSet"						""
		"IdleSoundLoop"					""
		//"Model"					"models/development/invisiblebox.vmdl"
		//"HeroID"					"116"
		"DrawParticlesWhileHidden" "1"

		"AbilityLayout"			"6"
		"Ability1"				"aoko_shield"
		"Ability2"				"aoko_facebreaker"
		"Ability3"				"aoko_short_beam"
		"Ability4"				"aoko_swap"
		"Ability5"				"aoko_circuits"
		"Ability6"				"aoko_intimidation"
		"Ability7"				"aoko_jumpback"
		"Ability8"				"aoko_sphere"
		"Ability9"				"aoko_lazers"
		"Ability10"				"aoko_3_beams"
		"Ability11"				"aoko_blue"
		"Ability12"				"presence_detection_passive"
		"Ability13"				"attribute_bonus_custom"
		"Ability14"				"hero_base_stats_bonus"

		"Combo"						"aoko_blue"
		"AttributeNumber"			"5"
		"Attribute1"				"aoko_circuits_attribute"
		"Attribute2"				"aoko_first_star_attribute"
		"Attribute3"				"aoko_bullet_attribute"
		"Attribute4"				"aoko_incantation_attribute"
		"Attribute5"				"aoko_magician_attribute"

		"StatusHealth"					"1200"
		"StatusHealthRegen"				"5"
		"StatusMana"					"1000"
		"StatusManaRegen"				"5.0"
		
		"ArmorPhysical"					"4"
		"MagicalResistance"				"20"
		
		"AttackCapabilities"			"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackRange"					"150"
		"AttackDamageMin"				"70"
		"AttackDamageMax"				"70"
		"AttackRate"					"1.0"
		"AttackAnimationPoint"			"0.23"
		
		"AttributePrimary"				"DOTA_ATTRIBUTE_INTELLECT"
		"AttributeBaseStrength"			"0"
		"AttributeStrengthGain"			"2.1"
		"AttributeBaseAgility"			"0"
		"AttributeAgilityGain"			"1.8"
		"AttributeBaseIntelligence"		"0"
		"AttributeIntelligenceGain"		"2.5"
		
		"MovementSpeed"					"320"
		"MovementTurnRate"				"0.8"

		"VisionDaytimeRange"			"1000"
		"VisionNighttimeRange"			"1000"
	}
}