"DOTAAbilities"
{
	//=================================================================================================================
	// Lancer : Rune of Combat
	//=================================================================================================================
	"cu_chulain_rune_of_combat"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/cu_chulain/cu_chulain_rune_of_combat"
		"MaxLevel"						"5"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/cu_chulain/cu_chulain_rune_of_combat"
		
		"AbilityCastPoint"				"0.0"
		"AbilityManaCost"				"100"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1.0"
		"AbilityCooldown"				"40"

		"precache"
		{
			"particle"				"particles/status_fx/status_effect_beserkers_call.vpcf"
			"particle"				"particles/units/heroes/hero_phantom_assassin/phantom_assassin_phantom_strike_end.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_phantom_lancer.vsndevts"
		}
		"AbilityValues"
        {
            "duration" "10"
            "bonus_atk" "4 5 6 7 8"
            "bonus_atk_max" "40 50 60 70 80"
            //"stun_dur" "0.25"
            "cooldown" "40"
            "bonus_attackspeed" "100 125 150 175 200"
            "bonus_attackspeed_loss" "10 12.5 15 17.5 20"
            "bonus_attackspeed_attacks" "6"
        }
	}
}