"DOTAAbilities"
{
	//=================================================================================================================
	// Lancer : Gae Bolg - The Spear of Impaling Barbed Death
	//=================================================================================================================
	"cu_chulain_gae_bolg"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/cu_chulain/cu_chulain_gae_bolg"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_CREEP"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PURE"
		"AbilityTextureName"			"custom/lancer_5th_gae_bolg"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"1.33"
		
		"IsCastableWhileHidden"			"1"
		
		"precache"
		{
			"particle"		"particles/units/heroes/hero_chaos_knight/chaos_knight_reality_rift.vpcf"
			"particle"		"particles/units/heroes/hero_centaur/centaur_double_edge.vpcf"
			"particle"		"particles/units/heroes/hero_axe/axe_culling_blade_kill.vpcf"
			"particle"		"particles/custom/lancer/lancer_heart_break_txt.vpcf"
			"particle"		"particles/items_fx/dagon.vpcf"
			"particle"		"particles/custom/diarmuid/gae_dearg_slash.vpcf"
			"particle"		"particles/cu_chulain/gae_bolg_pierce.vpcf"
			"soundfile"		"soundevents/game_sounds_heroes/game_sounds_lion.vsndevts"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"300"
		"AbilityCastRangeBuffer"		"1000"
		"AbilityCastPoint"				"0.7"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"18.0"

		// Damage.
		//-------------------------------------------------------------------------------------------------------------
		"AbilityDamage"					"400 500 600 700 800"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"400"
		
		"AbilityValues"
        {
            "delay" "0.7"
            "damage" "400 500 600 700 800"
            "heart_break" "200 240 280 320 360"
            "atr_hb_pct" "10 13 16 19 22"
            "sa_damage_per_level" "12"
        }
	}
}