"DOTAAbilities"
{
	//====================================
	// Lancer : Gae Bolg - The Spear of Striking Death Flight
	//====================================
	"cu_chulain_gae_bolg_jump"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/cu_chulain/cu_chulain_gae_bolg_jump"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_CREEP"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/lancer_5th_gae_bolg_jump"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AbilityType"					"ABILITY_TYPE_ULTIMATE"
		"AnimationPlaybackRate" 		"0.5"
		"AOERadius"						"%radius"
		"IsCastableWhileHidden"			"1"
		"precache"
		{
			"particle"		"particles/units/heroes/hero_huskar/huskar_burning_spear.vpcf"
			"particle"		"particles/cu_chulain/gae_bolg_proj.vpcf"
			"particle"		"particles/units/heroes/hero_warlock/warlock_rainofchaos_start_breakout_fallback_mid.vpcf"
			"particle"		"particles/units/heroes/hero_elder_titan/elder_titan_echo_stomp_cracks.vpcf"
			"particle"		"particles/custom/lancer/lancer_gae_bolg_hit.vpcf"
			"particle"  	"particles/custom/lancer/soaring/spear.vpcf"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"1300"
		"AbilityCastPoint"				"0.2"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"35"

		// Damage.
		//-------------------------------------------------------------------------------------------------------------
		"AbilityDamage"					"750 950 1150 1350 1550"

		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"800"
		
		"AbilityValues"
        {
            "delay" "0.2"
            "damage" "800 1000 1200 1400 1600"
            "radius" "550"
            "cast_range" "1300"
            "bonus_range" "650"
            "damage_per_agi" "4.5"	
        }
	}
}