"DOTAAbilities"
{
	"cu_chulain_relentless_spear"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/cu_chulain/cu_chulain_relentless_spear"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_CHANNELLED"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_BOTH"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityTextureName"			"custom/cu_chulain/cu_dash"
		"AbilityCastRange"				"300"
		"AbilityCastRangeBuffer"		"50"
		"AbilityCastPoint"				"0.2"
		"AbilityCooldown"				"18"
		"AbilityManaCost"				"100"
		"AbilityChannelTime"			"1.05"

		"precache"
		{
			"soundfile"			"soundevents/game_sounds_heroes/game_sounds_phantom_lancer.vsndevts"
			"particle"			"particles/custom/lancer/lancer_relentless_spear/lancer_relentless_spear.vpcf"
		}

		"AbilityValues"
        {
        	"distance" "375"
            "duration" "1.05"
            "damage" "80 95 110 125 140"
            "num_attacks" "8"
            "window_duration" "3"
            "damage_first" "150 175 200 225 250"
        }
	}
}