#base "cu_chulain_battle_continuation.kv"
#base "cu_chulain_protection_from_arrows.kv"
#base "cu_chulain_rune_magic.kv"
#base "cu_chulain_rune_of_disengage.kv"
#base "cu_chulain_rune_of_combat.kv"
#base "cu_chulain_rune_of_ferocity.kv"
#base "cu_chulain_rune_of_flame.kv"
#base "cu_chulain_rune_of_protection.kv"
#base "cu_chulain_relentless_spear.kv"
#base "cu_chulain_gae_bolg.kv"
#base "cu_chulain_gae_bolg_jump.kv"
#base "cu_chulain_gae_bolg_combo.kv"
	
"DOTAAbilities"
{
	//=================================================================================================================
	// Lancer : Wesen Gae Bolg
	//=================================================================================================================
	"cu_new_combo"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/cu_chulain/cu_new_combo"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_PURE"
		"AbilityTextureName"			"custom/lancer_5th_wesen_gae_bolg"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ALACRITY"
		"AbilityUnitTargetFlags"		"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AnimationPlaybackRate" 		"0.5"
		
		"precache"
		{
			"particle"		"particles/cu_chulain/combo_gb_targetted.vpcf"
			"particle"		"particles/cu_chulain/combo_gb_targetted_explosion.vpcf"
			"particle"		"particles/cu_chulain/combo_gb_targetted_jumo.vpcf"
			"particle"		"particles/healres/hpbar_healres_t3_uncleansable.vpcf"
			"particle"		"particles/cu_chulain/cu_combo_status.vpcf"
		}
		
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"2500"
		"AbilityCastRangeBuffer"		"99999"
		"AbilityCastPoint"				"0.5"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"120"


		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"400"
		
		"AbilityValues"
        {
            "cast_delay" "2"
            "stun_duration" "0.3"
            "damage" "750"
            "radius" "550"
            "damage_aoe" "1000"
            "target_debuffs_duration_strong" "4"
            "target_debuffs_duration_weak" "8"
            "slow_powerful" "40"
            "slow_powerful_desc" "70" // 40+ 30
            "slow_weak" "30"
        }
	}	
	"cu_chulain_rune_of_frost"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/cu_chulain/cu_chulain_rune_of_frost"
		"MaxLevel"						"5"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_HIDDEN"

		"AbilityTextureName"			"jakiro_ice_path"
		"AbilityManaCost"				"150"
		"AbilityCastPoint"				"0.2"
		"AbilityCastAnimation" 			"ACT_DOTA_ICE_VORTEX"
		"AnimationPlaybackRate" 		"2"
		"AbilityCastRange"				"1200"
		"AbilityCooldown"				"25"

		"precache"
		{
			"particle"				"particles/cu_chulain/cu_rune_of_frost.vpcf"
		}
		"AbilityValues"
        {
            "cooldown" "25"
            "radius" "250"
            "damage" "200 250 300 350 400"
            "slow_duration" "2"
            "slow_power" "40 50 60 70 80"
            "range" "1200"
        }
	}
	//=======================================
	// Attribute: Battle Continuation
	//=======================================
	"cu_chulain_battle_cont_attribute"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/cu_chulain/cu_chulain_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/lancer_attribute_improve_battle_continuation"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"10"

		"precache"
		{
		}

		"AbilityValues"
        {
            "min_damage" "200"
            "max_damage" "1500"
            "duration" "7"
        }
	}

	//=======================================
	// Lancer : Protection from Arrows
	//=======================================
	"cu_chulain_prot_arrows_attribute"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/cu_chulain/cu_chulain_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/lancer_attribute_protection_from_arrows"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"6"

		"precache"
		{
		}

		"AbilityValues"
        {
            "evasion_bonus" "35"
            "duration" "4"
        }
	}


	//=======================================
	// Lancer : Improve Gae Bolg
	//=======================================
	"cu_chulain_death_flight_attribute"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/cu_chulain/cu_chulain_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/cu_chulain/cu_chulain_death_flight_attribute"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"15"

		"precache"
		{
		}

		"AbilityValues"
        {
            "bonus_damage" "100"
            "damage_per_agi" "4.5"
            "bonus_range" "1000"
        }
	}	

	//=======================================
	// Lancer : The Heartseeker
	//=======================================
	"cu_chulain_heartseeker_attribute"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/cu_chulain/cu_chulain_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/cu_chulain/cu_chulain_heartseeker_attribute"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"15"

		"precache"
		{
		}

		"AbilityValues"
        {
            "heartbreak_threshold" "10 13 16 19 22"
            "combo_heartbreak" "40"
            "damage_per_level" "10"
        }
	}

	//=======================================
	// Lancer : Celtic Runes
	//=======================================
	"cu_chulain_celtic_runes_attribute"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/cu_chulain/cu_chulain_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/cu_chulain/cu_chulain_celtic_runes"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"10"

		"precache"
		{
		}

		"AbilityValues"
        {
            "cooldown_reduction" "75"
            "combo_heartbreak" "40"
        }
	}	
}