"DOTAAbilities"
{	
	"karna_vasavi_shakti"
	{		
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/karna/karna_vasavi_shakti"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/karna/karna_vasavi_shakti"
		
		"precache"
		{
			"particle"			"particles/custom/karna/vasavi_shakti/vasavi_shakti_beam.vpcf"
			"particle"			"particles/custom/karna/vasavi_shakti/vasavi_ground.vpcf"
			"particle"			"particles/custom/karna/vasavi_shakti/fire_stream.vpcf"
			"particle"			"particles/custom/karna/vasavi_shakti/ground_erupt/karna_fire_eruption.vpcf"
		}
		
		"AbilityCastPoint"				"0.4"
		"AbilityCooldown"				"52"
		"AbilityManaCost"				"800"
		
		"AbilityValues"
        {
            "cast_point" "0.4"
            "radius" "600"
            "damage" "1000 1300 1600 1900 2200"
            "remove_duration" "35"
            "cast_range" "1000"
        }
	}
}