#base "mana_shroud.kv"

"DOTAAbilities"
{
	//=================================================================================================================
	// Saber Alter : Mana Shroud
	//=================================================================================================================
	"arturia_alter_mana_shroud"
	{
		"BaseClass"          			"ability_lua"
		"ScriptFile"					"abilities/arturia_alter/arturia_alter_mana_shroud_attribute_passive"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityTextureName"			"custom/saber_alter_mana_shroud"
		"MaxLevel"						"1"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		
		"AbilityValues"
        {
            "mana_regen_bonus" "1"
        }
	}
	
	//=================================================================================================================
	// Saber Alter : Unleashed Ferocity
	//=================================================================================================================
	"saber_alter_unleashed_ferocity"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/arturia_alter/saber_alter_unleashed_ferocity"
		"MaxLevel"						"2"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_AOE "
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/saber_alter_unleashed_ferocity"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_6"
		"AnimationPlaybackRate" 		"1.5"
		"AOERadius"						"%radius"
		
		"precache"
		{
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_crystalmaiden.vsndevts"
			"particle"					"particles/custom/saber_alter/saber_alter_unleashed_ferocity.vpcf"
		}
		
		"AbilityCastPoint"				"0.5"
		"AbilityCooldown"				"17"
		"AbilityManaCost"				"200 300"
		
		"AbilityValues"
        {
            "cast_delay" "1.0"
            "radius" "450"
            "explosion_count" "5"
            "damage" "10"
        }
	}


	//=================================================================================================================
	// Saber Alter : Darklight attribute passive
	//=================================================================================================================
	"saber_alter_darklight_passive"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/arturia_alter/saber_alter_darklight_passive"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/saber_alter_darklight_passive"
		"MaxLevel"						"1"

		"AbilityValues"
        {
        }
	}
	//=================================================================================================================
	// Saber Alter : Derange
	//=================================================================================================================
	"arturia_alter_derange"
	{
		"BaseClass"          			"ability_lua"
		"ScriptFile"					"abilities/arturia_alter/arturia_alter_derange"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_TOGGLE | DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityTextureName"			"custom/saber_alter_derange"
		
		"AbilityCastPoint"				"0.3"
		"AbilityCooldown"				"10 8.5 7 5.5 4"
		"AbilityManaCost"				"100"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1.0"
		
		"AbilityValues"
        {
            "as" "80"
            "ms" "5 6 7 8 9"
            "dmg" "50 62.5 75 87.5 100"
            "maximum_charges" "9"
            "mana_drain_percentage_1" "0.15"
            "mana_drain_percentage_2" "0.75"
            "mana_drain_percentage_3" "3"
            "armor_bonus" "0.5 1 1.5 2 2.5"
            "mr_bonus" "2.5 5 7.5 10 12.5"
            "max_mana_consumption_per_second" "4"
        }
		
		
		
	}
	
	//=================================================================================================================
	// Saber Alter : Mana Burst
	//=================================================================================================================
	"saber_alter_mana_burst"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/arturia_alter/saber_alter_mana_burst"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_AOE "
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/saber_alter_mana_burst"
		"AOERadius"						"%radius"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_6"
		"AnimationPlaybackRate" 		"1.5"
		"precache"
		{
			"particle"		"particles/items2_fx/skadi_projectile.vpcf"
			"particle"		"particles/units/heroes/hero_nevermore/nevermore_shadowraze.vpcf"
			"particle"		"particles/units/heroes/hero_disruptor/disruptor_static_storm.vpcf"
		}
		
		"AbilityCastPoint"				"0.3"
		"AbilityCooldown"				"10 8 6 4 2"
		"AbilityManaCost"				"200"
		
		"AbilityValues"
        {
            "delay" "0.3"
            "radius" "400"
            "damage" "300 380 460 540 620"
        }
	}

	//=================================================================================================================
	// Saber Alter : MAX Mana Burst
	//=================================================================================================================
	"saber_alter_max_mana_burst"
	{
		"BaseClass"          			"ability_lua"
		"ScriptFile"					"abilities/arturia_alter/saber_alter_max_mana_burst"
		"MaxLevel"						"1"
		"RequiredLevel"					"26"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/saber_alter_max_mana_burst"
		"AbilityCastPoint"				"0.2"
		"AbilityCooldown"				"180"
		"AbilityManaCost"				"200"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1.0"		
		

		"precache"
		{
			"particle"		"particles/units/heroes/hero_nevermore/nevermore_shadowraze.vpcf"
			"particle"		"particles/units/heroes/hero_disruptor/disruptor_static_storm.vpcf"
			"particle"		"particles/units/heroes/hero_slark/slark_dark_pact_pulses.vpcf"
			"particle"		"particles/units/heroes/hero_obsidian_destroyer/obsidian_destroyer_sanity_eclipse_area.vpcf"
			"particle"					"particles/zlodemon/zlodemon_basic_circle.vpcf"
			"particle"					"particles/saber_alter/max_mana_burst/altoria_mmb_vacuum.vpcf"
			"particle"		"particles/custom/screen_blue_splash.vpcf"
		}
		
		"AbilityValues"
        {
            "radius" "1500"
            "delay"	 "1.3"
            "mana_per_second"	"300"
            "mana_duration"		"15"
            "mana_ratio" "1"
            "first_dmg_radius" "600"
            "second_dmg_radius" "1050"
            "third_dmg_radius" "1500"
        }
		
	}

	//=================================================================================================================
	// Saber Alter : Vortigern
	//=================================================================================================================
	"saber_alter_vortigern"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/arturia_alter/saber_alter_vortigern"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/saber_alter_vortigern"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"1.5"
		
		"precache"
		{
			"particle"	"particles/units/heroes/hero_magnataur/magnataur_shockwave.vpcf"
			"particle"	"particles/custom/saber_alter/saber_alter_vortigern_line.vpcf"
		}
		
		"AbilityCastPoint"				"0.2"
		"AbilityCooldown"				"27"
		"AbilityManaCost"				"400"
		"AbilityCastRange"				"600"
		
		"AbilityValues"
        {
            "radius" "600"
            "damage" "400 500 600 700 800"
            "low_end" "75"
            "high_end" "125"
            "stun_duration" "0.6"
        }
	}
	
	
	//=================================================================================================================
	// Saber Alter : Excalibur
	//=================================================================================================================
	"saber_alter_excalibur"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/arturia_alter/saber_alter_excalibur"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"	
		"AbilityTextureName"			"custom/saber_alter_excalibur"
		"AbilityType"					"ABILITY_TYPE_ULTIMATE"
		"precache"
		{
			"particle"				"particles/saber_alter/saber_alter_excalibur_beam.vpcf"
			"particle"				"particles/saber_alter/saber_alter_excalibur_beam_pepeg.vpcf"
			"particle"				"particles/custom/saber_alter/saber_alter_excalibur_cast.vpcf"
			"particle"				"particles/custom/saber_alter/saber_alter_excalibur_overcharge.vpcf"
			"particle"				"particles/custom/saber_alter/saber_alter_excalibur_beam.vpcf"
			"particle"				"particles/custom/saber_alter/saber_alter_excalibur.vpcf"
			"particle"				"particles/custom/saber_alter/saber_alter_excalibur_beam_charge.vpcf"
			"particle"				"particles/custom/saber_alter/excalibur/shockwave.vpcf"
			"particle"				"particles/custom/saber_alter/excalibur/hit.vpcf"
		}
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"1800"
		"AbilityCastPoint"				"0.2"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"45.0"
		
		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"800"
		
		// Ability Special
		//-------------------------------------------------------------------------------------------------------------
		"AbilityValues"
        {
            "delay" "2"
            "width" "300"
            "length" "1800"
            "speed" "1100"
            "damage" "120 155 190 225 260"
            "damagelvl" "2.5"
            "pause_duration" "3.0"
            "slow_power" "80"
            "slow_duration" "1"
            "lock_duration" "1"
        }
		
	}

	//=================================================================================================================
	// Saber Alter : Mana Discharge
	//=================================================================================================================
	"arturia_alter_mana_discharge"
	{
		"BaseClass"          			"ability_lua"
		"ScriptFile"					"abilities/arturia_alter/arturia_alter_mana_discharge"
		"MaxLevel"						"1"
		"RequiredLevel"					"26"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/arturia_alter/mana_discharge"
		
		"AbilityCastPoint"				"0.2"
		"AbilityCooldown"				"30"
		"AbilityManaCost"				"0"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_1"
		"AnimationPlaybackRate" 		"1.0"
		"precache"
		{
			"particle"	"particles/custom/saber_alter/god_is_great/boom.vpcf"
			"particle"	"particles/items2_fx/satanic_buff.vpcf"
			"particle"	"particles/custom/saber_alter/god_is_great/boom_buff.vpcf"
		}
		"AbilityValues"
        {
            "cast_delay" "0.2"
            "as" "80"
            "ms" "5 6 7 8 9"
            "dmg" "50 62.5 75 87.5 100"
            "mana_drain_percentage_1" "0.45"
            "mana_drain_percentage_2" "2.25"
            "mana_drain_percentage_3" "11"
            "armor_bonus" "1 2 3 4 5"
            "mr_bonus" "5 10 15 20 25"
            "damage" "250"
            "damage_mana" "100"
            "radius" "600"
            "stun_duration" "1.3"
            "stun_duration_self" "0.5"
            "max_mana_consumption_per_second" "20"
            "additional_mana_consumption_per_second" "46"
        }
			
	}

	//=======================================
	// Saber Alter Attribute : Improve Mana Shroud
	//=======================================
	"arturia_alter_improve_mana_shroud"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"          			"ability_lua"
		"ScriptFile"					"abilities/arturia_alter/arturia_alter_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/saber_alter_attribute_mana_shroud"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"12"

		"precache"
		{
		}

		"AbilityValues"
        {
            "bonus_mana" "500"
            "bonus_armor" "12 14 16 18 20"
            "bonus_mr" "6 7 8 9 10"
            "bonus_radius" "200"
            "stun_duration" "0.3"
        }
	}

	//=======================================
	// Saber Alter Attribute : Mana Blast
	//=======================================
	"arturia_alter_improve_mana_burst"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"          			"ability_lua"
		"ScriptFile"					"abilities/arturia_alter/arturia_alter_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/saber_alter_attribute_mana_blast"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"	
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"12"

		"precache"
		{
		}

		"AbilityValues"
        {
            "mana_required_for_catalyst" "100"
            "max_catalyst" "9"
            "catalyst_damage" "100"
            "mana_burst_mana_ratio" "10"
            "bonus_damage" "0.3"
        }
	}

	//=======================================
	// Saber Alter Attribute : Improve Ferocity
	//=======================================
	"arturia_alter_improve_ferocity"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"          			"ability_lua"
		"ScriptFile"					"abilities/arturia_alter/arturia_alter_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/saber_alter_attribute_improve_ferocity"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"12"

		"precache"
		{
		}

		"AbilityValues"
        {
            "vortigern_bonus_damage" "100"
            "vortigern_bonus_stun_duration" "0.3"
            "uf_mana_cost" "100"
            "uf_int_ratio" "0.75"
            "uf_str_ratio" "0.75"
        }
	}

	//=======================================
	// Saber Alter Attribute : The Sword of Ultimate Darklight
	//=======================================
	"arturia_alter_sword_of_ultimate_darklight"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"          			"ability_lua"
		"ScriptFile"					"abilities/arturia_alter/arturia_alter_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/arturia_alter/sword_of_ultimate_darklight"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"10"

		"precache"
		{
		}

		"AbilityValues"
        {
            "excalibur_bonus_damage" "22"
        }
	}

	//=======================================
	// Saber Alter Attribute : God is Great
	//=======================================
	"arturia_alter_god_is_great"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"          			"ability_lua"
		"ScriptFile"					"abilities/arturia_alter/arturia_alter_attributes"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/arturia_alter/mana_discharge"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"8"

		"precache"
		{
		}

		"AbilityValues"
        {
            "cast_delay" "0.2"
            "as" "50 55 60 65 70"
            "ms" "5 6 7 8 9"
            "dmg" "100 125 150 175 200"
            "mana_drain_percentage_1" "0.6"
            "mana_drain_percentage_2" "1.5"
            "mana_drain_percentage_3" "15"
            "armor_bonus" "36 42 48 54 60"
            "mr_bonus" "18 21 24 27 30"
            "damage" "250"
            "damage_mana" "100"
            "radius" "600"
            "stun_duration" "1.3"
            "stun_duration_self" "0"
            "max_mana_consumption_per_second" "20"
            "additional_mana_consumption_per_second" "46"
        }
	}
}